### ISSUE TITLE
Feature Request: Add option to extend membership until expiration date on cancellation.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#1004]
**Is your feature request related to a problem? Please describe.**
When a member cancels their subscription their access to content that was available during their membership is immediately canceled.

**Describe the solution you'd like**
Add a selectable option for membership levels to set membership expiration date for next payment instead of cancelling immediately.

**Describe alternatives you've considered**
Use custom code in a customization plugin to achieve this.

**Additional context**
Article on how to achieve part of the above mentioned.
https://www.paidmembershipspro.com/change-pmpro-membership-cancellation-to-set-expiration-date-for-next-payment-instead-of-cancelling-immediately/

**Comment by eighty20results** [comment]
Available as a plugin/add-on: https://eighty20results.com/product/membership-cancellation-policy-for-paid-memberships-pro/

**Comment by dparker1005** [comment]
This behavior can also be added to your site using the PMPro Cancel on Next Payment Date Add On: https://www.paidmembershipspro.com/add-ons/cancel-on-next-payment-date/
