### ISSUE TITLE
BUG: ProfileStartDate and pmpro_next_payment() inconsistencies for subscriptions with multiple month billing periods.

### ISSUE THREAD

**Issue by messica** [strangerstudios/paid-memberships-pro#1007]
There are some inconsistencies with the "next payment date" and subscription profile start date when a subscription cycle = multiple months. This is because the subscription profile start date is calculated assuming each month = 30 days, while pmpro_next_payment() uses strtotime() instead:

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/gateways/class.pmprogateway_stripe.php#L1467

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/functions.php#L613

e.g.
1 Year = 365 $trial_period_days
12 Months = 360 $trial_period_days

We could use strtotime() to calculate the $trial_period_days instead to sync dates better. This might also solve issues when users try to set expiration dates for levels with recurring subscriptions.

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/renewing-early/

**Comment by dparker1005** [comment]
Issue in Stripe class is in `subscribe()` and `create_plan()` functions.

**Comment by selfsilent** [comment]
I hope the fix for this becomes a priority as I'm getting a lot of complaints from people being charged earlier than their renewal and before the T&C's say that they can cancel their renewal.
