### ISSUE TITLE
From Email and From Name are not filtered when 'Only Filter PMPro Emails?' is checked

### ISSUE THREAD

**Issue by mjulian87** [strangerstudios/paid-memberships-pro#1019]
The following two filters have no effect as they are never passed to wp_mail if 'Only Filter PMPro Emails?' is checked:
- pmpro_email_sender
- pmpro_email_sender_name

To reproduce:

- Set From Email and From Name in settings
- Check Only Filter PMPro Emails
- Send PMProEmail
- Output : 
  ["From"] => "wordpress@domain"
  ["FromName"] => "WordPress"

**Comment by mjulian87** [comment]
The two filters have no effect at all, regardless of whether 'Only Filter PMPro Emails?' is checked.

pmpro_getOption("from_email") and pmpro_getOption("from_name") work if 'Only Filter PMPro Emails?' is checked, however these don't work either if 'Only Filter PMPro Emails?' is uncheked.

**Comment by dparker1005** [comment]
Resolved here: https://github.com/strangerstudios/paid-memberships-pro/commit/f5f1734b2d5bacad4c0da98d0394ecfa7e905b7e
