### ISSUE TITLE
Bug: Membership cancellations for the daily Membership Stats report don't match those for the monthly report

### ISSUE THREAD

**Issue by LMNTL** [strangerstudios/paid-memberships-pro#1023]
**Describe the bug**
Membership cancellations for the daily Membership Stats report don't match those for the monthly report

**To Reproduce**
1. Go to Memberships -> Reports
2. Click on "Details" under "Membership Stats"
3. Change report type to "Monthly" and note number of cancellations in a specific month
4. Change report type to "Daily" for that month and see if the daily cancellations add up to monthly number

**Screenshots**
![image](https://user-images.githubusercontent.com/7819986/61659217-a2e7a600-ac8c-11e9-8fcd-6df93829078b.png)
![image](https://user-images.githubusercontent.com/7819986/61659371-ef32e600-ac8c-11e9-87d9-18da7181784e.png)

**Expected behavior**
Membership cancellations should be consistent from report to report. Possibly expected that monthly numbers would be lower than daily numbers due to not including duplicate cancellations over a longer period of time, but that doesn't appear to always be the case.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
```
Wordpress 5.2.2, PMPro 2.0.7, PHP 7.2.15-1
```
</details>

**Comment by kimcoleman** [comment]
I'm reviewing some old escalated tickets and as far as I can tell this remains an issue with the plugin and should be resolved. I do not know if the PR linked above full resolves this issue.

**Comment by kimcoleman** [comment]
I just did some spot checking and do not think this issue remains. Jason's update here: https://github.com/LMNTL/paid-memberships-pro/commit/24d91cd7398b1c09908c2b7865e56864636972d2 may be the correct fix and this issue may no longer persist.
