### ISSUE TITLE
Additional Filters for Levels table

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#1024]
**Is your feature request related to a problem? Please describe.**

The filter `pmpro_membership_levels_table` currently allows a complete custom build of the Membership Levels table under Memberships > Settings > Levels. Building a new table to accommodate an extra custom column is challenging and time-consuming.

**Describe the solution you'd like**

The ability to use a filter to add extra columns after "Allow Signups" and before the buttons for edit, copy and delete. As such it doesn't require a total table rebuilt and doesn't interfere with that easily with level ordering.

**Describe alternatives you've considered**

Build a custom Levels table replacing the excisting table with the `pmpro_membership_levels_table` filter.

**Additional context**
If applicable, add any other context or screenshots about the enhancement here.

**Comment by dparker1005** [comment]
Added actions here: https://github.com/strangerstudios/paid-memberships-pro/commit/4603049b0f3390c3b08571e0e2f3c0f8e840922e
