### ISSUE TITLE
BUG: "Expired/Old/Cancelled Members" filters in Members List do not show the most recent membership data for users with multiple membership records.

### ISSUE THREAD

**Issue by messica** [strangerstudios/paid-memberships-pro#1050]
**Describe the bug**
"Expired/Old/Cancelled Members" filters in Members List do not show the most recent membership records for users with multiple membership records. The "Expired" date shown on the list is from the oldest membership record.

**To Reproduce**
1. Go to 'Memberships > Members'
2. Click on 'Show: Expired Members'
3. See each member's oldest expiration date.

**Expected behavior**
The most recent expiration date should be shown for each member.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WP 5.2.2
PMPro 2.0.7
```
</details>

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/expired-members-list-doesnt-sort-by-most-recent-expiration-date/

**Comment by messica** [comment]
This gist is a workaround in the meantime:
https://gist.github.com/messica/a15c76e8900de12fc1dab3d6eef9976a

**Comment by dparker1005** [comment]
This behavior is no longer happening.
