### ISSUE TITLE
BUG: (v2.1-Beta1) Unhandled errors during Stripe checkout

### ISSUE THREAD

**Issue by LMNTL** [strangerstudios/paid-memberships-pro#1061]
**Describe the bug**
On v2.1-Beta1, receiving unhandled Stripe errors when checking out with some Stripe test cards which are set to fail transactions.

**To Reproduce**
1. Checkout with Stripe for a paid level using card 4000008260003178
(test card description: "This test card requires authentication, but payments will be declined with an insufficient_funds failure code after successful authentication.")
2. Complete SCA authentication when prompted
3. See unhandled Stripe error

**Stack Trace**
[22-Aug-2019 21:07:48 UTC] PHP Fatal error:  Uncaught Stripe\Error\Card: Your card has insufficient funds. in /srv/www/wordpress-two/public_html/wp-content/plugins/paid-memberships-pro-2.1-Beta1/includes/lib/Stripe/lib/ApiRequestor.php:214 from API request 'req_Z1mYZD3RrAn7AJ'
Stack trace:
#0 /srv/www/wordpress-two/public_html/wp-content/plugins/paid-memberships-pro-2.1-Beta1/includes/lib/Stripe/lib/ApiRequestor.php(173): Stripe\ApiRequestor::_specificAPIError('{\n  "error": {\n...', 402, Object(Stripe\Util\CaseInsensitiveArray), Array, Array)
#1 /srv/www/wordpress-two/public_html/wp-content/plugins/paid-memberships-pro-2.1-Beta1/includes/lib/Stripe/lib/ApiRequestor.php(473): Stripe\ApiRequestor->handleErrorResponse('{\n  "error": {\n...', 402, Object(Stripe\Util\CaseInsensitiveArray), Array)
#2 /srv/www/wordpress-two/public_html/wp-content/plugins/paid-memberships-pro-2.1-Beta1/includes/lib/Stripe/lib/ApiRequestor.php(126): Stripe\ApiRequestor->_interpretResponse('{\n  "error": {\n...', 402, Object(Stripe\Util\CaseInsensitiveArray))
#3 /srv/www/wordpre in /srv/www/wordpress-two/public_html/wp-content/plugins/paid-memberships-pro-2.1-Beta1/includes/lib/Stripe/lib/ApiRequestor.php on line 214

Note: also happening for test card 4000000000000341 ("Attaching this card to a Customer object succeeds, but attempts to charge the customer fail."), minus the SCA challenge step.

**Expected behavior**
User is returned to checkout page with relevant error displayed at top of page.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

```
WP 5.2.2, PHP 7.2.15, PMPro v2.1 beta (tested with this commit: https://github.com/strangerstudios/paid-memberships-pro/commit/b6d46b7cb7dd077ee12ac9a31356084f3b8171b0)
```
</details>

**Comment by messica** [comment]
fixed in https://github.com/strangerstudios/paid-memberships-pro/pull/1062
