### ISSUE TITLE
(v2.1-Beta1) TypeError: Cannot read property 'card' of undefined

### ISSUE THREAD

**Issue by mjulian87** [strangerstudios/paid-memberships-pro#1064]
**Describe the bug**
When checking out for a level with a zero initial payment, after completing the SCA authentication, checkout fails with the error:

````
Uncaught (in promise) TypeError: Cannot read property 'card' of undefined
    at stripeResponseHandler (pmpro-stripe.js?ver=2.1 Beta1:154)
````

**To Reproduce**
1. Setup level with zero initial payment
2. Checkout with Stripe for level using card 4000000000003220
3. Complete SCA authentication

**Expected behavior**
Checkout should complete successfully after SCA Authentication.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WP 5.2.2, PHP 7.1.3, PMPro v2.1 beta
</details>

**Comment by mjulian87** [comment]
It's not for free levels, it's for paying levels, with a 0 initial payment. Card isn't available in the SetupIntent. I have documented this in the pull request. #1068.

**Comment by dparker1005** [comment]
As there haven't been any reports of this behavior since the SCA launch in PMPro 2.1, I am going to close this issue. If you are still seeing this behavior on your site, please feel free to open a new issue and we can take a closer look at this there.
