### ISSUE TITLE
(v2.1-Beta1) pmproRequireBilling should be pmpro_require_billing in pmpro-stripe.js

### ISSUE THREAD

**Issue by mjulian87** [strangerstudios/paid-memberships-pro#1065]
**Describe the bug**
Incorrect naming convention used for pmpro_require_billing (pmproRequireBilling) in pmpro-stripe.js, which is preventing plugins (such as add paypal to checkout) from disabling billing and therefore preventing the checkout form from submitting.

Also should the value of pmpro_require_billing be defined in this file? It's changing the scope of the variable.

**Comment by mjulian87** [comment]
It's not just the naming convention. Because this code is now inside the document.ready block, the declaration creates a second variable with a different scope. It needs to be declared outside of the block or only by the Add Ons. Again, I have documented this in the pull request. #1068.

**Comment by dparker1005** [comment]
The work included in the PR that you linked to above was also included in this PR, which has been merged and released: https://github.com/strangerstudios/paid-memberships-pro/pull/1084
