### ISSUE TITLE
(v2.1-Beta1) Accept terms and conditions lost input after SCA validation

### ISSUE THREAD

**Issue by uno-de-piera** [strangerstudios/paid-memberships-pro#1074]
**Describe the bug**
When a customer click for purchase a subscription, if terms and conditions is active, the checkbox input lost the value and appears a validation error message for accept terms and conditions again.

Deactivating terms and conditions all works fine.

**To Reproduce**
1. Go to purchase a subscription
2. Click accept terms and conditions
3. Submit the form

**Screenshots**
![image](https://user-images.githubusercontent.com/4218670/64060458-fffc4300-cbcc-11e9-8059-1dcfa7f398ca.png)

![image](https://user-images.githubusercontent.com/4218670/64060468-199d8a80-cbcd-11e9-9d02-e7ddd760a264.png)

![image](https://user-images.githubusercontent.com/4218670/64060470-2c17c400-cbcd-11e9-8456-499d44950055.png)

**Expected behavior**
That the terms and conditions input be saved after SCA verification.

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.
- [ ] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).

**WordPress Environment**
```
PHP version: 7.0.33
WordPress Version: 5.2.2
Paid Memberships Pro: 2.1 BETA
```

**Comment by ideadude** [comment]
Just auto checking the TOS and not requiring users to recheck it. This is okay with current best practices.
