### ISSUE TITLE
Billing Fields Squashed on Members List Dashboard

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/paid-memberships-pro#1082]
https://www.paidmembershipspro.com/forums/topic/help-billing-address-fields-are-squashed/

![image](https://user-images.githubusercontent.com/22073464/64276324-f7e33100-cf47-11e9-926b-63f8256c9a28.png)

**Comment by tictag** [comment]
There is apparently no easy method of customising the widths of these columns (except using CSS) so this issue should be converted to a feature request with the following suggested content:

The Members List is an incredibly useful feature within PMPro but it can get a little ‘busy’ especially when some plugins add columns to the default layout. You end up with the Username column taking almost half the page and Expires ends up squashed at the end!

**This feature request is to add column width adjusters to each column head in the Members and Orders Lists.**

So no matter what the table contains at least the customer can choose how the table is presented to them, giving the customer choice.

This is a feature that is present on many web-based tables and, presumably, is reasonably easy to implement.

See screenshot above for an example of the table being ‘squashed’.

**Comment by kimcoleman** [comment]
This CSS update was made to improve the columns of the Members List: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/css/admin.css#L345-L351. I do not believe we will add support to adjustable column widths unless that become something offered in the core WordPress list table class.

**Comment by dparker1005** [comment]
As of PMPro v3.0, the billing address fields are no longer shown on the Members List
