### ISSUE TITLE
Stripe 3D Secure TOS broken

### ISSUE THREAD

**Issue by nikifoth** [strangerstudios/paid-memberships-pro#1083]
**Describe the bug**
We're using a Terms of Service on the checkout page, which appears unticked and throws an error after going through completing the authentication in 3D secure. This does not occur when using a non-3DS card. Box was definitely ticked before clicking the submit and checkout button and the same error is received on resubmission.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Checkout' page
2. Enter billing information and card details
3. Tick box to agree to TOS
4. Click 'Submit and Checkout'
5. Click 'Complete Authentication' on 3DS popup
6. Redirects back to page with error about TOS

**Expected behaviour**
If the TOS box is unticked before submitting the form, throw an error. However, if the box is indeed ticked after the 3DS authentication the checkout should complete.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WP 5.2.2, PHP 7.3.8, PMPro 2.1 Beta
</details>

**Comment by ideadude** [comment]
Fixed here https://github.com/strangerstudios/paid-memberships-pro/commit/55a06de243985fe362be6bfdcbe293797adbc4c8

Will go out in the beta2 release.
