### ISSUE TITLE
Expiration date can't be translated

### ISSUE THREAD

**Issue by GabrielHenriqueRS** [strangerstudios/paid-memberships-pro#1090]
**Describe the bug**
The expiration date is not ready for i18n.

**To Reproduce**
https://github.com/strangerstudios/paid-memberships-pro/blob/08a8761c9176ab7a48cd0d15f29e7bb6a39d65b6/shortcodes/pmpro_account.php#L82

**Screenshots**
![expiration-bug](https://user-images.githubusercontent.com/38798917/64564581-3dc53e00-d328-11e9-9061-128174cc6b5a.PNG)

**Expected behavior**
The date will translate to any language. To fix problem you must use the i18n date function (https://codex.wordpress.org/Function_Reference/date_i18n).

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
This is a crucial string because is an important information that is displayed directly for the user.
</details>

**Comment by andrewlimaza** [comment]
This has been released in 2.1.3.
