### ISSUE TITLE
Uncaught TypeError: jQuery(...).validateCreditCard is not a function

### ISSUE THREAD

**Issue by contemplate** [strangerstudios/paid-memberships-pro#1102]
Just updated a client's site to the latest v2.1 and now getting a Javascript error on every page of the site.  Client is using the Kleo theme.

For example here:
https://thebalancedlifeonline.com/tbl-sisterhood-waitlist/

It's coming from this file:
/wp-content/plugins/paid-memberships-pro/js/pmpro-checkout.js?ver=2.1

Why would this file even load on non-checkout pages?

**Comment by contemplate** [comment]
Ok fixed the issue.  Apparently you have to set a Checkout page in the PMPro settings.  We use WooCommerce for purchasing memberships so didn't have a checkout page set.

**Comment by zeusdesignco** [comment]
Our checkout page is already set and we are still receiving this error. Any ideas?
