### ISSUE TITLE
2.1 Stripe - No authentication when zero initial payment

### ISSUE THREAD

**Issue by mjulian87** [strangerstudios/paid-memberships-pro#1103]
The removal of the following code from `pmpro-stripe.js` prevents authentication from initiating when subscription has zero initial payment.

````
if ( 'undefined' !== typeof( pmproStripe.setupIntent ) ) {
	if ( 'requires_action' === pmproStripe.setupIntent.status ) {
		// On submit disable its submit button
		$('input[type=submit]', this).attr('disabled', 'disabled');
		$('input[type=image]', this).attr('disabled', 'disabled');
		$('#pmpro_processing_message').css('visibility', 'visible');
		$('#pmpro_processing_message').css('visibility', 'visible');

		stripe.handleCardSetup( pmproStripe.setupIntent.client_secret )
			.then( stripeResponseHandler );
	}
}
````

**Comment by ideadude** [comment]
I thought this was duplicated code. Nice catch. Adding it back.

**Comment by ideadude** [comment]
Added back here:
https://github.com/strangerstudios/paid-memberships-pro/commit/6239137351d8efa791c90443106eefbe76d80240

And then fixed my typo here: https://github.com/strangerstudios/paid-memberships-pro/commit/f8dd0eb34fd684799f814223523484dda292ca88

I'm again getting some "must check the tos box" errors during these tests that are likely unrelated, but FYI. Closing this issue. Thanks again!

**Comment by mjulian87** [comment]
I don't get the 'must check the tos box' error. If you can provide steps to replicate it, I'll take a look at it.

There is now an issue where if the authentication fails for the setup intent, the subscription is still created at Stripe. There was a todo note in the original `pmpro-stripe.js` suggesting that in this scenario, the subscription was going to be deleted via ajax, this hasn't been implemented.

**Comment by ideadude** [comment]
The TOS issue is related to this fix we added to PMPro core:
https://github.com/strangerstudios/paid-memberships-pro/commit/55a06de243985fe362be6bfdcbe293797adbc4c8

In my case, I also had the Multiple Memberships per User plugin activated, which has its own version of the checkout page template. I have pushed a fix out to that add on.

Any other plugin or theme that has a version of the checkout template with the old TOS code will need to make a similar update.

We might be able to think of a way to recheck the tos box (maybe through JS) for cases where templates aren't being updated. Not sure if we want to add that kind of hacky code to the plugin though.

**Comment by mjulian87** [comment]
You could hook into the checkout preheader and set the post var. Something like this:
````
add_action( 'pmpro_checkout_preheader_before_get_level_at_checkout', function() {

	if( isset( $_POST['customer_id'] ) ) {
		
		$_REQUEST['tos'] = 1;
	}
});
````
`customer_id` is appended to the form during the `else if ( response.paymentIntent || response.setupIntent )` block in `pmpro-stripe.js`, and this code block isn't reached unless the customer has previously checked the tos box.

The other option is to append to to the form inside the `else if ( response.paymentIntent || response.setupIntent )` block the same way the card details are appended.
````
form.append( '<input type="hidden" name="tos" value="1"/>' );
````
I think either of these are ok, as the code won't be reached unless the customer has previously checked the tos box.
