### ISSUE TITLE
Coupon Applied returned data is shown to the user

### ISSUE THREAD

**Issue by himanshuahuja96** [strangerstudios/paid-memberships-pro#1105]
**Discount Applied returned data is shown to the user**
When we apply the coupon code the data returned after the validation is directly shown to the user.

**To Reproduce**
1. Go to the 'Discounts code section and create a discount code'
2. Checkout for the level you want to test and apply the discount code
3. And now you can see the data which is returned by the validation controller is directly visible to the user.

**Screenshots**

![Imgur Image](https://i.imgur.com/Tjqmfk8l.png)

**Expected behavior**
It should not be visible to the end-user

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress 5.2.3 running Twenty Seventeen theme.
Running PHP version: 7.1.20

**Plugins Active**
Display PHP Version
Paid Memberships Pro - Version 2.1 
Paid Memberships Pro - Register Helper Add On - Version 1.4
WP File Manager

**Comment by ideadude** [comment]
Should be fixed here https://github.com/strangerstudios/paid-memberships-pro/commit/7c7fe2351ec83abc98dff7aad43b8546f3eb6f34

v2.1.1 is going out right now
