### ISSUE TITLE
SSL Seal Code field instructions are inaccurate

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#1115]
**Is your feature request related to a problem? Please describe.**
The instructions on this line imply that you can paste a JavaScript tag in the SSL Seal Code field on the Payment Settings page. This is not accurate as we do not allow script tags here.

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/adminpages/paymentsettings.php#L269

**Describe the solution you'd like**
The inline documentation / message should be updated and a link should be added to this guide to use a filter to show your seal: https://www.paidmembershipspro.com/show-your-ssl-seal-code-on-membership-checkout/

**Comment by dparker1005** [comment]
Instructions were fixed here to note that JS is not allowed: https://github.com/strangerstudios/paid-memberships-pro/commit/b8b5512395f038f3b6ed8459db853cefe7de9f6d
