### ISSUE TITLE
unable to change/cancel a user's membership

### ISSUE THREAD

**Issue by planetjon** [strangerstudios/paid-memberships-pro#1120]
**Describe the bug**
A logical error exists within pmpro_changeMembershipLevel() that prevents memberships from expiring/being changed/cancelled.

**To Reproduce**
1. Attempt to change a user's membership from the WP Admin panel's "Edit Profile"
2. Membership remains unchanged

**Expected behavior**
When a user's membership expires/is changed/is cancelled the user's membership is expected to updated accordingly.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WordPress 5.1.2

PHP 7.2.19-0

Ubuntu0.18.04.2

Paid Memberships Pro 2.1.1
</details>

**Comment by ideadude** [comment]
I can't reproduce this bug.

Are you using any of our add ons or other code? How are your levels set up?

The PR you made seems to change a check we have to tell if the pmpro_changeMembershipLevel function was called to change a user's level to the level they already have.

One note is that changing a user's expiration date doesn't cancel their membership right away. It won't cancel until the expire membership cron job gets run that night.

**Comment by planetjon** [comment]
Upon further investigation, there was an inconspicuous MU plugin in our environment that was off record. My apologies!
