### ISSUE TITLE
Enhancement: Membership account access for expired and cancelled members.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#1128]
**Is your feature request related to a problem? Please describe.**
When a user's membership has expired or is canceled they no longer have access to the membership account page to view their history and previous invoices.

**Describe the solution you'd like**
Make the Membership Account and Invoice Pages available for users who previously had a membership

**Describe alternatives you've considered**
Assigning a free level to all users who does not have a membership level.

**Additional context**
N/A.

**Comment by dparker1005** [comment]
This was added in PMPro v2.3.
