### ISSUE TITLE
Support MAXFAILEDPAYMENTS for PayPal Gateways.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#1130]
**Is your feature request related to a problem? Please describe.**
We should consider handling failed payment limits in core.

**Describe the solution you'd like**
Users would like to cancel user's membership levels if the user's recurring payments failed. We can  maybe set this to 2-3 failed payments and filterable?

**Describe alternatives you've considered**
Failed Payment Limit Add On.

**Additional context**
https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECRecurringPayments/#maximum-number-of-failed-payments

**Comment by mircobabini** [comment]
Commit to set MAXFAILEDPAYMENTS=1

0620227

Done.
