### ISSUE TITLE
BUG: "Now" subscription update creates payment immediately

### ISSUE THREAD

**Issue by messica** [strangerstudios/paid-memberships-pro#1136]
**Describe the bug**
Creating a "Now" subscription update cancels the current subscription and creates a new subscription with first payment charged immediately.

**Expected behavior**
Creating a "Now" subscription update should cancel the current subscription and create a new subscription with the same start date as the old subscription.

**Support Ticket (Mods only)**
https://www.paidmembershipspro.com/forums/topic/urgent-now-updates-creating-immediate-duplicate-charges-in-stripe/

**Comment by ideadude** [comment]
Pulled in that PR.

Notes from Jess' PR

> • This creates the new Subscription using the Customer’s default Payment Method instead of a specific Payment Method (because we don’t have payment information available from $_REQUEST during the update). This might cause issues if there is no default Payment Method set. We could fix this by getting the old Payment Method ID and setting it explicitly for the new Subscription.
> • Another way we could fix this is by changing the way Subscription Updates work in general. Stripe’s API does allow us to update Subscriptions so we could actually update it with 1 request instead of cancelling, creating a new Plan, and subscribing to the new plan. This might be the easiest and cleanest way to do Subscription Updates but I’m not sure if that might conflict with other code in another plugin, etc
