### ISSUE TITLE
Bug: Order Status is blank for "Free" checkouts 

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#1145]
**Describe the bug**
The invoice generated for a free level checkout does not have a status set in the database.

This results in inconsistent behavior on the frontend Member pages as well as the admin dashboard. It also will confuse Add Ons that hook into status, such as the Member History Add On.

This inconsistency/unset status occurs both when you have a primary gateway set or if you have the "Testing Only" / "Free" gateway as your primary setting under Memberships > Settings > Payment Gateway & SSL.

**To Reproduce**
1. Check out for a Free level in your membership site.
2. View your membership account - Invoice 'status' shows as 'Paid' (that doesn't make sense - it was free)
3. View your invoice - 'status' shows as 'success' <- That's ok. It's a fallback.
4. View the admin orders page - 'status' is blank in that row
5. View the individual order in admin - 'status' is not set in dropdown
6. View the database row for the order - 'status' is empty.

Note: This may require a database update script to clean up old orders.

<img width="423" alt="Screen Shot 2019-10-14 at 10 08 09 AM" src="https://user-images.githubusercontent.com/5312875/66758145-b8bfce00-ee6b-11e9-950f-d891a70228d3.png">

**Comment by dparker1005** [comment]
This was fixed in PMPro v2.2.
