### ISSUE TITLE
BUG: Undefined property: MemberOrder::$user error after updating to PMPro v2.1.3

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/paid-memberships-pro#1149]
**Describe the bug**
BUG: "Undefined property: MemberOrder::$user" error on Orders Page

**To Reproduce**
1. Orders Page
2. Hover on an order

**Screenshots**
![image](https://user-images.githubusercontent.com/22073464/66921903-58c15700-f026-11e9-9d2e-2d1a1ace8535.png)

**Comment by tictag** [comment]
**For MODS only**
Further information here: https://www.paidmembershipspro.com/forums/topic/bug-undefined-property-memberorderuser-error-after-updating-to-pmpro-v2-1-3/

**Comment by tictag** [comment]
I have re-tested this issue with PMPro v2.2.5 and this no longer occurs. Please feel free to close the issue.

**Comment by kimcoleman** [comment]
Thank you I am glad it is resolved.
