### ISSUE TITLE
Payment Gateway Agnostic PMPro Billing User metadata collection during Checkout

### ISSUE THREAD

**Issue by afaqk9394** [strangerstudios/paid-memberships-pro#1151]
Currently, like most people, I use both Paypal Express and Stripe as payment gateways. For Stripe, I have billing address (and shipping address) turned off. My WP user metadata is set to collect email, username, and password only (as dictated by the theme).

Issue: today, when checking out, User metadata collection depends on the payment gateway selection, i.e. depending on the payment gateway selection made by my customer, I end up getting two different set of PMPro user metadata.

Stripe: card/exp/cvc (If I turn on billing address verification, I end up getting billing user metadata via PMPro during checkout)
Paypal Express: None (There is no way to get any billing user metadata).

I think what would help is to have a consistent billing user metadata fields regardless of the payment gateway method selected or WP theme used. In order to avoid duplication with some WP themes that collect Names, you could simply offer addition of First Name/Last Name as optional for billing user metadata. I am aware of the First/Last Name add-on, but that doesn't solve the problem as those fields gets tagged on as WP user metadata and formatting is at the mercy of WP theme being used (in my case, they looked horrible).

Why is that an issue? Because email marketing platform, reporting and analytics depend on consistent user metadata regardless of the WP theme or payment gateway.

**Comment by dparker1005** [comment]
Hi @afaqk9394,

In your post, you mentioned that you considered using the First/Last Name add-on; however, it seem like our PMPro Capture Name & Address for Offsite Gateways Add On may be closer to what you are looking for: https://www.paidmembershipspro.com/add-ons/capture-name-address-free-levels-offsite-gateway/

That add on will cause the same billing fields to be shown on the PMPro checkout page regardless of the payment gateway being used.

**Comment by dparker1005** [comment]
Closing support ticket due to inactivity.
