### ISSUE TITLE
Submit and Checkout button

### ISSUE THREAD

**Issue by afaqk9394** [strangerstudios/paid-memberships-pro#1152]
IMO, it would make sense to simplify "Submit and Checkout" to just "Place Order".

**Comment by dparker1005** [comment]
Hi @afaqk9394,

As that string is localized, you can change its wording by using the `gettext` filter in custom code. We have an example of that being done here:
https://gist.github.com/strangerstudios/f5c63c89c0ebd44c9418
You can add this code recipe to your site by creating a custom plugin or using the Code Snippets plugin available for free in the WordPress repository. <a href="https://www.paidmembershipspro.com/create-a-plugin-for-pmpro-customizations/" target="_blank" rel="noopener noreferrer">Read this companion article for step-by-step directions on either method</a>.

**Comment by dparker1005** [comment]
Closing support ticket due to inactivity.
