### ISSUE TITLE
Repeated use of Trial membership (trial abuse) -How to Stop

### ISSUE THREAD

**Issue by afaqk9394** [strangerstudios/paid-memberships-pro#1157]
HI there

we are an online shop with all digital offering, access to all products is offered under One membership with two payments plans, monthly and annual charges. We also delay subscription charge by 3 days, and offer that as Trial period (using Subscription payment delay or Trial add-on).

How to stop trial abuse, where someone repeatedly subscribing and cancelling before trial period expires? I am hoping that there is an option within settings to stop a repeat subscriber who cancelled during the trial window from re-subscribing again within a given window of time (say once every 3, 6, 9 or 12 months).

Thanks

**Comment by ideadude** [comment]
We'd like to have better support for this built into the core plugin, but in the meantime, here are some posts on our site about offering trials just once:

https://www.paidmembershipspro.com/offer-trial-memberships-that-can-only-be-used-once/

https://www.paidmembershipspro.com/how-to-stop-members-from-renewing-their-membership-level/

**Comment by dparker1005** [comment]
As we have not heard back from you, we are going to close this Issue as this question appears to be resolved. If you are still having trouble with this, please feel free to open a ticket from our Member Support page and our support team can help you add this functionality to your site there: https://www.paidmembershipspro.com/support/
