### ISSUE TITLE
Duplicate Free Orders, each with unique code (!!potential for Denial of Service/DoS vulnerability!!).

### ISSUE THREAD

**Issue by afaqk9394** [strangerstudios/paid-memberships-pro#1166]
**Describe the bug**
a customer is able to create duplicate orders when using our Free plan ($0).

**To Reproduce Main Issue**
1. Set up and save a $0 plan.
2. Sign up using the plan with a given email.
3. Sign up using the plan with the given email as many times you want.
4. Notice duplicate orders in the Orders menu. Each new order has its own unique Code. 
5. Additionally, it results in multiple POSTs to Zapier, one for each unique Order which is simply a side-effect of above behavior.

Additional Issues:
1. Free Orders sometimes randomly show stripe as gateway, which is weird.
2. Free (as well as Paid) orders seem to have UTC timestamp which is consistent with how payment gateway work out the timestamps for transactions BUT PMPro Orders is for human consumption so should follow the Wordpress configured timezone for Order Date/Time stamping (just convert it to whatever Wordpress is configured with while retaining UTC in the logs/backend for debugging purposes with payment Gateways).

**Screenshots**
https://ibb.co/nf00V83

**Expected behavior**
One user (i.e. one email and one WP User ID #) should only be allowed to checkout a given Plan only once, duplicate orders with the same plan ID should not be allowed, I can't think of a reason why they should be but open to hear author's take. Multiple attempts simply should redirect the user to his Membership Confirmation page.

**WordPress Environment**
PHP 7.1
Latest wordpress and PMPro plugin versions (as of Nov 6 2019)
Latest Stripe Payment API version.

**Comment by dparker1005** [comment]
Hi @afaqk9394,

We have an article here which contains a code recipe to prevent users from checking out for a membership level that they already have: https://www.paidmembershipspro.com/how-to-stop-members-from-renewing-their-membership-level/

That code recipe should help to discourage this kind of behavior. If needed, that code recipe can also be further modified to prevent the user from checking out if they have ever had that membership level before, though this would require custom development to implement.

**Comment by andrewlimaza** [comment]
While you can "spam" this by navigating back to the checkout after confirmation and processing the free checkout again. I recommend in setting up the article David shared as well as anti-spam efforts by following this guide as well - https://www.paidmembershipspro.com/protect-membership-site-spam-abuse-using-recaptcha/.
