### ISSUE TITLE
Free level cost text not filterable on Levels page.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#1173]
**Describe the bug**
The levels page cost text is not filterable if the level is free.

**To Reproduce**
1. Use Custom Level Cost Text/Filter to adjust pricing for a free level.
2. Go to level select page, wording should still be default "Free".

**Screenshots**
The screenshot example should replace all instances of cost text for all levels but only affects non-free levels.

<img width="797" alt="Screen Shot 2019-11-18 at 16 49 33" src="https://user-images.githubusercontent.com/12629136/69062405-8a617f80-0a23-11ea-9240-01c3cc2884bf.png">

**Expected behavior**
Level cost text should be filterable.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by dparker1005** [comment]
Fixed here: https://github.com/strangerstudios/paid-memberships-pro/commit/ef5b29e278a8c4cd2d7dc5b32e31095f04971b1f
