### ISSUE TITLE
WP timezone changing expiration months

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/paid-memberships-pro#1174]
**Describe the bug**
Changing the timezone in WordPress general settings seems to be able to offset PMPro expiration dates by a month.

With quick testing, this is what I've seen:
American timezone --> European timezone : Expiration dates are a month sooner
European timezone --> American timezone : Expiration dates are a month later

**To Reproduce**
1. Make a note of one of your user's expiration dates
2. Go to WordPress general settings
3. Change timezone (not sure exactly which ones cause this error, may need some trial and error)
4. Check if user's expiration date has been modified by a month

**Expected behavior**
Expiration date should not change based on the timezone

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Admins**
Tickets that may have this issue (both of these have seen the month be modified upon saving the user's "Edit User" page after setting an expiration date):
https://www.paidmembershipspro.com/forums/topic/issue-when-creating-a-user-and-adding-a-membership-level-and-mailchimp/
https://www.paidmembershipspro.com/forums/topic/expires-date-going-haywire/

**Comment by dparker1005** [comment]
WP 5.3 changelog blog post: https://wordpress.org/support/topic/read-this-first-wordpress-5-3-master-list/#post-12124062

`Dates or times being incorrect, permalinks being off by a day, other weirdness related to “time”

WordPress 5.3 received a significant upgrade to its date and time handling code. The previous code dated all the way back to over 10 years ago, when PHP 4 was still supported. This was a significant chunk of code scattered all through the core of WordPress, and it was very slow and a drag on performance.

With 5.3, most of this code has been updated or replaced with saner PHP 5.6 compatible code. A lot of the legacy has been removed. However, some plugins and themes may have relied on the side effects from how this code previously operated.

For this reason, some plugins or themes may be doing incorrect things. One such thing would be to call the date_default_timezone_set() function in PHP. WordPress works by setting the default timezone to UTC and then performing its own calculations to adjust times. Setting the default timezone incorrectly to anything else will result in these calculations being incorrect. WordPress will be overcompensating the timezone adjustments.

For backwards compatibility, it is crucial that plugins *not* change the default PHP timezone. The default timezone must be set to UTC at all times. Any problems you find with timezones or dates shifting is likely going to be a plugin or theme which is doing-it-wrong. This may not have mattered as much in previous versions of WordPress, but now that WordPress is using these newer functions more and less reliant on the old PHP 4 compatible code, then this is far more critical.

If you find a plugin or theme with a problem like this, please report it to their authors, or report it to the plugins team.`

**Comment by dparker1005** [comment]
Further testing shows that, when European time zone is set, months would list in the order "December, January, February, March, etc" instead of starting with January. This made December index 1, January index 2, etc.

I believe that this PR should show why this is the case and resolve this issue: https://github.com/strangerstudios/paid-memberships-pro/pull/1177

**Comment by arnalyse** [comment]
I have fixed the timezone calculation according to the new timezone handling introduced in WordPress 5.3

I will try to do a pull request for this.

**Comment by arnalyse** [comment]
I created this this pull request. Hope it helps :) #1217
