### ISSUE TITLE
Adding a custom column content to the new memberlist table cannot be done using the new filters.

### ISSUE THREAD

**Issue by aquiferweb** [strangerstudios/paid-memberships-pro#1184]
**Describe the bug**
Using the new filters 'pmpro_memberslist_extra_cols' and 'pmpro_members_list_user' it should be possible to add extra columns to the member list table - but the content is not being shown.

**To Reproduce**

1. Add a new column via a custom plugin and the filter pmpro_memberslist_extra_cols: 
```
function pp_memberslist_extra_cols_header($columns){
	$columns['parish'] = "Parish Name";
	return $columns;
}
add_filter('pmpro_memberslist_extra_cols','pp_memberslist_extra_cols_header',10,1);
```
2. Add content for the column using pmpro_members_list_user filter:
```
function pp_memberslist_extra_cols_body($item){
	if(get_user_meta($item->ID, "parishname", true))  $item->parish = get_user_meta($item->ID, "parishname", true);
	return $item;
}
add_filter('pmpro_members_list_user','pp_memberslist_extra_cols_body',10,1);
```
3. Column appears in table but content doesn't.

This is almost certainly due to the 'default' column name case in paid-memberships-pro\classes\class-pmpro-members-list-table.php using $item->$column_name instead of $item[$column_name]  in the column_default function.

**Comment by ideadude** [comment]
2 things to get this working. Let me know if this helps.

1. You will want to use the pmpro_memberslist_extra_cols_body action. You have

`add_filter('pmpro_members_list_user','pp_memberslist_extra_cols_body',10,1);`

Should be:

`add_Action('pmpro_memberslist_extra_cols_body','pp_memberslist_extra_cols_body',10,1);`

2. You will need the callback then to echo the content you want to show up in the table row. Also, make sure that that content starts with a <td> and ends with a </td>. That was expected before. The code to keep these old filters working needs to strip the td tag away, but as coded if there is no td tag, it won't show any content. We can look into that, but any old code that didn't have a td wouldn't have been showing anyway.

You should also be able to use the WP core List Table filters to add columns and data. We should write up an example of that on our blog, but it would basically be the same as other tutorials on doing that for a post list or user list, but check for our type of table instead.

I hope this helps.
