### ISSUE TITLE
Member search

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#1188]
**Describe the bug**
Members List page not returning any member search results in PMPro V2.2.1

**To Reproduce**
1. Go to Memberships > Members
2. Fill in a user name, first name, or email address of an existing user in the search box
3. Click on 'Search Members'
4. "No members found" returned 

**Expected behavior**
A list of members returned that fulfills the search criteria entered.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress 5.3
PMPro 2.2.1
PHP 7.3.2
MySQL 5.6.34

**Comment by ideadude** [comment]
Fixed here https://github.com/strangerstudios/paid-memberships-pro/commit/b62b62d87509d4a994d2a6493e45e55628fe9c86
