### ISSUE TITLE
recaptcha.php: May push HTML during CRON & AJAX operations

### ISSUE THREAD

**Issue by eighty20results** [strangerstudios/paid-memberships-pro#1189]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed or left unattended.

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/recaptcha.php#L4-L6

Should probably be: 

`
	//don't load in admin, during AJAX operations or while executing WP cron

	if ( is_admin() ||
         ( defined( 'DOING_AJAX' ) && DOING_AJAX ) ||
         ( defined( 'DOING_CRON' ) && DOING_CRON ) ) {
		return;
	}`

**Comment by dparker1005** [comment]
We now only load reCAPTCHA if the user is on the checkout page: https://github.com/strangerstudios/paid-memberships-pro/commit/3dc95acb06e131efca128208b6a22ec0f77f6a1d
