### ISSUE TITLE
Incorrect Members List queries

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/paid-memberships-pro#1207]
**Describe the bug**
There are two issues that should be addressed at the same time:
1. The member count displayed in the Members List may bee too high
2. Members list will show the oldest enddate for a user rather than the most recent for old users

**To Reproduce**
1. Find a user who has had multiple memberships in the past, but is now an old user
2. Navigate to `Memberships > Members` and change the "Show" dropdown to "Old Members"
3. Count the number of members shown and see that it is fewer than the number shown next to the search bar (Issue 1)
4. Find your user from step 1 and see that their enddate is the oldest of all their memberships instead of the most recent enddate (Issue 2)

**Expected behavior**
Count should be equal to the number of members shown and enddate for old members should be the most recent enddate

See proposed fix from PMPro customer:
<img width="1168" alt="Screen Shot 2020-01-07 at 1 39 27 PM" src="https://user-images.githubusercontent.com/24977505/71920738-6f72d800-3155-11ea-85e1-9f9c6dce74ac.png">
Original ticket (admins only): https://www.paidmembershipspro.com/forums/topic/incorrect-expiration-date-and-number-of-members-in-the-members-table/

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by andrewlimaza** [comment]
Thanks @dparker1005 I also noticed when you search it gives the wrong count values. I have 4 members, but when searching it will return a number like 71 and have 4 pages pagination.

<img width="1252" alt="Screen Shot 2020-01-22 at 13 32 03" src="https://user-images.githubusercontent.com/12629136/72890900-a8957580-3d1b-11ea-8254-cb53a6f8cd24.png">
