### ISSUE TITLE
Cancelling a PayPal Express Subscription at PayPal can result in "error cancelling" email.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#1208]
When our PayPal class is asked to cancel a subscription, we check here if we’re processing an IPN request to try to avoid double cancels like this.

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/gateways/class.pmprogateway_paypalexpress.php#L763-L766

But notice that our check is for the subscr_id. That is what PayPal Standard uses. PayPal Express uses the recurring_payment_id variable. So we need to check for that too.

We also need to update the same method in the PayPal class as we do in the PayPal Express class in case that one is loaded first (the 2 classes share a lot of code).

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/gateways/class.pmprogateway_paypal.php#L677

**Comment by tictag** [comment]
For further info, screenshots etc (**mods only**) see - https://www.paidmembershipspro.com/forums/topic/bug-pmpro-core-paypal-ipn-handling
