### ISSUE TITLE
Error not showing when editing discount page: Stripe integration currently does not support trial amounts greater than $0

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/paid-memberships-pro#1214]
**Describe the bug**
When a user is editing a level, the gateway is set to Stripe, and the "Custom Trial" checkbox is checked, a notice appears to warn them that Stripe does not support paid trials:
`Stripe integration currently does not support trial amounts greater than $0`

This notice is not shown when editing a discount code, who would otherwise not know of this limitation

**To Reproduce**
1. Set payment gateway to Stripe
2. Create a new discount code
3. Check "Recurring Subscription" and "Custom Trial"
4. See that there is no notice shown

**Expected behavior**
User should be notified that paid trials are not supported by Stripe while editing discount code

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Please share non-sensitive information about your hosting environment such as WordPress version, PHP version, Paid Memberships Pro and any related plugins versions.
```
</details>

**Comment by kimcoleman** [comment]
There's another "general" issue about this - it is true of all gateways AFAIK. 

https://github.com/strangerstudios/paid-memberships-pro/issues/1119

Do you want to close this one and provide more details on the other ticket?

**Comment by dparker1005** [comment]
Ah thanks! Missed that Issue.

Closing this duplicate issue.
