### ISSUE TITLE
User reported error in code

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/paid-memberships-pro#1222]
line 28 Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/web/staging/public_html/wp-content/plugins/paid-memberships-pro/includes/lib/name-parser.php on line 134
https://www.paidmembershipspro.com/forums/topic/i-found-an-error-code/#post-237923

**Comment by dparker1005** [comment]
Fixed here: https://github.com/strangerstudios/paid-memberships-pro/commit/17d106d3c2dda01dfa50f6f49dfc0ed2220e44c5
