### ISSUE TITLE
User reported error in code

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/paid-memberships-pro#1224]
Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /var/web/staging/public_html/wp-content/plugins/paid-memberships-pro/includes/lib/Stripe/lib/ApiRequestor.php on line 402

**Comment by dparker1005** [comment]
Stripe API updated in June 2020. Updated `ApiRequestor.php` does not call `array_key_exists()`.
