### ISSUE TITLE
Before and After Change Membership Level hook Argument Count Error

### ISSUE THREAD

**Issue by ajfick** [strangerstudios/paid-memberships-pro#1237]
**Describe the bug**
Using the `pmpro_after_change_membership_level` or `pmpro_before_change_membership_level` hooks, the arguments according to documentation should consist of `$level_id`, `$user_id` and `$cancel_level` according to documentation [here.](https://www.paidmembershipspro.com/hook/pmpro_after_change_membership_level/) However, configuring more than one argument for your hook will throw an ArgumentCountError as only 1 argument seems to be passed to that action, `$level_id`.

**To Reproduce**
1. Use either of the two hooks above as described in the documentation linked above (with 3 arguments).
2. Change a user's membership level
3. See Too Few Arguments error.

**Screenshots**
The `add_action` call (using wppb plugin boilerplate, which works for all other hooks I've used thus far)
<img width="975" alt="add_action" src="https://user-images.githubusercontent.com/19314419/74700959-35283c00-51d3-11ea-8860-3910c0425a31.png">

The callback function test. This is as described in the documentation, with 3 arguments. this function is within the `Sendgrid` class that can be seen as the variable in the above image.
<img width="822" alt="callback" src="https://user-images.githubusercontent.com/19314419/74700855-ea0e2900-51d2-11ea-90f1-a7e6c948b3c0.png">

Error thrown because only one argument is passed.
<img width="799" alt="Too Few Arguments" src="https://user-images.githubusercontent.com/19314419/74700935-2477c600-51d3-11ea-8535-31d87896eabc.png">

**Expected behavior**
I would expect that either the 3 arguments that are outlined in the docs are passed to my function when invoking the `pmpro_after_change_membership_level` hook, or that the docs should be changed to reflect that only the `$level_id` argument is passed.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
PHP Version: 7.3
Wordpress Version: 5.3.2
PMPro Version: 2.2.5
```
</details>

**Comment by andrewlimaza** [comment]
Please can you pass through `3` parameters when calling this hook, for example: `add_action( 'pmpro_after_change_membership_level', 'my_callback', 10, 3 );`

This should resolve your issue.

**Comment by ajfick** [comment]
@andrewlimaza 🤦‍♂ Thanks.
