### ISSUE TITLE
Support Page Builder "Element"-level Membership Restriction 

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#1239]
**Is your feature request related to a problem? Please describe.**
We've recently added element-level restrictions in the Elementor module. Other builders, such as Divi or Beaver Builder, would benefit from similar logic.

**Describe the solution you'd like**
Extend the "/includes/compatibility" files to support element-level membership requirements.

**Describe alternatives you've considered**
The current workaround to nest your builder element between two [membership] shortcodes does not always work and is clunky.

**Comment by CadvanceDes** [comment]
I have Beaver Builder and would love element-level restrictions. I'm currently using an elegant modules plugin which does this via rows but a PMPro Plugin for modules would be great!! Thanks

**Comment by kimwhite** [comment]
In Divi, I believe these are called "Modules" https://astucesdivi.com/en/liste-modules-divi/.

**Comment by ideadude** [comment]
We've done this for a number of builders now, so closing the issue. But if you'd like us to add or update compatibility for a specific builder, please open a new issue with as much information as possible. Thanks.
