### ISSUE TITLE
Paywall message gets injected in footer as opposed to the body.

### ISSUE THREAD

**Issue by KopanoM** [strangerstudios/paid-memberships-pro#1253]
<img width="423" alt="error1" src="https://user-images.githubusercontent.com/26299690/75357486-20763300-58ba-11ea-8af8-b165a80734b5.PNG">
**Describe the bug**

When I try to use the paid membership pro plugin for my WordPress website the message that is supposed to be shown to users who are Logged out gets injected in the footer. I am not sure if there is a plugin that is clashing with my website or if this is a bug on the paid memberships part. I am using a pro account. 

**To Reproduce**
1. Go to paid membership - settings - advanced settings
2. Where it says message for logged in users and logged out users I put some the text I would like to use to remind my users to subscribe to my site. 
3. When I check the live website the message has been placed in the footer and has replaced my default footer. 
<img width="894" alt="actual footer" src="https://user-images.githubusercontent.com/26299690/75356495-b27d3c00-58b8-11ea-9e45-b82ef2c345e8.PNG">

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
I am also using the Newspaper template.
The wordpress version I am using is 5.3.2
The WordPress plugins I am using are listed.

Activity Log
Advanced Ads
AMP
Co-Authors Plus
Duplicate Post
Easy WP SMTP
Login No Captcha reCAPTCHA (Google)
Paid Memberships Pro
Paid Memberships Pro - Add Member From Admin
Paid Memberships Pro - Email Confirmation Add On
Paid Memberships Pro - Limit Post Views Add On
Paid Memberships Pro - PayFast Gateway
Paid Memberships Pro - Reports Dashboard Add On
Paid Memberships Pro - Shipping Add On
tagDiv Cloud Library
tagDiv Composer
tagDiv Mobile Theme
tagDiv Newsletter
User Role Editor
WP-Stateless
WPForms
WPForms User Registration
Yoast SEO

--

--

<details>
```
Please share non-sensitive information about your hosting environments
<img width="423" alt="error1" src="https://user-images.githubusercontent.com/26299690/75356505-b5782c80-58b8-11ea-8b37-5ea1ee0dd3b8.PNG">
 such as WordPress version, PHP version, Paid Memberships Pro and any related plugins versions.
```
</details>

**Comment by dparker1005** [comment]
Hi @KopanoM,

Is this an issue that you are still seeing on your site? If so, can you please confirm where the "You've hit the limit!" text is coming from? Was that the text that was set as your message for logged out users on the Advanced Settings page?

If you would like to test whether this is a conflict with your theme or with other plugins on your site, I would recommend temporarily setting your website to a default WordPress theme, disabling all non-PMPro plugins, and then testing whether the issue still occurs.

**Comment by KopanoM** [comment]
Hi Dparker, the issue was resolved thanks
