### ISSUE TITLE
Umlaute (Ä,Ö,Ü) are Displayed as Questionmarks in Mails 

### ISSUE THREAD

**Issue by dipiana** [strangerstudios/paid-memberships-pro#1263]
**Describe the bug**
When receiving the german confirmation mail, umlauts are displayed as questionmarks.

**To Reproduce**
1. Set language to German
2. Buy a membership
3. See German confirmation mail with questionmarks

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.
![image](https://user-images.githubusercontent.com/7633078/75777562-7c2b3b00-5d56-11ea-9cf0-a00f3f45f268.png)

**WordPress Environment**
<details>
```
WordPress with WPML and PMpro - everything up to date.
```
</details>

**Comment by vsatmydynipnet** [comment]
They have ISO-8859-1 char set and use utf8 in mail. Run this on the german language mail files and all is good.

#!/bin/bash
# You just have to run it with the name of the file to convert, or using wildcards:
# $ 2utf8.sh *.sql

if [ $# -lt 1 ]
then
  echo "Use: "$0" <file_name>"
  echo "Convert files from ISO-8859-1 to UTF8"
  exit
fi

for i in $*
do
  if [ ! -f $i ]; then # Only convert text files
    continue
  fi
  # Generate temp file to avoid Bus error
  iconv -f ISO-8859-1 -t utf-8 $i -o $i.tmp
  mv $i.tmp $i
done

**Comment by ideadude** [comment]
Emails are now stored as strings in a php file and shouldn't have this problem anymore. Thanks again for the heads up and info to fix the older versions of PMPro.
