### ISSUE TITLE
Enhancement: Allow Per Level Checkout Options in Shortcode

### ISSUE THREAD

**Issue by ronalfy** [strangerstudios/paid-memberships-pro#1265]
**Is your feature request related to a problem? Please describe.**
User would like a dedicated checkout page for a particular level.

**Describe the solution you'd like**
Allow a level in the `pmpro_checkout` shortcode for level-specific shortcode output.

**Describe alternatives you've considered**
Can create a custom checkout template page, but that wouldn't be flexible on a level-specific context.

**Comment by dparker1005** [comment]
You can set up a redirect from your custom checkout page to the custom checkout page with the `level` parameter set in the URL. This will set the level for the checkout process.
