### ISSUE TITLE
Checkout: Country div inside bfirstname div

### ISSUE THREAD

**Issue by nbatch** [strangerstudios/paid-memberships-pro#1273]
**Describe the bug**
Within the checkout fields the Country select box is located with the FirstName div

**To Reproduce**
1. Visit membership checkout page
2. Inspect element

**Screenshots**
![Screenshot from 2020-03-19 15-01-41](https://user-images.githubusercontent.com/2873824/77081540-b81afd00-69f2-11ea-9018-a3fda9597724.png)

**Expected behavior**
This should be in it's own pmpro_checkout-field div

**WordPress Environment**
WordPress 5.3.2
PMP 2.2.6

**Comment by kimcoleman** [comment]
This placement of the country field is not part of core Paid Memberships Pro, but rather our State Dropdowns Add On. There is an existing Issue and open Pull Request to resolve this here: https://github.com/strangerstudios/pmpro-state-dropdowns/issues/26 and https://github.com/strangerstudios/pmpro-state-dropdowns/pull/27

**Comment by nbatch** [comment]
@kimcoleman Ah. I didn't realise it was from the plugin. I'll subscribe to that. Many thanks.
