### ISSUE TITLE
Emails in Languages Folder Need UTF-8 Encoding

### ISSUE THREAD

**Issue by ronalfy** [strangerstudios/paid-memberships-pro#1276]
**Describe the bug**

Files not encoded in UTF-8, particularly for the German language, are not showing special characters.

**To Reproduce**
1. Open files /languages/emails/de_DE/*
2. Observe the special characters are turned into question marks.

**Screenshots**

![utf8_issue](https://user-images.githubusercontent.com/636521/77346956-0f77e080-6d05-11ea-912e-056a631a1831.png)

**Expected behavior**

Files in other languages should show the correct characters.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by dparker1005** [comment]
Closing in favor of https://github.com/strangerstudios/paid-memberships-pro/issues/1263
