### ISSUE TITLE
Index Column size too large error 

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/paid-memberships-pro#1335]
**Describe the bug**
NOTICE: PHP message: WordPress database error Index column size too large. The maximum column size is 767 bytes. for query
CREATE TABLE `ace_pmpro_membership_levels` (
`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
`name` varchar(255) NOT NULL,
`description` longtext NOT NULL,
`confirmation` longtext NOT NULL,
`initial_payment` decimal(18,8) NOT NULL DEFAULT ‘0.00’,
`billing_amount` decimal(18,8) NOT NULL DEFAULT ‘0.00’,
`cycle_number` int(11) NOT NULL DEFAULT ‘0’,
`cycle_period` enum(‘Day’,’Week’,’Month’,’Year’) DEFAULT ‘Month’,
`billing_limit` int(11) NOT NULL COMMENT ‘After how many cycles should billing stop?’,
`trial_amount` decimal(18,8) NOT NULL DEFAULT ‘0.00’,
`trial_limit` int(11) NOT NULL DEFAULT ‘0’,
`allow_signups` tinyint(4) NOT NULL DEFAULT ‘1’,
`expiration_number` int(10) unsigned NOT NULL,
`expiration_period` enum(‘Day’,’Week’,’Month’,’Year’) NOT NULL,
PRIMARY KEY (`id`),
KEY `allow_signups` (`allow_signups`),
KEY `initial_payment` (`initial_payment`),
KEY `name` (`name`)
)

**To Reproduce**
MySQL8 was the problem

**WordPress Environment**
PMpro 2.2.6, WP 5.4, MySQL 8. PHP 7.4

**Comment by dparker1005** [comment]
Not enough information to replicate.
