### ISSUE TITLE
Notices of undefined index in $_SESSION when PayPal Express session is lost

### ISSUE THREAD

**Issue by mircobabini** [strangerstudios/paid-memberships-pro#1341]
**Describe the bug**
Happens when the PayPal Express session is lost for any reason.
```
PHP Notice:  Undefined index: pmpro_signup_username in /wp-content/plugins/paid-memberships-pro/classes/gateways/class.pmprogateway_paypalexpress.php on line 418
PHP Notice:  Undefined index: pmpro_signup_password in /wp-content/plugins/paid-memberships-pro/classes/gateways/class.pmprogateway_paypalexpress.php on line 419
PHP Notice:  Undefined index: pmpro_signup_email in /wp-content/plugins/paid-memberships-pro/classes/gateways/class.pmprogateway_paypalexpress.php on line 420
```

**To Reproduce**
1. Go to checkout page
2. Click on proceed (with PayPal Express)
3. Copy the paypal.com link and complete the checkout in anonymous mode (session is empty for sure)
4. See error in logs

Or any other CASE listed in issue [#1338](https://github.com/strangerstudios/paid-memberships-pro/issues/1338).

**Expected behavior**
Check if the session is still there. If not... well, damn it. Big issue :) Follow [#1338](https://github.com/strangerstudios/paid-memberships-pro/issues/1338)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
All at its latest.

**Comment by dparker1005** [comment]
The real solution is to better handle information when the user is sent to PayPal (https://github.com/strangerstudios/paid-memberships-pro/issues/1338). I am labeling this issue as if the request was just to handle the notices. The quick solution here is to wrap those in a `! empty()` before trying to access session contents.
