### ISSUE TITLE
Order date shifter ahead on success

### ISSUE THREAD

**Issue by mircobabini** [strangerstudios/paid-memberships-pro#1351]
**Describe the bug**
Every time a order is marked as "success", it's datetime is shifted in the future of 4 hours.

**To Reproduce**
Create an order and pay for it.

**Screenshots**
[screenshot loaded on snag.gy](https://i.snipboard.io/h7U94J.jpg)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by dparker1005** [comment]
There have been a number of updates since this bug report that have fixed various timestamp bugs in PMPro. Can you please confirm whether this behavior is still happening?

**Comment by mircobabini** [comment]
It's gone. :) Closing the issue.
