### ISSUE TITLE
Inconsistent enddates

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/paid-memberships-pro#1353]
**Describe the bug**
There are 2 main issues here:
1. End date can show different dates on different pages. Example:
- 2020-05-28 00:00:00 on the database
- 27/05/2020 on the Members list
- May 28 2020 on the Expires in Edit User
- 28/05/2020 on the membership history on Edit User
2. When someone renews an annual membership with the times above, they could lose a day of membership (ex the math that calculates new enddate could change sql enddate to 2021-05-27 10:28:58).

User experiencing this issue (admins only): https://www.paidmembershipspro.com/forums/topic/membership-start-date-showing-as-today/

**Expected behavior**
Enddates should be shown consistently across PMPro.

**Proposed solution**
Tracking time in addition to just date should help to make these dates more clear. By allowing users to see and edit the time of an enddate, both the Edit User and Member History pages would show the same date/time as the Members List, which is ultimately the way that we would want the enddate to be displayed (even though it would't necessarily be consistent with the database).

Saving the time at checkout would also allow for us to do better math while extending the enddate on renewal, and in the long run allow us to implement memberships with more specific enddates (such as 12 hour memberships).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by 360fun** [comment]
I have the same problem! every time I update a profile I lose a day 🤯
I have always to remember to put +1 day in order to prevent this...I tried to debug a bit but didn't find the problem. 🤔
I'm probably going to add `strtotime('+1 day', $timestamp);` to temporarily fix it.

**Comment by dparker1005** [comment]
This issue should now be resolved on the backend Edit User page, meaning that the losing a day on profile save issue should no longer occur; however, there still may need to be changes made to the Members List and Membership History add-on to convert timestamps correctly.

**Comment by mircobabini** [comment]
Connecting these 2 issues. #1406

**Comment by dparker1005** [comment]
PMPro 2.3-2.4 fixed a lot of timestamp/timezone related bugs. PMPro should no longer be affected by the timezone set for the site's server or database, and timestamps should be shown consistently across the site.
