### ISSUE TITLE
Cannot delete orders (Italian string / JS problem)

### ISSUE THREAD

**Issue by 360fun** [strangerstudios/paid-memberships-pro#1357]
With the Italian language active, the delete order doesn't work: the problem is the **apostrophe** which breaks the JS function "pmpro_askfirst" call.

**To Reproduce**
1. Set Italian language
2. Go to 'Membership > Orders'
3. Click on 'Elimina'
4. You cannot delete the entry

**Screenshots**
![image](https://user-images.githubusercontent.com/844090/83309494-b5fec700-a209-11ea-9301-5396549156e4.png)

**JS Problem**
![image](https://user-images.githubusercontent.com/844090/83274371-022c1600-a1ce-11ea-8000-929f4890a601.png)

**Comment by 360fun** [comment]
temporary JS fix:

jQuery(document).ready(function($) {
	$('#orders .delete a').each(function(a,b){
		b.href = b.href.replace("L\'","L\\'");
		b.href = b.href.replace("l\'","l\\'");
	});
});

**Comment by andrewlimaza** [comment]
I have submitted a Pull Request that should fix this issue @360fun, please feel free to test this. - https://github.com/strangerstudios/paid-memberships-pro/pull/1475

**Comment by 360fun** [comment]
thanks!
