### ISSUE TITLE
Please make the "now" after the price optional: it can be misleading in some languages

### ISSUE THREAD

**Issue by 360fun** [strangerstudios/paid-memberships-pro#1362]
In Italian is very confusing to read "200€ ora.", sounds like "200€ per hour" ("ora" = "now" and "hour" in Italian)! Please remove also the "." in the short version.

![image](https://user-images.githubusercontent.com/844090/83643780-bf44b680-a5b0-11ea-812f-31d41fa44068.png)

**ORIGINAL CODE (partial)**
```
function pmpro_getLevelCost( &$level, $tags = true, $short = false ) {
	// initial payment
	if ( ! $short ) {
		$r = sprintf( __( 'The price for membership is <strong>%s</strong> now', 'paid-memberships-pro' ), pmpro_formatPrice( $level->initial_payment ) );
	} else {
		$r = sprintf( __( '<strong>%s</strong> now', 'paid-memberships-pro' ), pmpro_formatPrice( $level->initial_payment ) );
	}
```

**PROPOSED CHANGE (partial)**
```
function pmpro_getLevelCost( &$level, $tags = true, $short = false, $now = true ) {
$_now = $now ? " now" : "";
	// initial payment
	if ( ! $short ) {
		$r = sprintf( __( 'The price for membership is <strong>%s</strong>'.$_now, 'paid-memberships-pro' ), pmpro_formatPrice( $level->initial_payment ) );
	} else {
		$r = sprintf( __( '<strong>%s</strong>'.$_now, 'paid-memberships-pro' ), pmpro_formatPrice( $level->initial_payment ) );
	}
```

**Comment by kimcoleman** [comment]
You can use the Custom Level Cost Text Add On to adjust how your price statements appear. See: https://www.paidmembershipspro.com/add-ons/pmpro-custom-level-cost-text/

**Comment by 360fun** [comment]
with this answer seems like that you don't want to improve your software: in Italian is just wrong how it appears at the moment...but nice to know there's a work around.
