### ISSUE TITLE
Discount Code Isn't Stored When Using 2Checkout

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/paid-memberships-pro#1368]
**Describe the bug**
When using a discount code with the 2Checkout Payment Gateway, the code is applied to the level during checkout and works as expected, however it isn't stored in the order

**To Reproduce**
1. Create a discount code
2. Checkout using the discount code
3. The billing amounts will be adjusted as expected and will be billed correctly through 2Checkout
4. While the payment has gone through and the order is a success, the discount code isn't saved to that order

**Expected behavior**
The discount code used should show up on that order

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress 5.4.2
- PMPro 2.3.3
- Memberlite 4.4
- PHP 7.4.6

**Comment by dparker1005** [comment]
This should have been fixed in the PMPro 2.5.1 and 2.5.4 updates. Testing now, the discount code is successfully being saved to the PMPro order when the user is sent to 2Checkout.
