### ISSUE TITLE
Authorize.net gateway does not make billing fields required

### ISSUE THREAD

**Issue by ronalfy** [strangerstudios/paid-memberships-pro#1377]
**Describe the bug**

On a blank WordPress install with just PMPro installed and the Authorize.net gateway active, the billing fields are not required.

**To Reproduce**
1. Use a blank WP install and install PMPro.
2. Use the Authorize.net gateway and place in sandbox or production mode.
3. Checkout as a level.
4. Billing fields are not required.

**Expected behavior**

Billing fields should be required for Authorize.net.

**Isolating the problem (mark completed items with an [x]):**

A workaround at the moment is to change gateways to Stripe, enable billing fields, save them. Then switch back to Authorize.net, re-save, and the billing fields should show up as required.

**Comment by dparker1005** [comment]
This should have been fixed here: https://github.com/strangerstudios/paid-memberships-pro/commit/33df2e16b0fd3a06a853a833b10a8c620232ae5c
