### ISSUE TITLE
Defect in the pmpro_search_filter() function

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#1394]
Reported by the plugin author of Media Library Assistant:

My testing reveals a defect in the pmpro_search_filter() function in the /includes/content.php file. The defect is in this line of code:

in_array($query->query_vars['post_type'], apply_filters('pmpro_search_filter_post_types', array("page", "post")))

The test fails when $query->query_vars['post_type'] is an array, not a string. The "post_type" parameter allows for multiple post types, as documented in the WP_Query class reference Post Type Parameters section; see the third example in this section.

I can change my plugin to avoid the defect, but you should correct the problem and allow for multiple post_type values. Let me know if there's anything else I can do to help.

**Comment by ideadude** [comment]
Let's create a new variable that casts this $query->query_vars['post_type'] to an array.

Then use array_intersect instead of in_array for the test.
