### ISSUE TITLE
Discount code does not work with “Select a Payment Plan” function

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/paid-memberships-pro#1396]
Discount codes don’t work when using the “Select a Payment Plan” option. https://www.paidmembershipspro.com/add-select-a-payment-plan-box-to-membership-checkout-code-demo/

Steps to recreate

- Set up the “Select a Payment Plan” function using as explained here https://www.paidmembershipspro.com/add-select-a-payment-plan-box-to-membership-checkout-code-demo/
- Add a discount code for the levels from the above function
- Try using the discount code on the checkout page.

https://p2.paidmembershipspro.com/discount-code-does-not-work-with-select-a-payment-plan-function/

**Comment by dparker1005** [comment]
As this is an issue with the code recipe and not the core PMPro plugin, I am closing this issue.
