### ISSUE TITLE
Membership Confirmation missing from email template.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#1429]
**Describe the bug**
The membership confirmation message included in email templates disappear when a discount code is applied to a checkout. This works okay without a discount code.

**To Reproduce**
1. Enable the membership confirmation for email by selecting the setting: "Check to include this message in the membership confirmation email."
2. Checkout normally without a discount code. The confirmation message shows correctly on the email.
3. Checkout for same level with a discount code. The confirmation message isn't in the email's content.

**Expected behavior**
Email confirmation message should show in the email's content, when checking out with a discount code.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by ronalfy** [comment]
Can confirm this bug on a customer's site.

**Comment by kimwhite** [comment]
Yup. found this too.

**Comment by fontaholic** [comment]
i'm happy to help you guys try to test this. i know we want to use coupon codes when we can.
