### ISSUE TITLE
Filter for Recaptcha Endpoints for Global Access

### ISSUE THREAD

**Issue by ronalfy** [strangerstudios/paid-memberships-pro#1434]
**Is your feature request related to a problem? Please describe.**

Users in China and other countries that ban Google cannot checkout using recaptcha.

**Describe the solution you'd like**
A filter to be able to change the endpoint.

Goal would be to comply with this doc: https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally

**Describe alternatives you've considered**

1. Unhooking the `add_action( 'wp', 'pmpro_init_recaptcha', 5 );` action and re-initialization with custom code.
2. An output buffer to do a str_replace.

**Comment by dparker1005** [comment]
Closing in favor of https://github.com/strangerstudios/paid-memberships-pro/issues/1436
