### ISSUE TITLE
Timezone Database errors since PMPro 2.4 upgrade

### ISSUE THREAD

**Issue by contemplate** [strangerstudios/paid-memberships-pro#1437]
Since we upgraded to PMPro 2.4 our error logs are filled with this:

WordPress database error Incorrect parameter count in the call to native function 'UNIX_TIMESTAMP' for query SELECT UNIX_TIMESTAMP(CONVERT_TZ(enddate, '+00:00', @@global.time_zone), '+00:00', @@global.time_zone)) FROM wp_pmpro_memberships_users WHERE user_id = '8865' AND status = 'active' LIMIT 1 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, FrmEntriesController::process_entry, FrmEntry::create, FrmEntry::create_entry, FrmEntry::continue_to_create_entry, FrmEntry::after_insert_entry_in_database, FrmEntry::after_entry_created_actions, do_action('frm_after_create_entry'), WP_Hook->do_action, WP_Hook->apply_filters, leo_add_applicant_level, PMProEmail->sendCheckoutEmail

We use a custom Application Form built in Formidable Forms for people to apply for membership.  After submission they are given an "Applicant" level in PMPro.  Our code snippet has been working fine until version 2.4.  Here is our snippet for reference:
`
/*-- PMPRO LEVEL: After Submission Routines -----------------*/
add_action('frm_after_create_entry', 'leo_add_applicant_level', 20, 2);
function leo_add_applicant_level($entry_id, $form_id){
	
 // Applicant Form Routines
 if($form_id == 2){ 
   if(!function_exists("pmpro_changeMembershipLevel")){
		return;
   } 
	 
   $member_level = 2; //Applicant level
   $user = wp_get_current_user(); //get logged in user
   if(!$user) {
       return; //don't continue if user doesn't exist
   }
   $user_id = $user->ID;	
   if(pmpro_hasMembershipLevel('5', $user_id )) { //Do not change level for existing member
	    $pmproemail = new PMProEmail();
	   // $pmproemail->sendCheckoutAdminEmail( $user );
	   	return;
   } else {
   		pmpro_changeMembershipLevel( $member_level, $user_id ); //assign level to user
	   $pmproemail = new PMProEmail();
	   $pmproemail->sendCheckoutEmail( $user );
	  // $pmproemail->sendCheckoutAdminEmail( $user );
   }
 }
	
}
`

**Comment by contemplate** [comment]
Ok actually it looks like you all already fixed this here:
https://github.com/strangerstudios/paid-memberships-pro/commit/c1a29f4b9e1fd28c6a384b5679bccbb44a5b74bc

I've applied it and tested it and it WORKS!

**Comment by ideadude** [comment]
Thanks! Glad the patch worked for you. 2.4.1 should go out soon.
