### ISSUE TITLE
WP User Avatar plugin conflicting with PMPro block dashboard feature

### ISSUE THREAD

**Issue by bluesteamhost** [strangerstudios/paid-memberships-pro#1445]
**Describe the bug**
Because PMPro does not have a profile/avatar addon native to PMPro, we are forced to use third party pluugins.  Due to this, WP User Avatar has been one of the recommended plugins to use.  However, when WP User Avatar or any plugin is installed that modifies the subscriber role to allow editing of posts for subscriber roles to allow editing of profile pictures, the block dashboard feature of PMPro is ignored.

See screenshots.

**To Reproduce**
1. Install PMPro
2. navigate to Memberships->Settings->Advanced
3. Enable the option "Block all users with the Subscriber role from accessing the Dashboard."
4. Test a Subscriber member and ensure this member is not able to access the dashboard.
5. Install WP User Avatar plugin
6. Navigate to Avatars->Settings
7. Enable the "Allow users to edit avatars" option
8. Test a Subscriber member and see now that this member is now able to access the dashboard and add new posts.

**Screenshots**
![image](https://user-images.githubusercontent.com/44110924/90048010-25e20100-dcd3-11ea-99c8-f27c878b503e.png)
![image](https://user-images.githubusercontent.com/44110924/90286633-8fe6db80-de76-11ea-8db6-53fa11145870.png)
![image](https://user-images.githubusercontent.com/44110924/90048080-43af6600-dcd3-11ea-921d-bd176a3f0940.png)
![image](https://user-images.githubusercontent.com/44110924/90048493-e49e2100-dcd3-11ea-859b-9b0c63bcb737.png)
![image](https://user-images.githubusercontent.com/44110924/90048561-fc75a500-dcd3-11ea-8a19-db8bb9f2e0d6.png)

**Expected behavior**
Even though the edit posts capability is available to subscribers, the dashboard should remain hidden.  The member should be redirected back to their Account Details page.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Tested on WordPress 5.5
PHP: 7.4.8
Web Server: LiteSpeed 7.6
DataBase: MariaDB 10.3.23
PMPRo: 2.4.1
WP User Avatar: 2.2.7

</details>

**Comment by bluesteamhost** [comment]
PMPro is aware of this type of "backdoor" by other plugins and have provided me with the following code recipe to further block access to the dashboard.

```
<?php
/**
 * Block dashboard access for custom roles pmpro_role_1 and pmpro_role_2.
 *
 * You can add this recipe to your site by creating a custom plugin
 * or using the Code Snippets plugin available for free in the WordPress repository.
 * Read this companion article for step-by-step directions on either method.
 * https://www.paidmembershipspro.com/create-a-plugin-for-pmpro-customizations/
 *
 */
function block_dashboard_for_custom_role( $block ) {
	global $current_user;

	//Update this line with your custom roles
	$roles_to_block = array( 'pmpro_role_1', 'pmpro_role_2' );

	if ( ! current_user_can( 'manage_options' )
		&& ! wp_doing_ajax()
		&& ! empty( array_intersect( $roles_to_block, $current_user->roles ) ) ) {
		$block = true;
	}

	return $block;
}
add_filter( 'pmpro_block_dashboard', 'block_dashboard_for_custom_role' );
```

Hope this helps someone.

**Comment by dparker1005** [comment]
I am  glad to see that you have found that code recipe to strengthen the dashboard blocking functionality. As a solution has been found for this issue, we are going to close this ticket.
