### ISSUE TITLE
Styling issue for update warning message.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#1451]
**Describe the bug**
When the upgrade check runs and shows an admin notice, this is not styled. Please see image for reference.

**Screenshots**
![upgrade-check-message](https://user-images.githubusercontent.com/12629136/90397636-6e653a00-e098-11ea-8a90-1c01b9ebc859.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by ideadude** [comment]
Should have been fixed here https://github.com/strangerstudios/paid-memberships-pro/commit/a17ebace8f301ea25f6f6ba8498655d623754639
