### ISSUE TITLE
stripe_billingaddress option causing issue in other gateways

### ISSUE THREAD

**Issue by knit-pay** [strangerstudios/paid-memberships-pro#1463]
If stripe_billingaddress is set to false, it is causing an issue in other plugins that need billing details, this option is forcefully setting all the fields as not required whereas they are required in other payment gateways. I think this function should be part of stripe gateway only, it should not be part of filters file.
https://github.com/strangerstudios/paid-memberships-pro/blob/114ceb9a8875279a108293acf82f714cce776d06/includes/filters.php#L125

**Comment by ideadude** [comment]
Can you provide steps to reproduce this?

Notice we have code here to avoid hiding the billing address fields if you are using a gateway other than Stripe.

https://github.com/strangerstudios/paid-memberships-pro/blob/114ceb9a8875279a108293acf82f714cce776d06/includes/filters.php#L136-L139

This is working in my own testing. I might be missing something though. Or maybe there is something else keeping the billing address from showing up on your checkout page.

**Comment by dparker1005** [comment]
This should have been resolved by this pull request: https://github.com/strangerstudios/paid-memberships-pro/pull/1513
