### ISSUE TITLE
This transaction cannot be processed. The country code in the shipping address must match the buyer's country of residence.

### ISSUE THREAD

**Issue by atifshah313** [strangerstudios/paid-memberships-pro#1470]
Hello There!

I am using PMPro version 2.4.4 with theme Course Builder By Thimpress. I recently moved my site to the new server and now i am having an issue at checkout. Whenever i try to checkout With a Level (with auto payment recurring) with PayPal Express it displays the error "This transaction cannot be processed. The country code in the shipping address must match the buyer's country of residence." and if I check out with the package in which auto payment recurring is deactivated the process goes according to the checkout flow. is this is a bug or what because I had a conversation with PayPal support and they said API calls and everything is good to go from there end so please look into the issue and please guide me to fix this issue if it's not a bug maybe it is because of site migration What you suggest waiting for your response thanks in advance.
![image](https://user-images.githubusercontent.com/70788342/92297118-5c6b0e80-ef55-11ea-8182-4d30102fa652.png)

**Comment by dparker1005** [comment]
Closing support ticket due to inactivity.
