### ISSUE TITLE
WordPress database error: [Column 'membership_id' in where clause is ambiguous]

### ISSUE THREAD

**Issue by lisaleague** [strangerstudios/paid-memberships-pro#148]
See - https://www.diigo.com/item/image/4okd6/0kyo

**Comment by strangerstudios** [comment]
Fixed here: https://github.com/strangerstudios/paid-memberships-pro/commit/1fd96d0df564b193f982cc9ad68408559e4aeecd

Thanks!

**Comment by lisaleague** [comment]
@strangerstudios that was an old one:)
