### ISSUE TITLE
pm pro aweber plugin stops working on wp blog

### ISSUE THREAD

**Issue by licensingguy** [strangerstudios/paid-memberships-pro#149]
Plugin works for a while, then this message appears:

AWeberAPIException:
Type: APIUnreachableError
Msg : Unable to connect to the AWeber API. (28 - connect() timed out!)
Docs: https://labs.aweber.com/docs/troubleshooting

**Comment by strangerstudios** [comment]
Closing, but please bring up here if this is still an issue https://github.com/strangerstudios/pmpro-aweber/issues
