### ISSUE TITLE
mollie payment gateway 

### ISSUE THREAD

**Issue by divine2** [strangerstudios/paid-memberships-pro#150]
After google out i found that by add on mollie payment can be integrated to pai membershi pro
Can u plzz suggest me how it will be done

**Comment by dwilmer** [comment]
I have looked for such a plugin, but so far I've been unsuccessful. I'm therefore writing my own: https://github.com/dwilmer/dw-pmpro-mollie
(note: at the time I post this, I just set up a basic repository and empty wordpress plugin, no code yet).

**Comment by DenisStetsenko** [comment]
@strangerstudios  I just started to build such kind of Add-On. Any help with be greatly appreciated!

**Comment by strangerstudios** [comment]
Nice! I'm going to close the issue here and follow up in the repo Denis posted here  https://github.com/DenisStetsenko/pmpro-gateway-mollie

If you need my attention on any issue there, reach out via our member forums or ping me on Twitter/etc. Thanks.

**Comment by kangarko** [comment]
@ghost @dwilmer are your solutions still available?

**Comment by kangarko** [comment]
@DenisStetsenko @dwilmer are your solutions still available?
