### ISSUE TITLE
"Cancel this user's subscription at the gateway" checkbox will uncheck when changing expiration date

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#1506]
**Describe the bug**
The checkbox to "cancel at the gateway" sometimes unchecks itself when changing a user's membership level details on the Edit User admin page.

**To Reproduce**
1. Go to Users > Edit a user.
2. Change the "expiration" from "No" to "Yes.
3. Check the box to "Cancel this user's subscription at the gateway".
4. Change the expiration date.
5. The cancel checkbox will uncheck.

**Expected behavior**
Once the user checks the box to cancel the subscription at the gateway it should stay checked.

**Comment by dparker1005** [comment]
Could not replicate this, but it doesn't look like anything has changed in the `/includes/profile.php` file.

**Comment by kimcoleman** [comment]
I'm going to close this. I don't see it happening anymore in our site like it did last year.
