### ISSUE TITLE
Password reset generates a fatal error

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/paid-memberships-pro#1520]
A user on .org has reported this error (I am not able to replicate): 

The error is thrown as soon as the user tries to retrieve the password upon email submission.

`An error of type E_ERROR was caused in line 776 of the file /wp-content/plugins/paid-memberships-pro/includes/login.php. Error message: Uncaught ArgumentCountError: Too few arguments to function pmpro_password_reset_email_filter(), 2 passed in /wp-includes/class-wp-hook.php on line 287 and exactly 4 expected in /wp-content/plugins/paid-memberships-pro/includes/login.php:776`

The password reset form works fine when the plugin is disabled and it seems like an issue with the `pmpro_password_reset_email_filter` function.

Is there a way to disable or override this function? What could be the cause of this issue?

**WordPress Environment**
`
WordPress 5.5.3
PHP 7.3.5
PMPro 2.5.2
Recurring Emails and Failed Payment Limit Add On.
`
As reported on .org here please: https://wordpress.org/support/topic/password-reset-fatal-error/

**Comment by andrewlimaza** [comment]
Unable to replicate this, we also pass in 4 parameters - https://github.com/strangerstudios/paid-memberships-pro/blob/2c0279800daaa78b52aa9e09bce8f0b204bfd4f2/includes/login.php#L776-L790

See code here, we explicitly set 4 arguments.

**Comment by dparker1005** [comment]
Closing as we were unable to replicate.
