### ISSUE TITLE
Mercadopago Gateway?

### ISSUE THREAD

**Issue by francotc** [strangerstudios/paid-memberships-pro#1524]
I would like to know if you are considering the incorporation of Mercadopago to the payment flow.

Attached link of the subscriptions system of mercadopago
https://www.mercadopago.com.ar/developers/es/guides/online-payments/subscriptions/introduction

**Comment by dparker1005** [comment]
Adding a payment gateway is a lot of work. We currently don't have plans to add any new gateways. Here is our documentation on how to add a new gateway if someone else wants to work on that. We will answer specific questions/etc to help.

https://www.paidmembershipspro.com/gateway/adding-a-new-gateway/

**Comment by rosamoraweb** [comment]
Anybody knows somebody can help with this integration with this payment gateway?
