### ISSUE TITLE
Discount Code - Trial Billing (bug)

### ISSUE THREAD

**Issue by jkbeck** [strangerstudios/paid-memberships-pro#155]
There is a bug with the trial billing duration. No matter what amount of time I set it to it always defaults to 1 month when the URL is sent to paypal.

My payment settings are PayPal Standard (Sandbox/Testing).

Below is a link to the Discount Code settings. Trial billing amount is set to $1.25 for the first 3 months.
http://prntscr.com/5g3vgu

When it comes up on PayPal it shows "Then $1.25 USD for the next month". It should show "Then $1.25 for the next 3 months".
Link to screenshot below.
http://prntscr.com/5g3xg8

The interesting thing is when I switch the Billing Amount payments to every 4 weeks and the trial amount to "for the first 12 subscription payments", the PayPal message changes to "Then $1.25 for the next 4 weeks". Once again only allowing 1 month for a trial period.

Whatever settings I use it always ends up being 1 month or 4 weeks of trial.

Here is the URL that gets generated when clicking the paypal button on the membership signup page.

https://www.sandbox.paypal.com/cgi-bin/webscr?business=billing%40paleomaps.com&cmd=_xclick-subscriptions&a1=1.50&p1=1&t1=M&a3=2.50&p3=1&t3=M&item_name=Premium+at+PaleoMaps&email=junker807%40gmail.com&no_shipping=1&shipping=0&no_note=1&currency_code=USD&item_number=2FC0050157&charset=UTF-8&rm=2&return=http%3A%2F%2Fkevlarcaveman.com%2Fmembership-account%2Fmembership-confirmation%2F%3Flevel%3D20&notify_url=http%3A%2F%2Fkevlarcaveman.com%2Fwp-admin%2Fadmin-ajax.php%3Faction%3Dipnhandler&src=1&sra=1&a2=1.25&p2=1&t2=M&srt=0&SOLUTIONTYPE=Sole&LANDINGPAGE=Billing

As you can see here "a2=1.25&p2=1&t2=M" it's setting p2=1 when it should be p2=3.

**Comment by strangerstudios** [comment]
We should test to see if this is still happening.
