### ISSUE TITLE
Paypal Checkout Button

### ISSUE THREAD

**Issue by MasterAgencySB** [strangerstudios/paid-memberships-pro#1560]
**Describe the bug**
We have problem with the image of the button of my checkout. The button is orrible, is deformid and not trasparent.
we would like to solve the problem by inserting a normal key. Is there any code to change the size of the image and make it normal?
moreover, nothing is aligned. I am attaching a screenshot to show you how bad the payment section is.
Has anyone had the same problem? If so, how did you solve it?

**Screenshots**
![image](https://user-images.githubusercontent.com/77920500/105628331-89548b00-5e3c-11eb-9c17-e436dd83aeee.png)

**Expected behavior**
I expected it to be all automatic. In the sense that everything was well aligned and that the keypad was perfect.

**WordPress Environment**
<details>
```

I have a version of Wordpress 5.6
and the PMP version is 2.5.2
```</details>

**Comment by kimcoleman** [comment]
There is code in our stylesheet to handle this but your theme is overriding it: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/css/frontend.css#L75-L77. Your theme is setting all form elements to 100% width.

Please follow up with your theme author regarding this layout issue.

You can also email us through our content form with the name of your theme. If it is open source and available for us to test with we can see about making the core plugin's CSS for that element more strongly enforce auto width. See: https://www.paidmembershipspro.com/contact/
