### ISSUE TITLE
Stripe Update "On/After" Option doesn't work.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#1577]
**Describe the bug**
When trying to update a user's Stripe subscription from the WordPress dashboard, this doesn't work when choosing "On Date" or "After Date" option as outlined here -  https://www.paidmembershipspro.com/gateway/stripe/#tab-subscription-updates

This seems that the cron this relies on doesn't get setup correctly - https://github.com/strangerstudios/paid-memberships-pro/blob/e3e3867aa4295f7d6eb1c398faf5872e69ca3e80/classes/gateways/class.pmprogateway_stripe.php#L26

**To Reproduce**

Quick check, use WP Crontrol to see if the above cron is created on PMPro activation.

1. Checkout as a user using Stripe.
2. Logout, login as an admin.
3. Navigate to this user created in step 1 and try to update their subscription on/after a date.
4. Use Crontrol/wait to see if sub updates. (the cron might not be setup).

**Comment by dparker1005** [comment]
Closing as Stripe Subscription Updates have been deprecated and removed in 3.0
