### ISSUE TITLE
Double period after plan in user email notification

### ISSUE THREAD

**Issue by JoelStickney** [strangerstudios/paid-memberships-pro#158]
paid-memberships-pro/classes/class.pmproemail.php

Line 762: I believe the ending period causes a double period in the user email (admin email doesn't suffer from this). Example:

An administrator at Site has changed your membership level.

The new level is Gold..

**Comment by strangerstudios** [comment]
Seems to be fixed in latest versions. If you still see the extra . double check any email templates you created via the email templates addon or in your theme. Thanks!
