### ISSUE TITLE
Enhance pmpro_next_payment function

### ISSUE THREAD

**Issue by mircobabini** [strangerstudios/paid-memberships-pro#1583]
**Is your feature request related to a problem? Please describe.**
Since `pmpro_next_payment` function lacks of a param for the membership level, there is no way to pass the third param to the getLastMemberOrder call https://github.com/strangerstudios/paid-memberships-pro/blob/60ab16975ad75cdb78340512a32390f1468dc1aa/includes/functions.php#L688

This cause an issue when combined with pmpro-gifts, for instance:
1. Annual membership from 1st Apr 2020
2. Gift bought on 1st Dec 2020
3. When using pmpro_next_payment, it takes 1st Dec 2020 and adds a cycle of 1 year, resulting in next_payment = 1st Dec 2021. Wrong.

**Describe the solution you'd like**
I think we can leave this old function as is. Don't like the idea to add a fourth param after the $format, it's unusual. Of course we can't add it as third param, would break backward compat.

But we can create a new nextPayment method for MemberOrder and use Gateway specific logic as suggested by Kim: https://github.com/strangerstudios/pmpro-cancel-on-next-payment-date/issues/9.

**Comment by mircobabini** [comment]
This work may conflict with the "subs table" work we are doing. We should revisit after the subs table work is ready.

**Comment by dparker1005** [comment]
As of 3.0, next payment dates should be retrieved by getting the subscription for the user and getting the next payment date from that Subscription object.
