### ISSUE TITLE
Login report is empty

### ISSUE THREAD

**Issue by onnimonni** [strangerstudios/paid-memberships-pro#159]
If I go into:

```
/wp-admin/admin.php?page=pmpro-reports&report=login
```

all the sections are empty.

But if i look at example user custom meta I can see:

```
 pmpro_logins         | {"last":"9.1.2015","thisdate":null,"month":1,"thismonth":"1","alltime":1}       
 pmpro_views          | {"last":"9.1.2015","month":3,"alltime":3,"thismonth":"1"}                       
```

I'm using latest version of the plugin: 1.7.15.2

**Comment by strangerstudios** [comment]
We've tweaked this code a bit. Do you know if you are still having this issue? I can't reproduce it.
