### ISSUE TITLE
 PHP Notice when PMPro pages haven't been configured

### ISSUE THREAD

**Issue by eighty20results** [strangerstudios/paid-memberships-pro#1592]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed or left unattended.

**To Reproduce**
`# tail -f <path to apache/nginx>/error_log`
Activate PMPro plugin in `/wp-admin/plugins.php`

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.

N/A

**Expected behavior**

PHP Notices are indicative of (potential) future problems, pollute the debug/error log and should be fixed to minimize false positives from end-users.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Standard, bare bones, WordPress 5.x installation with PMPro installed, but not configured.
```
</details>

**Comment by dparker1005** [comment]
This should have been resolved in PMPro v2.5.7 by this PR: https://github.com/strangerstudios/paid-memberships-pro/commit/c8f8bd5c6a50ca0b69c941a973b72644ae76f01a
