### ISSUE TITLE
Database encoding for text

### ISSUE THREAD

**Issue by adilelsaeed** [strangerstudios/paid-memberships-pro#162]
Hi,
There is a problem in some column (text) in the database, the current encoding (collection) is "latin1_swedish_ci" which made a problem when saving non-latin character (Arabic) it saved as question marks!,
some off this column is "name, description, and confirmation" in "wp_pmpro_membership_levels"  table.
I suggest to change all tables encoding to utf-8.

Thanks.

**Comment by adilelsaeed** [comment]
I think the plugin use the default WordPress database collection "DB_COLLATE", but any way I think it's will be great to enforce "utf8_general_ci" encoding for all plugin table.

**Comment by strangerstudios** [comment]
I'm not sure when we changed it, but we leave the collation out so WP uses the default. I notice that some other plugins set it specifically to utf8/utf8_general_ci and others specifically use the $wpdb->get_charset_collate() method to get the character set. I'll explore this a bit to see what we can/should do. If you have sources RE other WordPress devs choosing one way over another with reasoning, let me know. Thanks.

**Comment by strangerstudios** [comment]
Before I close this, I'd like someone to make sure that the dbDelta calls we do are going to use the default character set. It seems some other plugins are explicitly looking up and setting the default character set. Let's not do that if we don't have to anymore.

Some testing and WP codebase digging would help us be assured that these kinds of issues won't crop up again.

**Comment by dparker1005** [comment]
Tables now use chosen site collation in 3.0
