### ISSUE TITLE
We need a way to process all membership levels changes at once at the end of the page load.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#1628]
Plugins like the Mailchimp Add On or our Courses Add On need a way to process all level changes at once. If we do things one level change a time, we sometimes end up "toggling" a user in a mailing list or course enrollment. They get removed and then added back in during a later level change.

Our proposal is to:

1. hook into pmpro_before_change_membership_level.
2. the first time a user changes levels during a page load, save a list of the existing levels at that time
3. new action: pmpro_after_all_membership_level_changes, pass the array of old levels for users. fire on these hooks like PMPro Mailchimp does https://github.com/strangerstudios/pmpro-mailchimp/blob/dev/includes/api-wrapper.php#L174-L177
4. Code will hook into pmpro_after_all_membership_level_changes, get the old levels, get the new levels by calling pmpro_getMembershipLevelsForUser and can perform adds/removes in the add on or other API.

May be other issues for these already:
* make sure cache in pmproGetMembershipLevelsForUser accounts for $include_inactive
* make sure we clear the cache when a user's level changes.

**Comment by dparker1005** [comment]
PR to add this behavior above. RE your other concerns, we are learning the membership level cache here as long as the membership level change is successful:
https://github.com/strangerstudios/paid-memberships-pro/blob/dfbce960f59ba418e0ee5d2dc4b966001f3a6bcc/includes/functions.php#L1177-L1183

Here is the original issue for including `$include_active` in the cache: https://github.com/strangerstudios/paid-memberships-pro/issues/984
