### ISSUE TITLE
Some strings not translated. _ex function used instead of _e and no context defined in pot file

### ISSUE THREAD

**Issue by ecoeficiente** [strangerstudios/paid-memberships-pro#163]
pmpro.pot does not include contexts for certain strings. However, in the code  _ex( $text, $context, $domain )  function is used instead of _e. For those, $text is not translated using localized mo files.

Solution: Replace _ex with _e or include context in pot file.

**Comment by strangerstudios** [comment]
The context strings were not being added to the pot properly via the script we use. I like having the command line script and thought the context strings didn't really help translators that much. So I took out the _ex. Did we miss some? Can you link me to them or do a pull request to change them to just _e/etc?

**Comment by strangerstudios** [comment]
For some reason the script we use to generate the .pot file doesn't recognize the _x function. In practice, we've just replaced all of these with __ or_e as you suggest. I've just searched the repo and don't see any _x() calls anymore.

Thanks again for your help. Going to close this thread. But please open a new issue if there are any other missing strings or translation issues.
