### ISSUE TITLE
Strings not translated, plurals lack in pot file

### ISSUE THREAD

**Issue by ecoeficiente** [strangerstudios/paid-memberships-pro#166]
In pot file, the lines referred to localization.php should add the plurals for localization to work.
So:
# : includes/localization.php:23 includes/localization.php:23

msgid "Day"
msgstr ""

Should become:
# : includes/localization.php:23 includes/localization.php:23

msgid "Day"
msgid_plural "Days"
msgstr[0] ""
msgstr[1] ""

**Comment by strangerstudios** [comment]
We got this specific one at some time:
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/languages/paid-memberships-pro.pot#L6950

Closing this thread, but please open a new one if there are similar strings we're missing. Thanks.
