### ISSUE TITLE
Function to be prefixed

### ISSUE THREAD

**Issue by mircobabini** [strangerstudios/paid-memberships-pro#1661]
**Is your feature request related to a problem? Please describe.**
No problem with this... yet. The `wpd_add_query_vars` function should be prefixed. Don't know what `wpd_` stands for (?); WordPress Domain maybe? Btw `pmpro_stripe_apple_pay_add_query_vars` should be a good new name.

https://github.com/strangerstudios/paid-memberships-pro/blob/bf1d2376e77e7156aac52e5cf126f4268a04bec6/includes/lib/stripe-apple-pay/stripe-apple-pay.php#L14

**Comment by dparker1005** [comment]
Just PR'd, thank you @mircobabini!
