### ISSUE TITLE
Italian Translation Issue - Apostrophe Causes JS Error When Applying Discount Code

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/paid-memberships-pro#1662]
**Describe the bug**
The Italian translation has an apostrophe in the string 'Il codice <strong>%s</strong> è stato applicato all'ordine.' which results in a JS error when applying a discount code. 

**To Reproduce**
1. Set your default language to Italian
2. Apply a discount code by entering it in the field and hitting 'Apply'. 
3. You will get an error in the console containing a formatting error. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8989542/119348910-c40ce980-bc9d-11eb-87be-d765bc83fa05.png)

**Expected behavior**
No errors should occur when applying a discount code. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- PMPro 2.5.9.1
- WP 5.7

**Fix**

The string needs to be changed to `Il codice <strong>%s</strong> è stato applicato all\'ordine.`

**Comment by JarrydLong** [comment]
Occurred initially in https://www.paidmembershipspro.com/forums/topic/discount-coupon-code-error/ (moderators only)

**Comment by mircobabini** [comment]
I was able to replicate the issue, preparing the fix.
