### ISSUE TITLE
Select All option for "Required Levels" metabox.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/paid-memberships-pro#1692]
**Is your feature request related to a problem? Please describe.**
Some site owners have many levels.  If a post is for all the levels it can be cumbersome to check all the checkboxes.
Would be great to have a Select All button, or checkbox.

**Describe the solution you'd like**
Something like this works:
https://gist.github.com/ideadude/0166ef9082f76493559776278ee7edc6

![select-all](https://user-images.githubusercontent.com/8083630/125841036-0568ffae-7610-4895-a3ad-02cbdeb6a4f7.png)

**Comment by ideadude** [comment]
If/when @kimcoleman can suggest the UI/UX for this, we can update the gist and include something similar in the core plugin.
