### ISSUE TITLE
plugin seems to interfere with theme db queries

### ISSUE THREAD

**Issue by robwent** [strangerstudios/paid-memberships-pro#171]
In our theme there is query which shows similar articles to the current page.
It uses post__not_in to remove the id of the current page from the query, but this is being overridden by pmp with what looks like the id's of pages set to members only.

For example, the theme query arguments:

```
 array(4) {
  ["category__in"]=>
  array(1) {
    [0]=>
    int(31)
  }
  ["post__not_in"]=>
  array(1) {
    [0]=>
    int(36734)
  }
  ["showposts"]=>
  int(2)
  ["ignore_sticky_posts"]=>
  int(1)
```

should result in the query:

```
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts INNER JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) WHERE 1=1 AND wp_posts.ID NOT IN (36734) AND ( wp_term_relationships.term_taxonomy_id IN (31) ) AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'private') GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 2
```

but if I enable pmp then it changes to 

```
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts INNER JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) WHERE 1=1 AND wp_posts.ID NOT IN (211,24199,25123,25295,25296,25297,25298,25300,25301,25302,25303,26380,26996,26998,33576,43164) AND ( wp_term_relationships.term_taxonomy_id IN (31) ) AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'private') GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 2
```

Is there anyway we can get the theme and plugin to work together?

**Comment by robwent** [comment]
The part causing the issue is in wp-content/plugins/paid-memberships-pro/includes/content.php around line 159

    if($hidden_page_ids)
        $query->set('post__not_in', $hidden_page_ids);

**Comment by strangerstudios** [comment]
This is an old issue, but I think we still have it. Instead of "nuking" the post__not_in value there, we should merge our $hidden_page_ids with the existing ids in the ->post__not_in setting before resetting the value.

Let's recreate this (can maybe use some custom code to just set that value sooner or if we can find the theme in question here) and then see if merging our post ids into that field makes sense.

**Comment by ideadude** [comment]
Should be fixed here now https://github.com/strangerstudios/paid-memberships-pro/commit/179f556ecb4ad8ec004f99d885c8a2ba8adf3aa1
