### ISSUE TITLE
PMPro admin JavaScript loading for non-pmpro pages.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#1723]
**Describe the bug**
The `pmpro-admin` JavaScript file is enqueued unconditionally in the administrative area here:
https://github.com/strangerstudios/paid-memberships-pro/blob/a81b6b31037fbee637380f4bfbe63f9d92234378/includes/scripts.php#L111

The CSS applied by this script now targets and hides non-pmpro fields, e.g. Peepso Configuration pages, that have the class `.controls`.
https://github.com/strangerstudios/paid-memberships-pro/blob/a81b6b31037fbee637380f4bfbe63f9d92234378/js/pmpro-admin.js#L219

**To Reproduce**
1. Activate Paid Memberships Pro and [Peepso](https://wordpress.org/plugins/peepso-core/) plugins.
2. Navigate to Peepso > Configuration
3. Observe that all input fields are hidden
4. Open browser tools and check that pmpro-admin.js is loaded.

**Expected behavior**
The JavaScript file, `pmpro-admin.js`,should only be enqueued for PMPro administrative pages.
We could also consider using namespaced classes.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by ipokkel** [comment]
A temporary workaround that should resolve this conflict is to dequeue the file if the `page` URL parameter is not set or does not start with `pmpro-`

https://gist.github.com/ipokkel/2c522211efb3dbafdaf67833fb4ba905

**Comment by sc0ttkclark** [comment]
@ipokkel A new PR has been created to revisit this issue: https://github.com/strangerstudios/paid-memberships-pro/pull/1991
