### ISSUE TITLE
Email Settings Missing

### ISSUE THREAD

**Issue by hbcondo** [strangerstudios/paid-memberships-pro#1728]
Per the attached screenshots, it appears a variety of checkbox options that were originally available in PMP are now not available in v2.6 and above. Please confirm how PMP admins can now enable/disable "Send the site admin emails" options.

**Original Email Settings** (https://www.paidmembershipspro.com/documentation/initial-plugin-setup/step-4-email-settings/):
![image](https://user-images.githubusercontent.com/306958/129805949-bc8e0600-9a95-434a-a55a-4d9c057a3147.png)

**New Email Settings:**
![image](https://user-images.githubusercontent.com/306958/129806246-2e25f801-64a7-48a6-af15-726527c6a153.png)

**Comment by sc0ttkclark** [comment]
We are looking at this now and will let you know what we determine here.

**Comment by sc0ttkclark** [comment]
I looked over everything here -- this move was intentional. It wasn't removed entirely, you can now find the on/off settings under the Email Templates area, linked right next to the Email Settings page you are on now.
