### ISSUE TITLE
Paid Memberships Pro v1.8

### ISSUE THREAD

**Issue by enjoydevs** [strangerstudios/paid-memberships-pro#173]
Inside wp-admin:

admin.php?page=pmpro-paymentsettings

No data received
Unable to load the webpage because the server sent no data.
Error code: ERR_EMPTY_RESPONSE

**Comment by strangerstudios** [comment]
My guess is you needed to install a PHP module on your server for one of the gateways. Maybe mbyte string for Stripe. Going to close since this is so old, but feel free to post again if this is still a problem for you.
