### ISSUE TITLE
text not detected by loco

### ISSUE THREAD

**Issue by mmieszalski** [strangerstudios/paid-memberships-pro#1776]
untranslatable text not detected by loco

`<p>You have selected the following level:</p><p class="levellist">`

**Comment by mircobabini** [comment]
This is related to https://github.com/strangerstudios/pmpro-multiple-memberships-per-user/issues/80, because that string belongs to MMPU addon.

**Comment by andrewlimaza** [comment]
This should now be fixed with the `dev` branch. I have just regenerated the POT file and see that the text domain is correct. To apply this to your site, you may download the updated and most recent .pot, .mo and .po files.
