### ISSUE TITLE
Recaptcha is hidden when using v3 with PayPal Express.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#1789]
If you are using PayPal Express and have Recaptcha set up (I was using v3), the recaptcha is not showing up. It's also not throwing an error in the console.

The Recaptcha code is looking specifically for the element with id=pmpro_btn-submit and the PayPal button won't have that ID.

Recaptcha code:
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/recaptcha.php#L90

Checkout code:
 https://github.com/strangerstudios/paid-memberships-pro/blob/dev/pages/checkout.php#L514

We can maybe render the recaptcha on a different element that always exists. The submit buttons seem to be defined later.

We will want to test with the add PayPal Express add on to see if recaptcha works when using that as well.

**Comment by dparker1005** [comment]
This was fixed in PMPro v3.0.
