### ISSUE TITLE
Email Header variable returning incorrect user name for admins.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#1819]
**Describe the bug**
The !!name!! variable in the email header is returning incorrect results to admins. It returns the user's name for admin emails.

**To Reproduce**
1. Go to edit a user's profile page on WordPress.
2. Change the user's level.
3. Look at email sent to admin, should have Dear <<user>>, instead of Dear <<admin>>

**Screenshots**
Admin email received, showing the user's name instead of the admin name.

![Screen Shot 2021-10-13 at 14 35 43](https://user-images.githubusercontent.com/12629136/137147000-c6349a3a-65de-4823-a71a-bc4a995ec885.png)

**Expected behavior**
This should change the !!name!! variable to be the admin's name, i.e. Dear Admin, (or user the email is addressed to).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kerijacoby** [comment]
Noting here this was also reported and replicated in ticket #436394 (Moderators only)

**Comment by MaryOJob** [comment]
Similar issue - for moderators only: #443741

**Comment by michaelbeil** [comment]
This is happening in ticket 465663.
