### ISSUE TITLE
discount_code does not apply via AJAX call

### ISSUE THREAD

**Issue by shr3k** [strangerstudios/paid-memberships-pro#182]
PMPro 1.8

One of my testing membership level called WAITING has id 12. It's one time payment, 10 EUR.
Have assigned a discount code called WAITINGBYHALF which set price of this level to 5 EUR.

Calling checkout page with parameter ...checkout/?level=12&discount_code=WAITINGBYHALF works, discount_code is applied to both PayPal Express and Check gateways (I use https://github.com/strangerstudios/pmpro-pay-by-check).

AJAX call via: /wp-admin/admin-ajax.php?action=applydiscountcode&code=WAITINGBYHALF&level=12&msgfield=pmpro_message

produces
```
The WAITINGBYHALF code has been applied to your order. 	<script>		
		var code_level = {"id":"12","code_id":"1","level_id":"12","initial_payment":"5.00","billing_amount":"0.00","cycle_number":"0","cycle_period":"Month","billing_limit":"0","trial_amount":"0.00","trial_limit":"0","expiration_number":"0","expiration_period":"Month","name":"WAITING","description":"","allow_signups":"1"};				
		
		jQuery('#pmpro_message').show();
		jQuery('#pmpro_message').removeClass('pmpro_error');
		jQuery('#pmpro_message').addClass('pmpro_success');
		jQuery('#pmpro_message').addClass('pmpro_discount_code_msg');
		
		jQuery('#other_discount_code_tr').hide();
		jQuery('#other_discount_code_p').html('<a id="other_discount_code_a" href="javascript:void(0);">Click here to change your discount code</a>.');
		jQuery('#other_discount_code_p').show();
		
		jQuery('#other_discount_code_a').click(function() {
			jQuery('#other_discount_code_tr').show();
			jQuery('#other_discount_code_p').hide();			
		});
		
		jQuery('#pmpro_level_cost').html('<p>The <strong>WAITINGBYHALF</strong> code has been applied to your order.</p><p>The price for membership is <strong>5.00 Kč</strong> now. </p>');
		
						pmpro_require_billing = true;
							jQuery('#pmpro_billing_address_fields').hide();
				jQuery('#pmpro_payment_information_fields').hide();			
									
					jQuery('#pmpro_submit_span').hide();
					jQuery('#pmpro_paypalexpress_checkout').show();				
						</script>
```
But this initial_payment is not applied to requested amount after submitting the form.

**Comment by shr3k** [comment]
Temporarily solved by adding hidden field discount_code into form in applydiscountcode.php:
```
...
		jQuery('#<?php echo $msgfield?>').addClass('pmpro_discount_code_msg');

		if (jQuery("#discount_code").length) {
			jQuery('#discount_code').val('<?php echo $discount_code?>');
		} else {
			jQuery('<input>').attr({
				type: 'hidden',
				id: 'discount_code',
				name: 'discount_code',
				value: '<?php echo $discount_code?>'
			}).appendTo('#pmpro_form');
		}

		jQuery('#other_discount_code_tr').hide();
...
```

**Comment by danielsodkiewicz** [comment]
When this is implemented, the money is not taken from the account and the recurring payment us canceled automatically by PayPal (tested by using PyaPal Express). Please advice.

**Comment by shr3k** [comment]
Just test it with your favorite browser's developer console and you'll see what's going on. I my case (WP 4.1.1, Polylang, PMPro 1.8, billing address addon, pay by check addon, always HTTP/SPDY) the discount simply don't get applied as there was no value either in other_discount_code field or as $REQUEST discount_code.

**Comment by strangerstudios** [comment]
v1.8.1 had some fixes for discount codes. Let me know if they helped. Also 1.8.2 coming out in a few minutes.
