### ISSUE TITLE
reCAPTCHA only for Free levels doesn't work with discount codes

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/paid-memberships-pro#1840]
**Describe the bug**
User selects a level that is not free, enters in a discount code and sets it to $0. Then when they checkout, it fails and says the recaptcha field is missing.

**To Reproduce**
1. Enable reCAPTCHA and set it to Free Levels Only. 
2. Checkout with a level that is NOT free. 
3. Enter in a discount code that makes it Free. 
4. Submit Checkout
5. You'll get an error that the reCAPTCHA element is missing. 

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.

**Expected behavior**
reCAPTCHA should not be required if we're going from a paid level to a free level and a discount code is present. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WP 5.8.1
PMPro 2.6.2
</details>

**Comment by ideadude** [comment]
A fix for this could be to better detect when a level became free through custom code or a discount code and not require the recaptcha then, but...

An even better fix could be to remove the "only free levels" option entirely. Charging something does stop spam signups, but the checkout forms are being spammed by folks testing credit card numbers. Gateways are not able to stop this themselves and if your form is spammed a lot, the gateway can close your account or even bill you for the spam.

So in practice, every site should use recaptcha on all checkouts.

We can remove the option and treat the "only free levels" option as meaning always require recaptcha. We should test to make sure there aren't cases where this would break on folks sites.
