### ISSUE TITLE
Please complete all required fields.

### ISSUE THREAD

**Issue by ROB1NSON** [strangerstudios/paid-memberships-pro#186]
In the last couple days, I have had 3 people try to pay through Paid Membership Pro and get the error "Please complete all required fields."  I can reproduce this.  I installed v. 1.8 about 5 days ago and I verified it worked then.  A few people have successfully paid just after this verifiction (they all used a discount code), but is broken now - I tried to update the Stripe API but did not fix so I rolled back. 

The "WP Stripe" plugin does not work either - I tried deactivating it (I use it for donations), but did not fix so reactivated it.

Use discount code "suxors" to reduce standard membership to $1.00:
https://denverbiodiesel.com/join/membership-checkout/?level=16

**Comment by ROB1NSON** [comment]
Toggling the feature of "Show Billing Address Fields" with no luck - I suspect it has to do with this on the Stripe side - have a ticket in with them.

**Comment by strangerstudios** [comment]
1.8.1 has some fixes for things like this, but there are a few cases where "complete all fields" type errors come up with Stripe. (We need to do a better job of catching JS errors that Stripe throws at checkout. We miss them then submit the form without the AccountNumber/etc being updated to include the Stripe token. So PMPro just sees missing data.)

Some things to check:
* Make sure your Stripe API info is entered correctly and doesn't have any whitespaces around it
* Make sure you have the environment setting to live or test based on the API keys used.
* Make sure there are no other JavaScript errors on your checkout page that might keep PMPro from running the Stripe JS (this is a common one)
* Related to the above, make sure all JS and asset files are loading properly over HTTPS. Some themes/plugins don't do a good job at this and need to be fixed or something like WP HTTPS needs to be setup (turn force SSL off in PMPro if you do this)

There are some other cases that come up when using other addons (like require addresses on free levels along with the setting to not require addresses with Stripe) or fields added via Register Helper that are required but not showing up.

We can help you with these kinds of things in the member forum.

**Comment by ROB1NSON** [comment]
Updated to 1.8.1, still no luck. Her e is the js error:

Mixed Content: The page at 'https://denverbiodiesel.com/join/membership-checkout/?level=16' was loaded over HTTPS, but requested an insecure script 'http://www.google.com/jsapi?ver=4.1.1'. This request has been blocked; the content must be served over HTTPS.

**Comment by ROB1NSON** [comment]
Fixed - I had installed the 'SP Responsive header image slider' plug in. Deactivating it restored sanity. 

On the positive side: Updating the Stripe API from 2012 works fine.

**Comment by strangerstudios** [comment]
Glad you worked that out. FYI I built a troubleshooting guide for this issue here:
http://www.paidmembershipspro.com/2015/03/troubleshooting-issues-at-checkout-when-using-stripe/

And also have some updates to PMPro and the PMPro Address For Free Levels addon to fix some of these issues.
