### ISSUE TITLE
Unable to add Columns to Members List when site Language is not English

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/paid-memberships-pro#1876]
**Describe the bug**
When using the code from this tip: https://www.paidmembershipspro.com/add-custom-column-members-list-users-admin-pages/

The custom membership list column is not added when **Site language** (when set on General Settings page) is not English.

The filter is looking for $current_screen->id, which has been changed by changing language.
https://github.com/strangerstudios/paid-memberships-pro/blob/380dacfd0f715a424db47c504310039507ea28a5/classes/class-pmpro-members-list-table.php#L119-L123

**To Reproduce**
1. Add Code to site. https://gist.github.com/dparker1005/a7cc4a20cea4c5dcec4ba480701c4b7e
2. See Company Column on your Members List.
3. Change **Site language** to Spanish
4. Go back to the membership list.
5. Column is not created.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by andrewlimaza** [comment]
This has been merged and fixed (which should resolve the issue).
