### ISSUE TITLE
Issue with Multiple Payment Plugin

### ISSUE THREAD

**Issue by PRIZZA** [strangerstudios/paid-memberships-pro#188]
When switching between PayPal Express and Stripe, after unsuccessfully checking out with PayPal and switching back to credit card, the credit card info entry fields don't show up.

To fix this, simply allow PayPal to load the card fields. In "/classes/gateways/class.pmprogateway_paypalexpress.php", change the filter to true, like this:
add_filter('pmpro_include_payment_information_fields', '__return_true');

**Comment by strangerstudios** [comment]
Which "multiple payment plugin" are you using? To force the payment fields to show up with PayPal, you can add code like this to the other plugin so you don't have to edit the PMPro core files.

https://github.com/strangerstudios/pmpro-address-for-free-levels/blob/master/pmpro-address-for-free-levels.php#L54-L59

**Comment by PRIZZA** [comment]
Thanks for the reply, strangerstudios. I'm using this one: https://github.com/strangerstudios/pmpro-add-paypal-express/

I'll try using that function. The other thing I have to change is in stripeResponseHandler(). It never re-activates the PayPal button when the user fails to put in correct information. I have to add an extra call for jQuery('input[type="image"]').removeAttr("disabled"); to re-enable the PayPal Express image button.
