### ISSUE TITLE
Admin issues with other plugins after 2.6.4 update

### ISSUE THREAD

**Issue by robwent** [strangerstudios/paid-memberships-pro#1880]
**Describe the bug**
Any plugin admin pages using a class of `.controls` gets the content hidden on page load. 
It seems to be coming from here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/js/pmpro-admin.js#L219
This script is loading on all admin pages.

**To Reproduce**
1. Add a class of .controls anywhere non-pmpro in the admin area and load the page.

**Screenshots**
This is how the admin of a custom plugin used for generating emails looked before the update
![before](https://user-images.githubusercontent.com/411678/145594144-9027f7c3-a351-4402-805e-fac95f4c2280.PNG)

And after:
![after](https://user-images.githubusercontent.com/411678/145594177-37203a76-0031-4bce-83c0-c2131ace3fd3.PNG)

**Expected behavior**
PMPro only affects its own admin elements.
Since this was a custom plugin I've modified it to prefix the controls class and updated the CSS, but as it's a common class name it could affect other plugins.

**Comment by mircobabini** [comment]
When PMPro Email Templates was an AddOn, there were no wrapper class to make it more specific.

Now we have `.pmpro_admin_section-email-templates-content` so we can enhance the scope.

**Comment by robwent** [comment]
The line of code I linked to doesn't appear to be using any .pmpro classes.

```js
$(".controls").hide();
```

That runs on document ready.

Or do you mean that this was a result of moving the email addon to the main plugin?

**Comment by mircobabini** [comment]
I mean that this issue was there when it was an addon and it's still there now that we moved into the main plugin.

But, if before it was hard to be fixed, now it's easier because when can use that class in my previous message to enhance the scope.

Of course, as you pointed out, the code it's not scoped enough at the moment.

Gonna send a PR soon and it will be certainly fixed in an upcoming release.

**Comment by andrewlimaza** [comment]
This has been fixed and merged for an upcoming release here - https://github.com/strangerstudios/paid-memberships-pro/commit/148451c81686ea32c027044433f7a149467aeb94
