### ISSUE TITLE
There's no action hook for refunding or cancelling an order

### ISSUE THREAD

**Issue by codelion7** [strangerstudios/paid-memberships-pro#191]
I'm working on an integration for PMP w/ my affiliate plugin AffiliateWP, and I noticed that there's no action hook that can be used when refunding or cancelling an order. This is really important, because without this hook, there's no way to revoke unpaid referral commissions for orders that have been cancelled or refunded.

Can you add an action hook for this?

**Comment by strangerstudios** [comment]
You could try one of these and check the status of the order vs the previous status:
http://www.paidmembershipspro.com/hook/pmpro_update_order/
http://www.paidmembershipspro.com/hook/pmpro_updated_order/

**Comment by codelion7** [comment]
Thanks, it sounds simple enough. So, if I were to hook into pmpro_updated_order, how would I obtain the old status? And the current status is accessed via $order->status, correct?

Lastly, will this hook fire when the user cancels their membership, or just when an admin cancels their membership in the dashboard?

**Comment by strangerstudios** [comment]
I think this has been worked out by the AffiliateWP team. Let me know if this is still an issue, and I'll dig into the code again.
