### ISSUE TITLE
Headers already sent by class.pmprogateway_stripe.php

### ISSUE THREAD

**Issue by risingtide-edu** [strangerstudios/paid-memberships-pro#1920]
When accessing my website, PHP throws a number of errors on both the admin and the front pages, namely a "Headers already sent" error (see screenshot below) - this seems to be a bug in the class.pmprogateway_stripe.php file, since all of the errors are arising from there. I am unable to identify a fix for this issue myself unfortunately.

**Steps to reproduce the behavior:**
Unfortunately I am unable to link to the page giving the error, as it is occurring on a private development site. The errors are provided below, and I am happy to provide further context if needed.

**Errors:**
Deprecated: Required parameter $values follows optional parameter $livemode in ~/public_html/dev/wp-content/plugins/paid-memberships-pro/classes/gateways/class.pmprogateway_stripe.php on line 1767

Deprecated: Required parameter $gateway follows optional parameter $livemode in ~/public_html/dev/wp-content/plugins/paid-memberships-pro/classes/gateways/class.pmprogateway_stripe.php on line 1767

Warning: Cannot modify header information - headers already sent by (output started at ~/public_html/dev/wp-content/plugins/paid-memberships-pro/classes/gateways/class.pmprogateway_stripe.php:1767) in ~/public_html/dev/wp-includes/functions.php on line 6712

Warning: Cannot modify header information - headers already sent by (output started at ~/public_html/dev/wp-content/plugins/paid-memberships-pro/classes/gateways/class.pmprogateway_stripe.php:1767) in ~/public_html/dev/wp-admin/includes/misc.php on line 1310

Warning: Cannot modify header information - headers already sent by (output started at ~/public_html/dev/wp-content/plugins/paid-memberships-pro/classes/gateways/class.pmprogateway_stripe.php:1767) in ~/public_html/dev/wp-admin/admin-header.php on line 9

**Expected behavior**
Headers are handled correctly by the gateway code.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
PMPro Version - 2.7.2
WordPress Version - 5.8.3
PHP Version - 8.0.14
</details>

Any assistance with resolving this bug would be greatly appreciated.

Kind regards,
Jack.

**Comment by raphaelsuzuki** [comment]
Currently facing this very same issue, and waiting for the merge of #1978 since it indeed fixes it.
