### ISSUE TITLE
Formal German Translation Files from a Customer (Heiko)

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#1926]
Attached are two files with the formal German translations a customer sent through email.

[paid-memberships-pro-de_DE_formal.zip](https://github.com/strangerstudios/paid-memberships-pro/files/7952660/paid-memberships-pro-de_DE_formal.zip)

**Comment by andrewlimaza** [comment]
This should be included in next release, I marked it as "Blocking Next Release" as I'm eager to make PMPro as accessible as possible for all user's and customer's.

This status seemed a bit aggressive so removed it but it should be included in next release.

**Comment by ideadude** [comment]
Fixed here https://github.com/strangerstudios/paid-memberships-pro/commit/b0541a63c3eb5ca0e813cb04d66af727b4d4fd73
