### ISSUE TITLE
Duplicate customers in Stripe after SCA challenge

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/paid-memberships-pro#1937]
**Describe the bug**
When a new user checks out using Stripe and fails an SCA challenge, the Stripe Customer created to facilitate that checkout is not being deleted and is not linked to a WordPress user (since the checkout was not completed).

If the user then attempts to check out again, a new Customer will be created in Stripe as we don't have any reference to the original Customer created. This means that there will be duplicate customers in Stripe.

From a PMPro perspective, this should not cause any issues; however, this behavior does cause there to be "empty" customers in the Stripe Customer list.

**To Reproduce**
1. Set gateway to Stripe in Sandbox Mode
2. As a logged out user, purchase a membership with card `4000002760003184`. Will trigger SCA prompt
3. Choose to fail SCA verification
4. Check out again normally
5. See in Stripe that two Customers were created, and that only one of which has a subscription.

**Expected behavior**
There should not be duplicate Customer records in Stripe.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Potential Solutions**
- In a WP Option, save an array of customer IDs that were created but have not completed a checkout. Create a cron to delete those records periodically.
- Use Stripe Customer metadata to track Customers created by PMPro and whether they have completed a payment. Create a cron to delete Customers who were created by PMPro but have not completed a payment. Possible with Stripe Search API

**Comment by hbcondo** [comment]
Thanks for creating this issue, do you know when it will be resolved? The customer counts and reports in Stripe are now inaccurate due to these duplicate customers.

**Comment by dparker1005** [comment]
This is not an issue when using the Stripe Checkout Beta released in PMPro v2.8.
