### ISSUE TITLE
Shipping and Billing not captured

### ISSUE THREAD

**Issue by maxlibin** [strangerstudios/paid-memberships-pro#194]
Using Paypal Standard. any idea i need to modify anything?

**Comment by strangerstudios** [comment]
When PayPal Standard is used, we don't collect billing information locally. Users pay at PayPal and we don't get any information about how they paid.

We don't collect shipping information by default, although you can use the PMPro Shipping addon here:
https://github.com/strangerstudios/pmpro-shipping/blob/master/pmpro-shipping.php

Currently, we don't forward that shipping info to PayPal. It's only saved locally. However, we might in the future update that addon to send the info to PayPal.

We probably won't ever collect billing information on PayPal orders.

Hope this helps to clear things up.
