### ISSUE TITLE
Stripe Gateway ->refund() triggers an error

### ISSUE THREAD

**Issue by mircobabini** [strangerstudios/paid-memberships-pro#1945]
**Describe the bug**
When you try to `->refund()` on a Stripe order:

```php
$morder->Gateway->refund( $morder );
// => Call to undefined method Stripe\Charge::refund()
```

https://github.com/strangerstudios/paid-memberships-pro/blob/7e8db2d7bae942431c9379e43984e87ce1bf535b/classes/gateways/class.pmprogateway_stripe.php#L4324

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by andrewlimaza** [comment]
This should be fixed with PR - https://github.com/strangerstudios/paid-memberships-pro/pull/1948 (Let us know in the PR if it needs more work).

**Comment by mircobabini** [comment]
Yep. Just closed the PR as well.
