### ISSUE TITLE
Stripe webhooks broken in 1.8 -- "cus_XXXX" vs. "sub_XXXX"

### ISSUE THREAD

**Issue by nickd32** [strangerstudios/paid-memberships-pro#196]
Got a major issue here -- all our member orders just renewed for April (all our member accounts renew on the 1st of the month), but no payments are showing up in our WP database.

In Stripe, all the payments went through properly.  But all of the webhooks failed -- giving me a response of "Couldn't find the original subscription" for every single one.

So, digging through the latest entries in the `pmpro_membership_orders` table, I see that all the new orders we've added since upgrading to 1.8 are getting the Stripe Subscription ID (sub_XXXX) placed in the `subscription_transaction_id` column.

On previous versions of PMPro (1.7.x), it appears that the Stripe Customer ID (cus_XXXX) was placed in that column instead.

The problem is that the `stripe-webhook.php` file (specifically the `getOldOrderFromInvoiceEvent()` function) is looking for a cus_XXXX value.

```
// okay, add an invoice. first lookup the user_id from the subscription id passed
$old_order_id = $wpdb->get_var("SELECT id FROM $wpdb->pmpro_membership_orders WHERE subscription_transaction_id = '" . $customer_id . "' AND gateway = 'stripe' ORDER BY timestamp DESC LIMIT 1");
```

Of course, it will never find it, because now all orders have a sub_XXXX value.

I'm guessing this change was to prepare for allowing multiple subscriptions in PMPro v2.0.  But it has broken our membership site at the moment.

I can see two ways to fix this, and I need some input from Jason on his recommendation:
1. In  `class.pmprogateway_stripe.php`, restore the old method of using the cus_XXXX value on all orders again. 
2. Modify the Stripe webhook file to somehow do a cross-reference to find the correct customer ID based on their sub_XXXX number.  (Note: for this to work, you'll probably need to start storing each sub_XXXX ID inside the user meta, in addition to storing the cus_XXXX in the user meta like you're already doing.)

**Comment by nickd32** [comment]
I submitted a fix, using option 2 from my ticket, above. Stripe webhooks will how work with sub_XXXX orders, in addition to cus_XXXX orders.

**Comment by Ninjami-Juho** [comment]
I think there is a similar problem with the event type customer.subscription.deleted. It uses the getUserFromCustomerEvent function. Now the function only looks for the: 
```
$event->data->object->customer
```
and it return the cus_ , I think, in my case should look the sub_ like this:
```
$event->data->object->id
```

The error returned is:

> Stripe tells us a subscription is deleted, but we could not find a user here for that subscription. Could be a subscription managed by a different app or plugin. Event ID #evt_#####################.
-------------


So it doen't find it becase it looks for the cus_, thought it should look for the sub_ in our case. Can nickd32s fix be expanded to fix this too maybe?

I am not totally sure how to fix this myself...

**Comment by strangerstudios** [comment]
I believe this has been fixed. Thanks for your help. Please open a new issue if you run into anything related to this again.
