### ISSUE TITLE
Simple: Notice: Undefined variable: count

### ISSUE THREAD

**Issue by lordspace** [strangerstudios/paid-memberships-pro#198]
Notice: Undefined variable: count in \wp-content\plugins\paid-memberships-pro\adminpages\membershiplevels.php on line 561
Version: 1.8.2.2

That's when I go to: Membership Levels
/wp-admin/admin.php?page=pmpro-membershiplevels

**Comment by eighty20results** [comment]
See proposed fix/pull request #199

**Comment by kimcoleman** [comment]
This has been resolved.
