### ISSUE TITLE
Site Health Gateway Information should show the slug/stored value in case it gets translated

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/paid-memberships-pro#1988]
**Is your feature request related to a problem? Please describe.**
Gateway names currently get translated:

```
pmpro-gateway: Stripe (Ancienne clef)
pmpro-gateway-env: Environnement de production
```

It'll help to see what the gateway slug or ID and environment are (the stored value) as some translations can result in names getting lost or hard to identify in support

**Describe the solution you'd like**
Display the slug/stored value next to it

**Describe alternatives you've considered**
Discussed with dev team, the above will be the preferred option

**Additional context**
N/a

**Comment by andrewlimaza** [comment]
Closing this issue as it has been merged.
