### ISSUE TITLE
PHP 8 Warning - Deprecated:  Required parameter follows optional parameter in class.pmprogateway_stripe.php

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#1995]
**Describe the bug**
When PHP version is 8 or newer the following warning is logged in the debug log. 
PHP Deprecated:  Required parameter $values follows optional parameter $livemode in /path-to-site/wp-content/plugins/paid-memberships-pro/classes/gateways/class.pmprogateway_stripe.php on line 1767

**To Reproduce**
1. Set PHP version on the server to PHP 8 or newer
2. Enable debug and debug logging in wp_config.php
3. Checkout for a paid membership level with Stripe set as the payment gateway
4. FTP into server and navigate to /path-to-site/wp-content/debug.log and view warning in the log file.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

### wp-core ###

version: 5.9.1
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 11
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/customer/www/pmpro.---.com/public_html
wordpress_size: 47.45 MB (49752004 bytes)
uploads_path: /home/customer/www/pmpro.---.com/public_html/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /home/customer/www/pmpro.---.com/public_html/wp-content/themes
themes_size: 11.90 MB (12479115 bytes)
plugins_path: /home/customer/www/pmpro.---.com/public_html/wp-content/plugins
plugins_size: 63.03 MB (66092669 bytes)
database_size: 4.09 MB (4292608 bytes)
total_size: 126.47 MB (132616396 bytes)

### wp-active-theme ###

name: Memberlite (memberlite)
version: 4.5.2
author: Stranger Studios
author_website: https://www.strangerstudios.com
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, menus, automatic-feed-links, title-tag, custom-logo, post-thumbnails, align-wide, html5, post-formats, custom-background, editor-color-palette, editor-style, customize-selective-refresh-widgets, custom-header, infinite-scroll, widgets
theme_path: /home/customer/www/pmpro.---.com/public_html/wp-content/themes/memberlite
auto_update: Disabled

### wp-themes-inactive (5) ###

Twenty Nineteen: version: 2.2, author: the WordPress team, Auto-updates disabled
Twenty Seventeen: version: 2.9, author: the WordPress team, Auto-updates disabled
Twenty Twenty: version: 1.9, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.5, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.1, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (7) ###

Code Snippets: version: 2.14.3, author: Code Snippets Pro, Auto-updates enabled
Paid Memberships Pro: version: 2.7.5, author: Paid Memberships Pro, Auto-updates enabled
Paid Memberships Pro - Gift Levels Add On: version: 1.0.1, author: Stranger Studios, Auto-updates enabled
Paid Memberships Pro - Signup Shortcode Add On: version: 0.3, author: Paid Memberships Pro, Auto-updates enabled
Paid Memberships Pro - Zapier Add On: version: 1.2.0, author: Paid Memberships Pro, Auto-updates disabled
PMPro Generate Checkout Info: version: .1.1, author: David Parker, Auto-updates disabled
WP Mail Logging: version: 1.10.4, author: Wysija, Auto-updates enabled

### wp-plugins-inactive (23) ###

Contact Form 7: version: 5.5.6, author: Takayuki Miyoshi, Auto-updates enabled
Debug Bar: version: 1.1.2, author: wordpressdotorg, Auto-updates enabled
Elementor: version: 3.5.6, author: Elementor.com, Auto-updates enabled
Geolocation IP Detection: version: 5.0.0, author: Yellow Tree (Benjamin Pick), Auto-updates enabled
Import Users from CSV: version: 1.1, author: Andrew Lima, Auto-updates enabled
Kint Debugger: version: 1.2, author: Brian Fegter, Chris Dillon, Auto-updates enabled
Kint PHP Debugger: version: 2.0.2, author: hellofromTonya, Auto-updates enabled
Loco Translate: version: 2.6.0, author: Tim Whitlock, Auto-updates enabled
Mail logging - WP Mail Catcher: version: 1.5.4, author: James Ward, Auto-updates enabled
Nextend Social Login: version: 3.1.4, author: Nextendweb, Auto-updates enabled
Paid Memberships Pro - Add PayPal Express Add On: version: .6, author: Paid Memberships Pro, Auto-updates enabled
Paid Memberships Pro - Affiliates Add On: version: 0.5, author: Paid Memberships Pro, Auto-updates enabled
Paid Memberships Pro - Import Users from CSV Add On: version: .3.4, author: Stranger Studios, Auto-updates enabled
Paid Memberships Pro - Lock Membership Level: version: .3, author: Paid Memberships Pro, Auto-updates enabled
Paid Memberships Pro - Mailchimp Add On: version: 2.3.2, author: Stranger Studios, Auto-updates enabled
Paid Memberships Pro - Member Directory Add On: version: 1.1, author: Paid Memberships Pro, Auto-updates enabled
Paid Memberships Pro - Membership Maps Add On: version: 0.3, author: Paid Memberships Pro, Auto-updates enabled
Paid Memberships Pro - Register Helper Add On: version: 1.7, author: Paid Memberships Pro, Auto-updates enabled
Paid Memberships Pro - Social Login Add On: version: .3, author: Stranger Studios, Auto-updates enabled
SiteGround Optimizer: version: 7.0.6, author: SiteGround, Auto-updates enabled
Weglot Translate: version: 3.6.1, author: Weglot Translate team, Auto-updates enabled
WP Crontrol: version: 1.12.0, author: John Blackbourn & crontributors, Auto-updates enabled
WP Reset: version: 1.95, author: WebFactory Ltd, Auto-updates enabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 3.12.18-clouder0 x86_64
httpd_software: Apache
php_version: 8.0.16 64bit
php_sapi: apache2handler
max_input_variables: 3000
time_limit: 120
memory_limit: 768M
max_input_time: 120
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.66.0 OpenSSL/1.1.1l-fips
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.32-35-log
client_version: mysqlnd 8.0.16
max_allowed_packet: 33554432
max_connections: 500

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/customer/www/pmpro.---.com/public_html/wp-content
WP_PLUGIN_DIR: /home/customer/www/pmpro.---.com/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
0: Writable

</details>

**Moderators Only**: https://www.paidmembershipspro.com/forums/topic/registration-payment-issue-vmws/

**Comment by raphaelsuzuki** [comment]
Apparently related to #1920 and #1978.
