### ISSUE TITLE
Transaction ID/Order code truncated

### ISSUE THREAD

**Issue by corin12355** [strangerstudios/paid-memberships-pro#200]
For versatilitys sake with gateways, the code column pmpro_membership_orders code column length should rather be varchar 255 rather than varchar 10, that way you could possibly allow for developers/users to be able to use either the actual transaction ID from the gateway (without truncating it) or a random code from paid memberships pro.

**Comment by dparker1005** [comment]
That column was updated to `varchar(32)` here: https://github.com/strangerstudios/paid-memberships-pro/commit/4507049fb57293efb974947d0d4b9388c5953727
