### ISSUE TITLE
Bitcoin Payment Gateway

### ISSUE THREAD

**Issue by cryptoapi** [strangerstudios/paid-memberships-pro#201]
Hi,

We have published bitcoin gateway for pmpro on wordpress.org - https://wordpress.org/plugins/gourl-bitcoin-paid-memberships-pro/

Please can you add in your plugin file "/paid-memberships-pro/preheaders/confirmation.php" in line 9 code - && pmpro_getOption("gateway") != "gourl"

Here description - 
https://gourl.io/bitcoin-payments-paid-memberships-pro.html#notes

**Comment by kimcoleman** [comment]
This gateway is available as a separate plugin and will not be included in the core Paid Memberships Pro plugin.

**Comment by cryptoapi** [comment]
You already fixed this issue few years ago.
