### ISSUE TITLE
BUG: Paying with PayPal returns display name as username, rather then First Name Last Name

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/paid-memberships-pro#2028]
**Describe the bug**
When a user checkouts with Stripe or Check, their First Name Last Name is returned as the display name.
But when PayPal Express is used the display name is returned as username.  This happens with default PayPal use and when using the PayPal Express Add On.

**To Reproduce**
1.  Set up a site with Add Name Add on, no billing info.
2. Checkout with PayPal. The display name in the Directory is the username.
john.smith
3. Checkout with Stripe and Display name is First Name Last Name.
John Smith.
4. Install [Force First and Last Name as Display Name](https://wordpress.org/plugins/force-first-last/) same results as above.
Users can use the above plugin to "update" existing members.

**Scre
![Screen Shot 2022-04-15 at 10 45 14 AM](https://user-images.githubusercontent.com/8083630/163585119-b402ddf6-ef12-46e6-87bb-7ce05eb87499.png)
enshots**

**Expected behavior**
Display Name should be set as First Name, Last Name when names are entered.

**WordPress Environment**
WP 5.9.3, 
PMPro 2.7.5,  
Add Name to Checkout Add On 0.6
PHP version  7.4.28

**Comment by mircobabini** [comment]
Nice one. We should check if https://www.paidmembershipspro.com/add-ons/capture-name-address-free-levels-offsite-gateway/ is affected too.

**Comment by kimwhite** [comment]
Thank you @mircobabini ... surprisingly it WORKS if you have that plugin activated.
<img width="886" alt="Screen Shot 2022-04-15 at 1 22 35 PM" src="https://user-images.githubusercontent.com/8083630/163601563-780e5006-213f-4ba8-9d8e-e0fdcb0b99c9.png">

**Comment by mircobabini** [comment]
Thanks for reporting. Gonna investigate the buggy addon then.

**Comment by mircobabini** [comment]
Related to https://github.com/strangerstudios/pmpro-add-name-to-checkout/issues/29

**Comment by mircobabini** [comment]
So, this is happening because the Add Name To Checkout Addon is not hooked to `pmpro_checkout_new_user_array`.

Then, for new users, the `wp_insert_user` is not aware of the first/last name and not populating the display_name.
Also, for logged users, we missed the `update_user_meta display_name` after checkout.

**Comment by pietrodicaprio** [comment]
Hello there, may this bug affect the `$morder` object passed to `pmpro_subscription_payment_completed` and/or `pmpro_after_checkout`?
I use those actions for a custom integration but the `$morder` object looks to be always missing FirstName and LastName.
