### ISSUE TITLE
Non recurring free membership with enddate can be renewed by user

### ISSUE THREAD

**Issue by shr3k** [strangerstudios/paid-memberships-pro#203]
This can be solved in pages/levels.php line 54 by adding pmpro_isLevelFree check:

```
if(!pmpro_isLevelRecurring($current_user->membership_level) && !empty($current_user->membership_level->enddate) && !pmpro_isLevelFree($level))
```

and in pages/account.php line 34 by adding if

```
                                <?php if(!pmpro_isLevelRecurring($current_user->membership_level) && !empty($current_user->membership_level->enddate) && !pmpro_isLevelFree($level)) { ?>
                                    <a href="<?php echo pmpro_url("checkout", "?level=" . $current_user->membership_level->id, "https")?>"><?php _e("Renew", "pmpro");?></a>
                                <? } ?>
```

checkout.php needs to be fixed too to not allowing purchase new free membership from url call.

**Comment by shr3k** [comment]
TYPO: ...to not allowing purchase

**Comment by kimcoleman** [comment]
This is not something we will roll into the core plugin. All levels that have an expiration date allow "Renewal", regardless of if they are free or paid.

If you'd like to off a free membership that can only be used once, see: 
https://www.paidmembershipspro.com/offer-trial-memberships-that-can-only-be-used-once/

If you'd like to have a membership level no longer available for signups after a certain timeframe (i.e. a course with a specific start and end date that will not be available again), you can set the level to not allow signups under Memberships > Membership Levels > Edit Level.
