### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function pmpro_recaptcha_get_html

### ISSUE THREAD

**Issue by mircobabini** [strangerstudios/paid-memberships-pro#2058]
**Describe the bug**
This is happening because that function is not always loaded. Somehow, it happens in production for some people.

**To Reproduce**
```php
/**
 * To replicate the issue:
 * 1) Add this snippet
 * 2) Load the pmpro checkout page
 */
add_action( 'wp_head', function () {
	global $pmpro_pages, $recaptcha;

	// simulate recaptcha turned on
	$recaptcha = 1;

	// we are on the checkout page, good
	if ( pmpro_is_checkout() ) {
		// I want to get the page generated code earlier...
		do_shortcode( get_post( $pmpro_pages['checkout'] )->post_content );

		// ( ! ) Fatal error: Uncaught Error: Call to undefined function pmpro_recaptcha_get_html()
		// in /wp-content/plugins/paid-memberships-pro/pages/checkout.php on line 489
	}
} );
```

**Expected behavior**
We should load the recaptcha lib everywhere to avoid issues.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by andrewlimaza** [comment]
You may load the recaptcha on all instances by adding the following line of code to your custom plugin - `add_action( 'wp', 'pmpro_init_recaptcha', 10 );`

**Comment by mircobabini** [comment]
We discussed a bit on Slack and IRC @ideadude said that moving that function to the functions.php was good, since it's prefixed and there's no reason to load it conditionally. We can maybe enhance the pluggability.

I prepared a PR https://github.com/strangerstudios/paid-memberships-pro/pull/2112/commits and since I was on the functions.php I've also fixed some red highlights for undeclared variables and some docblocks which were messing up with static analyzers.

**Comment by ideadude** [comment]
Slated for 3.0 because this will cause breaking compatibility issues. This is a damned if you do, damned if you don't situation.

I agree with David in the comments of the PR that we should keep the recaptcha stuff in recaptcha.php, but define it in the main scope.

We also have to namespace or prefix the global vars used in all of this code. And do something to avoid conflicts if something else loaded the recaptcha library we include.
