### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by mrleemon** [strangerstudios/paid-memberships-pro#2063]
https://github.com/strangerstudios/paid-memberships-pro/blob/99089e9ef38b85fd358fc4661dc55cd125520641/blocks/membership/block.js#L42

Should "confitional" be "conditional"?

https://github.com/strangerstudios/paid-memberships-pro/blob/99089e9ef38b85fd358fc4661dc55cd125520641/blocks/member-profile-edit/block.js#L20

Should "Dynaimc" be "Dynamic"?

**Comment by mircobabini** [comment]
For sure. Thanks for reporting.

**Comment by mrleemon** [comment]
Another one:

https://github.com/strangerstudios/paid-memberships-pro/blob/99089e9ef38b85fd358fc4661dc55cd125520641/blocks/account-profile-section/block.js#L24

"their change password" => "change their password"

**Comment by mrleemon** [comment]
https://github.com/strangerstudios/paid-memberships-pro/blob/99089e9ef38b85fd358fc4661dc55cd125520641/blocks/login/block.js#L26

"loast" => "lost"

**Comment by mircobabini** [comment]
> "loast" => "lost"

Added to the PR.
