### ISSUE TITLE
Boleto payments

### ISSUE THREAD

**Issue by kerijacoby** [strangerstudios/paid-memberships-pro#2096]
Allow users to accept payment via Boleto which is an official (regulated by the Central Bank of Brazil) payment method in Brazil.
https://stripe.com/docs/payments/boleto

Requested in ticket #422823 (moderators only)

**Comment by andrewlimaza** [comment]
Closing this one out, as Stripe Checkout is now fully supported by Paid Memberships Pro and can be used with various payment methods.
