### ISSUE TITLE
Enable shortcodes for TOS Page's content

### ISSUE THREAD

**Issue by cliffordp** [strangerstudios/paid-memberships-pro#211]
Change https://github.com/strangerstudios/paid-memberships-pro/blob/dev/pages/checkout.php#L670 to
from
`<?php echo wpautop($tospage->post_content)?>`
to
`<?php echo wpautop(do_shortcode($tospage->post_content))?>`
(I tried to do a pull request but the preview showed the entire file red and the entire file green, making it impossible to see this single line change.)

https://wordpress.org/plugins/auto-terms-of-service-and-privacy-policy/ can auto-create Terms of Service (I'm the author). The addition of `do_shortcode()` enables shortcodes to work when inserting the chosen WP page's content.

Screenshots:
- PMP settings page: ![screen shot 2015-05-18 at 3 03 54 pm](https://cloud.githubusercontent.com/assets/1812179/7689228/50111bde-fd70-11e4-9952-595361ce7e66.png)
- before code change: 
  ![screen shot 2015-05-18 at 3 02 17 pm](https://cloud.githubusercontent.com/assets/1812179/7689231/574ef150-fd70-11e4-862f-a3b14caa4381.png)
- after code change: 
  ![screen shot 2015-05-18 at 3 01 35 pm](https://cloud.githubusercontent.com/assets/1812179/7689236/5cb592e8-fd70-11e4-8db2-f22366fbdd9f.png)

**Comment by strangerstudios** [comment]
Adding this into the 1.8.4.2 release going out soon. Silly that I did a whitespace pass on the whole code base to avoid that diff issue and I think it might be causing it here.

Did you do a pull against the latest repo before making your change?

**Comment by cliffordp** [comment]
Thanks for including.
Yes, I did off latest master. (Fork, Edit, Pull Request... but didn't submit the Pull)
