### ISSUE TITLE
!!levels_url!! variable present in checkout email instead of levels page URL 

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/paid-memberships-pro#2118]
**Describe the bug**
!!levels_url!! variable present in checkout email

**To Reproduce**
1. Purchase a membership or test **Checkout - Paid** email template
2. Read the email 
4. See !!levels_url!! variable present

**Screenshots**

![image](https://user-images.githubusercontent.com/4752949/170788925-0d318a42-7adc-4008-b53e-587b7581f690.png)

**Expected behavior**
The levels page URL should show.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.8.3, Memberlite 4.5.2, WordPress 6.0, and PHP 7.4.1
```
</details>

**Comment by andrewlimaza** [comment]
I am working on this, a PR should be available shortly.
