### ISSUE TITLE
Level cost text displays trial amount as free

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#2143]
**Describe the bug**
When setting a custom trial for a level and the trial period has a trial payment greater than 0 the level cost text is displayed as _your first payment is Free_ instead of the trial payment amount.

The logic that determines the trial cost text seems to work in the opposite as expected.

https://github.com/strangerstudios/paid-memberships-pro/blob/70cefd38cad3ee07e0bae4cc85ee1b1000bba24c/includes/functions.php#L446-L461

[if ( (float)$level->trial_amount > 0 )](https://github.com/strangerstudios/paid-memberships-pro/blob/70cefd38cad3ee07e0bae4cc85ee1b1000bba24c/includes/functions.php#L448) checks if the trial amount is greater than 0, (trial amount is not free), and if this is true returns cost text that's stating the trial amount is free.

The level cost  is still calculated correctly and reflects correctly at the payment gateway (PayPal Express used during testing)

**To Reproduce**
1. Go to Memberships > Settings > Payment Gateway and set up a PayPal Express sandbox account.
2. Go to Go to Memberships > Settings > Levels and create a new level
3. Set the level billing:
	3.1. Initial Payment 49
	3.2 Recurring 290 per 6 months
	3.3 Check Custom Trial
	3.4 Trial Billing Amount 145 for the first 1 subscription payments.
5. Save level and see level cost text: 

> $49.00 now and then $290.00 every 6 Months. After your initial payment, your first payment is Free.

**Screenshots**

-----

Level Settings - Billing

![220629-1656498259](https://user-images.githubusercontent.com/9744519/176414595-a37efe98-7d93-4373-b70b-dca02ea06586.png)

-----

Level Cost Text (Checkout)

![220629-1656498228](https://user-images.githubusercontent.com/9744519/176414663-385f83ed-16fe-4ac4-859f-aa54d54eda77.png)

-----

Level cost correct at payment gateway:

![220629-1656469965](https://user-images.githubusercontent.com/9744519/176413043-2347482d-321b-4cfb-b5bb-8f920e1aace8.png)

-----

**Expected behavior**
Level cost text to display the trial payment amount instead of _Free_

> The price for membership is $49.00 now and then $290.00 every 6 Months. After your initial payment, your first payment will cost $145.00.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Moderators Only**
Support ticket: #430413

**Comment by kimwhite** [comment]
Another user with this issue. Have replicated on test site. Work around until fixed use **Custom Level Cost Text** add on.
