### ISSUE TITLE
How to customize terms?

### ISSUE THREAD

**Issue by helloworld-616** [strangerstudios/paid-memberships-pro#2146]
How to customize terms inside the plugin?

**Comment by helloworld-616** [comment]
How can i also get all the shortcode recipes?

**Comment by andrewlimaza** [comment]
Hi @helloworld-616 

You may download any of our Add Ons on Github, or visit https://www.paidmembershipspro.com/free

To change wording in the plugin, I recommend using the `gettext` filter WordPress provides to replace certain terms to your needs, similar to this guide -  https://www.paidmembershipspro.com/using-str_replace-change-plugin-generated-language/

Please note that Github isn't used for support but bug reporting, if you need help with this please do not hesitate to reach out via https://www.paidmembershipspro.com/support

Thank you for understanding.

**Comment by helloworld-616** [comment]
I can't access the link

**Comment by michaelbeil** [comment]
Hey @helloworld-616, please reach out for pre-sales questions and general inquiries through our [contact form](https://www.paidmembershipspro.com/contact/).
