### ISSUE TITLE
PHP notice when clicking cancel

### ISSUE THREAD

**Issue by sumobi** [strangerstudios/paid-memberships-pro#216]
If a user happens to find and click the `Membership Cancel` page while logged out, this notice is displayed:

    PHP Notice:  Trying to get property of non-object in /wp-content/plugins/paid-memberships-pro/pages/cancel.php on line 44

Latest PMP + WP

**Comment by strangerstudios** [comment]
The cancel page shouldn't load if the user isn't a member (or is logged out). See the code in the preheader here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/preheaders/cancel.php#L10-L13

Maybe there is something on your system blocking that redirect?

**Comment by sumobi** [comment]
@strangerstudios interesting, I'll dig deeper and report back
