### ISSUE TITLE
Add PMPro Restrict Tab Support for New Elementor Container Element

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/paid-memberships-pro#2168]
Elementor has pushed out what [they call containers](https://elementor.com/help/container-element/) - we should integrate the PMPro restrict settings to show on the "container element" advanced settings tab as well.

**Comment by MaryOJob** [comment]
Moderators Only: #433080

**Comment by ipokkel** [comment]
Moderators Only: #446423

**Comment by michaelbeil** [comment]
A customer could use this (ticket 467403):

>I can see the “Required Memberships” meta box on my product admin pages and I can also see how to restrict certain elements on my page by using Elementor. The main issue is that I am using an Elementor single product template that is then used for all my products. I would like certain products to be restricted to certain members, so I cannot do this to my Elementor single product template sections as it would then restrict only sections in the product page and not the entire product page from being accessed in the first place. And it would then also apply these restrictions to all my products instead of just the specific ones I need it to be applied to.

**Comment by andrewlimaza** [comment]
This is supported, I can confirm that the Paid Memberships Pro option is showing on container elements.
![Uploading Screenshot 2024-02-19 at 15.43.55.png…]()
