### ISSUE TITLE
Form UI improvements

### ISSUE THREAD

**Issue by amdrew** [strangerstudios/paid-memberships-pro#217]
On the default 2015 theme the form labels wrap onto 3 lines:

![screen shot 2015-05-22 at 2 10 42 pm](https://cloud.githubusercontent.com/assets/52581/7762844/8b30a3a0-008c-11e5-887d-c4f16b977868.png)

Looking at frontend.css there's a width of 120px.

![screen shot 2015-05-22 at 2 14 04 pm](https://cloud.githubusercontent.com/assets/52581/7762868/d9e4ffdc-008c-11e5-8689-c70e379d9fec.png)

Unless there's a reason I've missed I propose removing the `width: 120px` along with the `float: left` and `text-align: right`.

After: 

![screen shot 2015-05-22 at 2 15 23 pm](https://cloud.githubusercontent.com/assets/52581/7762889/0281670a-008d-11e5-9622-a067e42dac81.png)

Asterisks, should they be on the same line as the labels?

Latest versions of PMP, WP, 2015.

**Comment by strangerstudios** [comment]
Ah. I hadn't looked at this in 2015. It stinks that it looks this way. I actually like 2015 more than the previous default themes.

I'm going to have our designer take a look and see if we can detect 2015 (or themes like it) and account for some of this.

FWIW, you can get over these things using custom CSS. Feel free to post to our member forums if you need the CSS for a specific site quickly.

**Comment by sumobi** [comment]
@strangerstudios no urgency, picked PMP for our weekly contributor day. Do you feel that the labels need to have a fixed width? In my opinion it would be much better (and compatible with more themes) if the width was removed entirely.

**Comment by kimcoleman** [comment]
This is fixed with the new table-free form layout design. See demo at:

http://demo.paidmembershipspro.com/twentyfifteen/membership-account/membership-checkout/?level=2
