### ISSUE TITLE
Required user fields not showing required asterisk

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#2180]
**Describe the bug**
When a User Field is added and set as required the required indicator asterisk is not displayed.

The `pmpro_checkout-field-hide-required` class is incorrectly added to the wrapper div for required fields.

```HTML
<div id="example_name_div" class="pmpro_checkout-field  pmpro_checkout-field-required pmpro_checkout-field-hide-required pmpro_checkout-field-text">
```

`$show_required` is set here:

https://github.com/strangerstudios/paid-memberships-pro/blob/9daa3614567b1b6b4a241dca74b6c7ae4434bc69/classes/class-pmpro-field.php#L88

The conditional argument that adds the class is looking for a `showrequired` attribute instead of `show_required` here:

https://github.com/strangerstudios/paid-memberships-pro/blob/9daa3614567b1b6b4a241dca74b6c7ae4434bc69/classes/class-pmpro-field.php#L1234

**To Reproduce**
1. Go to **Memberships > Settings > User Fields** and add a field and set the _Required_ option to _Yes_ and save.
2. Navigate to the checkout page.
3. See error.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
paid-memberships-pro v2.9.1
```
</details>

**Comment by ideadude** [comment]
Fixed here: https://github.com/strangerstudios/paid-memberships-pro/commit/75069383e71f021ddad41d7b5abbffcf932a8fb0
