### ISSUE TITLE
BUG: Create a New Level - Level templates, not available until after first level is created.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/paid-memberships-pro#2181]
**Describe the bug**
The prompt for creating a new level does not appear until after you have created the first level.

**To Reproduce**
1. New install of PMPro
2. Click on Create Level on PMPro Dashboard or the button that appears when there are no levels
3. No Level Template appears

**Screenshots**
https://capture.dropbox.com/Nka2h7nCNFP5dhbi

**Expected behavior**
When you click "Create a Membership Level" the Levels Template (popup) should appear.

**Comment by andrewlimaza** [comment]
Fix is coming out in new release. 👍
