### ISSUE TITLE
Fatal Error: Call to undefined function pmprorh_sanitize

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#2182]
**Describe the bug**
If the checkout registration form contains a date user field a fatal error is triggered on submit if the Register Helper Add On is not active:
`PHP Fatal error:  Uncaught Error: Call to undefined function pmprorh_sanitize()`

https://github.com/strangerstudios/paid-memberships-pro/blob/9daa3614567b1b6b4a241dca74b6c7ae4434bc69/classes/class-pmpro-field.php#L621

**To Reproduce**

1. Install and configure the Paid Memberships Pro plugin
2. Go to **Memberships > Settings > User fields** and create a required date field.
3. Go to the checkout page and register a new member.
4. See error.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by andrewlimaza** [comment]
Closing this as PR has been merged and queued up for release soon.
