### ISSUE TITLE
User Field group ID not formatted 

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#2183]
**Describe the bug**
When a field group is created, the group label is used as the selector ID, e.g. if the group name is More Information the ID rendered is `pmpro_checkout_box-More Information`  instead of `pmpro_checkout_box-more-information`.

**To Reproduce**

1. Go to Memberships > Settings > User Fields
2. Set Group Name to More Information.
3. Add any field type and save all settings
4. Navigate to checkout and user browser tools to inspect ID assigned for the group's  wrapping DIV.

**Screenshots**

![220727-1658913743](https://user-images.githubusercontent.com/9744519/182312086-c77bf31f-8a33-4595-8426-55acdbf309f4.png)

**Expected behavior**

Field Group IDs are formatted according to coding standards to allow easier selection via JavaScript/CSS and the possibility to add fields programmatically to a field group.

We could consider formatting the group ID with [pmpro_format_field_name](https://github.com/strangerstudios/paid-memberships-pro/blob/7095907c33bdcc486feb606c8d4f93af820dfb0f/includes/functions.php#L4289) as we do for the [field name](https://github.com/strangerstudios/paid-memberships-pro/blob/7095907c33bdcc486feb606c8d4f93af820dfb0f/adminpages/userfields.php#L29).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by andrewlimaza** [comment]
This has been fixed in the latest version of PMPro.
