### ISSUE TITLE
2 account page select menus shown

### ISSUE THREAD

**Issue by sumobi** [strangerstudios/paid-memberships-pro#219]
After letting the plugin install the required pages I'm seeing 2 Account page select menus:

![screen shot 2015-05-22 at 5 12 59 pm](https://cloud.githubusercontent.com/assets/52581/7764454/e3c37b00-00a5-11e5-81ae-337ce5ddbd04.png)

Only 1 page was added as expected:

![screen shot 2015-05-22 at 5 14 50 pm](https://cloud.githubusercontent.com/assets/52581/7764477/277252b8-00a6-11e5-884d-5981a6e4604b.png)

Fresh install, latest PMP and WP

**Comment by strangerstudios** [comment]
Issue cropped up when merging in a pull request. A fix is going out in 1.8.4.2 very soon. Thanks.
