### ISSUE TITLE
Visits, Views, and Logins Report Export CSV limited to 15 values only.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#2193]
**Describe the bug**
When the _Visits, Views, and Logins_ report is exported to CSV only 15 values included in the CSV

**To Reproduce**
1. Go to **Memberships > Reports**
2. Click on Details button lin in the _Visits, Views, and Logins_
3. Click on _Export to CSV_

**Expected behavior**
All values to be included in the exported report.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by ipokkel** [comment]
Moderators Only: Ticket #437402

**Comment by andrewlimaza** [comment]
Upon further investigation, we only show 15 records by default as we store details in a transient and a large data set would cause errors as transients can store a limited amount of characters.

There's no ETA on this one but we're looking into it and will fix this soon! :)

**Comment by michaelbeil** [comment]
Another customer (ticket 448220) is running into this.

**Comment by kimwhite** [comment]
Another customer (ticket 466376) is running into this.

**Comment by JarrydLong** [comment]
Note that you can add wp-admin/admin-ajax.php?action=login_report_csv&l=all or wp-admin/admin-ajax.php?action=login_report_csv&l=50 to the report URL and call it like this to get more results than 15 in the CSV file.

**Comment by michaelbeil** [comment]
Another customer (ticket 473400) is running into this.

**Comment by michaelbeil** [comment]
Another customer (ticket 480759) is experiencing this.

**Comment by michaelbeil** [comment]
Another customer (ticket 481538) is running this.
