### ISSUE TITLE
Membership Required Block setting lost on update/save

### ISSUE THREAD

**Issue by nickpagz** [strangerstudios/paid-memberships-pro#2243]
**Describe the bug**
The Membership Required Block has a setting for displaying a message for non-members, specifically the setting `What should users without access see?`.
If this is set as `Show the "no access" message.` setting, the setting is reverted to `Show nothing` on subsequent post edits and updates.

**To Reproduce**
1. Start a new post.
2. Insert a new Membership Required Block.
3. Set the `What should users without access see?` option to `Show the "no access" message.`.
4. Save the post draft or publish it.
5. Exit back to the dashboard.
6. Click to edit the post.
7. Save the draft or click on Update.
8. Notice the option `What should users without access see?` reverts to `Show nothing`.

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.

**Expected behavior**
I expected the setting to be maintained regardless of other changes made on the post. It appears the prop for this setting is not properly parsed when loaded in the editor, and then overridden on a subsequent save.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

- WordPress 6.02
- Paid Memberships Pro 2.9.5
- Other installed and active plugins: Jetpack 11.4-a.3, Akismet 5.0
- Theme is Twenty Twenty-One version 1.6

</details>

**Comment by andrewlimaza** [comment]
Thank you for your patience @nickpagz, I've made a change to the attribute which fixes this issue and should be included in the next release.

If you are okay with development, you may pull this change and run npm to rebuild the Javascript for the block should you need it urgently.

**Comment by nickpagz** [comment]
Thanks @andrewlimaza ! No urgency right now, so I'll wait for the next release.
