### ISSUE TITLE
PMP Bug: holds onto category-level membership required

### ISSUE THREAD

**Issue by rnikoley** [strangerstudios/paid-memberships-pro#2257]
I use categories to determine whether posts are for paid, free members, or public. I don't use "require membership."

If I have it set public or free for some period of time, it works as expected. I use custom excerpts as well.

I later I go to change a category from a public one to a free or paid, or free to paid, then PMP holds onto the previous category and serves up just as before.

Example just now. I had a post that was for free members with custom excerpt for the last 10 days. I went to put it behind the paywall, so simply switched the category from "Free Stuff Member" to one of the several categories that are for Paid Only. Nothing changed, except in Chrome from where I did the edits. On Safari and Opera, nothing worked. I cleared server caches, cleared browser caches, nothing.

What worked, I went in and disabled the PMP plugin, then re-activated, and that fixed it.

Should be easy to duplicate unless the issue is with my system exclusively.

I looked for but did not find any way to refresh PMP's own cache or whatever it uses.

**Comment by rnikoley** [comment]
Update: I've since found that PMP also holds onto whatever is in your custom or manual excerpt if you go back and edit it. You have to go deactivate and reactivate PMP plugin to fix it.

It's an easy fix, but it is a time-consuming bug...especially until you figure out the fix.

**Comment by rnikoley** [comment]
...In continued testing and experience, I am finding that ANY change whatsoever to assigned category OR edit to the manual/custom excerpt requires a "restart" of the PMP plugin.

Quite amazing that zero people have an interest in this issue.

It's a really sucky bug and easy to reproduce (at least on my system).

**Comment by andrewlimaza** [comment]
Hi @rnikoley 

Thanks for reposting this, I closed your previous Github issue as it didn't post correctly.

I have tested this and it's working as intended. These are the steps I have taken:

* Created a post that had no require membership (open to the public).
* Viewed the post, logged-in as a member and still all works fine. (With level 1)
* Restricted this post to a category which is linked to level 2 (so I shouldn't have access and be able to view it).
* Loaded the post and it is immediately restricted.

The same goes for the reverse of this by going from restricted categories to open categories. I'm not sure what would cause this caching if you visit the post in question (before restarting PMPro) could you try adding a random query parameter to your page's URL such as `?rnikoley=1` and reload the page to see if you get access or it restricts correctly depending on your test.

It sounds like caching may be interfering somewhere, our support team would be more than happy to help troubleshoot this further as it seems to be an issue isolated to your particular site - https://www.paidmembershipspro.com/support

Please let me know if there are any other specific steps I need to take.

**Comment by rnikoley** [comment]
It could be that this is only an issue when using custom excerpts, which I use heavily.

**Comment by rnikoley** [comment]
I don't often take a post from public or free member to a paid category anyway, so this is a relatively minor issue anyway.

**Comment by andrewlimaza** [comment]
I have tried with custom excerpts as well, I haven't been able to replicate it when switching between restricted categories. Our support team may be able to dig into this deeper with you.

**Comment by rnikoley** [comment]
I should stipulate that this ONLY is an issue when the post is restricted to a member level (free or paid) and it's a logged out non-member or logged out member and there is a custom excerpt.

In other other words, the real issue is:

If logged out so you can ONLY see the custom excerpt, any edits to that custom excerpt do not take for anyone logged out (member or non-member), irrespective of browser or clearing caches. I did try the random parameter appended to the end of the URL and that DID work to show me the excerpt in edited form.

**Comment by rnikoley** [comment]
OK, I went ahead and did a demo video so you can clearly see what's up. Over the 10mb limit here, so I put it on YouTube, unlisted.

https://youtu.be/RcjWDjtesz8

Take a look. I think I covered evertything.

**Comment by rnikoley** [comment]
If anyone is still listening I have discovered an additional logged in / logged out display issue.

PMP checkout buttons.

Wherever you put them in a post requiring membership (such as in the custom excerpt...how I use them), they only display if the reader is a member and is logged in. If just a random guy off the street, They don't display.

Kinda defeats their whole purpose. So really ironically funny.

EXCEPT...If it is a PUBLIC post, i.e., no involvement with PMP. Then they display fine whether logged in or logged out.

**Comment by andrewlimaza** [comment]
@rnikoley thanks for your patience, Github isn't used for support threads and we may take a while to attend to bug reports. If you need faster replies, you may open a support ticket on www.paidmembershipspro.com/support and a dedicated support person may help you through any site specific issues.

I've watched your video and I haven't been able to replicate the issue, and this seems to be due to caching of sorts. You are using SG Optimizer (Sitegrounds caching plugin) and you may work through this guide to ensure caching is correctly setup for your site with dynamic content / membership content - https://www.paidmembershipspro.com/documentation/advanced/caching/

Here is a fullpage screenshot, it shows that it's restricting correctly on my end.
![www freetheanimal com_2022_10_eat-food-not-too-much-mostly-food html](https://user-images.githubusercontent.com/12629136/199947134-a3cfe23b-3ed9-4116-8fda-a2ea33e451a4.png)

> PMP checkout buttons. Wherever you put them in a post requiring membership (such as in the custom excerpt...how I use them), they only display if the reader is a member and is logged in. If just a random guy off the street, They don't display.

I'm not sure I understand this request, how are you inserting the checkout buttons into the excerpt? It seems you're copying the Block HTML and inserting it into a custom excerpt?

**Comment by andrewlimaza** [comment]
Another way to test this URL is to view it in private or incognito browsing or separate devices to confirm that it's happening across all instances. I do suspect that caching may be involved here.

**Comment by rnikoley** [comment]
I’ll look into those caching issues and may disable Site Ground’s CDN and use the W3 Plugin instead. Makes sense. However, I should note that for some time I had no caching whatsoever and was still getting these issues.

Anyway, I’ll investigate further.

Regarding checkout buttons, yes, exactly. I go to the code editor and copy/paste the code into the excerpt. Has always worked. This issue seems to coincide with updating WP to 6.1.

At any rate, I only recently began using the checkout buttons, always used the shortcode as in your clipped image,  below. It was simple enough to go back and replace all the buttons with the checkout shortcode and I’ll just use that from here out.

Thanks.

--
Richard Nikoley
***@***.***
https://FreeTheAnimal.com
https://YouTube.com/c/RichardNikoley

**Comment by andrewlimaza** [comment]
Because there have not been any recent updates to this issue, we will be changing the status to closed.

If this issue is not resolved, please do not hesitate to reply to this conversation to get it re-opened.
