### ISSUE TITLE
Tag 2.9.6 was made on same commit of Tag 2.9.5

### ISSUE THREAD

**Issue by Kilbourne** [strangerstudios/paid-memberships-pro#2283]
https://github.com/strangerstudios/paid-memberships-pro/compare/2.9.5...2.9.6

**Comment by Kilbourne** [comment]
but the release is ok

**Comment by andrewlimaza** [comment]
Thanks for letting us know about this @Kilbourne, we will monitor future tags. You may always download the release from WordPress.org for a specific version.
