### ISSUE TITLE
Redirect loop to pmpro-dashboard on expired session

### ISSUE THREAD

**Issue by androidacy-user** [strangerstudios/paid-memberships-pro#2286]
**Describe the bug**
Whenever an admin session expires and the admin has to login again, PMPro keeps continuously redirecting to `/wp-admin/admin.php?page=pmpro-dashboard` in a loop until cookies are cleared.

**To Reproduce**
1. Have an expired session
2. Re-login
3. See pmpro keep redirecting to the above mentioned page in a loop.

**Screenshots**
n/a

**Expected behavior**
Redirects to admin dashboard instead of PMPro dashboard

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WP: 6,1,1

Server: Ubuntu 22.04 w/ OpenLiteSpeed 1.17.1, behind Cloudflare load balancer

PHP: LSPHP 8.1.9

PMPro: 2.9.6
```
</details>

**Comment by andrewlimaza** [comment]
@androidacy-user are you still facing this issue? I haven't been able to replicate this issue.

This sounds like your update_option isn't firing for some reason - please ensure that there's no caching happening within the WordPress dashboard side.

Any other information to help me replicate this issue may help here, but it sounds site specific.

What you can do to permanently stop this is to add this line of code to your custom plugin/child theme - 

`remove_action( 'admin_init', 'pmpro_admin_init_redirect_to_dashboard' );`

**Comment by andrewlimaza** [comment]
Thanks, it should only ever redirect you there once and Hummingbird must have been interfering with the option update call that occurs. I'm glad to hear you have figured this out. 

I'm going to close this issue out, you may use the snippet I've mentioned to totally disable this logic.

**Comment by andrewlimaza** [comment]
I forgot to add in that we're reworking this in a future version - as mentioned you can use the code recipe I shared to disable it completely as I have no ETA when this will be available.

Thanks for understanding.
