### ISSUE TITLE
The column headers in the member list are not localized

### ISSUE THREAD

**Issue by mrleemon** [strangerstudios/paid-memberships-pro#2294]
**Describe the bug**
The column headers in the member list (`/wp-admin/admin.php?page=pmpro-memberslist`) are not localized:

https://github.com/strangerstudios/paid-memberships-pro/blob/1a7eac544bf037ca8f3479682918782a3f883603/classes/class-pmpro-members-list-table.php#L74

**To Reproduce**
1. Set the language of your site to other than English (for example, Spanish)
2. Go to `www.example.com/wp-admin/admin.php?page=pmpro-memberslist`
3. See that the column headers are still in English

**Screenshots**
![cols](https://user-images.githubusercontent.com/2060659/205431621-2de5b9d3-3b51-46ec-b72d-05599024789a.jpg)

**Expected behavior**
The column names should be in the language set in the WP settings

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP 6.1.1

**Comment by mircobabini** [comment]
Thanks, found a few other not-i18n strings:

https://github.com/strangerstudios/paid-memberships-pro/blob/ff18b4d99c2b1fc14f92f370c60f6dd675096e44/adminpages/discountcodes.php#L930

https://github.com/strangerstudios/paid-memberships-pro/blob/ff18b4d99c2b1fc14f92f370c60f6dd675096e44/adminpages/discountcodes.php#L956

And others from recent releases. Gonna prepare a PR soon.

**Comment by mircobabini** [comment]
Nice, thanks @mrleemon, adding those as well.

**Comment by mircobabini** [comment]
Wrong text domain here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/adminpages/dashboard.php#L265
