### ISSUE TITLE
Phone formatting off for the United Kingdom 

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/paid-memberships-pro#2304]
**Describe the bug**
Phone formatting is off for the United Kingdom.

**To Reproduce**
1. Go to page
2. Type in a phone number
3. Please check out
4. The formatting is off

**Screenshot**

![image](https://user-images.githubusercontent.com/4752949/206519942-751fcb46-92be-42d1-9053-6c65fdd49b98.png)

e.g. 0 (738) 504-6589

**Expected behavior**
Display the correct phone formatting for the United Kingdom. Here is an article on phone number format in the UK: https://britishnumbers.com/blog/what-is-the-uk-phone-number-format/. This would require updating the `formatPhone` function. Set it up so if the numbers are X, the expected output is exactly Y for each permutation that might come up in the UK (e.g. with or without a leading 0). 

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).

This came up in ticket 462140.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.9.7, WordPress 6.1.1, PHP 8.0.26 
```
</details>

**Comment by JadeResources** [comment]
I faced a similar problem, the trouble is there are multiple formats for UK Phone numbers depending on location within the UK some are formatted as 01234 567890 while others are formatted as 0123 456 7890. Currently I have my own function for formatting the phone number in the format of 01234 567890

**Comment by andrewlimaza** [comment]
Here is an article that allows you to override the phone formatting in PMPro -> https://www.paidmembershipspro.com/how-to-format-the-member-phone-number-field-using-a-filter/

**Comment by michaelbeil** [comment]
That article resolves this
