### ISSUE TITLE
need a way to access reply from cybersource: invalidField_0...N for the invalid fields.

### ISSUE THREAD

**Issue by lvnilesh** [strangerstudios/paid-memberships-pro#231]
Thanks for a great plugin.

I installed dev branch from 3 hours ago in a new wordpress deployment - setup two membership levels 1, free another non-free with $1 monthly membership. connected with cybersource SOAP toolkit and generated a new transaction security key - set cybersource in production under pmpro

and then I tried to buy a membership  and got this error.

```
One or more fields in the request contains invalid data. Check that your billing address is valid.
```

This seems to map to error 102 in cybersource http://apps.cybersource.com/library/documentation/dev_guides/AFS_IG/html/soap_api.htm
which is hinting at `invalidField_0...N`

Appreciate if you can please guide on a way to locate the response back from cybersource so I can identify what data cybersource is finding invalid.

```
102
One or more fields in the request contains invalid data.
Possible action: See the reply fields invalidField_0...N for the invalid fields. Resend the request with the correct information.
```

**Comment by lvnilesh** [comment]
I tried multiple times with the same mastercard and cybersource transaction search detail consistently says:
```
Reason Code	102 
Reply Message	The field is invalid: card_type 
```

Is the plugin sending incorrect card_type?

**Comment by ideadude** [comment]
Not sure if we got to this one back in 2015, but we need to test the Cybersource integration and make sure it's working as intended.fffffffffff
