### ISSUE TITLE
PHP warnings when cron runs from command line

### ISSUE THREAD

**Issue by robwent** [strangerstudios/paid-memberships-pro#232]
Hi,
I recently turned off the wordpress cron to run it manually every hour but I keep getting php warning errors every time it runs.

```
PHP Warning:  session_start(): Cannot send session cookie - headers already sent in .../wp-content/plugins/paid-memberships-pro/paid-memberships-pro.php on line 27
PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent in .../wp-content/plugins/paid-memberships-pro/paid-memberships-pro.php on line 27
```

The cron I set up just calls the wp-cron.php file using curl.

As far as I can see, the lines giving the warnings should be checking if the cron was run by command line:

```
//if the session has been started yet, start it (ignore if running from command line)
if(defined('STDIN') )
{
    //command line
}
 else {
//warning
```

I see in wp-cron.php that DOING_CRON gets defined but assume that this couldn't be added as a check as it would break sites that don't have the standard cron disabled?

**Comment by strangerstudios** [comment]
We could add check for ?nosessions=1 or something like that that you could add to your cron URL.

Or I think it might be okay to not load the session when DOING_CRON depending on when WP runs WP_CRON. I think it might be contained to certain instances (e.g. homepage loads) or otherwise load via JS or something like that. I haven't looked at that code in a while.

**Comment by robwent** [comment]
At the moment I have added another defined for DOING_CRON and haven't had any more warnings through.
Not sure how best to check if everything's still running when using the wordpress cron and that check?

**Comment by robwent** [comment]
I'm getting a cron notification when pmpro fires off some reminder emails but not about the header warning s so seems to be working for me with a manual cron.

    //if the session has been started yet, start it (ignore if running from command line)
    if(defined('STDIN') || defined('DOING_CRON') )
    {
	//command line
    }

**Comment by ideadude** [comment]
Should be fixed here now https://github.com/strangerstudios/paid-memberships-pro/commit/f209525f316fdb0524731cd3125aa3411c9f472b#diff-b12ec92b8da06e8d4cfc3010ceffc3460f6ad02f274d7e65af71765f24794455
