### ISSUE TITLE
Orders table in dashboard/admin overlapping on mobile.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#2323]
**Describe the bug**
The Orders table within the WordPress dashboard has overlapping data/doesn't handle mobile view well.  See the screenshot below.

**To Reproduce**
1. Go to Memberships > Orders with a mobile device with a smaller screen such as iPhone 8/Android equivalent.

**Screenshots**
![IMG_6484](https://user-images.githubusercontent.com/12629136/210597877-fd9d180e-648d-41ee-b22f-ddd8d7351694.jpg)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by ideadude** [comment]
Fixed here: https://github.com/strangerstudios/paid-memberships-pro/pull/2334
