### ISSUE TITLE
pmpro_get_order_json returns an empty json string

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#2329]
**Describe the bug**
function `pmpro_get_order_json` returns an empty JSON string: `{}` instead of an order object converted to JSON.

For example, the email order popup uses this function to obtain the email address related to the order but is unable to achieve this due to no data inside the JSON created.

https://github.com/strangerstudios/paid-memberships-pro/blob/0ba2ce17a75ded52fd51770a383298f754acf561/includes/services.php#L116-L126

**To Reproduce**
1. Go to Memberships > Orders
2. Click on the "Email" link
3. See the error

**Expected behavior**
`pmpro_get_order_json` to return order data in json format.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress version: 6.1.1
PHP version: 7.4.30
Paid Memberships Pro version: 2.9.8
```
</details>

Moderators: #470324

**Comment by ideadude** [comment]
Fixed here: https://github.com/strangerstudios/paid-memberships-pro/pull/2340

Thanks!
