### ISSUE TITLE
Enahncement: Provide customized login error messages

### ISSUE THREAD

**Issue by dwanjuki** [strangerstudios/paid-memberships-pro#2359]
When one attempts to login using the PMPro login form with an email that's not registered on the site, there's a generic error response: "There was a problem with your username or password." 

A more specific error message notifying the user that there are no accounts matching the email would be helpful. This is how the default WordPress login handles this case.

Screenshots:
![WordPress login](https://user-images.githubusercontent.com/123358258/216552270-a1a76540-5fb3-454f-8f17-8ab66f4cd7b6.png)
![PMPro frontend login](https://user-images.githubusercontent.com/123358258/216552593-882006b4-f06b-4359-a118-baa9987a91b1.JPG)

**Comment by mircobabini** [comment]
> A more specific error message notifying the user that there are no accounts matching the email would be helpful.

There are plugins out there which aims to hide the fact an account exists/not-exist. If we change it the way you propose, we would also have to integrate with those plugins.

Not showing a specific error message is a (security) feature, not a bug.

**Comment by andrewlimaza** [comment]
@mircobabini looking at WordPress core, it shows the username is not registered on the site (which I do agree that it could be a security issue but if WP core does it I assume it's okay).

Also digging into this, I'm submitting a PR to fix this as we actually catch the various errors like core does but when throwing the error we don't dynamically get the error code (we constantly use 'failed' which is incorrect).
