### ISSUE TITLE
User is listed as `[none]` on Orders report tab for canceled orders

### ISSUE THREAD

**Issue by hbcondo** [strangerstudios/paid-memberships-pro#2368]
**Describe the bug**
User is listed as `[none]` on Orders report tab for canceled orders

**To Reproduce**
1. Install [Reason for Cancelling Add On](https://www.paidmembershipspro.com/add-ons/pmpro-reason-cancelling/) using default configuration
2. Have existing customer submit reason for cancelation and during self-cancelation process
3. Access wp-admin --> Memberships --> Orders page (/wp-admin/admin.php?page=pmpro-orders)
4. See User field with value `[none]`
![image](https://user-images.githubusercontent.com/306958/217457499-65d3672a-20ce-4d85-8cf8-bd5101664552.png)

5. Click on Code hyperlink for record with [none] and see cancelation reason entered in step 2 in Additional Order Information input:
![image](https://user-images.githubusercontent.com/306958/217456956-4eba2c46-5155-40f6-9695-f142bd3010c0.png)

**Expected behavior**
Populate User field with member username and email address like all other order records

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

- WordPress: v6.1.1
- PMP: v2.9.11
</details>

**Comment by JarrydLong** [comment]
Hi there

I've tried to replicate the same behavior by using PMPro 2.10.2 and the Reason For Cancelling Add On 0.2.1 but have been unable to do so.

I'd recommend opening a ticket on our Member Support Forums for further assistance as this is likely an isolated or site-specific case.

**Comment by hbcondo** [comment]
Thanks for your reply; the issue is still present with PMP v2.10.3 using the new [Stripe Checkout integration](https://www.paidmembershipspro.com/gateway/stripe/stripe-checkout/).

![image](https://user-images.githubusercontent.com/306958/231570114-8177372d-03dc-4965-a7d7-3f2f5094b0c6.png)

![image](https://user-images.githubusercontent.com/306958/231570193-098751e2-80da-4dfe-b1f9-3268370668aa.png)

**Comment by andrewlimaza** [comment]
@hbcondo please can you open a support ticket here https://www.paidmembershipspro.com/support

By default we do not delete the WordPress account when a user cancels. There may be custom code on your site that's deleting the WP user. We're more than happy to help you debug this.
