### ISSUE TITLE
Error when exporting Sales and Revenue report to CSV

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/paid-memberships-pro#2373]
**Describe the bug**
Exporting Sales and Revenue report to CSV shows error.

**To Reproduce**
1. Go to **Memberships > Reports**
2. Select the **Details** button under **Sales and Revenue**			
3. Next, click the **Export to CSV** button 
4. See **Error finding report data. Make sure transients are working.** 

**Screenshot**
![image](https://user-images.githubusercontent.com/4752949/218203164-39b11341-d7ec-4881-97cf-9050027487e6.png)

**Expected behavior**
The export should work, and it doesn't work in the past couple versions of Paid Memberships Pro. Export works for **Visits, Views, and Logins** and **Membership Stats** reports.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

A customer reported this (ticket ID 477658), and I was able to replicate this on 2.9.7 - 2.10.1.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.10.1, WordPress 6.1.1, PHP 7.4.30.
```
</details>

**Comment by michaelbeil** [comment]
Another customer (ticket ID 480923) reported this.

**Comment by JarrydLong** [comment]
We've been testing this on a couple of sites now and it appears to only happen when a site makes use of heavy caching (to the point that the admin pages are even cached). 

This results in the transient being cached as 'empty' and the above error is thrown. 

If this issue comes up, I'd recommend reaching out to your host first to see if they can disable or exclude cache on the reports you're trying to export.

**Comment by JarrydLong** [comment]
This PR fixes this issue https://github.com/strangerstudios/paid-memberships-pro/pull/2443

**Comment by michaelbeil** [comment]
[2.10.4](https://github.com/strangerstudios/paid-memberships-pro/releases/tag/2.10.4) includes the fix, so closing.
