### ISSUE TITLE
arabic language appear as ???  question mark

### ISSUE THREAD

**Issue by EngGemy** [strangerstudios/paid-memberships-pro#2376]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed or left unattended.

**To Reproduce**

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Please share non-sensitive information about your hosting environment such as WordPress version, PHP version, Paid Memberships Pro and any related plugins versions.
```
</details>

**Comment by andrewlimaza** [comment]
Hi @EngGemy 

You will need to change your database character set to UTF-8. I found this guide on WordPress.org - https://codex.wordpress.org/Converting_Database_Character_Sets

I hope this helps.
