### ISSUE TITLE
"now" does not always make sense for initial payments

### ISSUE THREAD

**Issue by Scott-N** [strangerstudios/paid-memberships-pro#240]
Regarding function `pmpro_getLevelCost()` in `paid-memberships-pro/includes/functions.php`

Describing the initial payment as the price for "now" looks weird when "now" is past. For example, suppose a membership requires an initial payment of $100 and then $10/month. When a longtime member visits their account page, under billing they will see "$100.00 now and then $10.00 per Month" -- even though the $100 charge was paid long ago. It looks like they might be charged the initial fee again.

My suggestion is to change "now" to "initially", so the price will appear as "$100.00 initially and then $10.00 per Month." Makes sense regardless of when it is displayed.

**Comment by strangerstudios** [comment]
Nice catch. Good idea. I'll think it over.
