### ISSUE TITLE
Whats's This? not translated

### ISSUE THREAD

**Issue by Ninjami-Juho** [strangerstudios/paid-memberships-pro#243]
Latest relase had this fix: "BUG: Added “CVV” and “What’s This?” from the checkout page to the .pot file."

Yes, the "What's This?" is in the .pot file, but when using Stripe checkout the translation is not showing on the checkout page.

Also the popup-cvv.html link  to the pages folder in pmpro plugin, so I have to replace it every time i update pmpro with my translated version. Would be cool if it used the one in the themes folder. I have to  replace these 2 things every time I update pmpro by hand.

**Comment by strangerstudios** [comment]
Merging with this issue: https://github.com/strangerstudios/paid-memberships-pro/issues/428

We will move the CVC page to be in code vs an .html file, making it easier to translate. Thanks.
