### ISSUE TITLE
Timezone Differs between Member History and Order

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/paid-memberships-pro#2447]
**Describe the bug**
The member history timestamp differs by 3 - 4 hours compared to the timestamp that is displayed on the order edit page. The order timestamp is correct as this correlates with a timestamp in Stripe according to a customer. 

**To Reproduce**
1. Edit your profile and scroll down to the Member History Section
2. Take note of the date for a specific entry
3. Click edit on that entry - the date in the order itself will be different

**Screenshots**

Member History
![image](https://user-images.githubusercontent.com/8989542/233913964-55399386-e6f7-4785-aabd-fe568d10a1c7.png)

Edit Order
![image](https://user-images.githubusercontent.com/8989542/233914006-2a62ff6c-6626-43fe-8f93-e84677d2c098.png)

**Expected behavior**
The two timestamps should be the same

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
PMPro 2.10.3
WP 6.2
```
</details>

**Comment by andrewlimaza** [comment]
This is related to this one -> https://github.com/strangerstudios/paid-memberships-pro/issues/2206

**Comment by RogerKolbu** [comment]
Still shows 4 hours difference on our site.
![Skjermbilde 2023-04-27 kl  00 02 50](https://user-images.githubusercontent.com/131647586/234713014-5203a6ad-1b6a-45b0-9557-ec99f9495155.png)

![Skjermbilde 2023-04-27 kl  00 03 03](https://user-images.githubusercontent.com/131647586/234713059-a0a7a3c9-71ef-4fa6-81d8-950d4cd5b820.png)
