### ISSUE TITLE
Authorize.net Transaction Key is not Hidden after saving.

### ISSUE THREAD

**Issue by aaronbwcollins** [strangerstudios/paid-memberships-pro#245]
As a security professional, it worries me that if someone gets access to my settings panel they can get my payment gateway api info. Please fix, thanks!

**Comment by aaronbwcollins** [comment]
![image](https://cloud.githubusercontent.com/assets/12265303/10121677/fe1802f8-64ac-11e5-90f6-dde015d0e84c.png)

**Comment by strangerstudios** [comment]
We could add in a few layers of fake security, but the system needs to be able to send the plaintext API key to Authorize.net so it would always be available to someone smart enough with access.

You should be able to limit what the API has permissions to do on the Authorize.net side to add a bit more security.

**Comment by strangerstudios** [comment]
Following up. I don't mean to be dismissive of your post. Security is important. As far as I know, it is not common practice to obfuscate or encrypt the API data like this.

One thing I can think of is to encrypt the keys and passwords using a salt in the wp-config.php. And then use that to decrypt the value before sending it to the API. In this case, if you somehow had admin access to PMPro (or just access to the PMPro settings pages) but didn't have access to the wp-config.php or to edit plugins/run PHP, you wouldn't be able to get the actual API keys.

That's quite a bit of work and a lot of assumptions for a narrow case of added protection IMO. But if there are solutions that other plugins/etc are using for this, I'm open to suggestions.

**Comment by strangerstudios** [comment]
Closing in favor of this issue, if anyone would like to continue this discussion.

https://github.com/strangerstudios/paid-memberships-pro/issues/268
