### ISSUE TITLE
Feature Request: Add filter to edit checkout metadata before send to Stripe

### ISSUE THREAD

**Issue by iamfiras** [strangerstudios/paid-memberships-pro#2466]
Hello,

We need a way to add metadata to Stripe checkout session before sending the params, especially for the subscription mode.
The same way it's done with the filters `pmpro_stripe_charge_params`, `pmpro_stripe_payment_intent_params`, `pmpro_stripe_create_subscription_array`, but these are in deprecated functions.

For now, and for my personal use case, I modified the plugin code file at the [line 1849](https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/gateways/class.pmprogateway_stripe.php#L1849) to add the following code:

```
$checkout_session_params = apply_filters( 'pmpro_stripe_before_checkout_custom', $checkout_session_params, $morder );
$checkout_session = Stripe_Checkout_Session::create( $checkout_session_params );
```

Thank you.

**Comment by andrewlimaza** [comment]
There is now a filter "pmpro_stripe_checkout_session_parameters"  that may be used - https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/gateways/class.pmprogateway_stripe.php#L1672
