### ISSUE TITLE
User fields not always included in the admin confirmation email.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#2471]
**Describe the bug**
Some custom user fields filled in on the checkout page are not included in the "Extra Fields" section of the checkout confirmation email the administrator receives. 

**To Reproduce**

1. Navigate to Memberships > Settings > User Fields and add a new field group named "test".
2. For the group settings select "Yes" for the "Show on checkout" option and "No" or "Yes (only admins)" for the "Show fields on user profile" option.
3. Create a new text field named "test" and save all settings.
4. Navigate to the membership checkout page for any level, fill in any value for the test field and complete the checkout procedure.
5. View admin checkout confirmation email to see the "test" field is not included.

**Expected behavior**
All custom user fields filled in at checkout to be included in the "Extra Fields" section of the admin checkout confirmation emails.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WordPress 6.2, 
Paid Memberships Pro 2.10.5, 
PHP 8.1.9
</details>

**Comment by kimwhite** [comment]
Until fixed, this recipe can work to add all fields to the admin email:
https://gist.github.com/kimwhite/e1b2ced424f0b1b8f9102dd50136179e
