### ISSUE TITLE
Confirmation Message field spacing not applied when Elementor is active.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/paid-memberships-pro#2480]
**Describe the bug**
The level Confirmation Message spacing is lost when Elementor is active. 

**To Reproduce**
1. PMPro and Elementor are installed and active.
2. Go to your LEVEL settings page. 
3. General Settings > Confirmation Message > Add a message with returns.
4. Check out for Level
5. See the confirmation message all runs together. No spacing.

**Screenshots**
(https://capture.dropbox.com/SLCvMlTiiA7QGxJ1)

**Expected behavior**
Confirmation Message should display with returns (P tags added). This does not happen when Elementor is active.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress 6.2.2
PMPro 2.10.5
Elementor 3.13.2

**Comment by ipokkel** [comment]
Could adding paragraphs to the confirmation message with the WordPress `wpautop` function could be considered here?

As a temporary workaround this custom code snippet seemed to help:

```PHP
function my_pmpro_confirmation_message( $confirmation_message, $pmpro_invoice ) {
	$confirmation_message = wpautop( $confirmation_message );
	return $confirmation_message;
}
add_filter( 'pmpro_confirmation_message', 'my_pmpro_confirmation_message', 50, 2 );
```

**Comment by andrewlimaza** [comment]
This is related (somewhat) - https://github.com/strangerstudios/paid-memberships-pro/issues/2022
