### ISSUE TITLE
Can't override email headers

### ISSUE THREAD

**Issue by chrisvanpatten** [strangerstudios/paid-memberships-pro#25]
PMPro is setting global email headers, making it impossible to override directly from [wp_mail](http://codex.wordpress.org/Function_Reference/wp_mail).

PMPro should "clean up after itself" or provide the ability to disable this functionality entirely.

More on a related issue is [here at WP Stack Exchange](http://wordpress.stackexchange.com/questions/9102/why-wont-wp-mail-let-me-set-the-from-header-when-plain-old-php-mail-will).

**Comment by strangerstudios** [comment]
This is now an option on the email settings tab of the pmpro settings. This stuff is tricky. There might be more we can do to have PMPro place nice with other emails, but closing this for now.
