### ISSUE TITLE
Feature Request: Support for Zeffy Payment Processor Middleman

### ISSUE THREAD

**Issue by the-sweet** [strangerstudios/paid-memberships-pro#2504]
**Is your feature request related to a problem? Please describe.**
When you use PMPro for a nonprofit association/club/organization, you run into the problem of having to deal with payment processor fees. Zeffy helps nonprofits bypass these fees, but PMPro still helps create memberships on-site. How can we integrate the two? 

**Describe the solution you'd like**
Ideally, if Zeffy is available as a "payment processor" (they use Stripe, so Zeffy is actually acting as a "middleman") in PMPro, they won't have to worry about memberships being created/paid for outside of PMPro and then needing additional confirmation before someone has access to members-only content on the organization's site.

**Describe alternatives you've considered**
Right now, the only alternatives seem to be embedding the Zeffy forms in PMPro pages using link text (since there's no way to edit the pages using Gutenberg or another editor; you'd have to create the pages outside of PMPro and embed the PMPro content with a shortcode) or continuing to use the existing processors and paying a fee.

**Additional context**
[Zeffy](https://www.zeffy.com/home/about-us)

**Comment by andrewlimaza** [comment]
Thanks for reaching out @the-sweet, I did a but of searching on Zeffy but it looks like they aren't offering a gateway API but more a hosted solution.

If their system supports Zapier, you could use Zapier to push data from Zeffy to Paid Memberships Pro (to assign them a membership level) - https://www.paidmembershipspro.com/documentation/compatibility/zapier/

You would have to link to your Zeffy store on your WordPress site for checkouts. I had a look for Zeffy's documentation but didn't find any API documentation about creating a payment plugin for WordPress in general.

**Comment by andrewlimaza** [comment]
If you need further help with talking through this, please reach out to our support team on www.paidmembershipspro.com/support as we don't actively monitor Github for support questions.

I hope this helps get you started.
