### ISSUE TITLE
Course Activation Button Redirect to Wrong Page!

### ISSUE THREAD

**Issue by Yallo90** [strangerstudios/paid-memberships-pro#2507]
**Describe the bug**
1 customer, 1 basic plan with unlim choose.
the payment is ok, but when the customer go to a course to activate by the button, here happen the mistake.
The button change page to LEVEL selection page and not activate the course.
I use Wordpress with MASTER STUDIO LMS

**To Reproduce**
1. Install Paid Memberships Pro, Paid Memberships Pro - Cancel on Next Payment Date, Paid Memberships Pro - Multiple Memberships per User

2. Activate these plugin and follow the standard istruction for the standard setup

3. Use only Stripe in Test mode

4. Create some course in different category...Basic, Med, Top

5. Create 3 Level with different price (27,37,47 $)

6. For each level select UNLIM course and one of the category...force the category with only subscription and not onetime payment.

7. Use a customer account, NOT THE ADMIN, and buy in test mode a basic level

8. When Done, go and choose the basic course and try to press the button.

9. Where it go?

**Screenshots**
Look Here... the mouse is on the button...look on the right bottom, there is the destination link.
It send to the level page where is necessary to buy a plan, but for the customer the plan was paied correctly.
![image](https://github.com/strangerstudios/paid-memberships-pro/assets/135993985/c00b60b9-84b1-421b-a187-14d64028c72b)

this is the video test
https://drive.google.com/file/d/18N6JX_wYESbDM-Xdfaxvr05W4VBmGIcw/view?usp=drive_web

**Expected behavior**
When buy a subscription the button inside the course not able the course, but send the customer direclty to pay again on the level page.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
Easy to say... a website with wordpress has a different plugin, witch one
- [ ] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
I use STOREFRONT theme
- [ ] I can reproduce this bug consistently using the steps above.
I delete e reinstall all, and the problem live again

**Comment by andrewlimaza** [comment]
Hi @Yallo90

The MasterStudy LMS plugin integrates with Paid Memberships Pro and we don't have any control over this functionality, I recommend to reach out to their support to assist you with this functionality and to ensure their integration still works with Paid Memberships Pro.

Just adding a note here, that we do not offer support through Github and it's best to reach out to our support team www.paidmembershipspro.com/support for support requests before asking here as we don't actively monitor our repos for support questions or related tickets.

To briefly answer your question, you might be able to redirect non-members away from the course using the Custom Post Type (CPT) Membership Access Add On instead - https://www.paidmembershipspro.com/add-ons/custom-post-type-membership-access/

Thank you for understanding.

**Comment by andrewlimaza** [comment]
Because there have not been any recent updates to this topic, I will close this issue.
