### ISSUE TITLE
2.11.1 - Submit Form no longer works - Invalid form controls error

### ISSUE THREAD

**Issue by drhvsb** [strangerstudios/paid-memberships-pro#2515]
**Describe the bug**
We have had to downgrade to 2.11 due to issue with submitting form on our site. Since the upgrade, the submit form no longer works, with "_An invalid form control with name='' is not focusable."_ error - See screenshot below.
I think this is in relation to the "Now using HTML5 required field attribute on required fields at membership checkout." enhancement with the latest update.

**Screenshots**
![image](https://github.com/strangerstudios/paid-memberships-pro/assets/135712549/a4f92977-8054-4d4a-ae41-7d0022381833)

**Expected behavior**
Form is completed as usual

**WordPress Environment**
<details>
```
Wordpress version 6.0.5
PHP 7.4.22
Paid Memberships 2.11.1 but currently back on 2.11

```
</details>

**Comment by andrewlimaza** [comment]
This has been resolved in version 2.11.2
