### ISSUE TITLE
Free Trial one time only?

### ISSUE THREAD

**Issue by Yallo90** [strangerstudios/paid-memberships-pro#2534]
Hi.
i'm using this plugin on wordpress.
Work very good. thanks.
One questione please.

How i can set the plugin to do ONE TIME FREE TRIAL for my service?
The problem is, now somebody use the page to subscribe to the free trial, after delete before to pay, after recreate the subscrition with the same credit cart or email address, after delete before to pay, again, again, again.

How i can fix this problem?

Is possibile to PMPRO pluign undestand when the customer tried the free trial of a product and the plugin show (on the order page) a correct payment of the product.

thank you so much, and sorry for my english.

**Comment by andrewlimaza** [comment]
Hi @Yallo90 

You may follow this guide to set up a one time trial that can only be used once - https://www.paidmembershipspro.com/offer-trial-memberships-that-can-only-be-used-once/

For any further questions or support, please can you open a ticket on www.paidmembershipspro.com/support.
