### ISSUE TITLE
Ask: Auto eraser script / feature 

### ISSUE THREAD

**Issue by brm-ryd** [strangerstudios/paid-memberships-pro#2538]
Hi Sorry,

I'm wondering in which part of files for the eraser script / feature of the plugins ?
- does mostly the action in the includes/privacy.php ?
- I kinda wondering how to add some way to include a cron task / cron job to trigger it though so it can just running for some schedule

Thank you

**Comment by andrewlimaza** [comment]
Hi @brm-ryd 

Thanks for reaching out, we do not offer support  on GitHub or customization requests of this nature within our support channels but I'll briefly talk through this to help get you started.

If you need a generic clean up script for all members and WordPress users you may need to rather have a cron job running custom SQL queries instead or calling specific functions to cancel the members level before deleting them.

If you want to use the privacy functions, you may set up a cron job with the callback of "pmpro_personal_data_eraser" (https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/privacy.php#L49C10-L49C36) and pass through the required parameters of $email_address and $page.

A local WordPress developer may be able to help customize your site further and configure an automated cleanup script for your site.

I am going to close this issue, I hope it helps get you started.
