### ISSUE TITLE
Affiliate WP integration

### ISSUE THREAD

**Issue by curtismchale** [strangerstudios/paid-memberships-pro#256]
Here's a direct link to the ticket over there: https://github.com/affiliatewp/AffiliateWP/issues/937

The problem is that it really doesn't seem that PMPro ever logs which discount code goes with the order in the order table. Sure it does in the code_uses table but it reads to me (making some assumptions) that the certificate_id column in the orders table should get the coupon_id saved in to it.

As it stands I have no idea how to get the any of the certificate_\* items to have any data in them during the checkout process when using a discount code.

**Comment by strangerstudios** [comment]
Worked with Pippin just now to use $order->getDiscountCode() to get the discount code instead of $order->discount_code, which should work in this case.

We're looking into making sure ->discount_code is always setup, but in the meantime using the method will fix things.

**Comment by curtismchale** [comment]
Awesome
