### ISSUE TITLE
Cannot upload/install github pmpro plugin

### ISSUE THREAD

**Issue by maia4t** [strangerstudios/paid-memberships-pro#2614]
**Description of problem**

Hi, I was directed by Pmpro admin to install the opensource full pmpro plugin from github, as we are a community group and cannot affored the paid versions. I have followed instructions very carefully on github from pmrpo to download then upload the plugin via wordpress and via my domain host file manager, however neither are working.

I removed -dev from the file name before uploading zip file to wordpress directly, however once clicking install, the new page is white/blank.

Then I uploaded the unzipped plugin to the wp-admin/content/plugins file in my one.com file manager. The plugin did not show up in wordpress.

I deleted the unzipped plugin from my file manager and uploaded the zipped plugin file. Once uploaded, I unzipped the file. The plugin still doesnt show up in wordpress.

Please help me install and activate pmpro.

**To Reproduce**
1. Go to 'https://www.mhub.community/wp-admin/plugin-install.php'
2. Click on 'browse'
3. Select pmpro github plugin zip file 
4. Cllick install
5. See error

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.
![image](https://github.com/strangerstudios/paid-memberships-pro/assets/144271588/dcecfbc2-2273-4052-92b0-80bceaa2e7f7)

**Expected behavior**
I expect to be able to install and activate the plugin either from wordpress directly and/or my file manager

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
 I am using the Astra theme on https://mhub.community with woocommerce and elementor (free) installed.
All my plugins are updated. I have tried deactivating all plugins and trying to upload the pmpro plugin, and it still didnt work.

**Comment by kimwhite** [comment]
Hello,
What Plugin are you trying to install?
If it is this one, it's available from the WordPress.org repository or the Plugin section of your site.
https://wordpress.org/plugins/paid-memberships-pro/
The above is the FULL Paid Memberships Pro (PMPro) plugin.

We do not monitor GitHub for support issues. You can use our contact our pre-sales support for assistance.
https://www.paidmembershipspro.com/contact/

**Comment by andrewlimaza** [comment]
For support, please reach out to https://www.paidmembershipspro.com/support
