### ISSUE TITLE
Duplicate user fields when duplicate field groups exists.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#2615]
**Describe the bug**
Two copies of a user field group and associated fields are displayed on the checkout page.

This may occur if the same field group is created with code and through creating a field group in the GUI Settings for User Fields.

**To Reproduce**
1. Create a user field group and a user field with code and add the code snippet to a customization plugin. (Example: https://gist.github.com/ipokkel/a97eb6c5308b0dda3fc07d84df47771a)
2. In the WordPress dashboard navigate to Members > Settings > Users Fields and create a user field group with the same group name as the group created with code, e.g. "More Information", add a field to the group, and save settings.
3. Navigate to the front-end membership checkout page.

**Screenshots**
![2023-09-06_16-38-48](https://github.com/strangerstudios/paid-memberships-pro/assets/9744519/f926ef51-1d4a-44d6-a5b8-1495b55d7958)

**Expected behavior**
A field group should be displayed once only on the checkout page.

A workaround for this is to remove the line that creates the field group using the `pmpro_add_field_group` function from the customization code when a group with the same name was created in the GUI Settings for User Fields.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress 6.3.1
PMPro 2.12.2

**Comment by MaximilianoRicoTabo** [comment]
<img width="609" alt="image" src="https://github.com/strangerstudios/paid-memberships-pro/assets/1678457/89e7c85f-8f1e-4c22-a67b-f61812171684">
It also adds dup ID which is not ok

**Comment by MaximilianoRicoTabo** [comment]
https://github.com/strangerstudios/paid-memberships-pro/pull/2625

**Comment by andrewlimaza** [comment]
The fix has been merged in.
