### ISSUE TITLE
PHP 8.1 warning: Array to string conversion with [pmpro_member] 

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/paid-memberships-pro#2618]
**Describe the bug**
When using [pmpro_member] on a page. The log shows a warning. 

**To Reproduce**
Steps to reproduce:
1. Go to a page
2. Add [pmpro_member] 
3. After adding, you will see this error in the PHP log:

```
PHP Warning:  Array to string conversion in /wp-content/plugins/paid-memberships-pro-dev/shortcodes/pmpro_member.php on line 139
```
**Expected behavior**
There should not be an error.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.12.2, WordPress 6.3.1, PHP 8.1.22
```
</details>

**Comment by MaximilianoRicoTabo** [comment]
https://github.com/strangerstudios/paid-memberships-pro/pull/2622

**Comment by MaximilianoRicoTabo** [comment]
https://trello.com/c/gzGjlSO9/379-add-new-docs-https-wwwpaidmembershipsprocom-documentation-shortcodes-general-shortcodes-pmpro-member-shortcode
