### ISSUE TITLE
Erroneous link for the Social Login Add On

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/paid-memberships-pro#2620]
**Describe the bug**
There’s an erroneous link for the Social Login Add On. 

**To Reproduce**
1. Go to Add Ons page
3. Scroll down to Social Login Add On
4. Click on the title 
5. You will be lead to the PMPro wp.org page
6. This is the bad link: https://www.paidmembershipspro.com/wp/pmpro-social-login/?utm_source=plugin&utm_medium=pmpro-addons&utm_campaign=add-ons&utm_content=pmpro-social-login 

**Expected behavior**
It should go to pmpro.com - https://www.paidmembershipspro.com/add-ons/social-login-add-on/?utm_source=plugin&utm_medium=pmpro-addons&utm_campaign=add-ons&utm_content=pmpro-social-login

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.12.2, WordPress 6.3.1, PHP 8.0.29
```
</details>

**Comment by MaximilianoRicoTabo** [comment]
https://github.com/strangerstudios/pmpro-social-login/pull/18

**Comment by MaximilianoRicoTabo** [comment]
this issue is not really a bug. There's an issue behind https://www.paidmembershipspro.com/ rewrite rules as far as i understand and as per we were talking with @ideadude  last week. Perhaps we can create a task for someone else in the team to fix this ? Thoughts  @andrewlimaza @dparker1005  ?

**Comment by andrewlimaza** [comment]
This has been resolved.
