### ISSUE TITLE
SameSite attribute missing from pmpro_visit cookie  

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/paid-memberships-pro#2626]
**Describe the bug**
PMPro does not use a `SameSite` attribute in the `pmpro_visit` cookie. 

**To Reproduce**
1. Go to a site that has PMP installed
2. Enable inspector
3. Click console
4. See message: `Cookie “pmpro_visit” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

A customer informed us about this. **Here's the part from an external security scan:**

```
<alertitem>
<pluginid>10054</pluginid>
<alertRef>10054</alertRef>
<alert>Cookie without SameSite Attribute</alert>
<name>Cookie without SameSite Attribute</name>
<riskcode>1</riskcode>
<confidence>2</confidence>
<riskdesc>Low (Medium)</riskdesc>
<confidencedesc>Medium</confidencedesc>
<desc><p>A cookie has been set without the SameSite attribute, which means that the cookie can be sent as a result of a ‘cross-site’ request. The SameSite attribute is an effective counter measure to cross-site request forgery, cross-site script inclusion, and timing attacks.</p></desc>
<instances>
<instance>
<uri>[https://site.com/</uri&gt]
<method>GET</method>
<param>pmpro_visit</param>
<attack/>
<evidence>Set-Cookie: pmpro_visit</evidence>
<otherinfo/>
</instance>
</instances>
<count>1</count>
<solution><p>Ensure that the SameSite attribute is set to either ‘lax’ or ideally ‘strict’ for all cookies.</p></solution>
<otherinfo/>
<reference><p>[https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site</p></reference&gt](https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site%3C/p%3E%3C/reference&gt);
<cweid>1275</cweid>
<wascid>13</wascid>
<sourceid>1</sourceid>
</alertitem> 
``` 

**Expected behavior**
The pmpro_visit cookie should have a `SameSite` attribute. 

**Isolating the problem :**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.12.2, WordPress 6.3.1, PHP 8.0.30
```
</details>

**Comment by andrewlimaza** [comment]
I'm unable to replicate this issue, I'll keep it open to give others a chance to comment on this.

Tried on Chrome and Safari.
