### ISSUE TITLE
The annual membership report always shows zero cancellations

### ISSUE THREAD

**Issue by dwanjuki** [strangerstudios/paid-memberships-pro#2627]
**Describe the bug**
The annual membership reports shows zero cancellations for every year even when cancellations have happened. 

**To Reproduce**
1. Go to _Memberships > Reports_. Note the number of cancellations in the Membership Stats widget.
2. Click _Details_ in the _Membership Stats_ widget.
2. Customize the report to show _Annual_ stats.
3. Check the generated charts. You may also export to CSV.
4. Observe that the reports show 0 cancellations

**Expected behavior**
If there were some cancellations, the annual membership stats report charts and CSV should display this info

**Isolating the problem**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WP 6.3.1
PHP 8.0.30
PMPro 2.12.2
</details>

**Comment by MaximilianoRicoTabo** [comment]
added the fix for CSV export  as well. @dwanjuki  for whenever you can or want to test it.

**Comment by julesgamble** [comment]
Remove me from your list. I no longer use this app and don't even have Wordpress anymore. Sent from my iPhoneOn Oct 12, 2023, at 11:05 AM, Maximiliano Rico ***@***.***> wrote:﻿
added the fix for CSV export  as well. @dwanjuki  for whenever you can or want to test it.

**Comment by michaelbeil** [comment]
@julesgamble you can unsubscribe by unwatching the [Paid Memberships Pro GitHub repository](https://github.com/strangerstudios/paid-memberships-pro/) as shown here: https://github.com/orgs/community/discussions/35086

**Comment by julesgamble** [comment]
No idea how to even login to that account anymore. I only created the Github account for support on this app. Quickly realized how slow Wordpress loads content compared to Shopify. And run my subscription and products through that instead. Sent from my iPhoneOn Oct 13, 2023, at 2:00 PM, Michael Beil ***@***.***> wrote:﻿
@julesgamble you can unsubscribe by unwatching the Paid Memberships Pro GitHub repository as shown here: https://github.com/orgs/community/discussions/35086

**Comment by andrewlimaza** [comment]
@julesgamble unfortunately this isn't something we can do from our end by the looks of it. You would need to log in/reset your Github password and load this issue in your browser and then unsubscribe.

I hope this helps.
