### ISSUE TITLE
Subscription is not cancelled if all the member's orders are in refunded status

### ISSUE THREAD

**Issue by dwanjuki** [strangerstudios/paid-memberships-pro#2672]
**Describe the bug**
If all a member's previous orders are in the `refunded` status, and if the member's subscription hasn't been canceled by an admin, the member's subscription isn't cancelled when they cancel their membership via the _Membership Cancel_ page.

See: https://github.com/strangerstudios/paid-memberships-pro/blob/f49464571b7e712face31133c51f0349b305f568/includes/functions.php#L1055

**To Reproduce**
1. Using a new account, sign up for a membership with a recurring subscription.
2. Refund the order associated with the membership.
3. Switch to the test account and cancel your membership.
4. Observe that the subscription is still active at the gateway.

**Expected behavior**
The subscription is cancelled if the member cancels.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
PMPro 2.12.4
</details>

**Comment by ideadude** [comment]
This might "just be fixed" in 3.0. Let's test and close if true.

**Comment by dwanjuki** [comment]
Tested on PMPro v3.0 RC 1. The subscription is cancelled when the member cancels, even when all their previous orders are in the refunded status. Closing.
