### ISSUE TITLE
Allow more user-friendly and accessible ways to close the "Register a Stripe Webhook" modal

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#2682]
**Describe the bug**
When a user is setting up the Stripe gateway, we show a modal to help them understand next steps related to registering a Stripe Webhook.

This modal can only be dismissed using the small "x" icon in the upper right of the popup.

We want to also support using the ESC key, as well as clicking anywhere outside the modal to dismiss it.

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.
![image](https://github.com/strangerstudios/paid-memberships-pro/assets/5312875/f0a7055f-d18b-4bfd-8c4e-6b24322efbee)

**Expected behavior**
ESC or clicking outside the modal should dismiss it. We support ESC on the Add New Level > Templates modal. (I guess should also support clicking outside the box to dismiss on that one too).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by andrewlimaza** [comment]
Closing as this has been merged in.
