### ISSUE TITLE
We use Billing address as members address.  If they move, we need to update their address. How can I update the Billing Address ? 

### ISSUE THREAD

**Issue by padam10** [strangerstudios/paid-memberships-pro#2705]
We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://www.paidmembershipspro.com/documentation/

**Technical support for premium extensions or if you're an active paid member**
Submit a ticket on our helpdesk by visiting https://www.paidmembershipspro.com/new-topic/ (Please note that an [active paid membership](https://www.paidmembershipspro.com/pricing) is required for paid support.)

**General usage and development questions**
- WordPress.org Forums: https://wordpress.org/support/plugin/paid-memberships-pro
- Website: https://www.paidmembershipspro.com/contact/

**Comment by andrewlimaza** [comment]
Hi @padam10,

Thank you for reaching out, we do not offer support on GitHub and recommend to reach out to one of the outlined channels as mentioned above.

You may create these fields in User Fields to show up on the member's edit profile page. Here is a guide you may follow that outlines it in more detail - https://www.paidmembershipspro.com/display-the-members-billing-address-fields-on-the-edit-user-page-for-admin-only/
