### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by tbenterprises** [strangerstudios/paid-memberships-pro#274]
please I have to add another payment gateway to paid membership pro in my wordpress site how do I get that done? 
2Checkout is very difficult to approve application to use paidpro. they don't even support it in their policy. prefer you guys should remove their gateway from your payment gateway option.

**Comment by eighty20results** [comment]
Are you looking fro help to create a payment gateway for PMPro or to use one of the other payment gateways we have available?

**Comment by tbenterprises** [comment]
I like to create a payment  gateway that i can use but let me get approval
to use their services on my site first then i will contact you.

Thanks

On Tue, Jan 12, 2016 at 2:24 PM, Thomas Sjolshagen <notifications@github.com

**Comment by strangerstudios** [comment]
Here is our FAQ on adding a new gateway. If you put your gateway add on online on GitHub or somewhere similar and share the repo with us, we can help with specific issues.

https://www.paidmembershipspro.com/adding-a-new-payment-gateway-option-to-paid-memberships-pro/
