### ISSUE TITLE
LifterLMS streamline mode and the /membership/ CPT slug

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#2820]
**Describe the bug**
When you are using PMPro and LifterLMS in streamline compatibility mode, the llms_membership post type is still reserving the /membership/ slug. Sites cannot use the slug `membership` for a page.

**To Reproduce**
Steps to reproduce the behavior (have PMPro installed alread):
1. Create a page called Membership with slug `membership`
2. The page loads fine.
3. Install LifterLMS and set it up in streamline mode.
4. Go back to your membership page. It shows a 404.

**Comment by MaximilianoRicoTabo** [comment]
Can't reproduce this one either on dev or v3 branches. Lifter 7.5.3. pmpro-courses  enabled. Any further setting i could be missing ? Anything special in the permalinks settings ?

<img width="990" alt="image" src="https://github.com/strangerstudios/paid-memberships-pro/assets/1678457/e7e151f5-76c8-4d30-aeca-abe330c51a75">
<img width="1728" alt="image" src="https://github.com/strangerstudios/paid-memberships-pro/assets/1678457/82a37f7a-e588-40a3-ab71-5581a90521b7">
