### ISSUE TITLE
Plans to support PayFlow Pro

### ISSUE THREAD

**Issue by drrobotnik** [strangerstudios/paid-memberships-pro#29]
Feature Request: Since PayPal is pushing new subscribers to PayFlow Pro accounts, is there any plan to support this API? I've had to go through the process a couple times asking the client to request the Website Payment Pro account, and it's been pulling teeth to get PayPal to do it. Not to mention they have to actually cancel the account they went through the verification process for and do it again.

**Comment by strangerstudios** [comment]
Payflow support is now in core. At this time, you need a separate addon here to manage recurring subscriptions with Payflow. That may be moved into core at some time in the future. It's been running well for a while, but does represent a different paradigm than we have with other gateways around syncing recurring orders and cancellations.

https://github.com/strangerstudios/pmpro-payflow-recurring-orders
