### ISSUE TITLE
View With selector in admin bar not working as expected in Firefox web browser.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#2907]
**Describe the bug**
When logged in as an administrator the "View As" selection in the admin bar does not allow selection when using the Firefox web browser. This does not occur when using a Chromium-based browser.

**To Reproduce**
1. Log in to site as an administrator using Firefox as web browser
2. Go to a member's only post
3. From the admin bar, click on "View: With Access" dropdown
4. Notice that the dropdown immediately closes up and does not allow selecting another options

**Screenshots**

https://github.com/strangerstudios/paid-memberships-pro/assets/9744519/640c2354-0d83-4815-9013-9f762030db9b

**Expected behavior**
Administrators should be able to select a "View As" option when using Firefox.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
Paid Memberships Pro 3.0
</details>

**Comment by andrewlimaza** [comment]
For now, admins can revert back to using this code snippet if they're on FireFox while we look into this issue further - https://gist.github.com/andrewlimaza/823ddff62b8aedafc4d4d6663ab9f695 (and tweak this to remove or add access)

I was able to replicate it with FireFox.
