### ISSUE TITLE
pmpro_has_membership_access uses global $post / getfile.php always allows access

### ISSUE THREAD

**Issue by MannyC** [strangerstudios/paid-memberships-pro#291]
I was having an issue locking down files as described here: http://www.paidmembershipspro.com/locking-down-protecting-files-with-pmpro/

Turns out that getfile.php calls pmpro_has_membership_access [here](https://github.com/strangerstudios/paid-memberships-pro/blob/e4e6e9740b5f3f05cd44e391ea5a423f154fae30/services/getfile.php#L71), which always [returns true because $post->post_type isn't set ](https://github.com/strangerstudios/paid-memberships-pro/blob/9e87b184a44aa33d8e49919225eec1d9451f30a0/includes/content.php#L18), and therefore always allowed access to the files.

**Comment by strangerstudios** [comment]
Tutorial here:
http://www.paidmembershipspro.com/change-membership-level-on-cancellation-or-expiration/

Code bits for non-members here:
https://gist.github.com/strangerstudios/dccc7944ca2d8cd993de#file-pmpro_after_change_membership_level_cancel-php

**Comment by strangerstudios** [comment]
Thanks for the heads up. I rewrote that bit to use queried_object instead of the $post global and to avoid returning "true" for posts without post types.

Let me know if this works for you:

https://github.com/strangerstudios/paid-memberships-pro/commit/af4488e48c4c0c26d8ec537fa00d5f866caac47e

**Comment by MannyC** [comment]
That's great, my adhoc testing says that works.

Thanks!
