### ISSUE TITLE
Err creating recurring payments with PayPal Express

### ISSUE THREAD

**Issue by dtcao2502** [strangerstudios/paid-memberships-pro#2943]
I tried to pay for the membership packages using PayPal Express.I passed through the step of entering card information and was redirected to the confirmation screen. At the final step, when calling the endpoint https://api-3t.sandbox.paypal.com/nvp received an INVALID_REQUEST error with the message 'Request is not well-formed, syntactically incorrect, or violates schema.'

Request:
{
  "method": "POST",
  "timeout": 60,
  "redirection": 5,
  "httpversion": "1.1",
  "user-agent": "WordPress/6.5; https://*******.**",
  "reject_unsafe_urls": false,
  "blocking": true,
  "headers": {
    "content-type": "application/json",
    "PayPal-Request-Id": "77847765-be24-4f92-9c63-4b14be37ec62"
  },
  "cookies": [],
  "body": "METHOD=CreateRecurringPaymentsProfile&VERSION=72.0&PWD=FEZXF9DF7T5U5ZHE&USER=sb-tqedv29758064_api1.business.example.com&SIGNATURE=AwVcvC6gFsIXFSZLvhHOiIVUaGtCAJrq286sUUDeTjqVRSnM8k9mO.s-&BUTTONSOURCE=PaidMembershipsPro_SP&TOKEN=EC-9R659795AV2302426&INITAMT=110.00&AMT=100.00&CURRENCYCODE=JPY&PROFILESTARTDATE=2024-04-09T04:47:33Z&TAXAMT=10.00&BILLINGPERIOD=Day&BILLINGFREQUENCY=1&AUTOBILLOUTAMT=AddToNextBilling&NOTIFYURL=https%3A%2F%2F*****.***.**%2Fwp-admin%2Fadmin-ajax.php%3Faction%3Dipnhandler&DESC=Test+at+%E3%82%AA%E3%83%B3%E3%83%A9%E3%82%A4%E3%83%B3%E8%AC%9B%E5%BA%A7&MAXFAILEDPAYMENTS=1",
  "compress": false,
  "decompress": true,
  "sslverify": false,
  "sslcertificates": "/home/****/****/public_html/wp-includes/certificates/ca-bundle.crt",
  "stream": false,
  "filename": null,
  "limit_response_size": null,
  "_redirection": 5
}

Response:
{
  "headers": {},
  "body": {
    "name": "INVALID_REQUEST",
    "message": "Request is not well-formed, syntactically incorrect, or violates schema.",
    "debug_id": "d289ac4e483e2",
    "details": [
      {
        "location": "body",
        "issue": "MALFORMED_REQUEST_JSON",
        "description": "The request JSON is not well formed."
      }
    ],
    "links": []
  },
  "response": {
    "code": 400,
    "message": "Bad Request"
  },
  "cookies": [],
  "filename": null,
  "http_response": {
    "data": null,
    "headers": null,
    "status": null
  }
}

I'm using the LearnPress plugin, but I think the issue lies within the core of PMPro
I encountered this exception in the subscribe() function inside the classes/gateways/class.pmprogateway_paypal.php file.

**Comment by andrewlimaza** [comment]
Thanks for creating an issue @dtcao2502 here is a fix that is pending to be included in a future release - https://github.com/strangerstudios/paid-memberships-pro/pull/2944

You may apply this code to your site for the time being to resolve the issue. We've found this issue only happened with sandbox accounts and not live accounts.

**Comment by dtcao2502** [comment]
Great, it's working.
