### ISSUE TITLE
is there option to set default level, after expirition

### ISSUE THREAD

**Issue by shimondoodkin** [strangerstudios/paid-memberships-pro#298]
is there option to set default level, after expiration
after a membership expires it sets no level at all and it makes a problem for my website
is there an option to make it to switch to other free level i have

**Comment by strangerstudios** [comment]
Tutorial here:
http://www.paidmembershipspro.com/change-membership-level-on-cancellation-or-expiration/

Code bits for non-members here:
https://gist.github.com/strangerstudios/dccc7944ca2d8cd993de#file-pmpro_after_change_membership_level_cancel-php
