### ISSUE TITLE
Deprecate unused "pmpro_showRequiresMembershipMessage" function.

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#2998]
This function is not used anywhere: [pmpro_showRequiresMembershipMessage](https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/functions.php#L875)

The function should be deprecated. PR should be done against the 3.1 branch.

**Comment by andrewlimaza** [comment]
Closing this as PR has been merged in.
