### ISSUE TITLE
Unsupported Payment Methods

### ISSUE THREAD

**Issue by mrortach** [strangerstudios/paid-memberships-pro#3022]
MaxCoach, I bought your theme a long time ago but I never had the time to create content. Now I'm trying again, but the payment methods do not work in my country.

Paid Memberships Pro: Stripe, Paypal... These are not supported in your country. 
Supported:
Iyzico

**Comment by kimwhite** [comment]
Hello,
Our team does not monitor GitHub for support questions.
Please get in touch with us through our contact form and let us know what payment gateways you are looking for.
https://www.paidmembershipspro.com/contact/

**Comment by andrewlimaza** [comment]
@mrortach This sounds like you would need to contact the payment gateway providers for assistance here and ensure that they are supported within your and your customer's countries. 

As Kim mentioned, please feel free to reach out to our support for any questions you may have. I am going to close this ticket and mark it as resolved as we do not offer technical support through GitHub.

Thank you for understanding.
