### ISSUE TITLE
View: My Access tab needs background color - not visitable when screen is smaller

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/paid-memberships-pro#3053]
**Describe the bug**
When a screen is smaller and the admin bar "View As" bar is not viewable to when on the "View:My Access" page as it has no set background color like the other views.

**To Reproduce**
1. Go to a page on the site. 
2. Select View: My Access
3. Shrink screen so admin bar has to wrap
4. Can't see View:My Access Tab

**Screenshots**
[If applicable, please attach a screenshot to make your issue clearer.](https://capture.dropbox.com/VWoZRe6Fm9tsZxg4)
![Screenshot 2024-07-10 at 4 10 20 PM](https://github.com/strangerstudios/paid-memberships-pro/assets/8083630/5aafa71b-7ecb-4b29-be1a-537e79b81dde)

**Expected behavior**
To see the tab

**Comment by kimwhite** [comment]
Temp fix with custom CSS.
#wpadminbar span.pmpro_admin-view.pmpro_admin-view-current {
    background-color: rebeccapurple;
}

**Comment by kimcoleman** [comment]
I am on the fence on us fixing this. It's really a WP problem in general - smaller screens also wrap the "username".
