### ISSUE TITLE
Stop recurring payment requests from paypal express if membership levels cancel

### ISSUE THREAD

**Issue by tashi1990** [strangerstudios/paid-memberships-pro#307]
Hello,

I am using recurring payment options.

And when i update my membership plans its updating in the dashboard but recurring is still working for both; "One for the previous membership level and Other for the updated one". Same in the case of cancellation.

When i cancelled my membership its shows the Membership Level None for user and in the members list that specific member is removed but recurring still working for it.

I am stuck in between.

Please Reply into this ASAP.

Thanks & Regards
Gulshan Chandan

**Comment by strangerstudios** [comment]
If you are still having this issue, please reach out through our member support forums. We would need more information from you and access to your site to figure out why your subscriptions aren't cancelling when the membership levels are cancelled in WP/PMPro.
