### ISSUE TITLE
Hook on the password recovery form page

### ISSUE THREAD

**Issue by dioliviers** [strangerstudios/paid-memberships-pro#3072]
**Is your feature request related to a problem? Please describe.**
My website uses reCaptcha, including for sign-in and password recovery. When users try to recover their password on PMPro recovery page, they fail, because WordPress action expects a reCaptcha code and none was sent.

Without the support for reCaptcha in PMPro,  I would need to unfortunately disable the reCaptcha support in all password recovery forms, even the native ones.

**Describe the solution you'd like**
I would like to insert an action hook that would allow me to insert a reCaptcha shortcode or inline code. 

**Describe alternatives you've considered**
I tried to use the sign-in hooks, but the password recovery form  doesn't use any hook.

**Additional context**
I am willing to send a pull request, if you agree with this improvement.

**Comment by andrewlimaza** [comment]
Hi @dioliviers 

Thanks for this, what reCaptcha plugin or solution are you using? I'd like to test this and look into it some more.

**Comment by dioliviers** [comment]
Hello, we currently use the plugin "Advanced Google reCAPTCHA".
   ᚛



Em seg., 22 de jul. de 2024 às 10:16, Andrew Lima ***@***.***>
escreveu:

**Comment by dioliviers** [comment]
@andrewlimaza 

Hi, we currently use the plugin "Advanced Google reCAPTCHA".

**Comment by dioliviers** [comment]
@andrewlimaza 

https://github.com/strangerstudios/paid-memberships-pro/pull/3073/commits/d53f0bd9e9187c4a6bf8326a9dc3d13f6e8c0b12
