### ISSUE TITLE
Failed CC transaction does not re-enable Paypal button [Fix included]

### ISSUE THREAD

**Issue by PRIZZA** [strangerstudios/paid-memberships-pro#315]
While using dual payment methods (Stripe and PayPal), when incorrect info is found and the "Processing…" message is removed, the credit card Submit button is re-enabled, but the Paypal button image stays disabled. 

To fix this, you must remove the "disabled" attribute from image type buttons as well. I modified stripeResponseHandler() in "/classes/gateways/class.pmprogateway_stripe.php":

```
 function stripeResponseHandler(status, response) {
                if (response.error) {
                    jQuery('.pmpro_btn-submit-checkout').removeAttr("disabled");
                     // Re-enable the PayPal button
                    jQuery('input[type="image"]').removeAttr("disabled");
```

**Comment by strangerstudios** [comment]
I believe we've fixed this in another commit. Closing the issue, but please open again if this is still happening for you. Thanks!
