### ISSUE TITLE
Version Numbers in Templates Break Custom Templates

### ISSUE THREAD

**Issue by AnadarProSvcs** [strangerstudios/paid-memberships-pro#3153]
**Is your feature request related to a problem? Please describe.**
When PMP updates beyond the version in a template, it ceases using the template. The version is handy to verify against the changelog for potential issues, but it's frustrating that the template ceases to work. It's not intuitive to track down and does little to minimize issues.

**Describe the solution you'd like**
Follow a model more like what WooCommerce uses where the admin gets a warning that the templates are out of date and they should be reviewed, but continue to use the template.

**Describe alternatives you've considered**
I have considered removing the version numbers to see if that would work but even if it does, it makes it more difficult to track down potential issues because you don't when it was last updated.

**Additional context**
If applicable, add any other context or screenshots about the enhancement here.

**Comment by andrewlimaza** [comment]
Hi @AnadarProSvcs 

You should be able to choose which template is loaded/used under the Memberships > Settings > Pages settings area (at the bottom of this screen). This gives you the ability to override a specific page's template.

Can you please tell me more about your custom templates. I'd like to replicate and look into this further, is it included in a theme/plugin or did you manually add in this template?

**Comment by AnadarProSvcs** [comment]
No, those change the pages themselves. We overrode the templates like checkout.php, account.php, etc.  using these instructions - https://www.paidmembershipspro.com/documentation/templates/

I'm attaching our checkout.php file as a sample.

[checkout.zip](https://github.com/user-attachments/files/17244333/checkout.zip)

**Comment by andrewlimaza** [comment]
Thanks for the feedback, we have added in an option to choose which page template to load when we detect a custom page template as mentioned previously.

Here is a screenshot for reference.
![Screenshot 2024-10-04 at 10 04 14](https://github.com/user-attachments/assets/1b96211d-ed0c-4106-91f0-8f145fd936b1)

You may change this option to "Always use my custom page template". I also recommend to set your custom template version to something like `999` to avoid any confusion with the system here as we use the released plugin version in which the template had changed.

I hope this helps clear things up. If you need more help with this, please reach out to our support at www.paidmembershipspro.com/support
