### ISSUE TITLE
Error: "Please complete all required fields." when using Authorize.net

### ISSUE THREAD

**Issue by antelopeweb** [strangerstudios/paid-memberships-pro#316]
Hi I have Version PMPro 1.8.9 and am trying to get authorize.net to work.  I get the error "Please complete all required fields." when submitting payment in either sandbox or live mode.  Other checkout methods including mail in check and paypal standard work fine.  Also I have woocommerce and I know that the authorize.net is working as we have successfully done sales there.  Can someone please help me! I am also a paid member of pmpro I am just needing fast help, hoping maybe someone here will help out.

**Comment by strangerstudios** [comment]
I'll check in on your threads in the member forums, but these troubleshooting tips for Stripe also apply to Authorize.net in some ways: http://www.paidmembershipspro.com/troubleshooting-issues-at-checkout-when-using-stripe/

**Comment by antelopeweb** [comment]
Thanks Jason, I did check this thread already and have verified that it is only when I enable the authorize.net payment option that this happens.

I do have a pmpro-customizations plugin and register helper as I have a number of custom fields going on.  I would be happy to give you cpanel and admin access so you can poke around if you’d like.

Greyson Schwing
Antelope Web
“Web and Marketing for Small Businesses”
www.antelopeweb.com<http://www.antelopeweb.com/>
203-283-7466

You are receiving this email because you are either a client, prospect, partner, referral source, networking partner, or otherwise a friend of or have some business or interest with Antelope Networks and/or Greyson Schwing.  If you wish to be removed from further communication opportunities, simply reply to this message with the word "remove" in the subject and you will no longer receive communications from us.

**Comment by strangerstudios** [comment]
It's probably a register helper fields issue. A typical one is if you have fields showing up after_password or something like that. Logged in users don't have that area because the password field isn't shown. So you need to make those fields not required or use a PHP if(is_user_logged_in) $profile = "only"; else $profile = true; And then use that variable to set the profile property of the field so it doesn't get considered at checkout for logged in users.

I'll double check that if you've given us access via one of the member forum threads.

**Comment by antelopeweb** [comment]
Okay that’s be great thank you so much.  Here’s the access info:

Semimac.org/cpanel
User emsociety
Pass X,|>s9!7YO4VkW0KW{9}

Semimac.org/wp-admin
User admin
Pass Ve31@isAX2g)NuXdGY

I appreciate the help

Greyson Schwing
Antelope Web
“Web and Marketing for Small Businesses”
www.antelopeweb.com<http://www.antelopeweb.com/>
203-283-7466

You are receiving this email because you are either a client, prospect, partner, referral source, networking partner, or otherwise a friend of or have some business or interest with Antelope Networks and/or Greyson Schwing.  If you wish to be removed from further communication opportunities, simply reply to this message with the word "remove" in the subject and you will no longer receive communications from us.

**Comment by strangerstudios** [comment]
FYI you are replying to GitHub emails and so your replies are being posted to the GitHub issue online, public. I've snipped out your access data online, but you should actually change it to be safe. These issue replies are likely distributed to others watching the issues/etc.

Sorry if that was unclear.

**Comment by antelopeweb** [comment]
Ok thanks once we are done I will change my passwords

Greyson Schwing
Antelope Web
“Web and Marketing for Small Businesses”
www.antelopeweb.com<http://www.antelopeweb.com/>
203-283-7466

You are receiving this email because you are either a client, prospect, partner, referral source, networking partner, or otherwise a friend of or have some business or interest with Antelope Networks and/or Greyson Schwing.  If you wish to be removed from further communication opportunities, simply reply to this message with the word "remove" in the subject and you will no longer receive communications from us.

**Comment by antelopeweb** [comment]
Ok passwords changed now and posted as a private reply in member forum post.  If you need, email me directly at greyson@antelopeweb.com<mailto:greyson@antelopeweb.com> and I can send to you

Greyson Schwing
Antelope Web
“Web and Marketing for Small Businesses”
www.antelopeweb.com<http://www.antelopeweb.com/>
203-283-7466

You are receiving this email because you are either a client, prospect, partner, referral source, networking partner, or otherwise a friend of or have some business or interest with Antelope Networks and/or Greyson Schwing.  If you wish to be removed from further communication opportunities, simply reply to this message with the word "remove" in the subject and you will no longer receive communications from us.

**Comment by strangerstudios** [comment]
Going to follow up in the member forum thread.

**Comment by metawise** [comment]
What was the issue though? I'm having exactly same error with Stripe.
