### ISSUE TITLE
IPN requests not validating.

### ISSUE THREAD

**Issue by pbaylies** [strangerstudios/paid-memberships-pro#318]
I was getting 500 Internal Server errors from PayPal on IPN request validation. I've [submitted a pull request](https://github.com/strangerstudios/paid-memberships-pro/pull/317) to fix this issue, updating the URL and post behavior for the IPN handler as PayPal suggests in their documentation.

**Comment by strangerstudios** [comment]
Thanks for the pull request. It has been merged and will be in the next release.

There is another issue when using PayPal on the sandbox site that others might run into. Information on that here: http://www.paidmembershipspro.com/paypals-tls-1-2-http1-1-upgrade-impact-membership-site/
