### ISSUE TITLE
When I use the paypal express plugin to use paypal in addition to stripe, it says "javascript: (void)0"

### ISSUE THREAD

**Issue by wittwebdesigns** [strangerstudios/paid-memberships-pro#319]
When I use the paypal express plugin to use paypal in addition to stripe, it says "javascript: (void)0". I am running the sweet date theme through theme forest and seventh queen (author) and when I try to select the paypal button it does nothing. When hovering over it I get the javascript error.

I have double, triple checked the setup to make sure the api credentials are right, and when I use them separately it works fine. 

I can give access to the site if someone from stranger studios can help and would put an icon of PM PRO on the footer of the site I am building with it which is going to be advertised heavily.

**Comment by eighty20results** [comment]
Hi,

Would you mind reporting this in our [support forum ](http://www.paidmembershipspro.com/forums/forum/members-forum/)? It's a little more secure to share access credentials via our private forum.
