### ISSUE TITLE
Error: "Please complete all required fields."

### ISSUE THREAD

**Issue by pxlpshr** [strangerstudios/paid-memberships-pro#32]
Having a bit of a problem. It was also reported 5 days ago by another user on the WP support forums. [1]

a. I'm using Stripe in test mode. 
b. I've enabled stripe lite. [pmpro_stripe_lite = apply_filters("pmpro_stripe_lite", true);]
c. I've filled out the form with correct and valid information (triple checked)
d. The form returns "Please complete all required fields."
d. If I disable Stripe lite and fill out the entire billing section appropriately (which also includes selecting a credit card type), then it works just fine.
e. Using Safari 6.0.02

[1] http://wordpress.org/support/topic/please-complete-all-required-fields

[2] Screenshot

![Screen Shot 2013-01-09 at 11 19 19 PM](https://f.cloud.github.com/assets/983647/55721/75e7cf7c-5ae5-11e2-9f9b-a1d5e98dd865.png)

When I submit the form, the CVV is completed. I've tested this numerous times.

**Comment by s3w47m88** [comment]
I'm experiencing this with PayPal in Production mode.

**Comment by antelopeweb** [comment]
I am experiencing this with authorize.net and have started a new issue
