### ISSUE TITLE
Brazilian payment methods

### ISSUE THREAD

**Issue by matteusbarbosa** [strangerstudios/paid-memberships-pro#330]
Just saw that we've got a pt_BR language, but let me tell you the gateways  used (Stripe, Braintree Payments, PayPal Express...) are not popular in Brazil. 2 @brazil we do use most the national PagSeguro, Moip, TrayCheckout rather than international ones. 3 could someone tell me about the plugin popularity in Brazil (something like the downloads rate) ? This info could allow me and others to invest time and add the support for them...

**Comment by renatonascalves** [comment]
I agree!

**Comment by strangerstudios** [comment]
We don't have plans for any of the gateways you listed. You can read our FAQ on adding a new gateway here: https://www.paidmembershipspro.com/adding-a-new-payment-gateway-option-to-paid-memberships-pro/

**Comment by renatonascalves** [comment]
@strangerstudios Can you provide any information? Maybe if one sees a demand, one can invest time in creating a gateway for one.

Thank you! :)

**Comment by samirbridi** [comment]
I would very much like to have the Pagseguro options at least because the Brazilian people trust their payments system. Unfortunately, only Paypal is available, which many people still do not trust.

**Comment by samirbridi** [comment]
@renatonascalves how to create this addon for the plugin?

**Comment by renatonascalves** [comment]
@samirbridi I'd recommend checking their documentation. :)

**Comment by samirbridi** [comment]
@renatonascalves Unfortunately I do not understand much how to do the integration, that is, create the payment addon for the Pagseguro in the plugin. I even know where it has the documentation and everything, but as I do not know how to develop yet, and my knowledge is very basic, I can not put the Pagseguro.
