### ISSUE TITLE
Paid membership Pro 1.8.9.2 issues with Expiration Dates Add On

### ISSUE THREAD

**Issue by jbruggeling** [strangerstudios/paid-memberships-pro#331]
Since the update to 1.8.9.2 from 1.8.9.1 custom expiration dates set via the Expiration Dates Add On do not work. They still show on the checkout and level pages but they show as 'never expire' both under the Membership Account Page and in the admin membership list.

Reverting back to  1.8.9.1 fixed the issue.

**Comment by eighty20results** [comment]
Hi,

Thanks for this report. We've got a couple of fixes pending to address this issue.

**Comment by kimcoleman** [comment]
This should be resolved in the current releases. If you are still experiencing this incompatibility with the latest release of PMPro and the Set Expiration Dates Add On, please open a new issue.
