### ISSUE TITLE
wp_new_user_notification email - formatting is being stripped.

### ISSUE THREAD

**Issue by markkelly1982** [strangerstudios/paid-memberships-pro#345]
The default formatting of WP new user email if stripped once the PMP plugin is active.

The issue seems to be with the following line:

`$message .= '<' . network_site_url("wp-login.php?action=rp&key=$key&login=" . rawurlencode($user->user_login), 'login') . ">\r\n\r\n";`

as documented on this page https://developer.wordpress.org/reference/functions/wp_new_user_notification/

Basically once it hits that line, it strips all the formatting out of the email for some reason. If I remove that line, the email formatting sends correctly.

I've tested this on a new install of WP. Version 4.5.3 with only the PMP plugin activated.

Any ideas on why this is happening?

**Comment by markkelly1982** [comment]
Removing the opening and closing brackets on 

'$message .= network_site_url("wp-login.php?action=rp&key=$key&login=" . rawurlencode($user->user_login), 'login') . "\r\n\r\n";'

seems to solve the issue.

**Comment by Mrnt** [comment]
@markkelly1982 I had similar problems and tried to fix it with this change:
https://github.com/strangerstudios/paid-memberships-pro/pull/260
