### ISSUE TITLE
Register Helper Example - read only in member profile view

### ISSUE THREAD

**Issue by Booga-23** [strangerstudios/paid-memberships-pro#347]
I have manged to get a member number field added via the register helper plugin.
It needs to be able to be imported and exported via CSV, which is all working.
These are historical membership numbers that have to be editable by admin but read only for members.

I am really struggling to get it to appear in the member profile as read only. Once this issue is resolved I can actually start using PMPro.

Any help would be greatly appreciated.
P.S. Small not for profit club so paid support is not possible at the moment.

<?php
/*
Plugin Name: Register Helper Example
Plugin URI: http://www.paidmembershipspro.com/wp/pmpro-customizations/
Description: Register Helper Initialization Example
Version: .1
Author: Stranger Studios
Author URI: http://www.strangerstudios.com
*/
//we have to put everything in a function called on init, so we are sure Register Helper is loaded
function my_pmprorh_init()
{
    //don't break if Register Helper is not loaded
    if(!function_exists("pmprorh_add_registration_field"))
    {
        return false;
    }
    //define the fields
    $fields = array();
    $fields[] = new PMProRH_Field(
        "member-number",                // input name, will also be used as meta key
        "text",                         // type of field
        array(
            "label"=>"Membership Number",   // custom field label
            "memberslistcsv"=>true,     // show on CSV file
            "profile"=>"admins"         // only show in profile for admins
        ));
    //add the fields into a new checkout_boxes are of the checkout page
    foreach($fields as $field)
        pmprorh_add_registration_field(
            "checkout_boxes", // location on checkout page
            $field            // PMProRH_Field object
        );
    //that's it. see the PMPro Register Helper readme for more information and examples.
}
add_action("init", "my_pmprorh_init");

**Comment by strangerstudios** [comment]
We need to fix our docs and comments in the code. The value to have a field appear on the profile page for admins only is "only_admin".

Hope you were able to figure this out.
