### ISSUE TITLE
HTML5 WC3 validation fails on checkout.php 

### ISSUE THREAD

**Issue by jbruggeling** [strangerstudios/paid-memberships-pro#352]
Hi there I'm seeing two simple errors that are easy to fix

1) the tables include boarder and width attributes that are not used (width 100%) is default anyhow. This should be removed and placed into the table class CSS not that its even needed

2) bstate and bcountry are missing a ID that matches the label throwing errors again easy fix with id=xxx

**Comment by strangerstudios** [comment]
Thanks for these notes. I think we can squeeze these updates into the next release.

**Comment by jbruggeling** [comment]
Any updates on getting these issues fixed as it looks a bit ugly having red errors when someone tries to validate our checkout page.

**Comment by strangerstudios** [comment]
The next release includes an update to switch the checkout table to use divs instead of a table/etc. We will work to have it HTML5 validate as well.

**Comment by jbruggeling** [comment]
Changing to divs would be great. 

The Register Helper plugin is div and the main plugin uses tables. I ended up editing one of the Register Helper functions to output a table for consistency.
