### ISSUE TITLE
functions.php translation level

### ISSUE THREAD

**Issue by nosTa1337** [strangerstudios/paid-memberships-pro#353]
It seems that the variable is not getting translated when it includes the `<strong>`tag. As soon as I removed it and added it to the template file (`<strong>`) the translation worked.

functions.php

```
old: 
line 339: $r = sprintf(__('<strong>%s per %s</strong>.', 'pmpro')...
line 346: $r = sprintf(__('<strong>%s every %d %s.</strong>', 'pmpro')

new: 
line 339: $r = sprintf(__('%s per %s.', 'pmpro')...
line 346: $r = sprintf(__('%s every %d %s.', 'pmpro')
```

**Comment by strangerstudios** [comment]
Is this still happening? Which language? Maybe we had the untagged version translated but not the tagged version.

**Comment by nosTa1337** [comment]
No idea as I canceled my project.

**Comment by kimcoleman** [comment]
I'm going to close this issue as it is not being currently reported. Please reopen the issue if you require further help.
