### ISSUE TITLE
Problem Editing User Page

### ISSUE THREAD

**Issue by Leinad4Mind** [strangerstudios/paid-memberships-pro#369]
Hi there, when i'm on wp-admin/user-edit.php?user_id=???

And I try to edit any kind of information, it works great, except when I change the Level of the user.
So the problem comes to this plugin. The problem is that I get a 504 error after the page enter on a loop for a lot of time.

I've done a lot of tests and when I delete this code from includes/profile.php:

```
    //emails if there was a change
    if(!empty($level_changed) || !empty($expiration_changed))
    {
        //email to admin
        $pmproemail = new PMProEmail();
        if(!empty($expiration_changed))
            $pmproemail->expiration_changed = true;
        $pmproemail->sendAdminChangeAdminEmail(get_userdata($user_ID));

        //send email
        if(!empty($_REQUEST['send_admin_change_email']))
        {
            //email to member
            $pmproemail = new PMProEmail();
            if(!empty($expiration_changed))
                $pmproemail->expiration_changed = true;
            $pmproemail->sendAdminChangeEmail(get_userdata($user_ID));  
        }
    }
```

The problem dissappears. So something wrong is happening on this "email" function.

**Comment by Leinad4Mind** [comment]
To be more specific the problem comes to this code:

`//email to admin
		$pmproemail = new PMProEmail();
		if(!empty($expiration_changed))
			$pmproemail->expiration_changed = true;
		$pmproemail->sendAdminChangeAdminEmail(get_userdata($user_ID));`

**Comment by strangerstudios** [comment]
> $pmproemail->sendAdminChangeAdminEmail(get_userdata($user_ID));

Are you having other issues sending email on your site? It seems like maybe the script is dying at this point.

**Comment by dparker1005** [comment]
As we have not heard back from you, we are going to close this issue. If you are still seeing this behavior on your site, please feel free to open a new Issue or a support ticket at [https://www.paidmembershipspro.com/support/](https://www.paidmembershipspro.com/support/).
