### ISSUE TITLE
membership level name changed into ???

### ISSUE THREAD

**Issue by banpie** [strangerstudios/paid-memberships-pro#374]
When I created my first Membership Level in Chinese, all the Chinese characters were changed into ???????
How could I solve it?

**Comment by strangerstudios** [comment]
Is this still happening? What is the character type of the wp_pmpro_ tables in your DB. Maybe you can change these manually to fix this one off.

**Comment by dparker1005** [comment]
As we have not heard back from you, we are going to close this issue. If you are still seeing this behavior on your site, please feel free to open a new Issue or a support ticket at [https://www.paidmembershipspro.com/support/](https://www.paidmembershipspro.com/support/).
