### ISSUE TITLE
Hook pmpro_before_change_membership_level not returning old membership level

### ISSUE THREAD

**Issue by MrVibe** [strangerstudios/paid-memberships-pro#381]
## The placement of the hook "pmpro_before_change_membership_level" seems incorrect.

```
do_action("pmpro_before_change_membership_level", $level_id, $user_id, $old_levels, $cancel_level);
```

---

If we run a simple function to detect the old membership Id of the user by using the $level_id, it will always return the new membership id. Which means we can not use this hook to detect the old membership id of the user when she changes the membership level.

Apparently, this hook needs to be called a few lines above its current implementation.

I have submitted a pull request for this : https://github.com/strangerstudios/paid-memberships-pro/pull/380

**Comment by FranciscoHV** [comment]
Any update of this issue?

**Comment by strangerstudios** [comment]
I believe the hook is in a good place now and passes parameters to make it easier to detect the old level. Please open again if you are still having issues.
