### ISSUE TITLE
Checkout Error

### ISSUE THREAD

**Issue by empressdianna** [strangerstudios/paid-memberships-pro#385]
Using version PMP 1.8.11.2.

Tried to test a Braintree Payment while in Live/Production. It says "Processing" before producing the final error: "Please complete all required fields" even though all fields were completed. Verified that Merchant ID, Public Key, Private Key & Client-side Encryption Key are correct. 

Looked at J Console and this is what's there: 

JQMIGRATE: Migrate is installed, version 1.4.1
2www.ambwdate.com/:652 A Parser-blocking, cross-origin script, https://secure.comodo.com/trustlogo/javascript/trustlogo.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
2www.ambwdate.com/:940 A Parser-blocking, cross-origin script, https://secure.comodo.com/trustlogo/javascript/trustlogo.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

The trust logo is my javascript for my newly purchsed Comodo SSL certificate. I also tried taking this code out of the payment gateway settings but it didn't correct it.  
Right now my settings are set to: 
Force SSL: Yes with Javascript redirects
(Checked) Pass all generated HTML through a URL filter to add HTTPS to URLs used on secure pages. Check this if you are using SSL and have warnings on your checkout pages.
I have tinkered with these settings to no avail. 

I have also tried deactivating most of my nonessential plugins but nothing worked. Here is a list of my active plugins:
Adblock Blocker
All in One SEO Pack
bbPress (never deactivated)
bbPress - Report Content
BuddyViews
BuddyPress (never deactivated)
BuddyPress compliments
Chat Room
Easy Plugin for Adsense (never deactivated)
GD bbPress Tools
Jetpack by Wordpress.com
Maintenance Mode
Paid Memberships Pro (never deactivated)
Paid Memberships Pro -bbPress AddOn
Paid Memberships Pro - Mailchimp Addon
rtMedia for Wordpress, Buddypress, bbpress (never deactivated)
ShortPixelImage Optimizer
Wordfence Security
WP User Manager
WP-Spamshield.

I'd like to get my checkout working asap. What can I do?This is the link to my checkout page: https://www.ambwdate.com/membership-account/membership-checkout/?level=7

**Comment by eighty20results** [comment]
For the cross-script warnings, you may want to ensure that the JS included is wrapped in `<script type="text/javascript"></script>` tags within the option field on the "Payment Settings" page.

I'm not a Braintree expert (by any stretch of the imagination!), but the fields required/not required by Braintree payments are (supposed to be) defined on the Braintree site (for your account) as well. Those have to match the fields that PMPro require(s).

**Comment by strangerstudios** [comment]
I've pushed a fix to the Sweetdate theme to address this. Update the theme if you can. The main fix was to remove the code between `<?php if($gateway == "braintree") { ?>` and `<?php } ?>` in paid-memberships-pro/pages/checkout.php around line 665
