### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by Vad1mo** [strangerstudios/paid-memberships-pro#386]
I just made a little plugin performance test.

When the plugin is installed it take 2.3 sek to load the a site or 80% of the time.  I have just installed the plugin and have no config changes.

<img width="1236" alt="bildschirmfoto 2016-10-14 um 00 49 51" src="https://cloud.githubusercontent.com/assets/1492007/19369915/c961c6f0-91a8-11e6-825d-6a77433b585e.png">

to me this seems to be quite a lot. 
I am using `P3 performance profiler` by godaddy

**Comment by jbruggeling** [comment]
2.3 seconds is super slow I'm seeing about 1 second for pmp on my shared hosting. Would suggest to try some faster hosting. The developers recommend in most cases to use VPS with dedicated resources. 

Would be great if there was a way that disabled PMP from loading its elements on some pages or even the opening page that users hit to speed things up.

**Comment by Vad1mo** [comment]
I run my WP site on dedicated hardware Intel Xeon E3 1230v2 32GB RAM. There are other services installed but they are all idling. The CPU is never about 10%-20% 

I repeated the test again on when there was no traffic at all except WP. with the same result.

**Comment by jbruggeling** [comment]
Not really normal on that hardware, check disk usage and queue depth as well. Are you running of SSD or magnetic storage? I run of Intel Enterprise SSD's. 

Is your LAMP stack optimized as WordPress combined with memberships do hit the stack pretty hard without caching.

**Comment by strangerstudios** [comment]
I hope you've figured out the performance issues on your site.

I'm open to discussions on specific ways we can improve performance if you'd like to open a new issue with more information.
