### ISSUE TITLE
Set Expiration Dates Add On does not work with 1.8.11.x

### ISSUE THREAD

**Issue by jbruggeling** [strangerstudios/paid-memberships-pro#389]
Hi there just updated to PMP 1.8.11.2 and the Set Expiration Dates Add On is not being recognized. memberships are showing expire in x months instead of expire on DD/MM/YYYY. Works fine on the  1.8.10.x branch.

**Comment by strangerstudios** [comment]
Are you using a certain gateway? Can you provide info on how to recreate this?

**Comment by jbruggeling** [comment]
Using braintree but the issue appears even on the 'levels page' where the date is wrong.

Updating to 1.8.11.x then applying the set expiration plugin up shows the behavior. This is with no modification of any plugin files.

**Comment by jbruggeling** [comment]
and its now working with the 1.8.12.1 update with no changes on my behalf. Not sure what changed between versions but working good with  1.8.12.1
