### ISSUE TITLE
Sms gateway

### ISSUE THREAD

**Issue by Helenvog** [strangerstudios/paid-memberships-pro#392]
Hello,is it possible to add new gateway like PayGol,Allopass,Fortumo?

**Comment by jbruggeling** [comment]
You can adapt one of the existing gateway's code to the API requirements of your payment gateway when its not included if your good with programming and understanding API's. Alternatively I believe they can code a new gateway for you as a chargeable project.

**Comment by strangerstudios** [comment]
Here is our FAQ on adding new gateways: https://www.paidmembershipspro.com/adding-a-new-payment-gateway-option-to-paid-memberships-pro/
