### ISSUE TITLE
Braintree php7.0 support

### ISSUE THREAD

**Issue by grantcodes** [strangerstudios/paid-memberships-pro#402]
Hi there, just had an issue with memberships not being created when using braintree on php7.0. Reverting back to php5.6 seems to fix the issue.

I imagine it's a fairly easy fix but the issue seems to be in the xml handling in https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/lib/Braintree/Braintree/Xml/Generator.php

Maybe the library is just due to be updated?

**Comment by ttshivers** [comment]
I actually had the same problem myself and wrote a fix for it: https://github.com/strangerstudios/paid-memberships-pro/pull/417
