### ISSUE TITLE
Use add_query_arg in pmpro_url

### ISSUE THREAD

**Issue by strangerstudios** [strangerstudios/paid-memberships-pro#409]
Possibly other places.

**Comment by eighty20results** [comment]
Need to parse the incoming arguments to UR. Something along the lines of: 

`
$arg_pairs = explode('&', $querystring);
$query_args = array();
foreach ( $arg_pairs as $qa ) {
     $ia = explode('=', $qa);
     $query_args[$ia[0]] = $ia[1];
}

$url = add_query_arg( $query_args, $url);
`

**Comment by dkd903** [comment]
@eighty20results can be done in a much simple way, something like this:

parse_str( parse_url( $url, PHP_URL_QUERY ), $query_args );

PR: https://github.com/strangerstudios/paid-memberships-pro/pull/411

Please let me know if this looks okay.
