### ISSUE TITLE
Cancel Gateway Subscriptions without having to put orders in "cancelled" status.

### ISSUE THREAD

**Issue by strangerstudios** [strangerstudios/paid-memberships-pro#41]
Right now, when you cancel a membership, PMPro sets the last order's status to "cancelled" and checks that status to see if a level has been cancelled.

Now that we are showing orders in the admin and using their statuses for other reporting (i.e. to check if an ORDER has really been cancelled), let's have PMPro check the membership_levels_users table RE cancellations instead of the orders table.

**Comment by ideadude** [comment]
First step. Audit all core code and add ons that might be using the order status.

**Comment by ideadude** [comment]
Here is one place where we check the status of an order:
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/services/ipnhandler.php#L263

In the PayPal IPN handler, we check if an order in question has already been cancelled before trying to cancel the related subscription. This concept, that a subscription attached to an order has been cancelled, needs to be preserved somehow.

**Comment by dparker1005** [comment]
Resolved in 3.0
