### ISSUE TITLE
TML + PMPro Warning - Creating default object from empty value

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#415]
There is a minor bug issue with PMPro and TML that a user reported.

Here is the wp.org link to the thread which the user resolved the issue - https://wordpress.org/support/topic/warning-creating-default-object-from-empty-value-41/

Will be looking into this further when I get a chance.

**Comment by eighty20results** [comment]
Unrelated to TML and is fixed for users who use something other than UTC + Offset as their timezone: https://github.com/strangerstudios/paid-memberships-pro/pull/414
