### ISSUE TITLE
Mysql error: missing key names when plugin creates table pmpro_membership_levelmeta

### ISSUE THREAD

**Issue by itibet** [strangerstudios/paid-memberships-pro#419]
Hi,
mysql complains about missing key names when plugin creates table pmpro_membership_levelmeta:

`Incorrect index name '' for query ALTER TABLE wp_pmpro_membership_levelmeta ADD KEY '' ('pmpro_membership_level_id') made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), include_once('/plugins/paid-memberships-pro/paid-memberships-pro.php'), pmpro_checkForUpgrades, pmpro_db_delta, dbDelta, `

I fixed it by adding key names in  paid-memberships-pro/includes/upgradecheck.php as follows:

`	$sqlQuery = "`
`		CREATE TABLE '" . $wpdb->pmpro_membership_levelmeta . "' (`
`		  'meta_id' int(10) unsigned NOT NULL AUTO_INCREMENT,`
`		  'pmpro_membership_level_id' int(10) unsigned NOT NULL,`
`		  'meta_key' varchar(255) NOT NULL,`
`		  'meta_value' longtext,`
`		  PRIMARY KEY ('meta_id'),`
`--		  KEY ('pmpro_membership_level_id'),`
`++		  KEY 'pmpro_membership_level_id' ('pmpro_membership_level_id'),`
`--		  KEY ('meta_key')`
`++		  KEY 'meta_key' ('meta_key')`
`		);`
`	";`

Thank you

**Comment by strangerstudios** [comment]
Fixed here https://github.com/strangerstudios/paid-memberships-pro/commit/67b0bad87f11d106becb3e0460d7901d973e5fd9

Will go out with the next release. Thanks for the heads up and suggested fix!
