### ISSUE TITLE
Add a button to user profile to activate autopay each month or deactivate. 

### ISSUE THREAD

**Issue by StAsMaNn** [strangerstudios/paid-memberships-pro#429]
Hello! I need help. I want to add a button in user profile. Every user can activate autopay and deactivate it. If i am a user. I click this button and every month it will automatically take money from my card. Is this possible?

**Comment by strangerstudios** [comment]
We have an addon to do this at checkout:
https://www.paidmembershipspro.com/add-ons/auto-renewal-checkbox-membership-checkout/

But the user can't turn this on and off in their profile like you suggest. If users have a recurring subscription, by default when they cancel their membership is cancelled immediately. But you can change it to cancel at the end of the payment period instead. Here is some info on that: https://www.paidmembershipspro.com/change-pmpro-membership-cancellation-to-set-expiration-date-for-next-payment-instead-of-cancelling-immediately/

If you setup cancellations to do that, then that button in the profile can simply cancel the user's membership. However re-enabling monthly payments would be harder. Users would have to checkout again.

I believe the Stripe API has a way to pause a subscription, but we haven't coded anything to integrate with that. Pausing is really hard to do and not something we've decided to tackle.

**Comment by strangerstudios** [comment]
There may be other membership plugins that handle this pausing use case and I would suggest looking into those.
