### ISSUE TITLE
User can buy different levels, not only one.

### ISSUE THREAD

**Issue by StAsMaNn** [strangerstudios/paid-memberships-pro#431]
Is there a way, that a user can buy 2 levels at once, but not only one?

**Comment by eighty20results** [comment]
Hi,

If you (on this site) navigate to the "Multiple Memberships Per User" add-on (MMPU) and install it on your site, you'll have the ability to let your members order more than a single membership level during the checkout process for themselves. 

Please note that the MMPU add-on is early beta quality, so there may (probably) be issues that we haven't identified or fixed yet (this is why it's not yet available from the "Memberships" -> "Add-ons" sub-menu on your site). Thus you should be prepared to do a fair bit of testing for your specific needs/use cases.

**Comment by StAsMaNn** [comment]
That is super! But i need to pay for this add on, yes?

**Comment by eighty20results** [comment]
You have to pay for support and one click updates once it is released, yes.
