### ISSUE TITLE
Monthly payment or year payment in single membership option

### ISSUE THREAD

**Issue by aakankshk** [strangerstudios/paid-memberships-pro#434]
Hi

is it possible to make one membership having a option to pay monthly and yearly  option

for example 

$1 for each month OR $12 for yr with stripe

**Comment by strangerstudios** [comment]
You can use 2 levels and some custom code or an addon of ours:
https://www.paidmembershipspro.com/add-select-a-payment-plan-box-to-membership-checkout-code-demo/

Or you can use custom code (Register Helper) to add a field to checkout to choose the payment plan then detect that and set the price based on the selected value: https://www.paidmembershipspro.com/modify-level-price-at-checkout-based-on-user-selections/
