### ISSUE TITLE
Issue with using UNIX_TIMESTAMP mysql function 

### ISSUE THREAD

**Issue by jhoopes** [strangerstudios/paid-memberships-pro#437]
Hi There,

We've been using this plugin and have run into an issue where the membership end date seems to not be working correctly.  I think the problem is, is that the plugin is assuming that the timezone of a server or mysql is set to being UTC, but it may not often be the case for servers such as shared hosting servers that may set them to whatever datacenter or location they may be in.

This causes a problem when using the UNIX_TIMESTAMP function to convert a datetime field into a timesamp because that function will assume the datetime string is a datetime within mysql's timezone setting.  (which very often is just set to 'SYSTEM' which then refers to the server timezone)

-----
As an example, in our case, let's say the server's timezone is set to America\New_York, or EST, and then we have our Wordpress Timezone set to America\Chicago.

If we're using the sql function, the timestamp we get back is a UTC timestamp, but the date that is stored in the database is assumed to be in the EST timezone.  Using real dates from the enddate field on our mysql server:

UNIX_TIMEZONE('2018-02-21 00:00:00') returns to us 1519189200
This can then be converted into GMT for readability to: Wed, 21 Feb 2018 05:00:00 GMT

The problem though, is that because we set the wordpress timezone into America\Chicago, the script is assuming that the timestamp is in UTC, but it's not because the mysql conversion function is assuming EST, so when the conversion happens in your script to the America\Chicago Time, this is the time that we get back:

Wed, 20 Feb 2018 11:00:00 

And the problem with that, is then the date that is shown on the user edit page is now the day before the actual end date.  And if we make any other changes to the user record, the expiration date now becomes the 20th instead of the 21st like it should be.  And if we make any changes to the user record, the previous day is now saved, and the whole process starts over again.

-----

This seems to be related to this person's issue here as well:
https://www.paidmembershipspro.com/forums/topic/auto-changing-expiration-dates/

Was this fixed with #420 , but then reverted again here? b7839ee3dc10b424918b78a083cc84f8ad5bd9f3

Thanks for your help on this...

**Comment by strangerstudios** [comment]
We working on an update to how dates are handled across the plugin that should fix this. It's slow going.

The #420 patch might fix date issues in that specific situation. The other patch doesn't revert it, but avoids a warning in some situations. They should function the same.

**Comment by strangerstudios** [comment]
Using this issue as our base for the timestamp/etc updates.

**Comment by dparker1005** [comment]
PMPro 2.3 fixed a lot of timestamp/timezone related bugs. PMPro should no longer be affected by the timezone set for the site's server or database.
