### ISSUE TITLE
Issue - Wrong expiry date

### ISSUE THREAD

**Issue by dgalictalk** [strangerstudios/paid-memberships-pro#438]
Hi There!

I'm using the plugin for some time and also with many members! Since months ago I'm experiencing a few issues that occurs randomly affecting the expiry date of the members.
Using the version v1.8.11.2 with Paypal standard.

This happens around to 10% of the members:
1.  Small date difference ( 1 day to 1 month) - Seems to happens when Paypal returns the order as a success and it comes with a wrong date.
2. Large date difference - Sometimes 4 or 6 month of difference.
3. Double membership period - Occurs in all of my levels (1 or 3 years) duplicating the period of the membership (turning into 2 or 6 years).
4. Fixed Expiry date for all orders in the same month - In some months of the year all the orders created in this month expiry in the same day.

The more strangest thing is that this occurs very randomly without a pattern , so It's very difficult to guess from where the error comes, sometimes seems from the Paypal return request.

Here the Double period case:

![order](https://cloud.githubusercontent.com/assets/20763916/23492465/4d10a046-fee3-11e6-9ffd-953129b59a43.png)

And at this list (exported to CSV from the plugin) we can see this case and the Fixed Expiry (4.) ocurring:

![list](https://cloud.githubusercontent.com/assets/20763916/23492636/5a43e4d4-fee4-11e6-8880-ebd980bf4e8a.png)

Any clue of why this is happening?
Something here was already related and/or fixed in the newer versions?

**Comment by strangerstudios** [comment]
There might be a couple things going on here.

For the entries that are off by one day: https://www.paidmembershipspro.com/time-zones-one-day-errors/

The steps in that article can often fix off by one issues. There are however some off by one issues that remain that we're working on a rather subtle patch for.

RE the 2 years expiration, this might be a user who renewed early. If you checkout for a level you have already, it will extend your membership one more year. So if you checkout and then checkout again on the same day, a 1 year expiring membership will expire for you in 2 years now.

**Comment by bryansayler** [comment]
I'm having the one day error while hosting on WP Engine. They have told me that given the shared environment, I'm unable to make the timezone change on a server level.

Additionally, I'm using Event Espresso to manage events that are time sensitive. Consequently, the timezone setting in WordPress settings needs to be set to my local time zone.

With my current setup, whenever I save a user in the WordPress Admin User Profile the membership expiration loses a day. Any ideas how I should approach? Previous commenter mentioned a "subtle patch".

**Comment by slavajacobson** [comment]
Had this issue as well yesterday.

Member signed up on March 29 but the expiry date is off which is April 2nd 2020 

So it's off by about 4 days! Does anybody know what could be causing this? (Version 1.9.5.3)

**Comment by dparker1005** [comment]
PMPro 2.3-2.4 fixed a lot of timestamp/timezone related bugs. PMPro should no longer be affected by the timezone set for the site's server or database, and timestamps should be shown consistently across the site.
