### ISSUE TITLE
Feature Request: Export PMPro report data to .CSV

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#439]
Feature Request: Export PMPro report data to .CSV

**Comment by Nate33231** [comment]
Is there an expected time when this feature would be added?

**Comment by andrewlimaza** [comment]
We currently don't have any ETA for this @Nate33231 - it's in the review and testing stages. You may apply this Pull Request to your site and test it out further as it is working from our initial tests.

**Comment by andrewlimaza** [comment]
This is implemented, I will close this feature request.
