### ISSUE TITLE
Membership Cancellation Errors

### ISSUE THREAD

**Issue by meserlian** [strangerstudios/paid-memberships-pro#443]
Hey, 

I keep getting errors when a member cancels their subscription: 

ERROR GETTING SUBSCRIPTION WITH STRIPE:CUSTOMER CUS_9ESXZRK8HLMLMM DOES NOT HAVE A SUBSCRIPTION WITH ID SUB_AKSVJAPNBRRGCA

Even though the cancellation goes through the users still sees the error, anyone have an idea about this?

**Comment by meserlian** [comment]
Any idea about this error?

**Comment by strangerstudios** [comment]
Can you share the steps to recreate this? Is it happening every time a user cancels? If not, when specifically is it happening? Can you share how you levels are setup? Is there any reason that PMPro and Stripe might be out of sync?

**Comment by contemplate** [comment]
Hey @strangerstudios this has become a significant issue.  Almost 100% of the time when members cancel they see a Stripe error.  This is happening on 3 different sites we manage.  It got worse with version v1.9.4.1 which tried to prevent double cancel button clicks and now sends the admins emails about these cancellations.

The Stripe subscription does successfully cancel but any type of after level change process fails.  For example we extend the rest of the user's term and update their tags in InfusionSoft after the Cancel event. 

Ironically I've yet to be able to reproduce the issue.  I'll signup with a live Paid subscription for a few days and then cancel it and all goes well.  Yet every other user has reported seeing the Stripe error.  Odd.

There are numerous threads as of late reporting this issue:
https://www.paidmembershipspro.com/forums/topic/stripe-cancellation-error-2/
https://www.paidmembershipspro.com/forums/topic/stripe-cancel-subscription-error/
https://www.paidmembershipspro.com/forums/topic/cancellation-error-with-stripe/

**Comment by ideadude** [comment]
Thanks @contemplate for the issue. This is number one on my plate now to figure out. I'm with you that my early attempts to recreate this were failing but we've noticed it all over the place, even on our own site. I will try to compile information here RE the issue and post and update ASAP.

**Comment by contemplate** [comment]
Thanks @ideadude I noticed your new release today didn't have this fix yet.  Any estimation 1.9.4.3 will be released.  No pressure but it's been a taxing situation for my clients with large membership sites which talk to InfusionSoft or Convertkit, etc.  for after cancel follow up.  This leads to them trying to push for whole platform changes :(    Anyway I'm preaching to the choir here.

Anything I can do to help?  Have you been able to replicate the issue?  If I could replicate it myself I could then try to help debug the issue with you.

**Comment by ideadude** [comment]
Closing this as I think other updates have fixed this. Can reopen or open a new one if this is still happening in certain cases.
