### ISSUE TITLE
Changing CVV to CVC

### ISSUE THREAD

**Issue by meserlian** [strangerstudios/paid-memberships-pro#444]
Hi,

Is there any way to change CVV to CVC on the pmpro_billing shortcode. 

Tried editing the billing.php and checkout.php file with not luck. 

Thanks.

**Comment by strangerstudios** [comment]
It seems CVC is more commonly used nowadays. We may update this in the core plugin (at least when used on the front end). In the meantime, you can look into writing some custom code that uses the gettext filter:  https://gist.github.com/strangerstudios/0ff19daaee3bcfc76b441982c1c6645e

**Comment by strangerstudios** [comment]
We're working on the checkout page UI and can update this to say "Security Code (CVC)" instead of CVV.

**Comment by andrewlimaza** [comment]
Here is a Pull Request - https://github.com/strangerstudios/paid-memberships-pro/pull/506

I have not changed any of the important code that would affect functionality of PMPro but simply adjusted the labels instead.
