### ISSUE TITLE
Set billing country by GeoIP (and let admin select fallback country)

### ISSUE THREAD

**Issue by bradydan** [strangerstudios/paid-memberships-pro#445]
Billing country in the checkout would be better set by:

1. GeoIP (there are [free WP plugins for this](https://en-gb.wordpress.org/plugins/geoip-detect/))
2. Allow admin to set a default country in the admin screens, which is used as a fallback where GeoIP fails

**Comment by strangerstudios** [comment]
Good idea for an addon. We are building this into our VAT tax addon if you're using that.

**Comment by strangerstudios** [comment]
We could write a quick gist for this that piggy backed on one of the GeoIP plugins. Not sure if we would include this in the core plugin since it would depend on GeoIP support and has minimal impact.
