### ISSUE TITLE
PMP may be hijacking redirects on login

### ISSUE THREAD

**Issue by tnorthcutt** [strangerstudios/paid-memberships-pro#446]
I'm attempting to use the [WP Discourse](https://github.com/discourse/wp-discourse) plugin to facilitate a connection between a WordPress site and a Discourse install. The site uses Paid Memberships Pro.

The intended functionality is that when clicking "Log In" on the Discourse install, a visitor is taken to the WP install, where the log in and are then redirected back to the Discourse install (and are now logged in, because WP is being used as an SSO provider).

On the site I'm working on, this works correctly, until PMP is activated, at which point the redirect does not occur, and the visitor is instead taken to `/wp-admin`. You can view the associated issue on the `wp-discourse` repo here: https://github.com/discourse/wp-discourse/issues/275

Is it possible that PMP is hijacking the redirect? If so, is there a suggested way to mitigate this problem? I'm happy to provide any additional needed information to help investigate and solve this.

Thanks!

**Comment by eighty20results** [comment]
Hi,

Not sure how PMro would be causing this unless you have an add-on (Member pages, the social login add-on, for instance) or some custom code/gist that does it. 

The PMPro plugin itself doesn't really care how people log in or authenticate itself.

**Comment by jbruggeling** [comment]
I see the same issue without cross site integration, When users login using a URL formatted as the following https://foo.com/wp-login.php?redirect_to=https://foo.com/membership-account non admin users will see the appropiate page correctly YET when the user is a admin they are hijacked and taken to foo.com/wpadmin

**Comment by tnorthcutt** [comment]
> Not sure how PMro would be causing this unless you have an add-on (Member pages, the social login add-on, for instance) or some custom code/gist that does it.

This was with no other plugins active, and a default theme.

**Comment by strangerstudios** [comment]
Here's where we add the login redirect.

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/login.php#L37

This code will disable it if run on init:

    remove_filter('login_redirect','pmpro_login_redirect', 10, 3);

I'll think if it makes sense to add a setting to adjust how this works.

**Comment by strangerstudios** [comment]
I think it makes sense to run this filter later and then set our default redirect_to's here (including redirecting admins to the dashboard) only if the $redirect_to passed in is empty.
