### ISSUE TITLE
Override error message

### ISSUE THREAD

**Issue by meserlian** [strangerstudios/paid-memberships-pro#451]
Hey, 

Is there any way to override the error message found here without changing the core plugin: 
https://github.com/strangerstudios/paid-memberships-pro/blob/cd74537bd8266ae60094a6592e72a9890674756d/preheaders/checkout.php#L368

**Comment by eighty20results** [comment]
Yes. 

Use the gettext filter & search for the string whenever text for the 'paid-memberships-pro' domain is being processed (needs to be wrapped in a function & have the correct add_filter() included):

`
if ( 'paid-memberships-pro' === $domain ) {
      if ( false != preg_match( '/text I want to replace/', $text ) ) {
          $translated = "The text I want!";
     }
}
`
