### ISSUE TITLE
Recurring Payments

### ISSUE THREAD

**Issue by nitishdoshi44** [strangerstudios/paid-memberships-pro#460]
Hello,

I need some help regarding one functionality my client wants. He wants to implement something like below.
1) First time user will have subscription for 3 days with the amount of $5.
2) After 3 days on 4th day, an amount of $10 will get deducted automatically on every after every 14th day.
It means that after 3 days on 4th day one payment of $14 should happen automatically and then after 14 days ie., on 15th day again payment of $10 will get deducted.

If there is some solution for this type of functionality then I would like to suggest for a Pro package for your plugin. But first I need to clear out this functionality.

**Comment by eighty20results** [comment]
If you have installed the plugin (and are using the Stripe gateway), you'll see that it's possible to configure scheduled changes to subscription plans on a per-user basis via their user profile page (for an admin).

I can see a scenario where that could be used to configure the solution you're looking for, but I believe it would require custom code to do so.

**Comment by nitishdoshi44** [comment]
Actually I don't want it on per user basis. I want to do this functionality globally. Means any user which comes to website and want's to be a member then for the first time only $5 will be charged and it is for 3 days only. After that on every 15th day, recurring payments will occur of $10. 

So any user coming for first time and want's membership then he / she will have this type of membership facility.

Can we do that ?? If yes then can you give me some idea how we can make changes in the code ?? A hint would be nice..

**Comment by eighty20results** [comment]
I misunderstood what you were asking for, sorry. I thought you wanted 3 different prices at different times. The way you describe it above, it seems like 2 prices (the initial cost with a 3 day delay associated with it, before you start a recurring 15 day payment cycle). This is something PMPro supports and can provide with the inclusion of the Subscription Delay Plus Add-on.

**Comment by nitishdoshi44** [comment]
Great. This is exactly what I am looking for. For this I have to purchase Pro package + addon right ? Can you give me link from where I can do that ?

**Comment by eighty20results** [comment]
The membership for PMPro is about receiving support for the plugin, plus getting one-click install & updates for the Plus add-ons. The PMPro Plugin itself is GPLv2 licensed for use & development.
