### ISSUE TITLE
Left sidebar menu items + tabs?

### ISSUE THREAD

**Issue by paaljoachim** [strangerstudios/paid-memberships-pro#490]
Having menu items two places seems a bit redundant to me.

Left sidebar:
![screen shot 2017-08-29 at 13 31 19](https://user-images.githubusercontent.com/5323259/29818856-634b19e0-8cbe-11e7-840a-b88fb21e6ac7.png)

Tabs:
![screen shot 2017-08-29 at 13 31 55](https://user-images.githubusercontent.com/5323259/29818871-714ef4e4-8cbe-11e7-9675-5a7af4c603e1.png)

It makes the plugin seem more complicated then it should. It would be better to remove the sidebar menu items and just keep the tabs. Then add in a way to style the various pages...

**Comment by strangerstudios** [comment]
Hi, thanks for the feedback and suggestions here in the issues. I'll chime in...

Redundant isn't necessarily bad. I think it's okay to have menu items in the default WP menu and another set of tabs for the most common settings setup as they are now in the order you need to go through them to complete a PMPro setup.

Related to this, I've been thinking about ways we could have a setup "wizard". WooCommerce does something like that. What's hard for me is that there are many different types of membership site, and depending on which type you are, different decisions would be made to streamline the setup.

**Comment by dparker1005** [comment]
Thank you for your suggestion here, however as we do not plan on removing either of those navigation methods, we are going to close this issue.
