### ISSUE TITLE
Using another language for the plugin but English in the backend?

### ISSUE THREAD

**Issue by paaljoachim** [strangerstudios/paid-memberships-pro#491]
I would like to keep English in the WordPress backend but Norwegian for the plugin.

It would be great to set the language used for the plugin AND have sections for customizing the default text of each page.

**Comment by strangerstudios** [comment]
I think something like this might work for you:
https://gist.github.com/scarstens/11378999

**Comment by paaljoachim** [comment]
Thank you!
