### ISSUE TITLE
Add metadata to the order when a new charge is made in Stripe

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#494]
Metadata in Stripe allows you to add key-value data to the charges. See: https://stripe.com/docs/api#metadata

**Comment by strangerstudios** [comment]
What kind of stuff would we want to add to the order? Also important to remember to keep it to order-related things vs customer-related or subscription-related.

**Comment by kimili** [comment]
Stripe metadata can be arbitrary key/value pairs, which can make it useful for searching, filtering, and exporting transactions within Stripe. In my PMPro implementation, I have a lot of different membership levels to select from. I want to add the membership level name to each transaction with Metadata.

I suggest adding a filter that allows someone to add their own metadata to transactions. I don't think it needs to add any metadata by default. I'll by happy to submit a pull request for this.

**Comment by kimili** [comment]
I've submitted Pull Request #1468 to add this functionality into the Stripe gateway class.

**Comment by dparker1005** [comment]
This functionality was included in https://github.com/strangerstudios/paid-memberships-pro/commit/582f545d1691309d4d3b9d54117fadb847180c6f
