### ISSUE TITLE
Discount Code placement under CVV

### ISSUE THREAD

**Issue by contemplate** [strangerstudios/paid-memberships-pro#498]
Hey @strangerstudios so I guess I never noticed this until now but I see the Discount Code box at checkout on every membership site I've built below the CVV.

<img width="564" alt="screen shot 2017-09-08 at 8 22 09 am" src="https://user-images.githubusercontent.com/1093666/30211865-9643f4ac-9470-11e7-97a8-635e935d9702.png">

Not sure if it's always been there but we have more and more customers mistakenly hitting the "Apply" button after filling in their credit card info rather than the submit button.

I can hide this field through CSS but could the placement of this be re-thought?  or have it hidden by default like the one at the top?

**Comment by strangerstudios** [comment]
That's a good point. We've been looking at this during a UI update and thinking about making that a text link instead of a button. That might help.

Better ways to choose if this is displayed etc could be helpful for other reasons.

**Comment by contemplate** [comment]
Excellent.  Yes text link or something else would be great.  The only button after the CC info should be the Submit button.

**Comment by strangerstudios** [comment]
Another thing we should do is show an error ("Please enter a discount code to apply.") when the apply button is clicked and the discount code is empty. This will make it more clear that the apply here refers to the discount code.

**Comment by kimcoleman** [comment]
I'm going to create a new issue for potentially adding the error message ("Please enter a discount code to apply.") when the apply button is clicked and the discount code is empty.
