### ISSUE TITLE
Custom countries and states php include

### ISSUE THREAD

**Issue by jbruggeling** [strangerstudios/paid-memberships-pro#504]
There doesn't appear to be a easy way to change this to say Australia without editing the includes themselves. They are not plugable functions and the hooks documentation only mentions changing the default country not whole arrays.

Suggest way to make changes that is persistent when updating pmpro version

**Comment by andrewlimaza** [comment]
Would you mind telling me what you would like to do?

Would you like to change the default country or alter the dropdown list to alter what countries are shown?

**Comment by jbruggeling** [comment]
Alter the drop down of both states and countries in a way that is persistent between updates

**Comment by strangerstudios** [comment]
You can use this addon to get country/state dropdowns:
https://github.com/strangerstudios/pmpro-state-dropdowns

If you use a gist to set the default country to Australia, it should update the state dropdown to start with that. https://www.paidmembershipspro.com/hook/pmpro_default_country/

**Comment by jbruggeling** [comment]
not really what I was after. Adding 2 java script includes and a full page of PGP to change the array values of the states and countries is crazy!

**Comment by jbruggeling** [comment]
All I want is to make the values in /wp-content/plugins/paid-memberships-pro/includes states.php and countries.php 'sticky' between updated ie override the arrays using a custom function.

**Comment by andrewlimaza** [comment]
Thank you for the feedback regarding this, the State Dropdown is to dynamically populate states according to country selection - as it's quite a large list to populate all countries with their relevant states/provinces.

We made use of existing libraries under the MIT license :)

Glad to hear you have figured out another solution!
