### ISSUE TITLE
Download JS and enqueue locally instead of hotlinking via Google URL

### ISSUE THREAD

**Issue by strangerstudios** [strangerstudios/paid-memberships-pro#510]
Here:
https://github.com/strangerstudios/paid-memberships-pro/blob/1b3fa753389aa5ddd3ed3c4b872b3199de9a1ab0/adminpages/reports/sales.php#L27

and here:
https://github.com/strangerstudios/paid-memberships-pro/blob/93af4cdc2be8e4a758d03c4546eab5f06712732a/adminpages/reports/memberships.php#L23

**Comment by andrewlimaza** [comment]
Pull Request -> github.com/strangerstudios/paid-memberships-pro/pull/522
