### ISSUE TITLE
Unset fields in pmpro_required_billing_fields not working

### ISSUE THREAD

**Issue by virtginia** [strangerstudios/paid-memberships-pro#519]
As I saw at the example in PayPal standard, I'm trying to make a custom gateway with no required fields and even when i call this function:

static function pmpro_required_billing_fields($fields)
		{
			unset($fields['bfirstname']);
			unset($fields['blastname']);
			unset($fields['baddress1']);
			unset($fields['bcity']);
			unset($fields['bstate']);
			unset($fields['bzipcode']);
			unset($fields['bphone']);
			unset($fields['bemail']);
			unset($fields['bcountry']);
			unset($fields['CardType']);
			unset($fields['AccountNumber']);
			unset($fields['ExpirationMonth']);
			unset($fields['ExpirationYear']);
			unset($fields['CVV']);
			
			return $fields;
		}

I still get the same error:

Por favor completa todos los campos requeridos.

Can't go on with the payment process.

Please, could you check it?

Best regards,
Virginia

**Comment by strangerstudios** [comment]
Can you put your gateway code on GitHub and share with us so we can help out?
