### ISSUE TITLE
Initial Setup Wizard

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#527]
This is a nice-to-have but we should look at creating a setup Wizard similar to WooCommerce's new one.

Allow user's to iterate through the main settings easily upon initial install -

1. Setup your PMPRo pages 
2. Setup a membership level
3. Setup a payment gateway
4. Give an option to install Memberlite (once on wp.org)

Ability to skip entire wizard or skip each step and do the ones you only want to for now! :)

**Comment by dparker1005** [comment]
Closing as this was implemented in 2.10
