### ISSUE TITLE
Support url encoded filenames in getfile.php

### ISSUE THREAD

**Issue by strangerstudios** [strangerstudios/paid-memberships-pro#529]
Per this comment here: https://www.paidmembershipspro.com/locking-down-protecting-files-with-pmpro/#comment-34283

> So I added $uri = urldecode($uri); on line 37 of getfile.php

**Comment by andrewlimaza** [comment]
Should I just add the code from the comment and submit a PR @strangerstudios ?

**Comment by andrewlimaza** [comment]
Here is the Pull Request -> https://github.com/strangerstudios/paid-memberships-pro/pull/547
