### ISSUE TITLE
IMPROVEMENT: Organizations & Representatives

### ISSUE THREAD

**Issue by cdgdigital** [strangerstudios/paid-memberships-pro#532]
When the membership is used for Organizations/Companies instead of for People, PMPro lacks a way to appropriately set the relationship between each Organization and its Representatives as well as the business information that appears on the Directory and the inherited permissions.

The "user" is a Person, with email, who may create and be responsible for an Organization, into which he may add other existing users.  

Within each Organization there may be one user who is the Owner/Director/Responsible, another user who makes the payments, another user who updates the marketing info on the Directory, etc.  The info that shows up on the Directory should be the Organization's, not the users'.  The Organization HAS the "membership" and its Representatives/Users may inherit that membership's access permissions, etc.

This is the idea of a "simple CRM" structure.

**Comment by dparker1005** [comment]
You can have multiple user accounts under a single parent account (organization) by using our PMPro Sponsored Members Add On: https://www.paidmembershipspro.com/add-ons/pmpro-sponsored-members/

Adding additional CRM features would require a 3rd party plugin or custom development to implement. If you would like hands-on assistance developing this additional functionality, please feel free to reach out to one of our PMPro Partner Developers here to discuss further: https://www.paidmembershipspro.com/developers/

**Comment by dparker1005** [comment]
Closing support ticket due to inactivity.
