### ISSUE TITLE
Plugin modifies Home URLs for new sites created on Multisite via secure URL

### ISSUE THREAD

**Issue by servesense** [strangerstudios/paid-memberships-pro#535]
On a Multisite installation, when PMPro is activated and a new site is created (by any means), the new site's "Home URL" is affected.  If the URL of the page used to create the new site was secured via https, the new site's Home URL will be secured, starting with https.  If the URL of the page was not secured, the new site's Home URL will be http.

With PMPro (core) activated, the "Home" URL has https as the beginning, but the “Siteurl” URL has http.  Again, this is only when the URL used to create the new site started with https.

This is not default WP behavior and creates issues, especially in cases where sites are using domain mapping as their sites try to redirect to https but don't have security certificates, which results in security warnings.

To track down the issue I pushed my site to staging and disabled all plugins and re-enabled them one by one and finally found it to be PMPro.  It doesn't seem to be caused by any of the add-ons because I disabled them and still had the issue with just the core PMPro plugin active.

As mentioned, this occurs regardless of the means used to create a new site.  I happens by doing it manually by going to Network Admin -> Add Site, or using PMPro add-ons, or by using a Gravity Forms add-on (which I tried just for testing).  Regardless of the method used to create the new site, if it was done from a secure URL, the new site's Home URL will be secure, which shouldn't happen.

In my case, I want to have a secure checkout process but I don't want the customer's new site to use https since their site doesn't have SSL installed.

**Comment by dparker1005** [comment]
The use of an SSL certificate is required by the PCI Security Standards Council on any site accepting credit cards and is required by most gateways even if the checkout is completed “offsite”. For this reason, we recommend that every site running Paid Memberships Pro use SSL.

We have an article here which talks more about why we require SSL and how to set it up on your site: https://www.paidmembershipspro.com/configuring-wordpress-always-use-httpsssl/

**Comment by dparker1005** [comment]
Closing support ticket due to inactivity.
