### ISSUE TITLE
Using NULL instead of 000-00-00 00:00:00

### ISSUE THREAD

**Issue by strangerstudios** [strangerstudios/paid-memberships-pro#542]
Thomas asks: Can we start setting the enddate to NULL instead of insisting on setting it to an ‘invalid’ date? It greatly simplifies checking the field and any error checking (IS NULL or IS NOT NULL).

**Comment by ideadude** [comment]
Dupe: https://github.com/strangerstudios/paid-memberships-pro/issues/892
