### ISSUE TITLE
If you have a pmpro_levels_array filter that relies on the level ID-based-index (e.g. unset( $levels[7] ) to remove level 7 from the array) the filter will not work as expected after the reordering

### ISSUE THREAD

**Issue by travislima** [strangerstudios/paid-memberships-pro#545]
Opened on behalf of a user.

SITUATION

- When a user has customized the level_order, on the levels page there's a routine to resort the levels
- This routine changes the levels array from be indexed by level ID to being indexed by incremental numbers
- Then, after the resorting, the pmpro_levels_array filter is applied

ISSUE

If you have a pmpro_levels_array filter that relies on the level ID-based-index (e.g. unset( $levels[7] ) to remove level 7 from the array) the filter will not work as expected after the reordering

SOLUTION(s)

1) Move the filter above the re-sorting loop so the change in indexing doesn't matter

2) Use the level ID to index the re-sorted levels array as it was before the resort...
$reordered_levels[$level_id] = $pmpro_levels[$key];

I ended up doing both on our theme-level levels.php template.

**Comment by toddlevy** [comment]
Hi, that was me :) Didn't realize there was a repo.

**Comment by dparker1005** [comment]
The recommended approach here would be to loop through the `$pmpro_levels` array until you find the level with the desired ID, and then remove that level from the array with `unset()`.

For reference: https://www.geeksforgeeks.org/how-to-remove-an-array-element-in-a-foreach-loop/
