### ISSUE TITLE
PayPal Standard: No IPN messages

### ISSUE THREAD

**Issue by eighty20results** [strangerstudios/paid-memberships-pro#550]
After configuring the PayPal Express credentials (API Keys, etc), I cleared them, saved the settings, then configured the default gateway to "PayPal Standard" and supplied a payment recipient email address.

Since then, IPN messages are no longer arriving at my test server (PMPro 1.9.3/WordPress 4.8.2) after a successful recurring billing checkout and completed (sandbox.)paypal.com payment.

**Comment by eighty20results** [comment]
Working on this issue with a review of the PayPal Standard gateway sources. Will submit pull requests when appropriate.

**Comment by dparker1005** [comment]
I assume that this is no longer an issue on your site, but for reference, we have an article here on troubleshooting PayPal IPN issues:
https://www.paidmembershipspro.com/troubleshooting-paypal-ipn-issues-with-paypal-express-paypal-standard-or-paypal-website-payments-pro/
