### ISSUE TITLE
Not sure where to report issues with CSV importer

### ISSUE THREAD

**Issue by efc** [strangerstudios/paid-memberships-pro#553]
The PMPro CSV importer was forked from a project that has not been updated in three years, but the [StrangerStudios fork](https://github.com/strangerstudios/import-users-from-csv) does not include an issues page. I've reported an [issue](https://github.com/sorich87/import-users-from-csv/issues/22) on the original project, but wanted you to be aware of it as well and could not report it on your project.

**Comment by ideadude** [comment]
Thanks. I've turned on issues on our fork and added one related to the one you posted on the original project. https://github.com/strangerstudios/import-users-from-csv/issues/2
