### ISSUE TITLE
Stripe Settings Page Field Order

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#559]
Inside Stripe the Publishable and Secret key are in a different order to the settings page inside PMPro.

We should swop these around to keep it inline with Stripe dashboard.

There has been a few user mistakes with putting in the incorrect order in the dashboard page.

**Comment by eighty20results** [comment]
Could we not just add a check for the `_pk_` and `_sk_` strings in the respective fields? (Think it's useful to have validation anyway.)

**Comment by andrewlimaza** [comment]
It's annoying from a UX perspective, where this will be copy top line and paste in top line and so on.

Will be really quick to swop around.

**Comment by andrewlimaza** [comment]
But I do agree on the validation too :)

**Comment by eighty20results** [comment]
I wasn't suggesting we shouldn't swap the order, simply that swapping it - i.e. a change in the current behavior - is likely to cause as many problems as the current order is (force of habit), so we probably _need_ to add validation if we're going to change the current order.

**Comment by ideadude** [comment]
@greathmaster is on the case now

Switch the order (since that's the order Stripe is using now) and show an error on the payment settings page always if the secret key starts with pk or the private key starts with sk.

**Comment by greathmaster** [comment]
Submitted pull request: #574

**Comment by greathmaster** [comment]
The pull request from above was merged into core in version 1.9.4.2
