### ISSUE TITLE
ENHANCEMENT - PDF Invoices

### ISSUE THREAD

**Issue by travislima** [strangerstudios/paid-memberships-pro#563]
Send out PDF Invoices to members when they are charged for memberships. This can be an optional .

**Comment by andrewlimaza** [comment]
This is great idea! Maybe we can do an add-on for this (Better PDF Invoices) ?

**Comment by greathmaster** [comment]
I had created this gist that did PDF versions of the invoice:

https://gist.github.com/greathmaster/ea7cab507af67b9bc0af41ea7d3e84e2

It relies on 3 additional libraries: 

- https://github.com/dompdf/dompdf
- https://github.com/PhenX/php-svg-lib
- https://github.com/PhenX/php-font-lib

**Comment by travislima** [comment]
Thanks @greathmaster !
