### ISSUE TITLE
One click pmpro-customizations.php creation

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#570]
With the code editor updates in WP 4.9, now is the time to add the one-click pmpro-customizations.php creation feature to core PMPro.

We can add a "button" to the advanced settings tab and/or addons tab to "generate a PMPro Customizations plugin" to use for custom gists. Clicking would create /plugins/pmpro-customizations/pmpro-customizations.php with the default header from here https://www.paidmembershipspro.com/create-a-plugin-for-pmpro-customizations/

If the plugin is already installed or active, it should instead show a link to edit.

If we make the button do the setup via AJAX, we can just have it convert to the "Your customizations plugin can be edited here" link to go to the edit screen.

We should work to have the frontend interface for gists on our website at the same time and link to them.

**Comment by andrewlimaza** [comment]
Could we not add this to the 'Add Ons' section? User's will be able to install the plugin from here and activate it?

We won't ever roll an update out on our end for the plugin template (Although this would be only for paying customers I guess that need a license key, unless we bypass a license key to install this plugin).

**Comment by eighty20results** [comment]
@ideadude  Can you assign this one to me?

**Comment by ideadude** [comment]
The WP Snippets plugin works really well for customizations. We are going to update our docs to recommend using that plugin. We no longer need this feature.

https://wordpress.org/plugins/code-snippets/
