### ISSUE TITLE
Level Information Shortcode

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#571]
Similar to the pmpro_member shortcode, the request would be to create a pmpro_level shortcode and allow the site owner to display a specific level's details in the format:

[pmpro_level id="2" field="description"]

All level meta information would be available, including:
level_name, level_description, level_confirmation, 

Pricing information including:
default_cost_text, initial_payment, billing_amount, cycle_number, cycle_period, billing_limit, trial_amount, trial_limit, expiration_number, expiration_period

**Comment by ideadude** [comment]
Should support also [pmpro_level name="Level Name"] even though the name can later change and break that. I think many people might want to use it that way. We don't have slugs or nice names for levels. Might be worth thinking about.

**Comment by andrewlimaza** [comment]
Do we have a shortcode for the current user's level? It could be cool to do `[pmpro_level id="current_user" field="description, enddate"]` etc.

**Comment by andrewlimaza** [comment]
Maybe that's another shortcode we should do.

**Comment by andrewlimaza** [comment]
Here you go :) - https://github.com/strangerstudios/paid-memberships-pro/pull/576
