### ISSUE TITLE
"View Page" Link for "Membership Checkout" in Admin should append a level ID

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#579]
It would be a better user experience if the "View Page" link for the "Membership Checkout" page in the admin Memberships > Page Settings page would default to the first level in the levels array. Currently the page redirects to the levels page since no ?level=ID attribute is set in the URL.

**Comment by andrewlimaza** [comment]
Wrote this up -> https://github.com/strangerstudios/paid-memberships-pro/pull/606

Added in a filter too so people can adjust it in case they don't want the first level to be viewed for whatever reason.

**Comment by ideadude** [comment]
Alternatively we can/should choose a default level if you go to the checkout page without a level set.

Options would be the first level found, the cheapest (free) level, the first paid level, the cheapest paid level. Probably going with number 1 by order is best.
