### ISSUE TITLE
Tighter integration with WooCommerce Registration page.

### ISSUE THREAD

**Issue by paaljoachim** [strangerstudios/paid-memberships-pro#585]
It would be great to add the subscription level directly into the WooCommerce registration page as an added field. Either by extra registration code or another way. Then using the default WooCommerce payment fields for paying for the subscription.

What I am looking at it making it very simple to use Paid Memberships Pro as a part of WooCommerce. One would only need to create the levels page and perhaps checkout and everything else would probably be handled directly by WooCommerce.

The flow:
WooCommerce registration page with the various fields, and a (Paid memberships pro) subscription field showing multiple levels at the bottom just before the submit button. The user selects among the levels and amount comes up and the user clicks submit. Stripe or PayPal payment shows up and the user pays. One is automatically redirect back to the site to the WooCommerce after signup page. 

Why: It makes is very simple to create a subscription using the default WooCommerce registration page.

Btw
If something similar to this is possible today. Do please direct me to the docs. I am working on the nonprofit site and I am trying to find the best and simplest way of having the user pay the yearly fee before being logged in and purchasing organic food the nonprofit sells. Thanks.

**Comment by andrewlimaza** [comment]
Thanks for the input Paal :)

You are able to use the WooCommerce Integration which can be found over here - https://www.paidmembershipspro.com/add-ons/pmpro-woocommerce/

This allows you to set a product as a membership, so user's may add this to their cart and it will assign the membership level after the order has been processed and remove the level if that order is cancelled/pending etc.

You could possibly upsell these products on the cart page if they are not in the cart.

Also you may need WooCommerce Subscriptions installed if you are wanting to do recurring subscriptions as WooCommerce will handle the billing and not Paid Memberships Pro.

I hope this helps get you somewhere :)

**Comment by paaljoachim** [comment]
Thanks Andrew. I have found other solutions.

**Comment by andrewlimaza** [comment]
Thanks for the update Paal! All the best :)

**Comment by paaljoachim** [comment]
Have a great day Andrew!..:)
