### ISSUE TITLE
Recaptcha Updates

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#592]
Can we update the API version we are using?

Can we integrate Invisible Recaptcha?
https://developers.google.com/recaptcha/docs/invisible

**Comment by andrewlimaza** [comment]
Should this be a separate option that will allow for invisible Recpatcha or V2?

**Comment by andrewlimaza** [comment]
Looks like we just need to add `data-size="invisible"` to the recaptcha init to enable it.

**Comment by andrewlimaza** [comment]
Busy building an option for it, works by simply adding `data-size="invisible"` and creating a new API Key for Invisible Recaptcha.

**Comment by andrewlimaza** [comment]
Pull Request -> https://github.com/strangerstudios/paid-memberships-pro/pull/607
