### ISSUE TITLE
Translations borked

### ISSUE THREAD

**Issue by pbrocks** [strangerstudios/paid-memberships-pro#593]
Confirmed the issue reported in this thread:

https://www.paidmembershipspro.com/forums/topic/translation-not-fully-working/

Tried cleaning up pot file here

https://github.com/pbrocks/paid-memberships-pro/tree/pbrx-t18n-12dec

**Comment by andrewlimaza** [comment]
Just a note to remember that GlotPress will load over the pot files in most cases (usually when language is about 70%+ translated on WordPress.org) 

Always double check the strings there.

**Comment by dparker1005** [comment]
For incomplete translations, you can also use a plugin such as Loco Translate to translate strings directly on your site: https://wordpress.org/plugins/loco-translate/
