### ISSUE TITLE
Set Expiration Dates Add On not getting current year

### ISSUE THREAD

**Issue by jbruggeling** [strangerstudios/paid-memberships-pro#594]
After the recent updates Set Expiration Dates Add On using 'Y' for current year actually gets current year +1. Not good for cash flow giving away a whole year of membership!

**Comment by andrewlimaza** [comment]
I am unable to recreate this issue, I have just tested this on local environment with expiration date of Y-12-31 

Expiration date is equal to 31 December 2018

**Comment by andrewlimaza** [comment]
Are you using any custom code that may affect membership levels or any other add ons?

**Comment by jbruggeling** [comment]
@andrewlimaza the issue was only presenting for members that signed up in the calander month of December where it would bump the year by one instead of keeping the current year.

The code issue is in the set expiration addon and appears to be doing this by design. I have removed them offending if statement and it has returned to what I would consider normal behavior.

**Comment by jbruggeling** [comment]
Line 66 to 74 is the offending code - 

` $M = date("m", current_time('timestamp'));
    if ($M == 12) {
        //set to Jan
        $M2 = "01";
        //set this year to next
        if ($has_Y) {
            $Y = $Y2;
        }`

**Comment by andrewlimaza** [comment]
Thanks for the feedback. Will test this further :) and work through it.

**Comment by andrewlimaza** [comment]
I think moving forward as a temporary solution to rather set the date from Y-12-31 to 2017-12-31 which for this year will be 2018-12-31

**Comment by dragonjhlee** [comment]
The expiration date of new membership is like 15 or 16 years later although I set it up 1 year from current time on this membership level.
