### ISSUE TITLE
Forced log out

### ISSUE THREAD

**Issue by dmmoelle** [strangerstudios/paid-memberships-pro#595]
My main admin user is being logged out when clicking the "Orders" link of PMPro and directed to this link:
http://michiganjaycees.org/login/?redirect_to=http%3A%2F%2Fwww.michiganjaycees.org%2Fwp-admin%2Fadmin.php%3Fpage%3Dpmpro-orders&reauth=1

I have deleted the user account and recreated the account with the same username and the problem persists. 

other links and other user accounts work fine.

as a solution I will discontinue using that username, But I wanted to report it here as a bug.

**Comment by ideadude** [comment]
That's odd. Is the username "admin"? Does this happen on a default theme with only PMPro installed?

**Comment by dparker1005** [comment]
As we have not heard back from you, we are going to close this issue. If this is still behavior that you are seeing on your site, please feel free to open a new issue and we can continue this discussion there.
