### ISSUE TITLE
Merge the Better Logins Report Add On into Core

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#610]
https://github.com/strangerstudios/pmpro-better-logins-report

**Comment by ideadude** [comment]
Just override the logins report with this one. Make sure any updates to the core logins report (check the history) also happened in the better logins report code.

May be a reverse compat issue with blank fields showing up the first time you activate with the new code.

**Comment by kimcoleman** [comment]
Make sure the pulled in code doesn't fatal error if both the core plugin has this feature and the "Better Logins Add On" is active - maybe deactivate it or unhook it?
