### ISSUE TITLE
Use WP List Tables for Members List, Orders, etc and Add Sorting to Columns

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#611]

**Comment by andrewlimaza** [comment]
We could maybe look at this since it's a custom table -> https://www.w3schools.com/howto/howto_js_sort_table.asp

**Comment by andrewlimaza** [comment]
This wouldn't take pagination into consideration though.

**Comment by eighty20results** [comment]
I'm still not clear on why a homegrown solution is better/more flexible than using the `WP_List_Table` class in core (it's marked as private, but the workaround for that is [described in the Codex.](https://codex.wordpress.org/Class_Reference/WP_List_Table)

The class comes with easily extendable sorting support for individual columns, adding columns using standard filters/actions, integration with the bulk edit functionality, etc. Both of the latter suggests it won't be updated often or to any large degree, in spite of the warning on the Codex page.

**Comment by andrewlimaza** [comment]
Agree Thomas, we should use WP classes where possible, will make filtering a lot easier.

**Comment by ideadude** [comment]
Some notes on pursuing this:

* Let's start with the member's list first. Update that and see how it feels in the wild. It's the most important use case.
* We can keep the "Show [ Levels ]" and Search bar hard coded.
* The count sentence is redundant with the pagination the WP List Table provides
* Can get rid of the pmpro_memberslist_calculate_revenue filter and section. (Leave a hook there for people to write a plugin to insert stuff there.)
* Remove our pagination code
* Need to filter into the list table pagination to add our level option into the URL
* New class PMPro_Members_List_Table extends WP_List_Table in classes/class-pmpro-members-list-table.php
* adminpages/memberslist.php will have the headings, wrapper, dropdown and search, then load the PMPro_Members_List_Table class and ->display();
* hide checkboxes in the list table
* show current columns
* don't need to show the edit/delete etc row action links. separate issue to add that later if we want
* Keep the pmpro_members_list_sql filter.

**Comment by ideadude** [comment]
Also need to do this row by row:

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/adminpages/memberslist.php#L193-L195

**Comment by ideadude** [comment]
* Support the # of results/limit box in the screen options

* We want to support all of the actions and filters in place (minus that revenue one)

* We want to support the pmpro_memberslist_extra_cols_header and pmpro_memberslist_extra_cols_body actions. Needs a lot of thought. I think Thomas' plugin had a solution.

**Comment by pbrocks** [comment]
Working for the most part, including search
still have an issue with pmproCaps

[branch here built on v1.9.6](https://github.com/strangerstudios/paid-memberships-pro/compare/dev...pbrocks:dev-196-list-table?expand=1)

[Screencast for current state using WP List Tables](https://monosnap.com/file/frRmuTfyXDNpbAvCsGKS1sg9DEnmLY)

**Comment by dparker1005** [comment]
If we do make the Orders table a WP_List_Table, it would be nice to be able to bulk-update order statuses.

**Comment by dparker1005** [comment]
This has been implemented gradually and fully released in 3.0
