### ISSUE TITLE
Add "paid orders" options to orders filter and revenue report filter.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#612]
In some places, it would be nice to filter orders and order-related reports to only show orders with total > 0.

**Comment by andrewlimaza** [comment]
This could be cool, should it just be an option under the 'Show' field, or should it be separate so user's can filter dates + paid orders?

**Comment by ideadude** [comment]
On the orders page, I think an option "Only Paid Orders" would be good that applies the filter. I suppose we can add an "Only Free Orders" option as well. Maybe we're making that dropdown too long then.

For the Membership Stats, we should add a new option to the levels dropdown "All Paid Levels" and I guess "All Free Levels". It would loop through the levels and use pmpro_isLevelFree() to see if it's free or paid and only include IDs etc etc in the SQL

**Comment by andrewlimaza** [comment]
Pull Request available - https://github.com/strangerstudios/paid-memberships-pro/pull/815
