### ISSUE TITLE
Show invoices that are refunded on the account/invoices pages.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#614]
Instead of hiding refunded invoices, show them on the account and invoices pages on the frontend, but note that they were refunded.

**Comment by andrewlimaza** [comment]
What do you think of this?

I had played around with showing all statuses?

<img width="1015" alt="screen shot 2018-02-20 at 12 27 54" src="https://user-images.githubusercontent.com/12629136/36419074-9475a27e-1639-11e8-9917-69362c83a866.png">
<img width="703" alt="screen shot 2018-02-20 at 12 28 00" src="https://user-images.githubusercontent.com/12629136/36419075-94a94872-1639-11e8-9db4-a0e940c0d26b.png">

Maybe we should show the status as well inside the invoice and printed invoice?

**Comment by andrewlimaza** [comment]
This is on the membership-account and membership-invoice pages.

**Comment by andrewlimaza** [comment]
PR created here - https://github.com/strangerstudios/paid-memberships-pro/pull/820

Image for reference:
<img width="589" alt="screen shot 2018-11-21 at 14 47 22" src="https://user-images.githubusercontent.com/12629136/48842229-69c50200-ed9c-11e8-9a95-1816792284ec.png">
