### ISSUE TITLE
Discount Code Improvements

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#615]
* Show discount code used on the edit order page in the dashboard.
* Show discount code used as a column in the members list.
* Show discount code used as a column on the orders list.
* Allow for searching for orders by discount code.
* Link to orders per discount code view from the discount codes page.
* Add sorting/order by filters to the Discount Codes page.

**Comment by andrewlimaza** [comment]
This will definitely be useful! Will be thinking about this already, let's chat about it tomorrow! :)

**Comment by ideadude** [comment]
I think this is the only one left:

* Link to orders per discount code view from the discount codes page.

**Comment by kimcoleman** [comment]
Done in PR #844
