### ISSUE TITLE
Feature Request: Integrate with LifterLMS

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#621]
There has been a request for PMPro to integrate with LifterLMS.

**Comment by kimcoleman** [comment]
Another request was made for this integration. For reference: https://wordpress.org/support/topic/lifterlms-integration-3/

**Comment by dparker1005** [comment]
Our Courses Add On includes support for LifterLMS: https://www.paidmembershipspro.com/add-ons/pmpro-courses-lms-integration/
