### ISSUE TITLE
Bug: Labels duplicating on Long Form address on Billing Page

### ISSUE THREAD

**Issue by woodwardmatt** [strangerstudios/paid-memberships-pro#623]
City & State field labels are being duplicated at: https://github.com/strangerstudios/paid-memberships-pro/blob/7771567a3d2799f9e26b7f3202f3cb3088db7989/pages/billing.php#L130

Proposed: Remove trailing, non text-domain string from code...

`<label for="bcity"><?php _e('City', 'paid-memberships-pro' );?>City</label>`

Should become:

`<label for="bcity"><?php _e('City', 'paid-memberships-pro' );?></label>`

**Comment by andrewlimaza** [comment]
Here is a Pull Request for this fix - https://github.com/strangerstudios/paid-memberships-pro/pull/637

**Comment by ideadude** [comment]
Pulled in and going out in next update. Maybe next Tuesday.
