### ISSUE TITLE
Update to Stripe v3/Elements, with support for Stripe/Apple Pay

### ISSUE THREAD

**Issue by eighty20results** [strangerstudios/paid-memberships-pro#626]
Customers requesting support for Apple Pay in the PMPro Stripe gateway.

Adding Apple Pay will require changing the gateway to use Stripe Connect & upgrade to the Elements functionality (v3 of the Stripe API front & backend code, so it's likely a major development effort).

**Comment by woodwardmatt** [comment]
Came up against this last night too. Not using [Stripe's Elements](https://stripe.com/docs/stripe-js/elements/quickstart) implementation (v3) now means that the "Out of the Box" implementation of Stripe.js (v2) is not eligible for a pre-completed SAQ A from Stripe to meet PCI compliance for payments. You'd have to complete the [in-detail 56 page self-assessment](https://www.pcisecuritystandards.org/documents/PCI-DSS-v3_2-SAQ-A_EP.pdf).

Going forward providing the elements implementation would provide PMP customers with the option of more easily achieving PCI compliance through Stripe (as long as they follow the pre-requisites). 

Stripe support provided the following information for migrating to V3 if it's of help? [Stripe Elements Migration Guide](https://stripe.com/docs/stripe-js/elements/migrating)

**Comment by contemplate** [comment]
Apple Pay would be nice but really really would like to be using Stripe Elements for PCI compliance as @woodwardmatt mentioned.  56 page self-assessment isn't fun.

**Comment by ideadude** [comment]
We could potentially work on this in 2019. There are enough motivated customers (maybe with budgets and developers) who could help out with this.

We can develop it as an add on initially, perhaps with limited functionality, and consider merging it into the core PMPro plugin later.

If anyone gets serious about working on this, let's have a discussion first and stub out the architecture type questions first.

**Comment by contemplate** [comment]
Hey @ideadude if I have time in the new year I can try to help.  
Have you seen this migration guide:
https://stripe.com/docs/stripe-js/elements/migrating

It doesn't look like it would be too difficult to modify the existing gateway.  Although I haven't really looked at your existing Stripe gateway code yet :)

**Comment by ideadude** [comment]
@contemplate Yeah, definitely. I was going to have someone on the team look into it too.

I thought we could build it out as a new plugin (pmpro-stripe-elements) and get it working before merging into the core as a replacement.

Are you going to be at WordCamp US in Nashville by any chance? Otherwise, we should try to get together (I'm in PA) to talk this through some time.

**Comment by danielbala** [comment]
Is the level of effort still considerable if it is for "Purchase Access to a Page, Post or “Thing”" add-on?
 - not for subscription, or recurring invoice, etc?
If you can point us in the direction, we'd be glad to take a stab at it...
Thanks

**Comment by DNRStudios** [comment]
RE: Stripe.js V3 and PMPro. 
We got notice from Stripe that we need to upgrade by June 7th or face the 56 page PCI self assessment. Has anyone here made any progress on the Stripe.js V3 integration, in particular with PMPro, since their most recent update says they won't support V3 until later this summer. Just hoping to not have to reinvent the wheel if we don't have to.

**Comment by kimcoleman** [comment]
@DNRStudios can you forward a copy of the email you received to info@paidmembershipspro.com. I am curious why you would receive this notice when others may not be.

**Comment by kdkd** [comment]
This is... not great. We got the stripe email as well, we have two weeks to switch to the newer APIs or deal with the enormous self-assessment, including a ridiculous amount of documentation, paying a third party to do external security scans, etc. I forwarded the email we received.

**Comment by contemplate** [comment]
Yeah I have numerous clients that need to have this updated.  I unfortunately don't have the time in the next few weeks to contribute but could contribute maybe $200 toward development @kimcoleman

**Comment by DNRStudios** [comment]
I will have one of our developers spend some time on this today and see what he can come up with. I'll post an update later. I'm just concerned about the fast turnaround and not having enough time for proper testing and dealing with conflicts/issues. Hopefully since this is already in the hopper for PMPro, they can arrange a reprieve for us until this update can be completed.

**Comment by DNRStudios** [comment]
Update. My guy looked into it and he is just not super comfortable updating directly into the plug in. Hopefully they will turn around a quick update that will solve this before June 7th

**Comment by contemplate** [comment]
@kimcoleman or @ideadude we are days away from needing to be compliant.  In case it helps here is the warning screen on the Stripe compliance dashboard reccomending we upgrade to Stripe.js V3

https://www.dropbox.com/s/zxtmpzymo4t5x2g/Screen%20Shot%202019-06-03%20at%203.47.18%20PM.png?dl=0

**Comment by hbcondo** [comment]
@contemplate, I see the same PCI Compliance message in my Stripe dashboard too. We haven't received an e-mail from Stripe (yet) about updating but would you mind providing a redacting version of the email you received so we can try and prepare? Thanks.

**Comment by contemplate** [comment]
Is there any progress being made on this?

**Comment by DNRStudios** [comment]
Not that I have seen yet although Stripe hasn't menaced us about it recently either.

**Comment by kimcoleman** [comment]
Please see https://github.com/strangerstudios/paid-memberships-pro/releases/tag/v2.1-Beta1 for the update.

**Comment by dparker1005** [comment]
PMPro is now using Stripe Elements and, as of 2.5, supports Apple Pay, Google Pay, and Microsoft Pay: https://www.paidmembershipspro.com/pmpro-update-2-5-apple-google-pay-divi-builder/
