### ISSUE TITLE
Add Support For Russian Payment Gateways

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#629]
A user has requested to support the following Russian payment gateways:

Robokassa https://www.robokassa.ru/en/
Yandex Checkout https://checkout.yandex.com/

**Comment by kimcoleman** [comment]
Adding a payment gateway is a lot of work. We currently don't have plans to add any new gateways. Here is our documentation on how to add a new gateway if someone else wants to work on that. We will answer specific questions/etc to help.

https://www.paidmembershipspro.com/gateway/adding-a-new-gateway/

**Comment by dparker1005** [comment]
Closing in favor of https://github.com/strangerstudios/paid-memberships-pro/issues/754
