### ISSUE TITLE
Add order to existing member

### ISSUE THREAD

**Issue by 2bgraphics** [strangerstudios/paid-memberships-pro#630]
If you go to Members List and click '+order' under a username the following occurs:

**1. Left menu navigation is highlighted as 'Add Member'**
Can 'Orders' be highlighted instead?

**2. Browser title bar is 'Add Member'**
Change to 'Add Order'

**3. Button to submit form is 'Add Member'**
Change to 'Add Order'

**4. After clicking 'Add Member' there is an error 'The user account has been created, but there were other errors setting up membership: Unable to add/update PMPro Register Helper registration fields for this member'.**
This is misleading because the user account is already created and the order is just being added to an existing user.
Can the PMPro Register Helper registration fields hidden from the 'Add Order' form?

**Comment by andrewlimaza** [comment]
Thanks for the feedback, this seems to be an issue with Add Member Add On.

I have patched point #3 already - https://github.com/strangerstudios/pmpro-add-member-admin/pull/13

With regards to the first 2 points, what happens is we just alter the 'Add Member' admin page according to some query values this is why the title and menu item is as is. Unfortunately, we won't be able to change this easily and will require a bit of work.

Regarding point 4 - I am still testing this on my end and will let you know some further feedback.

**Comment by 2bgraphics** [comment]
1&2: Okay. This is very minor.
3: Excellent that works well.
4: Okay thanks.

**Comment by andrewlimaza** [comment]
Would it be possible to share the code that you are using for the custom fields for point 4 as I tested this with the default code example from Paid Memberships Pro Documentation - https://www.paidmembershipspro.com/documentation/register-helper-documentation/code-examples/

No errors were thrown when I had tested it.

**Comment by 2bgraphics** [comment]
This appears to be working now. I have changed the register helper fields since reporting this including removing a checkbox (replacing with a select drop-down). This may have been the issue but I can't confirm without reverting all changes.

**Comment by andrewlimaza** [comment]
Thanks for this, glad to hear it's working.

I'll keep an eye out for this.

**Comment by ideadude** [comment]
Closing this issue. If you still are having issues, please open one on the pmpro-add-member-admin repo.
