### ISSUE TITLE
Members List filters

### ISSUE THREAD

**Issue by 2bgraphics** [strangerstudios/paid-memberships-pro#631]
On the Members List page there is a filter to show 'All Levels'.

This does not seem to work for 'Cancelled Members', 'Expired Members' and 'Old Members' on testing.

**Comment by andrewlimaza** [comment]
I have just tested this on my local environment and it works as intended (for all instances mentioned).

Would you mind generating a bug report so we may look into this further?

https://www.paidmembershipspro.com/how-to-enable-debugging-on-you-your-wordpress-site/

**Comment by andrewlimaza** [comment]
Thanks for the debug log, it seems that there are no errors pertaining to Paid Memberships Pro filter.

How many members should be on the list?

Please can you open a support thread on paidmembershipspro.com so one of our support engineers can help you trouble shoot this issue for you.

Thank you for your understanding.
