### ISSUE TITLE
On Time Zones and Off By One Day Errors

### ISSUE THREAD

**Issue by mjulian87** [strangerstudios/paid-memberships-pro#648]
Although this issue is only apparent when there's a mismatch of timezones, I think the issue is actually being caused by applying the gmt_offset when reading from the database.

If current_time("timestamp") is used to store the data (which it is), then it will be stored in the timezone of the blog (with the offset) and no offset need be applied when retrieving the data. By applying the offset when reading the data, I think you're essentially offsetting it twice. 

I modified line 81 of the MemberOrder class to remove the offset as follows (it also needs to be removed on line 322):

$dbobj = $wpdb->get_row("SELECT *, UNIX_TIMESTAMP(timestamp) as timestamp FROM $wpdb->pmpro_membership_orders WHERE id = '$id' LIMIT 1");

This resolves the issue in the limited testing that I have done. Thanks.

**Comment by eighty20results** [comment]
It’s both as easy, and significantly more complex than what you describe, but there is a pull request already: #581

**Comment by mjulian87** [comment]
I did look at that pull request, however I'm not referring to the UNIX_TIMESTAMP, this doesn't appear to be causing the issue here. I was referring to this code:

 + " . ($gmt_offset * 3600) . "

Which appears to be applying the offset, to a timestamp that has already been offset. This seems to be a different issue to the pull request that you have linked.

**Comment by eighty20results** [comment]
Line 81 isn’t the memberorder class portion of the pull request eliminates the gmt offset as well. #581 is a comprehensive change to how PMPro handles time ( for start/end dates, time stamps, etc.)

**Comment by mjulian87** [comment]
Oh yes you're right, I missed that. It also means that line 80 can be deleted from the MemberOrder class.

**Comment by eighty20results** [comment]
Good call on removing the `get_option()` call. I've updated the pull request accordingly.

**Comment by dparker1005** [comment]
PMPro 2.3-2.4 fixed a lot of timestamp/timezone related bugs. PMPro should no longer be affected by the timezone set for the site's server or database, and timestamps should be shown consistently across the site.
