### ISSUE TITLE
js errors triggered by WordPress code manipulation

### ISSUE THREAD

**Issue by smeric** [strangerstudios/paid-memberships-pro#651]
Hi,

I'm not sure why but WordPress transform a js comment into HTML that then triggers a js error :

In `pages/billing.php` line 371 and `pages/checkout.php` line 621
```javascript
<script>
    <!--
    // Find ALL <form> tags on your page
    jQuery('form').submit(function(){
```
becomes

```javascript
<script>
<!--
	// Find ALL 

<form> tags on your page
	jQuery('form').submit(function(){
```
and triggers this js error

`Uncaught SyntaxError: Unexpected token <`

So, I just copied those 2 files into my theme, removed the "<" and ">" around the "form" word and the problem was solved :)

Thank you.

Séb.

**Comment by eighty20results** [comment]
There's also the question of whether you're using any optimization plugin/service (a plugin or service that optimizes JavaScript, CSS and/or CSS. Examples are the WP Optimizer plugin for WordPress, or one of the services from CloudFlare (to mention two).

**Comment by smeric** [comment]
@andrewlimaza : I am using chrome and this "error" occurs at page load.
@eighty20results : I'll check for that... there are many other plugins installed but I don't think that there are code optimisation ones. I'll try on a fresh wp install with pmpro alone and, if the problem is caused by some other plugins, I'll try to find which one and will report here :)

**Comment by kimcoleman** [comment]
I'm going to close this issue as it has not been reported by any additional users. Please open a new ticket in our support area if you continue to have this problem.
