### ISSUE TITLE
reCAPTCHA issue?

### ISSUE THREAD

**Issue by 2bgraphics** [strangerstudios/paid-memberships-pro#656]
Added reCAPTCHA and get a white screen across the whole website with the following logged error
**PHP Parse error:  syntax error, unexpected '[' in /Applications/MAMP/htdocs/hlhs/wp-content/plugins/paid-memberships-pro/includes/lib/recaptchalib.php on line 77**

This has been tested on both a local and live server with the same result. Latest versions of WP and PMPro.

**Comment by andrewlimaza** [comment]
Thank you for sharing this with us.

What PHP version is your site currently running?

**Comment by 2bgraphics** [comment]
This could be the issue as the server available for this project runs 5.3.29 which I know is quite out of date. Which version do you suggest for me to test?

**Comment by andrewlimaza** [comment]
Paid Memberships Pro recommends PHP version 5.6 or higher. I would start at 5.6 and see if the issue persists.

**Comment by 2bgraphics** [comment]
That has solved the issue using PHP5.6. Thanks for your prompt help.

**Comment by andrewlimaza** [comment]
You are most welcome! Glad to hear it is working as intended now.

**Comment by 2bgraphics** [comment]
On the membership registration form it is inserted below 'Confirm E-mail Address' and above the billing address fields. Ideally it should be updated to 'before_submit_button' but I'm not sure where to update this value. Please can you tell me the filename and line of code to edit?

**Comment by andrewlimaza** [comment]
Here is where the recaptcha field is displayed on the checkout page - https://github.com/strangerstudios/paid-memberships-pro/blob/dev/pages/checkout.php#L222-L229

You should be able to move this right before the submit button and create a custom page template following this guide - https://www.paidmembershipspro.com/documentation/templates/

**Comment by 2bgraphics** [comment]
Excellent, thanks. That's worked out well.
