### ISSUE TITLE
Bug: pmpro_next_payment() - Based on Payment received date, not Payment due date

### ISSUE THREAD

**Issue by woodwardmatt** [strangerstudios/paid-memberships-pro#658]
Hey guys,

Just working through some dunning processes and noticed that when looking at the inbuilt PMPRO function for checking when the next payment is due, that the next date is being based of when the last order was paid, not when it was due.

Ergo, if you had a customer that paid on the 5th of every month, but was late last month (eventually paying you on the 10th for example), that the function would tell you the next payment is due on the 10th of the following month, as opposed to the 5th when it is actually due. 

**Note**: This is specifically in relation to customers on a recurring payment subscription, and in my case using a failed payment handling process that retries every 3/5/7 days after failure.

https://github.com/strangerstudios/paid-memberships-pro/blob/fd8e340e10cce69d7e4364c8d981856af48c1ce5/includes/functions.php#L587

**Comment by dparker1005** [comment]
This issue should be resolved by the Subscriptions Table included in PMPro v3.0.
