### ISSUE TITLE
 allow certain IPs free access to all content?

### ISSUE THREAD

**Issue by pbrocks** [strangerstudios/paid-memberships-pro#666]
Feature request

The latest version of both.

Is it possible allow certain IPs free access to all content? Could I pay to have that addon created?

https://www.paidmembershipspro.com/forums/topic/allow-certain-ips-free-access/

**Comment by eighty20results** [comment]
IMHO, this is a bad idea (and impossible to enforce since most every IP address these days is behind a NAT gateway and thus is shared by multiple people). How would it handle things like a user who should have access but happens to be at Starbucks, for instance? (Or any proxy/reverse proxy).

**Comment by ideadude** [comment]
Best done by custom gist similar to this:
https://www.paidmembershipspro.com/how-to-have-a-paid-memberships-pro-level-with-access-to-everything/

https://gist.github.com/strangerstudios/5774136#file-my_pmpro_has_membership_access_filter-php

If it seems like a common need, we could build an add on with a UI to store the IP addresses.
