### ISSUE TITLE
php7.2 compatibility

### ISSUE THREAD

**Issue by pbrocks** [strangerstudios/paid-memberships-pro#667]
Seems like there are some incompatibilities with 7.2, according to the two respondents in this thread:

https://www.paidmembershipspro.com/forums/topic/urgent-customers-cant-complete-registration/#post-147151

**Comment by chill986** [comment]
The plugin works all the way through PayPal transaction completion, but then no membership is added, and no notifications go out.  I had my production and dev sites both set to php7.2.4, and rolled them back to 7.1, and everything now works.

If you wanted to test in the dev site, I could set it back to php7.2.4?  Just let me know.

**Comment by ideadude** [comment]
I believe this has been fixed here https://github.com/strangerstudios/paid-memberships-pro/commit/a7d217dc3e408998648eb9b35acbefd11cc0c7ce#diff-140593b08fa33b86d2773b5c0ba5fdea (and the following 2 commits by andrew).

Let me know if you're still having issues.
