### ISSUE TITLE
class.pmprogateway_strip.php alters pmpro_required_billing_fields even when not active

### ISSUE THREAD

**Issue by buddhabackpacker** [strangerstudios/paid-memberships-pro#676]
In trying to create a list of required billing fields for a specific case, the filter 'pmpro_required_billing_fields' in header checkout.php has another active filter that returns a shortened list of fields.   I have no payments active, and have traced it to this particular file line 130.   Somehow the Stripe gateway is loading even though there are no payments for this particular website.

commenting out line 130 solves the problem but I can't find where this gateway is being included.  Still working on a workaround.

**Comment by mircobabini** [comment]
Fix: https://gist.github.com/mircobabini/467ccfe8aad8046b82a97264fc568200

**Comment by dparker1005** [comment]
This issue was fixed here: https://github.com/strangerstudios/paid-memberships-pro/commit/33df2e16b0fd3a06a853a833b10a8c620232ae5c
