### ISSUE TITLE
Hide Metafields for certain usergroups

### ISSUE THREAD

**Issue by ghost** [strangerstudios/paid-memberships-pro#681]
Hi there,

on my membership site I am using metafields/customfields in the content and I don't want that certain usergroups can see those fields.

I tried this code here but it does not filter the meta/customfields

`function my_init_change_pmpro_content_filter_priority()
{
	remove_filter('the_content', 'pmpro_membership_content_filter', 5);
	add_filter('the_content', 'pmpro_membership_content_filter', 15);
}
add_action('init', 'my_init_change_pmpro_content_filter_priority');`

**Comment by kimcoleman** [comment]
What method are you using to insert your meta fields into your content?

Most likely you can use the WordPress filter for get_(meta_type)_metadata (https://codex.wordpress.org/Plugin_API/Filter_Reference/get_(meta_type)_metadata) to write a custom filter to only display content for allowed levels.

**Comment by dparker1005** [comment]
As we have not heard back from you, we are going to close this issue. If this is still something that you would like to look into, please feel free to create a new issue.
