### ISSUE TITLE
MAXFAILPAYMENTS not being used?

### ISSUE THREAD

**Issue by Leinad4Mind** [strangerstudios/paid-memberships-pro#684]
So in paypal on all subscriotions I got:
This profile will be suspended after: No limit failure

And therefor the user is always active even if he doesnt pay.

How can I fix this? For what I read the code that uses the API should make use of:
MAXFAILPAYMENTS=1

Any idea how to solve this bug?

**Comment by mircobabini** [comment]
Commit to set MAXFAILEDPAYMENTS=1

0620227

Done.
