### ISSUE TITLE
PMPro/Authorize.net Subscription ID Disconnect Report

### ISSUE THREAD

**Issue by strangerstudios** [strangerstudios/paid-memberships-pro#7]
Customers using PMPro with Authorize.net from version 1.2(ish) through 1.3.8 may have members who signed up with accounts that are not properly connected with the subscription at Authorize.net.

There was a bug during those versions that used the pre-authorization transaction id instead of the subscription transaction id when saving the order in PMPro. This means that when those users cancel their account from PMPro, Authorize.net will not be updated to actually cancel the payment subscription.

I am developing a script that will loop through your members and check for broken subscription ids. This will give you a list of members you should manually check in Authorize.net to see if their subscription is available if it should be... or cancelled if it should be. You'll also be able to update the subscription ID in PMPro so the accounts are linked again.

This is a big problem because you may have customers who think they have cancelled but are still being billed. We will help you resolve these conflicts as best we can. This script will help with that.

**Comment by nickwebservices** [comment]
Just jumping in because I need the same exact thing.

Please advise if the script is ready for "looping through your members and check for broken subscription ids."

**Comment by strangerstudios** [comment]
Here is the script for checking subscription IDs. We may be updating it in the near future, but it does what it says it does for now: https://github.com/strangerstudios/pmpro-subscription-check
