### ISSUE TITLE
Issue with Latest Update & 2checkout Gateway!

### ISSUE THREAD

**Issue by CeirtStudiosAP** [strangerstudios/paid-memberships-pro#701]
Hi everyone,

This is the error i am facing after clicking "Proceed to checkout" on the latest version of pmpro.

The 1.9.4.2 is working great!

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function pmpro_after_checkout_update_consent(), 1 passed in /home/ceirtc5/public_html/wp-includes/class-wp-hook.php on line 288 and exactly 2 expected in /home/ceirtc5/public_html/wp-content/plugins/paid-memberships-pro/includes/privacy.php:483 Stack trace: #0 /home/ceirtc5/public_html/wp-includes/class-wp-hook.php(288): pmpro_after_checkout_update_consent(5) #1 /home/ceirtc5/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /home/ceirtc5/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /home/ceirtc5/public_html/wp-content/plugins/paid-memberships-pro/classes/gateways/class.pmprogateway_twocheckout.php(231): do_action('pmpro_before_se...', 5, Object(MemberOrder)) #4 /home/ceirtc5/public_html/wp-includes/class-wp-hook.php(286): PMProGateway_Twocheckout::pmpro_checkout_before_change_membership_level(5, Object(MemberOrder)) #5 /home/ceirtc5/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filte in /home/ceirtc5/public_html/wp-content/plugins/paid-memberships-pro/includes/privacy.php on line 483 `

**Comment by CeirtStudiosAP** [comment]
When will it be fixed 👍

**Comment by dparker1005** [comment]
This was resolved in PMPro 2.0.5.

**Comment by CeirtStudiosAP** [comment]
Lol
