### ISSUE TITLE
Integration with a new payment gateway FORTUMO SMS payment (offsite)

### ISSUE THREAD

**Issue by emothek** [strangerstudios/paid-memberships-pro#702]
I'm having issue with callback from Fortumo , here is Fortumo SDK : https://merchants.fortumo.com/integration-and-testing/web/

Main issue for now is my custom plugin is not INSERTING into the table "sdurWdckpmpro_memberships_users" in order to properly track which user has paid for membership, please note that "sdurWdckpmpro_membership_orders" is having successfully updated with an insert like this : 
23379AB657 | 47f23d8c4d0dea443846def46f7a3ae4 | 10 | 2 |   |   |   |   |   |   |   |   | 1.00 | 0 |   | 14 | 0 |   | 1 | Fortumo |   |   |   |   | success | fortumo | live | FORTUMO23379AB657 | FORTUMO23379AB657 | 2018-06-08 02:09:31 |  

when I add  "add_filter('pmpro_checkout_confirmed', array('PMProGateway_paypalexpress', 'pmpro_checkout_confirmed'));"  I have missing User ID , PAYMENT_TRANSACTION_ID , SUBSCRIPTION_TRANSACTION_ID; 

here is the code I built so far : 

`<?php
    //include pmprogateway
    require_once(dirname(__FILE__) . "/class.pmprogateway.php");
    
    //load classes init method
    add_action('init', array('PMProGateway_fortumo', 'init'));
    
    class PMProGateway_fortumo extends PMProGateway
    {
        function __construct($gateway = NULL)
        {
            $this->gateway = $gateway;
            return $this->gateway;
        }                                       
        
        /**
         * Run on WP init
         *       
         * @since 1.8
         */
        static function init()
        {           
            //make sure Pay by SMS is a gateway option
            add_filter('pmpro_gateways', array('PMProGateway_fortumo', 'pmpro_gateways'));
            
            //add fields to payment settings
            add_filter('pmpro_payment_options', array('PMProGateway_fortumo', 'pmpro_payment_options'));
            add_filter('pmpro_payment_option_fields', array('PMProGateway_fortumo', 'pmpro_payment_option_fields'), 10, 2);
            add_filter('pmpro_checkout_after_payment_information_fields', array('PMProGateway_fortumo', 'pmpro_checkout_after_payment_information_fields'));

            //code to add at checkout
            $gateway = pmpro_getGateway();
            if($gateway == "fortumo")
            {
                add_filter('pmpro_include_billing_address_fields', '__return_false');
                add_filter('pmpro_include_payment_information_fields', '__return_false');
                add_filter('pmpro_required_billing_fields', array('PMProGateway_fortumo', 'pmpro_required_billing_fields'));

                add_action('pmpro_checkout_before_processing', array('PMProGateway_fortumo', 'pmpro_checkout_before_processing'));
                add_filter('pmpro_checkout_default_submit_button', array('PMProGateway_fortumo', 'pmpro_checkout_default_submit_button'));
                add_filter('pmpro_checkout_before_change_membership_level', array('PMProGateway_fortumo', 'pmpro_checkout_before_change_membership_level'), 10, 2);
                add_filter('pmpro_after_checkout', array('PMProGateway_fortumo', 'pmpro_after_checkout'));

            }
        }
        

        /**
         * Instead of change membership levels, send users to PayPal to pay.
         *
         * @param int           $user_id
         * @param \MemberOrder  $morder
         *
         * @since 1.8
         */
        static function pmpro_checkout_before_change_membership_level($user_id, $morder)
        {
            global $discount_code_id, $wpdb;
                        
            //if no order, no need to pay
            if(empty($morder))
                return;
                            
            $morder->user_id = $user_id;                
            $morder->saveOrder();
            
            //save discount code use
            if(!empty($discount_code_id))
                $wpdb->query("INSERT INTO $wpdb->pmpro_discount_codes_uses (code_id, user_id, order_id, timestamp) VALUES('" . $discount_code_id . "', '" . $user_id . "', '" . $morder->id . "', now())"); 
            
            do_action("pmpro_before_send_to_fortumo", $user_id, $morder);
            
            $morder->Gateway->sendToFortumo($user_id, $morder);
        }

        /**
         * Swap in our submit buttons.
         *
         * @param bool $show
         *
         * @return bool
         *
         * @since 1.8
         */
        static function pmpro_checkout_default_submit_button($show)
        {
            global $gateway, $pmpro_requirebilling;
            
            //show our submit buttons
            ?>
            <span id="pmpro_fortumo_checkout" <?php if(($gateway != "fortumo") || !$pmpro_requirebilling) { ?>style="display: none;"<?php } ?>>
                <input type="hidden" name="submit-checkout" value="1" />        
                <input type="image" value="<?php _e('Check Out with Fortumo', 'paid-memberships-pro' );?> &raquo;" src="<?php echo apply_filters("pmpro_fortumo_button_image", "https://assets.fortumo.com/fmp/fortumopay_150x50_red.png");?>" />
            </span>
            
            <span id="pmpro_submit_span" <?php if(($gateway == "fortumo") && $pmpro_requirebilling) { ?>style="display: none;"<?php } ?>>
                <input type="hidden" name="submit-checkout" value="1" />        
                <input type="submit" class="pmpro_btn pmpro_btn-submit-checkout" value="<?php if($pmpro_requirebilling) { _e('Submit and Check Out', 'paid-memberships-pro' ); } else { _e('Submit and Confirm', 'paid-memberships-pro' );}?> &raquo;" />               
            </span>
            <?php
        
            //don't show the default
            return false;
        }

        /**
         * Make sure Fortumo is in the gateways list
         *       
         * @since 1.8
         */
        static function pmpro_gateways($gateways)
        {
            if(empty($gateways['fortumo']))
                $gateways['fortumo'] = __('Pay by SMS', 'paid-memberships-pro' );
        
            return $gateways;
        }
        
        /**
         * Get a list of payment options that the SMS gateway needs/supports.
         *       
         * @since 1.8
         */
        static function getGatewayOptions()
        {           
            $options = array(
                'sslseal',
                'nuclear_HTTPS',
                'gateway_environment',
                'instructions',
                'currency',
                'use_ssl',
                'tax_state',
                'tax_rate',
                'service_id',
                'secret'
            );
            
            return $options;
        }
        
        /**
         * Set payment options for payment settings page.
         *       
         * @since 1.8
         */
        static function pmpro_payment_options($options)
        {           
            //get stripe options
            $fortumo_options = PMProGateway_fortumo::getGatewayOptions();
            
            //merge with others.
            $options = array_merge($fortumo_options, $options);
            
            return $options;
        }
        
        /**
         * Display fields for SMS options.
         *       
         * @since 1.8
         */

        static function pmpro_payment_option_fields($values, $gateway)
        {
        ?>
        <tr class="pmpro_settings_divider gateway gateway_fortumo" <?php if($gateway != "fortumo") { ?>style="display: none;"<?php } ?>>
            <td colspan="2">
                <?php _e('Fortumo Settings', 'paid-memberships-pro' ); ?>
            </td>
        </tr>       
        <tr class="gateway gateway_fortumo" <?php if($gateway != "fortumo") { ?>style="display: none;"<?php } ?>>
            <td colspan="2">
                <strong><?php _e('Note', 'paid-memberships-pro' );?>:</strong> <?php _e('Please insert your SERVICE ID and SECRET provided on the settings dashboard on Fortumo.' );?>
            </td>   
        </tr>   

        <tr class="gateway gateway_fortumo" <?php if($gateway != "fortumo") { ?>style="display: none;"<?php } ?>>
            <th scope="row" valign="top">   
                <label for="service_id"><?php _e('Fortumo Service ID', 'paid-memberships-pro' );?>:</label>
            </th>
            <td>
                <input type="text" id="service_id" name="service_id" size="60" value="<?php echo esc_attr($values['service_id'])?>" />
            </td>
        </tr>  

        <tr class="gateway gateway_fortumo" <?php if($gateway != "fortumo") { ?>style="display: none;"<?php } ?>>
            <th scope="row" valign="top">
                <label for="secret"><?php _e('Secret', 'paid-memberships-pro' );?>:</label>
            </th>
            <td>
                <input type="text" id="secret" name="secret" size="60" value="<?php echo esc_attr($values['secret'])?>" />
            </td>
        </tr>

        <tr class="gateway gateway_fortumo" <?php if($gateway != "fortumo") { ?>style="display: none;"<?php } ?>>
            <th scope="row" valign="top">
                <label for="instructions"><?php _e('Instructions', 'paid-memberships-pro' );?></label>                  
            </th>
            <td>
                <textarea id="instructions" name="instructions" rows="3" cols="80"><?php echo wpautop(  wp_unslash( $values['instructions'] ) ); ?></textarea>
                <p><small><?php _e('Who to write the check out to. Where to mail it. Shown on checkout, confirmation, and invoice pages.', 'paid-memberships-pro' );?></small></p>
            </td>
        </tr>   

        <?php
        }

        /**
         * Remove required billing fields
         *       
         * @since 1.8
         */
        static function pmpro_required_billing_fields($fields)
        {
            unset($fields['bfirstname']);
            unset($fields['blastname']);
            unset($fields['baddress1']);
            unset($fields['bcity']);
            unset($fields['bstate']);
            unset($fields['bzipcode']);
            unset($fields['bphone']);
            unset($fields['bemail']);
            unset($fields['bcountry']);
            unset($fields['CardType']);
            unset($fields['AccountNumber']);
            unset($fields['ExpirationMonth']);
            unset($fields['ExpirationYear']);
            unset($fields['CVV']);
            
            return $fields;
        }

        /**
         * Save session vars before processing
         *
         * @since 1.8
         */
        static function pmpro_checkout_before_processing()
        {
            global $current_user, $gateway;

            //save user fields for PayPal Express
            if(!$current_user->ID)
            {
                //get values from post
                if(isset($_REQUEST['username']))
                    $username = trim(sanitize_text_field($_REQUEST['username']));
                else
                    $username = "";
                if(isset($_REQUEST['password']))
                    $password = sanitize_text_field($_REQUEST['password']);
                else
                    $password = "";
                if(isset($_REQUEST['bemail']))
                    $bemail = sanitize_email($_REQUEST['bemail']);
                else
                    $bemail = "";

                //save to session
                $_SESSION['pmpro_signup_username'] = $username;
                $_SESSION['pmpro_signup_password'] = $password;
                $_SESSION['pmpro_signup_email'] = $bemail;
            }

            //can use this hook to save some other variables to the session
            do_action("pmpro_fortumo_session_vars");
        }

        /**
         * Show instructions on checkout page
         * Moved here from pages/checkout.php
         * @since 1.8.9.3
         */
        static function pmpro_checkout_after_payment_information_fields() {
            global $gateway;
            global $pmpro_level;

            if($gateway == "fortumo" && !pmpro_isLevelFree($pmpro_level)) {
                $instructions = pmpro_getOption("instructions");
                echo '<div class="pmpro_fortumo_instructions">' . wpautop(wp_unslash( $instructions )) . '</div>';
            }
        }

        /**
         * Send the data/order to Fortumo's server
         *
         * @param \MemberOrder $order
         * $user_id, $morder
         */
        function sendToFortumo(&$user_id, &$order)
        {                       
            global $pmpro_currency;         
            
            //taxes on initial amount
            $initial_payment = $order->InitialPayment;
            $initial_payment_tax = $order->getTaxForPrice($initial_payment);
            $initial_payment = round((float)$initial_payment + (float)$initial_payment_tax, 2);
            
        
            
            //build Fortumo Redirect URL
            $environment = pmpro_getOption("gateway_environment");
            
            if("sandbox" === $environment || "beta-sandbox" === $environment) {
                $fortumo_url = "http://pay.fortumo.com/mobile_payments";
            } else {
                $fortumo_url = "http://pay.fortumo.com/mobile_payments";
            }
            
            if(pmpro_isLevelRecurring($order->membership_level))
            {               
                 
                //other args
                $fortumo_args = array(
                    'service_id' =>  pmpro_getOption("service_id"),

                    'cuid' =>  $user_id, // string : custom id optional refers to specific user in the system, username 21

                    'operation_reference' => '', // optional param unique per every transaction oder_12345

                    //'credit_name' => '', // can be used to override default credit name, only for virtual credit services

                    //'product_name' => '', // can be used to override default product name

                    //'price' => 2.00, // override virutal currency exchange rate FLOAT 2 decimals

                    //'currency' => '', // string ISO 4217 override virtual currency EUR USD ...etc

                    //'country_code' => '', // string ISO Alpha-2 eg : MY

                    //'amount' => 1, // amount param 

                    //'display_type' => '',

                    //'tc_id' => 39, // Tariffclass ID is an optional parameter that allows you to preselect a specific price point for virtual credit services.

                    //'tc_amount' => 199, // Tariffclass amount is an optional parameter that allows you to specify a specific amount of credits that you want to sell at a specified tariffclass.

                    //'msisdn' => 61234556789 // MSISDN parameter can be used for prefilling consumer phone number in the payment flow in case you already know that for example from their signup process.

                    //'mcc' => 722, // Mobile country code used together with mobile network code allows you to preselect consumer carrier in countries with carrier selection.

                    //'mnc' => 310, // Mobile network code used together with mobile country code allows you to preselect consumer carrier in countries with carrier selection.

                    //'msisdn_edit_disabled' => true, // Optional parameter that can be used together with mobile country code and mobile network code in case you need to prevent consumers from making payments from phone numbers other than they have signed up with.

                    //'test' => ok, // Test parameter allows you to initialize a payment in sandbox mode even after the service has already been switched live. In case test parameter value is set as ok, sandbox payment is processed successfully. In case test parameter value is set as fail, unsuccessful sandbox payment is processed.

                    'sig' => '', //  md5 checksum of the REQUEST PARAMS and SECRET concatenated together

                    //'callback_url' => '', // Callback URL parameter allows you to override the return to merchant URL configured on Fortumo dashboard. 
                );                  
                                
            }
            else
            {
                //other args
                $fortumo_args = array(
                    'service_id' =>  pmpro_getOption("service_id"),

                    'cuid' =>  '', // string : custom id optional refers to specific user in the system, username 21

                    'operation_reference' => '', // optional param unique per every transaction oder_12345

                    //'credit_name' => '', // can be used to override default credit name, only for virtual credit services

                    //'product_name' => '', // can be used to override default product name

                    //'price' => 2.00, // override virutal currency exchange rate FLOAT 2 decimals

                    //'currency' => '', // string ISO 4217 override virtual currency EUR USD ...etc

                    //'country_code' => '', // string ISO Alpha-2 eg : MY

                    //'amount' => 1, // amount param 

                    //'display_type' => '',

                    //'tc_id' => 39, // Tariffclass ID is an optional parameter that allows you to preselect a specific price point for virtual credit services.

                    //'tc_amount' => 199, // Tariffclass amount is an optional parameter that allows you to specify a specific amount of credits that you want to sell at a specified tariffclass.

                    //'msisdn' => 61234556789 // MSISDN parameter can be used for prefilling consumer phone number in the payment flow in case you already know that for example from their signup process.

                    //'mcc' => 722, // Mobile country code used together with mobile network code allows you to preselect consumer carrier in countries with carrier selection.

                    //'mnc' => 310, // Mobile network code used together with mobile country code allows you to preselect consumer carrier in countries with carrier selection.

                    //'msisdn_edit_disabled' => true, // Optional parameter that can be used together with mobile country code and mobile network code in case you need to prevent consumers from making payments from phone numbers other than they have signed up with.

                    //'test' => ok, // Test parameter allows you to initialize a payment in sandbox mode even after the service has already been switched live. In case test parameter value is set as ok, sandbox payment is processed successfully. In case test parameter value is set as fail, unsuccessful sandbox payment is processed.

                    'sig' => '', //  md5 checksum of the REQUEST PARAMS and SECRET concatenated together

                    //'callback_url' => '', // Callback URL parameter allows you to override the return to merchant URL configured on Fortumo dashboard. 
                 ); 
            }                       
            
            ksort($fortumo_args);

            $fortumo_args['sig'] = md5(http_build_query( $fortumo_args ).pmpro_getOption("secret"));// signature : calculate MD5 of req params and SECRET concatenated .

            //anything modders might add
            /*$additional_parameters = apply_filters("pmpro_paypal_express_return_url_parameters", array());

            foreach( $additional_parameters as $key => $value ) {
                
                $fortumo_args[$key] = $value;
            }*/

            $nvpStr = "";
            
            //$account_optional = apply_filters('pmpro_paypal_account_optional', true);
            /*
            if ($account_optional) {
                $fortumo_args['SOLUTIONTYPE'] = "Sole";
                $fortumo_args['LANDINGPAGE'] = "Billing";
            }*/
            
            $nvpStr = http_build_query( $fortumo_args );
            //$nvpStr = apply_filters("pmpro_paypal_standard_nvpstr", $nvpStr, $order);
            
            //Build complete URI for paypal redirect
            $fortumo_url = "{$fortumo_url}/{$fortumo_args['service_id']}?{$nvpStr}";
            
            //wp_die(str_replace("&", "<br />", $fortumo_url));
            //echo $fortumo_url; 
            //$txt = $fortumo_url;
            //$myfile = file_put_contents('logs.txt', $txt.PHP_EOL , FILE_APPEND | LOCK_EX);

            wp_redirect($fortumo_url);
            exit;
        }

        function check_signature($params_array, $secret) {
            ksort($params_array);

            $str = '';
            foreach ($params_array as $k=>$v) {
              if($k != 'sig') {
                $str .= "$k=$v";
              }
            }
            $str .= $secret;
            $signature = md5($str);

            return ($params_array['sig'] == $signature);
        }

        /**
         * Review and Confirmation code.
         *
         * @since 1.8
         */
        static function pmpro_checkout_confirmed($pmpro_confirmed)
        {
            global $pmpro_msg, $pmpro_msgt, $pmpro_level, $current_user, $pmpro_review, $pmpro_paypal_token, $discount_code, $bemail;

            //Fortumo Call Backs
              // check that the request comes from Fortumo server
            $secret = 'd9c970c0db70b11fb47594c004783ee2'; // insert your secret between ''

            if(in_array($_SERVER['REMOTE_ADDR'], array('1.2.3.4', '2.3.4.5'))) {
                // check the signature
                if( (!empty($secret) || check_signature($_GET, $secret)) && (preg_match("/completed/i", $_GET['status'])) ) {

                    $_SESSION['payer_id'] = sanitize_text_field($_REQUEST['payment_id']);
                    /* 
                    $_SESSION['paymentAmount'] = sanitize_text_field($_REQUEST['paymentAmount']);
                    $_SESSION['currCodeType'] = sanitize_text_field($_REQUEST['currencyCodeType']);
                    $_SESSION['paymentType'] = sanitize_text_field($_REQUEST['paymentType']); 
                    */

                    $morder = new MemberOrder();
                    $morder->getMemberOrderByFortumoToken(sanitize_text_field($_REQUEST['payment_id']));
                    $morder->Token = $morder->paypal_token; $pmpro_paypal_token = $morder->paypal_token;
                    if($morder->Token)
                    {

                            if(preg_match("/completed/i", $_GET['status'])) //$morder->Gateway->getExpressCheckoutDetails($morder))
                            {
                                $pmpro_review = true;
                            }
                            else
                            {
                                $pmpro_msg = $morder->error;
                                $pmpro_msgt = "pmpro_error";
                            }
                    }
                    else
                    {
                        $pmpro_msg = __("The Fortumo Token was lost.", 'paid-memberships-pro' );
                        $pmpro_msgt = "pmpro_error";
                    }
                    
                    
                    if(empty($pmpro_msg) && !empty($_REQUEST['confirm']) && $pmpro_review)
                    {
                        $morder = new MemberOrder();
                        $morder->getMemberOrderByFortumoToken(sanitize_text_field($_REQUEST['payment_id']));
                        $morder->Token = $morder->paypal_token; $pmpro_paypal_token = $morder->paypal_token;
                        if($morder->Token)
                        {
                            //set up values
                            $morder->membership_id = $pmpro_level->id;
                            $morder->membership_name = $pmpro_level->name;
                            $morder->discount_code = $discount_code;
                            $morder->InitialPayment = $pmpro_level->initial_payment;
                            $morder->PaymentAmount = $pmpro_level->billing_amount;
                            $morder->ProfileStartDate = date_i18n("Y-m-d") . "T0:0:0";
                            $morder->BillingPeriod = $pmpro_level->cycle_period;
                            $morder->BillingFrequency = $pmpro_level->cycle_number;
                            $morder->Email = $bemail;

                            //set up level var
                            $morder->getMembershipLevel();
                            $morder->membership_level = apply_filters("pmpro_checkout_level", $morder->membership_level);

                            //tax
                            $morder->subtotal = $morder->InitialPayment;
                            $morder->getTax();
                            if($pmpro_level->billing_limit)
                                $morder->TotalBillingCycles = $pmpro_level->billing_limit;

                            if(pmpro_isLevelTrial($pmpro_level))
                            {
                                $morder->TrialBillingPeriod = $pmpro_level->cycle_period;
                                $morder->TrialBillingFrequency = $pmpro_level->cycle_number;
                                $morder->TrialBillingCycles = $pmpro_level->trial_limit;
                                $morder->TrialAmount = $pmpro_level->trial_amount;
                            }

                            if($morder->confirm())
                            {
                                $pmpro_confirmed = true;
                            }
                            else
                            {
                                $pmpro_msg = $morder->error;
                                $pmpro_msgt = "pmpro_error";
                            }
                        }
                        else
                        {
                            $pmpro_msg = __("The Fortumo Token was lost.", 'paid-memberships-pro' );
                            $pmpro_msgt = "pmpro_error";
                        }
                    }

                    if(!empty($morder))
                        return array("pmpro_confirmed"=>$pmpro_confirmed, "morder"=>$morder);
                    else
                        return $pmpro_confirmed;

                }
            }

        }

        /**
         * Process charge or subscription after confirmation.
         *
         * @since 1.8
         */
        function confirm(&$order)
        {
            if(pmpro_isLevelRecurring($order->membership_level))
            {
                $order->ProfileStartDate = date_i18n("Y-m-d", strtotime("+ " . $order->BillingFrequency . " " . $order->BillingPeriod, current_time("timestamp"))) . "T0:0:0";
                $order->ProfileStartDate = apply_filters("pmpro_profile_start_date", $order->ProfileStartDate, $order);
                return $this->subscribe($order);
            }
            else
                return $this->charge($order);
        }

        /**
         * Code to run after checkout
         *
         * @since 1.8
         */
        static function pmpro_after_checkout($user_id, $morder)
        {
            global $gateway;

            if($gateway == "fortumo")
            {
                if(static::$is_loaded && !empty($morder) && !empty($morder->Gateway) && !empty($morder->Gateway->customer) && !empty($morder->Gateway->customer->id))
                {
                    update_user_meta($user_id, "pmpro_fortumo_customerid", $morder->Gateway->customer->id);
                }
            }
        }

        
        /**
         * Process checkout.
         *
         */
        function process(&$order)
        {
            if(empty($order->code))
                $order->code = $order->getRandomCode();         
            
            //clean up a couple values
            $order->payment_type = "Fortumo";
            $order->CardType = "";
            $order->cardtype = "";
            
            //just save, the user will go to PayPal to pay
            $order->status = "review";                                                      
            $order->saveOrder();

            //check for initial payment
            if(floatval($order->InitialPayment) == 0)
            {
                //auth first, then process
                if($this->authorize($order))
                {                       
                    $this->void($order);                                        
                    if(!pmpro_isLevelTrial($order->membership_level))
                    {
                        //subscription will start today with a 1 period trial
                        $order->ProfileStartDate = date_i18n("Y-m-d") . "T0:0:0";
                        $order->TrialBillingPeriod = $order->BillingPeriod;
                        $order->TrialBillingFrequency = $order->BillingFrequency;                                                   
                        $order->TrialBillingCycles = 1;
                        $order->TrialAmount = 0;
                        
                        //add a billing cycle to make up for the trial, if applicable
                        if(!empty($order->TotalBillingCycles))
                            $order->TotalBillingCycles++;
                    }
                    elseif($order->InitialPayment == 0 && $order->TrialAmount == 0)
                    {
                        //it has a trial, but the amount is the same as the initial payment, so we can squeeze it in there
                        $order->ProfileStartDate = date_i18n("Y-m-d") . "T0:0:0";                                                       
                        $order->TrialBillingCycles++;
                        
                        //add a billing cycle to make up for the trial, if applicable
                        if($order->TotalBillingCycles)
                            $order->TotalBillingCycles++;
                    }
                    else
                    {
                        //add a period to the start date to account for the initial payment
                        $order->ProfileStartDate = date_i18n("Y-m-d", strtotime("+ " . $order->BillingFrequency . " " . $order->BillingPeriod, current_time("timestamp"))) . "T0:0:0";
                    }
                    
                    $order->ProfileStartDate = apply_filters("pmpro_profile_start_date", $order->ProfileStartDate, $order);
                    return $this->subscribe($order);
                }
                else
                {
                    if(empty($order->error))
                        $order->error = __("Unknown error: Authorization failed.", 'paid-memberships-pro' );
                    return false;
                }
            }
            else
            {
                //charge first payment
                if($this->charge($order))
                {                           
                    //set up recurring billing                  
                    if(pmpro_isLevelRecurring($order->membership_level))
                    {                       
                        if(!pmpro_isLevelTrial($order->membership_level))
                        {
                            //subscription will start today with a 1 period trial
                            $order->ProfileStartDate = date_i18n("Y-m-d") . "T0:0:0";
                            $order->TrialBillingPeriod = $order->BillingPeriod;
                            $order->TrialBillingFrequency = $order->BillingFrequency;                                                   
                            $order->TrialBillingCycles = 1;
                            $order->TrialAmount = 0;
                            
                            //add a billing cycle to make up for the trial, if applicable
                            if(!empty($order->TotalBillingCycles))
                                $order->TotalBillingCycles++;
                        }
                        elseif($order->InitialPayment == 0 && $order->TrialAmount == 0)
                        {
                            //it has a trial, but the amount is the same as the initial payment, so we can squeeze it in there
                            $order->ProfileStartDate = date_i18n("Y-m-d") . "T0:0:0";                                                       
                            $order->TrialBillingCycles++;
                            
                            //add a billing cycle to make up for the trial, if applicable
                            if(!empty($order->TotalBillingCycles))
                                $order->TotalBillingCycles++;
                        }
                        else
                        {
                            //add a period to the start date to account for the initial payment
                            $order->ProfileStartDate = date_i18n("Y-m-d", strtotime("+ " . $order->BillingFrequency . " " . $order->BillingPeriod, current_time("timestamp"))) . "T0:0:0";
                        }
                        
                        $order->ProfileStartDate = apply_filters("pmpro_profile_start_date", $order->ProfileStartDate, $order);
                        if($this->subscribe($order))
                        {
                            $order->status = apply_filters("pmpro_check_status_after_checkout", "success"); //saved on checkout page    
                            return true;
                        }
                        else
                        {
                            if($this->void($order))
                            {
                                if(!$order->error)
                                    $order->error = __("Unknown error: Payment failed.", 'paid-memberships-pro' );
                            }
                            else
                            {
                                if(!$order->error)
                                    $order->error = __("Unknown error: Payment failed.", 'paid-memberships-pro' );
                                
                                $order->error .= " " . __("A partial payment was made that we could not void. Please contact the site owner immediately to correct this.", 'paid-memberships-pro' );
                            }
                            
                            return false;                               
                        }
                    }
                    else
                    {
                        //only a one time charge
                        $order->status = apply_filters("pmpro_check_status_after_checkout", "success"); //saved on checkout page                                            
                        return true;
                    }
                }
                else
                {
                    if(empty($order->error))
                        $order->error = __("Unknown error: Payment failed.", 'paid-memberships-pro' );
                    
                    return false;
                }   
            }   

            return true;
        }

        
        function authorize(&$order)
        {
            //create a code for the order
            if(empty($order->code))
                $order->code = $order->getRandomCode();
            
            //simulate a successful authorization
            $order->payment_transaction_id = "FORTUMO" . $order->code;
            $order->updateStatus("authorized");                                                 
            return true;                    
        }
        
        function void(&$order)
        {
            //need a transaction id
            if(empty($order->payment_transaction_id))
                return false;
                
            //simulate a successful void
            $order->payment_transaction_id = "FORTUMO" . $order->code;
            $order->updateStatus("voided");                 
            return true;
        }   
        
        function charge(&$order)
        {
            //create a code for the order
            if(empty($order->code))
                $order->code = $order->getRandomCode();
            
            //simulate a successful charge
            $order->payment_transaction_id = "FORTUMO" . $order->code;
            $order->updateStatus("success");                    
            return true;                        
        }
        
        function subscribe(&$order)
        {
            //create a code for the order
            if(empty($order->code))
                $order->code = $order->getRandomCode();
            
            //filter order before subscription. use with care.
            $order = apply_filters("pmpro_subscribe_order", $order, $this);
            
            //simulate a successful subscription processing
            $order->status = "success";     
            $order->subscription_transaction_id = "FORTUMO" . $order->code;             
            return true;
        }   
        
        function update(&$order)
        {
            //simulate a successful billing update
            return true;
        }
        
        function cancel(&$order)
        {
            //require a subscription id
            if(empty($order->subscription_transaction_id))
                return false;
            
            //simulate a successful cancel          
            $order->updateStatus("cancelled");                  
            return true;
        }

        /**
         * PAYPAL Function
         * Send HTTP POST Request
         *
         * @param   string  The API method name
         * @param   string  The POST Message fields in &name=value pair format
         * @return  array   Parsed HTTP Response body
         */
       /* function PPHttpPost($methodName_, $nvpStr_) {
            global $gateway_environment;
            $environment = $gateway_environment;

            $API_UserName = pmpro_getOption("apiusername");
            $API_Password = pmpro_getOption("apipassword");
            $API_Signature = pmpro_getOption("apisignature");
            $API_Endpoint = "https://api-3t.paypal.com/nvp";
            if("sandbox" === $environment || "beta-sandbox" === $environment) {
                $API_Endpoint = "https://api-3t.$environment.paypal.com/nvp";
            }

            $version = urlencode('72.0');

            //NVPRequest for submitting to server
            $nvpreq = "METHOD=" . urlencode($methodName_) . "&VERSION=" . urlencode($version) . "&PWD=" . urlencode($API_Password) . "&USER=" . urlencode($API_UserName) . "&SIGNATURE=" . urlencode($API_Signature) . "&BUTTONSOURCE=" . urlencode(PAYPAL_BN_CODE) . $nvpStr_;

            //post to PayPal
            $response = wp_remote_post( $API_Endpoint, array(
                    'timeout' => 60,
                    'sslverify' => FALSE,
                    'httpversion' => '1.1',
                    'body' => $nvpreq
                )
            );

            if ( is_wp_error( $response ) ) {
               $error_message = $response->get_error_message();
               die( "methodName_ failed: $error_message" );
            } else {
                //extract the response details
                $httpParsedResponseAr = array();
                parse_str(wp_remote_retrieve_body($response), $httpParsedResponseAr);

                //check for valid response
                if((0 == sizeof($httpParsedResponseAr)) || !array_key_exists('ACK', $httpParsedResponseAr)) {
                    exit("Invalid HTTP Response for POST request($nvpreq) to $API_Endpoint.");
                }
            }

            return $httpParsedResponseAr;
        }*/

    }
`

**Comment by ideadude** [comment]
If you create a GitHub repo for your project and share it, it will be easier for us to work with, test, and contribute.

RE why there is no entry in the memberships_users table. It looks like you copied the PayPal Standard gateway, which might make sense based on how Fortumo works, but the PP Standard implementation doesn't give the user a membership level at checkout. Instead, it waits for the PayPal IPN system to send an update in the background, which is then processed here  https://github.com/strangerstudios/paid-memberships-pro/blob/dev/services/ipnhandler.php#L104

You may need to create a similar script to bundle with your gateway plugin to process messages from the gateway. Or maybe if you are returned to the site from Fortumo after checking out, you can process that to find the order you created and make a call to pmpro_changeMembershipLevel/etc.

**Comment by emothek** [comment]
@ideadude  hi, thanks for the explanations, I will try the suggestions out and yes I used Paype Standard, by the way Fortumo has the ability to fire a callback or custom endpoint to handle the update allowing a backend script to switch pending payment to confirmed 🔢 , 

I will try this ASAP and make GitHub repo for fortumo integration, thanks again :)

**Comment by ideadude** [comment]
2Checkout works in a similar way. It sends a message and/or just redirects to the handler script. FYI, you can check out how we do that here https://github.com/strangerstudios/paid-memberships-pro/blob/dev/services/twocheckout-ins.php

Good luck with things. If you get the gateway working, we'd be happy to promote it to our users.
