### ISSUE TITLE
Lots of warnings and notices when sending failed payment emails.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#703]
A lot of the data used to populate the emails may not be available and should be checked to avoid warnings and notices. The email will look funny as well with some of the info missing.

Data here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/class.pmproemail.php#L519-L542

Also the admin email: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/class.pmproemail.php#L566-L587

Funny email example:

> The current subscription payment for your PMPro Dev membership has failed. Please click the following link to log in and update your billing information to avoid account suspension. (scrubbed)
> 
> Account: ppstest5 (email@domain.com)
> 
> The most recent account information we have on file is:
> 
> : 
> Expires: /

**Comment by ideadude** [comment]
Another one from a customer: https://www.paidmembershipspro.com/forums/topic/bug-pmpro-core-php-notice-after-updating-to-pmpro-v2-2-3/

Need to update these checks to use !empty() and check if the membership_level object exists before checking for a property.

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/class.pmproemail.php#L866

**Comment by dparker1005** [comment]
This was fixed here: https://github.com/strangerstudios/paid-memberships-pro/commit/31e9cfe0eb944306221b8fdca8312a46453fbbff
