### ISSUE TITLE
TML 7 removes pmpro_register_redirect

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#712]
When TML 7 is active with PMPro, when a user clicks on register they are directed to the default WordPress registration page instead of the levels page. I'm not sure if this is common functionality with TML activated.

**Comment by andrewlimaza** [comment]
This redirects to the TML /register page.

**Comment by kimcoleman** [comment]
Fixed in https://github.com/strangerstudios/paid-memberships-pro/pull/709/commits/2645e2c25a0a396586bf1364e67355f920fb8c97
