### ISSUE TITLE
wp-login.php redirect

### ISSUE THREAD

**Issue by Sawrz** [strangerstudios/paid-memberships-pro#715]
Hi, 
I can't access on wp-login.php anymore without being redirected to the login page. First, I thought TML causes the issue, because deactivating it stopped the redirect. Therefore, I exchanged several mails with Jeff but we didn't found the problem. Out of curiosity I deactivated PM Pro (was the only recently component updated besides the redirect plugin of TML) and the redirect did not happen too. So I assume the problem has to do more with the update of PMPro than with TML, since TML was still active when I deactivated PMPro. 

I want to avoid the redirect because I use 2FA. Moreover, I feel the idea appealing to have 2 kinds of logins: One for the staff and another one for the members.

Hope you can resolve the issue.

Best,
Sandro

**Comment by ideadude** [comment]
PMPro should only redirect if the action=register. Users would then be redirected to the levels page.

If you are using another form of registration that requires that redirect be disabled, you can use this gist: https://gist.github.com/travislima/661dc43b23b9a9e663888d1f01ea0d1c

We also try to account for this in our add-ons. For example, our BuddyPress add-on has a setting to choose which registration page to use, PMPro or BP.

I'm going to close this issue, but if you can provide more information on how to recreate the issue, we can take a look and see if there is a fix. Thanks.
