### ISSUE TITLE
PMPro with TML 7 interferes with post passwords

### ISSUE THREAD

**Issue by jfarthing84** [strangerstudios/paid-memberships-pro#719]
TML used to handle all actions. However, it no longer does. So, `wp-login.php` is still needed to process the `postpass` action. PMPro's login redirect stops this from happening. Expect a PR soon!

**Comment by jfarthing84** [comment]
For anyone who may be experiencing this and needs a fix until my pull request is merged, you can use the following code snippet:

```
function filter_pmpro_login_redirect( $redirect ) {
	if ( $action = tml_get_request_value( 'action' ) ) {
		$redirect = tml_action_exists( $action );
	}
	return $redirect;
}
add_filter( 'pmpro_login_redirect', 'filter_pmpro_login_redirect' );
```

**Comment by marksplace** [comment]
Hi sorry new to all this where do i put that code

**Comment by jfarthing84** [comment]
In your theme's functions.php file.
