### ISSUE TITLE
Themed Profiles on the Frontend

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#724]
This is possible with Theme My Login. In the latest versions of TML, the functionality has been moved to a paid module that works well.

We should explore including themed profile functionality in the core plugin, as a Plus Add On, or maybe a feature for Memberlite.

**Comment by andrewlimaza** [comment]
This issue may be related - https://github.com/strangerstudios/paid-memberships-pro/issues/727

I think it could be a nice to have. Not sure if it will cause more issues than solve?

**Comment by aquiferweb** [comment]
Agreed - this is the main reason we used TML - to allow a member profile to be edited by the member without taking them to the WP admin backend. Login pages and Lost Password pages can be handled by the free version of TML but the profile pages cannot without a paid version
