### ISSUE TITLE
Why I can't see the Spanish translation?

### ISSUE THREAD

**Issue by jrcorales** [strangerstudios/paid-memberships-pro#725]
Hi guys!

I'm using PMPRO plugin for my website but my website is in Spanich and I can't see the translation on my website.

How can I set Spanich translation the default language for PMPRO?

What happened if I delete all the translations files and only have the Spanish file activated in PMPRO?

I'm using Loco translate plugin

Thanks!

Joel Reyes

**Comment by andrewlimaza** [comment]
Hi Joel,

I am working through the GitHub issues. 

Paid Memberships Pro supports GlotPress and you may have a look here to see if the strings are translated - https://translate.wordpress.org/projects/wp-plugins/paid-memberships-pro

If you are still experiencing issues, please feel free to reach out to our support team on www.paidmembershipspro.com
