### ISSUE TITLE
Use user profile language settings for translations in the WP backend

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/paid-memberships-pro#726]
Currently, PMPro will default to the site's language setting. However, WordPress allows each individual user profile to set their own language. Defaulting to the current profile's language setting, then the site setting would be preferred.

**Comment by dparker1005** [comment]
Fix here, to be released in 2.6. https://github.com/strangerstudios/paid-memberships-pro/commit/a9c4a11a030a4ec92923ce7ddae013635237d02e
