### ISSUE TITLE
Front-end login page

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#727]
User's have requested that PMPro have a built in front-end login page.

**Comment by ideadude** [comment]
As long as the Theme My Login plugin is free and working and not too bloated, our answer will be to install that plugin.

I am considering implementing a kind of front end profile (requires paid add on for TML) as an add on of our own or as part of the member directory add on.

https://github.com/strangerstudios/paid-memberships-pro/issues/724

**Comment by aquiferweb** [comment]
Now that TML is no longer free - can we expedite an 'in-house' solution to this? Don't need to replicate all that TML does - first step would be themed "login" page, next step a themed "edit profile" page I would suggest. I've seen @ideadude mention that this will take some time, but not sure how to help/push this idea? I've had an outdated TML plugin with a modified version number sitting in our sites for over a year now...
