### ISSUE TITLE
Welcome Page, Dashboard, and Menu Updates

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#741]
This work is being done in this branch:
https://github.com/strangerstudios/paid-memberships-pro/tree/welcome-page

1. We are adding a "Dashboard" page under Memberships as the top level default admin page.

2. Users will be redirected here after activating the plugin.

3. The dashboard will have "Welcome" section with 3 columns: Get Started, License, Get Involved

4. We will reconsider which pages have menu items in the sidebar admin menu, the top admin bar, and which pages have tabs/etc.

**Comment by ideadude** [comment]
Q: Should we NOT redirect to the welcome page if multiple plugins are activated at the same time? If not, let's show a notice with a link to the welcome page.

**Comment by ideadude** [comment]
Let's set the Memberships sidebar menu item to show up above the "Appearance" menu.

**Comment by ideadude** [comment]
Sidebar Menu:
* Dashboard
* Members
* Orders
* Levels
* Discount Codes
* Reports
* Settings
* - Page Settings
* - Payment & Gateway Settings
* - Email Settings
* - Advanced Settings
* Add Ons

Add Ons should add their menu item to the end of the list. Or they can add a submenu item under settings.

Admin Toolbar:
* Dashboard
* Members
* Orders
* Levels
* Discount Codes
* Reports
* Settings
* Add Ons

Add Ons should only add an item to the admin bar menu if it is something users will want quick access to from the frontend. E.g. we don't need a link for the Email Templates add on since admins should set that up once and be good. However, the Approvals Add On should add a menu item to the admin bar since you want to visit the approvals page repeatedly even after settings things up.

**Comment by ideadude** [comment]
Tabs on the dashboard and other pages should match the main menu items from the core plugin:

Dashboard | Members | Orders | Reports | Settings | Add-Ons

Settings Sub Menu:
Levels | Discount Codes | Pages | Payment Gateway & SSL | Email | Advanced

**Comment by kimcoleman** [comment]
This is complete on my end and has been merged into v2.0 branch. One remaining item for @ideadude is to somehow get the "Memberships" menu in the left admin menu to stay active/open when on a "settings" subpage.

**Comment by andrewlimaza** [comment]
Been chatting to Kim, I would personally like a quick link to get to the 'membership level' settings and maybe advanced settings. Find I redirect user's quite a bit to these two areas in customer support.

Something to think about, don't want to confuse the new UI/UX by adding non tab sections to admin menu / toolbar.

**Comment by ideadude** [comment]
Left to do:
* Fix menu so the memberships memu is open and highlighted when you are on a sub sub menu/tab.
* Move Memberships up to the CPT area of the menu

**Comment by ideadude** [comment]
Going to close now.

We can create a plugin/gist to show all links (maybe with the - in front for sub tabs) in the menu.
