### ISSUE TITLE
Feature Request: Redirect user's to a page for their first login

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#742]
A user would like to have the ability to redirect members to a specific page on their first login and never let user's access that page thereafter.

For more information: https://www.paidmembershipspro.com/forums/topic/show-a-logged-in-user-a-page-once-on-their-first-log-in-only/

**Comment by kimcoleman** [comment]
I don't think we would build this in core, but I could see a gist for it to insert a user_meta and do the redirect then update the meta to never redirect again.

Look to code in the Member Homepages Add On for some basis for this recipe.

**Comment by dparker1005** [comment]
Closing as this feature would not be built into core.
