### ISSUE TITLE
Bug: Missing Records When Exporting Orders to CSV

### ISSUE THREAD

**Issue by khlau10** [strangerstudios/paid-memberships-pro#743]
When exporting Orders to CSV (by clicking on the Export to CSV button in Orders page), the downloaded CSV file does not contain all of the records as per shown in the Orders page. This happened on me as I have more than 4000 records.

For the moment I work around this issue by changing `pmpro_set_max_orders_per_export_loop` filter to value that is more than 2000 and also more than the total Orders records I have. Of course this will consume more server memory but did solve the issue. I think a proper fix is needed on the core code so that it will work on 2000 default value.

Just to clarify, it is not a problem of memory limit or execution time limit (in php.ini) that cause this, because I enabled the wordpress debug mode and the memory consumption is way below 100MB from the debug log. Also the CSV export file is successfully downloaded and formatted correctly, it is just that more recent records are missing from the file.

Version of Paid Membership Pro: v1.9.5.3

**Comment by ideadude** [comment]
Thanks for the heads up on this. We are going to try to recreate it and see if we can figure out what is going on here. Thanks for posting your work around as well.

**Comment by dparker1005** [comment]
In version 2.1, we addressed an issue where the first 2000 or so orders might be skipped when exporting orders on large sites. This should have resolved the behavior on your site as well. If this is behavior that you are still seeing on the most recent version of PMPro, please feel free to open a new issue and we can look into this further there.
