### ISSUE TITLE
Feature request: Add Google Pay Integration

### ISSUE THREAD

**Issue by AnsieLima** [strangerstudios/paid-memberships-pro#744]
A client wants to add Google Pay Integration to Stripe. This is a similar request to the Apple Pay feature request, found here https://github.com/strangerstudios/paid-memberships-pro/issues/626

**Comment by ideadude** [comment]
No plans currently. Here are our docs on how to add a new payment gateway add on if anyone else wants to tackle it. We will answer specific questions to help you develop the add on, but can't provide direct assistance.

https://www.paidmembershipspro.com/gateway/adding-a-new-gateway/

**Comment by dparker1005** [comment]
This feature was released in v2.5.
