### ISSUE TITLE
If a user only had one level to cancel, say that level instead of All Levels

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#747]
In the code here, if a specific level is chosen to cancel, we include that in the email. Else we show "All Levels".

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/class.pmproemail.php#L154

We can do better. If they only had one level to begin with, let's just tell them that level so we don't confuse them.

**Comment by kimcoleman** [comment]
I am working to recreate this - if the user clicks the "Cancel" button on their membership account page, the system properly sends the single level ID to the email.

It seems that the "All Levels" text shows up when the members is "cancelled" by the system (failed payment or just natural membership expiration.

**Comment by kimcoleman** [comment]
Fixed in https://github.com/strangerstudios/paid-memberships-pro/pull/798
