### ISSUE TITLE
Change blacklist to blocklist/etc

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#750]
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/services/getfile.php#L102

**Comment by ideadude** [comment]
Rename and then add code in /includes/deprecated.php to apply any filters for the old ...blacklist filter to the newly named one.

**Comment by kimcoleman** [comment]
Trying to locate places that need the update:

https://github.com/strangerstudios/paid-memberships-pro/blob/991993479b6df3217b4b80d2fb63f1fee970e300/services/getfile.php#L102-L112

Then needs to add filter `pmpro_getfile_extension_blacklist` to deprecated replaced to `pmpro_getfile_extension_blocklist`.

**Comment by kimcoleman** [comment]
Should we use this same approach? 

https://github.com/strangerstudios/memberlite/blob/c25b0af7795e7671c757250076225fba81b7f67c/inc/deprecated.php

**Comment by kimcoleman** [comment]
This recipe should also be updated: https://gist.github.com/ideadude/137bb0d06f8f49fc262c2fad3010c440#file-my_pmpro_getfile-php

**Comment by kimcoleman** [comment]
Resolved issue https://github.com/strangerstudios/paid-memberships-pro/pull/832
