### ISSUE TITLE
Cyrillic symbols support in levels description

### ISSUE THREAD

**Issue by AiratHalitov** [strangerstudios/paid-memberships-pro#752]
## Levels Page:
![pmpro-bug](https://user-images.githubusercontent.com/4050715/45596420-2f726980-b9d5-11e8-87d2-3607b497bb9e.png)
- cyrillic symbols support in levels description (on other pages Russian language is looks good).
- "per" word is not translated (maybe it's theme issue, because [I translated your plugin on GlotPress](https://translate.wordpress.org/locale/ru/default/wp-plugins/paid-memberships-pro)).

### Example Data (level description):
```
[checklist]
<ul>
 	<li>Материалы категории Start</li>
 	<li><strong>15% скидка</strong> на все продукты</li>
 	<li>Закрытый чат поддержки</li>
</ul>
[/checklist]
[checklist uncheck=true]
<ul>
 	<li>Материалы категории Pro</li>
 	<li>Закрытые онлайн встречи</li>
 	<li>Материалы категории VIP</li>
 	<li>Закрытый VIP клуб</li>
 	<li>Персональная поддержка</li>
</ul>
[/checklist]
```
I tested you plugin a year ago and everything was good. 

### Question: 
How can I mark a level as if it's popular or how can i add something like "Bestseller" mark? Do you have any shortcode for this?

## Checkout Page (part 1):
![pmpro-bug2](https://user-images.githubusercontent.com/4050715/45596423-34371d80-b9d5-11e8-9403-1d49ccde386b.png)
- Cyrillic symbols support (the same issue).
- [checklist] shortcode is not working (on posts this shortcode is working good). 

## Checkout Page (part 2):
![pmpro-bug3](https://user-images.githubusercontent.com/4050715/45596429-4618c080-b9d5-11e8-8055-d857af06abe8.png)
- [WPGlobus](https://wordpress.org/plugins/wpglobus/) plugin support ([github](https://github.com/WPGlobus/WPGlobus))
- Can you make a PayPal button more attractive and bigger? (just a wish) And the button now is not translatable. 

Here is a [docs](https://wpglobus.com/documentation/wpglobus-compatibility-with-themes-and-plugins/) and [solution](https://wordpress.org/support/topic/optimization-for-mobile-devices/#post-9877531).
Filter the database entry before you output it:
`apply_filters( 'the_title', $text_from_database );`

Can you fix this issues?
Thanks for good plugin!

## Configuration:
- PMPro 1.9.5.4 
- WordPress 4.9.8
- WPGlobus 1.9.16

**Comment by AiratHalitov** [comment]
Maybe the Cyrillic symbols issue associated with my localhost server. I should test it on my live server.

**Comment by AiratHalitov** [comment]
On my live server Cyrillic symbols issue is solved. 
But on `/membership-account/membership-checkout/?level=3` page `[checklist]` shortcode is not working. 
Maybe can you recommend me some code/filter to add in `functions.php` to solve this issue?

**Comment by andrewlimaza** [comment]
This is usually caused by database tables encoding, I think you could adjust it to UTF-8.

We are looking into trying to solve this issue on initial installations.

I hope this helps, please keep us posted.

**Comment by ideadude** [comment]
RE the checlist shortcode. We don't automatically apply shortcodes in the level description and confirmation message areas anymore. You can use this gist to do that though: https://gist.github.com/kimcoleman/af70a4971453216ebed4c67c8a4d8223

**Comment by AiratHalitov** [comment]
@ideadude 
Thanks for gist!

**Comment by AiratHalitov** [comment]
Why will you not add this gist for confirmation page to core?
