### ISSUE TITLE
Support iDeal payment option in Stripe.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#753]
Request to support iDeal payment gateway in Stripe -> https://www.paidmembershipspro.com/forums/topic/ideal-payment-gateway-integration/

**Comment by ideadude** [comment]
Looks like a lot of work and would need to be done as a new gateway option: https://stripe.com/docs/sources/ideal

The way we integrate with Stripe uses their API features specifically for charging credit cards. So we can't easily add new payment features Stripe offers.

We need/want to integrate for recurring subscriptions and each payment option handles that differently (it seems the iDeal stuff through Stripe requires custom API calls).

**Comment by michaelbeil** [comment]
A [customer **moderators only**](https://www.paidmembershipspro.com/forums/topic/ideal-support/) requested this:

>Stripe has built-in iDeal / Sofort support too! It just has to be enabled. Like you did recently with Apple pay for example. Hence I’m wondering when we can see that option?

Another [customer **moderators only**](https://www.paidmembershipspro.com/forums/topic/i-want-a-ideal-option-on-my-website-so-i-did-choose-stripe-as-payment-gateway/) request:
>I did choose stripe as payment method so that people can pay with Ideal. I first setup everything, so the gateway settings are all correct. I checked the instructions on the website.

>I keep seeing only the visa options when i try to checkout. I don’t see nothing of strip or ideal options. I just can’t figure out if I need an additional plugin or where the problem is.

**Comment by dparker1005** [comment]
iDeal can now be used in the Stripe Checkout Beta released in PMPro v2.8.
