### ISSUE TITLE
Plugin triggers a fatal error with new sales report widget by price breakdown

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#755]
PHP version incompatibility with `$prices_formatted = []`

See: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/adminpages/reports/sales.php#L424

**Comment by andrewlimaza** [comment]
I'm unable to recreate this? What version of PHP is this?

Could probably change it to `$prices_formatted = array();`

I tested this on 5.6 and 7.2, please let me know if I need to have any other Add On's installed?

**Comment by ideadude** [comment]
It was [] being used which breaks PHP < 5.4. We should always use array() until that function is deprecated (don't think there are plans though). Fixed.
