### ISSUE TITLE
Translation not being use site-wide

### ISSUE THREAD

**Issue by PaulKempf** [strangerstudios/paid-memberships-pro#760]
Hello,
French translation packages don't seem to be applied on several places across the site : for example, it does not translate "Membership never expires" nor "Membership expires after XX".

**Comment by andrewlimaza** [comment]
Thanks for this @PaulKempf, could you please have a look on GlotPress to see if this is translated - https://translate.wordpress.org/projects/wp-plugins/paid-memberships-pro

GlotPress will load as priority over the .po files. If the GlotPress translation doesn't exist then it will fallback to the .po files.

**Comment by PaulKempf** [comment]
It seems the GlotPress translation isn't down for the stable packages (53% done). It doesn't seem to reach to the .po file though.

**Comment by andrewlimaza** [comment]
It's possible that GlotPress is loading first - I know GlotPress should load after a certain % completed.

You could try the following code temporarily -> https://gist.github.com/andrewlimaza/c3e63d969e7c8421bb4da8a53a459b0c

**Comment by PaulKempf** [comment]
Thanks, I tried setting up the PMProCustom plugin (which works, as another custo I'm using is triggered), but no luck, still get some stuff untranslated... Any other idea ?

**Comment by andrewlimaza** [comment]
We'd have to look at the strings that aren't translating, are any of the strings generated from another PMPro Add On?

**Comment by andrewlimaza** [comment]
You can always filter this directly using the following filter -> https://www.paidmembershipspro.com/hook/pmpro_level_expiration_text/

**Comment by ideadude** [comment]
The one string specified seems wrapped now. https://github.com/strangerstudios/paid-memberships-pro/blob/991993479b6df3217b4b80d2fb63f1fee970e300/includes/functions.php#L505

So guessing it was a translation pack issue. Going to close this.

FYI, it is true there are many translations < 95% that won't be automatically downloaded or applied. You can manually download .po/.mo files from GlotPress and move them into your language folder at /wp-content/languages/paid-memberships-pro/ and PMPro should load them.
