### ISSUE TITLE
Easily show renewed vs new orders in Orders Table

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#772]
A user requested of an easy way to determine if an order is recurring or new (with minimal/no searching).

**Comment by ideadude** [comment]
Let's also think about ways to update the reports with this info.

**Comment by ideadude** [comment]
Here is a gist that does this:
https://gist.github.com/strangerstudios/30bff40a5fbe5f95a9f3

We may not want to use this method in the core update... perhaps we can track if an order is recurring or not in the orders table or something to make it easier to query against/etc.

**Comment by andrewlimaza** [comment]
I think a gist will work for now, let's hold off on this feature for a bit? It doesn't come up too often. Blog post should be a solution.

**Comment by travislima** [comment]
Hello, just a note here that a user is asking for a way to report upon their recurring revenue.

Basically, they want to see how much active recurring revenue orders they have on their membership site. I took a look at the gist mentioned above but was not too sure how to make that work.

Is there someone who would be willing to write up a blog post or some points on this?

**Comment by michaelbeil** [comment]
A customer sent in a ticket (ID 385768) with the following request: 

>do you have any report system where from we can get estimated expected recurring payment report for the future months.

**Describe the solution you'd like**
Add an expected recurring payment report.

**Comment by andrewlimaza** [comment]
This is coming soon @michaelbeil

**Comment by michaelbeil** [comment]
A different customer sent in a ticket (ID 387122) with the following request: 

>Where do I check for recurring invoices for members on our dashboard?

**Comment by michaelbeil** [comment]
PR #1871 addresses this.
