### ISSUE TITLE
BUG: Stripe version number shows for other gateways

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/paid-memberships-pro#774]
The Stripe version number shows regardless of which gateway is selected under Memberships >> Payment Gateway & SSL.

**Comment by eighty20results** [comment]
Believe this has been resolved in Dev already (pull request from @andrewlimaza)

**Comment by andrewlimaza** [comment]
It should be resolved in dev. Redid pull because there was duplicate logic here (hit copy twice by mistake)

**Comment by andrewlimaza** [comment]
New PR just removed the duplicate classes etc. 👍🏻
