### ISSUE TITLE
Braintree: PHP Deprecated:  Function create_function() is deprecated

### ISSUE THREAD

**Issue by eighty20results** [strangerstudios/paid-memberships-pro#778]
Need to update Braintree library to support PHP 7.2+ as the `create_function()` method is being deprecated. Current upstream Braintree library resolves this issue: https://github.com/braintree/braintree_php/tree/master/lib

**Comment by ideadude** [comment]
We should update the Braintree lib to the latest, test, and include if all good.

**Comment by ideadude** [comment]
Make sure to test in PHP 5.6 and 7.2

**Comment by greathmaster** [comment]
Submitted pull request with updated Braintree library here: https://github.com/strangerstudios/paid-memberships-pro/pull/829
