### ISSUE TITLE
enhancement: Showing billing address on the edit user profile

### ISSUE THREAD

**Issue by pbrocks** [strangerstudios/paid-memberships-pro#780]
Suggestion coming out of threads 

https://www.paidmembershipspro.com/forums/topic/adding-custom-fields-to-registration/

**Comment by pbrocks** [comment]
Essentially implementing this gist

https://gist.github.com/strangerstudios/7771903

into the core plugin

**Comment by eighty20results** [comment]
Something to keep in mind, perhaps, is that there will be a number of custom solutions to this problem "out there"...

**Comment by andrewlimaza** [comment]
This can now be easily achieved via User Fields (nocode) - https://www.paidmembershipspro.com/display-the-members-billing-address-fields-on-the-edit-user-page-for-admin-only/

It can also be shown for members, not just admins with the latest version of WordPress.
