### ISSUE TITLE
Integration with buddypress: where I can make member's profile publicly viewable

### ISSUE THREAD

**Issue by sebthesun** [strangerstudios/paid-memberships-pro#788]
I want the profile of members publicly viewable but it seams impossible cause the field where we can set redirect exclusion only accept existing pages, I can't put in there the buddypress profile page.

**Comment by CrandellWS** [comment]
https://www.paidmembershipspro.com/add-ons/buddypress-integration/  

Does that not help you?? Are you using that plugin?

Maybe this should be posted there...
https://github.com/strangerstudios/pmpro-buddypress

**Comment by kimcoleman** [comment]
@CrandellWS - your comment is correct. This is a feature of the BuddyPress Add On.
