### ISSUE TITLE
Stripe (or all?) refunds should generate a customer e-mail notification

### ISSUE THREAD

**Issue by lkraav** [strangerstudios/paid-memberships-pro#79]
If there's one thing I've learned about memberships, it's that people want to know about getting their money back as quickly as possible.

Stripe is my own target gateway, but this probably applies in general.

**Comment by kimcoleman** [comment]
The Stripe Gateway as the option to send an email when the order is refunded. We also now offer a checkbox to send an email to the customer when the "Membership Level" is changed.

**Comment by ideadude** [comment]
The 2.8 updates have refund support for Stripe, including emailing the user when a refund is initiated from Stripe.

The code does not yet support partial refunds, but we will track that effort in another issue.
