### ISSUE TITLE
Save user_id when going to PayPal Express if the user happens to be logged in

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#790]
For new users, we won't know the user_id in advance to save it to the order before going to PayPal Express. So the user shows up as [none] in the dashboard.

However, if an existing user is logged in, there is no harm is saving the user id for these orders and would help to find orphaned orders that get stuck at token or review status.

**Comment by greathmaster** [comment]
Submitted pull request: https://github.com/strangerstudios/paid-memberships-pro/pull/818
