### ISSUE TITLE
This line confuses my code highlighting and could be reworked to use prepare()

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#791]
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/functions.php#L608

**Comment by pbrocks** [comment]
[Only using the strtotime()](https://github.com/pbrocks/paid-memberships-pro/blob/dev-prepare-nextpaydate/includes/functions.php#L608). 
`
// last payment date
$lastdate = date_i18n( 'Y-m-d', $order->timestamp );

// next payment date
$nextdate = strtotime( '+' . $level->cycle_number . ' ' . $level->cycle_period, $order->timestamp );
`

**Comment by eighty20results** [comment]
> [Only using the strtotime()](https://github.com/pbrocks/paid-memberships-pro/blob/dev-prepare-nextpaydate/includes/functions.php#L608).
> 
> ```
> // last payment date
> $lastdate = date_i18n( 'Y-m-d', $order->timestamp );

date_i18n() isn't needed here, so may want to keep it simple:
`$lastdate = date( 'Y-m-d H:I:s', $order->timestamp );`
> 
> // next payment date
> $nextdate = strtotime( '+' . $level->cycle_number . ' ' . $level->cycle_period, $order->timestamp );
> ```

Avoid concatenating: `$nextdate = strtotime( "+{$level->cycle_number} {$level->cycle_period}", $order->timestamp );`

And make sure to check that the member vars are indeed set before using.

**Comment by pbrocks** [comment]
In that function I don't think we need `$lastdate` at all since we're don't need a formatted date. That variable was used in the original SQL, but not now.

**Comment by pbrocks** [comment]
[Merged on this PR](https://github.com/strangerstudios/paid-memberships-pro/pull/833)

Issue can be closed, but I can't do that.
![Alt text](https://monosnap.com/image/aCzc3UdZDr185kUtez7RmaNTUXQfL3.png)
