### ISSUE TITLE
Freshen up Core Plugin Images 

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#794]
Another issue references removing unused images in the core plugin. This issue suggests we improve and "modernize" the graphics below to be vector .svg / scalable images:

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/images/printer.gif
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/images/CCV-back.jpg
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/images/CCV-front.jpg
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/images/creditcards.gif

**Comment by travislima** [comment]
PR - https://github.com/strangerstudios/paid-memberships-pro/pull/807
