### ISSUE TITLE
pmpro_paypal_express_return_url_parameters adds additional parameters to the notify_url instead of paypal return argument

### ISSUE THREAD

**Issue by craftdigital** [strangerstudios/paid-memberships-pro#80]
When additional parameters are added using the pmpro_paypal_express_return_url_parameters filter, for instance using the PMPro Addon Package they are appended incorrectly to $nvpStr when they should be added to $paypal_args['return'] in the Paypal Standard Gateway (LN 182).

This breaks the functionality of the pmpro_after_checkout hook as the 'ap' variable is not passed back to the confirmation page.

Related to this, the use of PMPro Addon Package with the Paypal Express Gateway does not receive the 'ap' variable. LN385 in pmpro-addon-packages.php could be changed to `$url .= "&ap=" . $pmproap_ap;` to fix this.

**Comment by strangerstudios** [comment]
No can be done via this addon: https://github.com/strangerstudios/pmpro-auto-renewal-checkbox

**Comment by strangerstudios** [comment]
* deleted a comment earlier I posted by accident *

I will look into this again to see if it is still an issue. Thanks

**Comment by strangerstudios** [comment]
I think we can use this new filter (pmpro_set_express_checkout_nvpstr) now:
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/gateways/class.pmprogateway_paypalexpress.php#L560
