### ISSUE TITLE
Stripe billing cycle limit not stopping the subscription

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#800]
This is a possible bug that may need some more testing, if you set a billing cycle limit with Stripe the user will continue to be billed even after the billing cycle is met.

Also related, the membership level text turns red if you set the billing cycle limit and shows this error when editing the level -  "The billing details for this level are not supported by Stripe. Please review the notes in the Billing Details section below."

**Comment by ideadude** [comment]
haha we just took out the notices re this not working because we thought it was working

**Comment by dparker1005** [comment]
Can use Billing Limits Add On: https://www.paidmembershipspro.com/add-ons/pmpro-stripe-billing-limits/?utm_source=plugin&utm_medium=pmpro-membershiplevels&utm_campaign=add-ons&utm_content=stripe-billing-limits
