### ISSUE TITLE
Merge in one of the PMPro Rest API plugins and update it.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#805]
We have these two plugins that add REST API support to PMPro:
https://github.com/strangerstudios/pmpro-rest-api

https://github.com/eighty20results/pmpro-rest-api

They take a different angle on implementing the REST API. The first extends the user route to have additional end points to get PMPro-related data. The second sets up a PMPro route that we can add methods to.

Let's discuss which is the proper method, merge the code in, update and get it ready to work in core.

**Comment by ideadude** [comment]
Related issue https://github.com/strangerstudios/paid-memberships-pro/issues/448

**Comment by andrewlimaza** [comment]
I personally liked how Hersha did it. It was close to the examples on WordPress developer's handbook.

We need to discuss this a little bit more, I personally like to add in our own "pmpro" route to get membership specific data.

**Comment by ideadude** [comment]
Closing this issue. We can open new ones when suggestions come up for extensions to the API.
