### ISSUE TITLE
Page Builder Compatability

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#808]
There are various compatibility issues with page builders covered here: https://www.paidmembershipspro.com/using-page-builders-to-enhance-your-sites-membership-pages/

For the most popular page builders, we should bundle the necessary code to run PMPro and the builder together.

Let's add a folder includes/compat/ and file includes/compat.php

The required code for each page builder will go in a separate file in includes/compat

includes/compat.php will hook into init (maybe after_setup_theme) to loop through the builders, check if they are active, and if so load the compatibility file.

We could setup an array like:

```
$compat_checks = array(
    array(
        'file' => 'divi.php',
        'check_type' => 'constant',
        'check_value' => 'SITEORIGIN_PANELS_VERSION',
    ),
);
```

And then loop through, see the check_type and so check if defined(check_value) then load divi.php from the compat folder.

Maybe spell out compatibility.

Related https://github.com/strangerstudios/paid-memberships-pro/issues/579

**Comment by andrewlimaza** [comment]
Would `after_theme_setup` be a good hook? I was thinking `plugins_loaded`, just to ensure all the plugins have loaded. This is still fairly early on.
