### ISSUE TITLE
PMPro 2.0: Add Ons Affected

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#813]
If a plugin has been updated to support features/updates to the 2.0 release / 2.0 milestone, list them in a comment here.

Current known plugins include:
- https://github.com/strangerstudios/pmpro-reports-dashboard/
- https://github.com/strangerstudios/pmpro-sitewide-sales/
- https://github.com/strangerstudios/pmpro-member-history/

**Comment by kimcoleman** [comment]
A branch for the three plugins below has been made that should be merged and pushed when launching 2.0:
- https://github.com/strangerstudios/pmpro-reports-dashboard/tree/report-widget-button
- https://github.com/strangerstudios/pmpro-sitewide-sales/tree/report-widget-button
- https://github.com/strangerstudios/pmpro-member-history/tree/report-widget-button

**Comment by kimcoleman** [comment]
Also reported to have issues:

- https://github.com/strangerstudios/pmpro-cpt
- https://github.com/strangerstudios/pmpro-multiple-memberships-per-user
- https://github.com/strangerstudios/pmpro-limit-post-views
- https://github.com/strangerstudios/pmpro-membership-manager-role

**Comment by pbrocks** [comment]
https://github.com/strangerstudios/pmpro-series is not Gutenberg-ready because of its CPT.

**Comment by dparker1005** [comment]
All add ons are now PMPro 2.0 compatible.
