### ISSUE TITLE
PayPal Express Discount Codes Not Working

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#814]
Discount codes are not working with PayPal Express. It shows that discounts apply and when you view the transaction inside PayPal (after receiving payment) it has billed the user the full amount.

**Comment by andrewlimaza** [comment]
Unable to recreate this issue, tested a discount code with PayPal Express for both: once-off and recurring levels. Worked as intended.

**Comment by dparker1005** [comment]
Closing as there is not enough information to replicate.
