### ISSUE TITLE
Uninstall script didn't show up

### ISSUE THREAD

**Issue by pbrocks** [strangerstudios/paid-memberships-pro#817]
Looks like this was incorporated a while back, but maybe lost somewhere along the way:

[https://github.com/strangerstudios/paid-memberships-pro/issues/8](https://github.com/strangerstudios/paid-memberships-pro/issues/8)

**Comment by ideadude** [comment]
I don't know if I really coded this lol or have a phantom memory of it, but we need to redo it.

We should intercept the clicking of the delete plugin button on PMPro and show a popup asking if they really want to do that... all membership and order data will be deleted. Can use the askfirst JS function here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/js/paid-memberships-pro.js#L7

Or better, we can redirect to a custom page that explains what we delete and don't delete with a button to confirm and a JS confirmation on that "Are you really really sure?".

Don't know how either of these would work if deleted via a bundled action.

**Comment by dparker1005** [comment]
We now have an advanced setting where users need to opt-in to deleting all PMPro data on plugin deletion.
