### ISSUE TITLE
Add Feature: Hour(s) and Minute(s) as an option to the Billing amount

### ISSUE THREAD

**Issue by AnsieLima** [strangerstudios/paid-memberships-pro#823]
Add Hour(s) and or Minute (s)  in the drop-down menu > Membership Levels > Billing Details > Billing Durations 
Guideline:
1. Have a separate level for the 1-hour trial/etc.
2. Setup a cron job on your server to ping a script every few minutes.
3. The script will find users of that level and see if the timestamp on their last order or the timestamp of the last entry in the pmpro_memberships_users table to see if it is > 30minutes old. If so, cancel the user's level.

**Comment by petitwilly** [comment]
I am interested in adding this function.

**Comment by andrewlimaza** [comment]
@petitwilly, shouldn't be too difficult. Although it could put a bit of strain on the site if you are having a cron running every X minutes. (Thinking of shared hosting etc).

But definitely achievable.

**Comment by ideadude** [comment]
No plans to work on this now. When we've thought about it in the past, it makes sense to build this as an add on.

**Comment by kimcoleman** [comment]
This is in code review in the granular-expirations branch: https://github.com/strangerstudios/paid-memberships-pro/blob/granular-expirations/readme.txt

**Comment by ideadude** [comment]
That branch was merged and is ready to be pushed with v2.6.
