### ISSUE TITLE
Bug: Joined date displaying incorrect

### ISSUE THREAD

**Issue by AnsieLima** [strangerstudios/paid-memberships-pro#824]
Joined Date Displaying incorrect.

A user reported that the actually joined date was, for example, November 21, 2018
But in the Member List, it displays as November 30, -0001
https://postimg.cc/sBqTX2R7

**Comment by ideadude** [comment]
We need the steps to recreate this. We've seen and fixed related issues in the past.

**Comment by dparker1005** [comment]
Not enough information to replicate.
