### ISSUE TITLE
Trying to Cancel Stripe Subscriptions Twice Again. When users checkout for a new level.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#826]
Related to this thread:
https://www.paidmembershipspro.com/forums/topic/email-error-when-users-change-subscription/

To recreate:
* Payment gateway = Stripe
* Have a new user checkout for a recurring subscription.
* Have the same user checkout for a different recurring subscription.

You get an email RE a cancellation failed. Check Stripe logs and PMPro will have tried to cancel the sub twice.

**Comment by DiegoCach** [comment]
This happens to me in paypal express also, i was able to somewhat fix the bug in stripe, but im not able  to recreate the fix with paypal express,what i basically saw with stripe was that at the function cancelSubscriptionAtGateway in the folder classes/gateways, the foreach tried to look if the invoice was not closed and if the invoice sub was the same as the sub's id but never did anything if the invoice was closed already, so it always jumped to the catch for some reason, I don't know if this is an optimal solution, but it helps to understand the problem in someways. here the code i used to fix the problem: 
`function cancelSubscriptionAtGateway($subscription, $preserve_local_membership = false)
		{
			//need a valid sub
			if(empty($subscription->id))
				return false;

			//make sure we get the customer for this subscription
			$order = new MemberOrder();
			$order->getLastMemberOrderBySubscriptionTransactionID($subscription->id);

			//no order?
			if(empty($order))
			{
				//lets cancel anyway, but this is suspicious
				$r = $subscription->cancel();

				return true;
			}

			//okay have an order, so get customer so we can cancel invoices too
			$this->getCustomer($order);

			//get open invoices
			$invoices = $this->customer->invoices();
			$invoices = $invoices->all();

			//found it, cancel it
			try
			{
				//find any open invoices for this subscription and forgive them
				if(!empty($invoices))
				{
					foreach($invoices->data as $invoice)
					{
						if(!$invoice->closed && $invoice->subscription == $subscription->id)
						{
							$invoice->closed = true;
							$invoice->save();
						}else if($invoice->closed && $invoice->subscription == $subscription->id){
							return true;
						}
					}
				}

				//sometimes we don't want to cancel the local membership when Stripe sends its webhook
				if($preserve_local_membership)					
					PMProGateway_stripe::ignoreCancelWebhookForThisSubscription($subscription->id, $order->user_id);
				
				//cancel
				$r = $subscription->cancel();
				return true;
			}
			catch(Exception $e)
			{
				return false;
			}
		}`

**Comment by DiegoCach** [comment]
This happens to me in paypal express also, i was able to somewhat fix the bug in stripe, but im not able to recreate the fix with paypal express,what i basically saw with stripe was that at the function cancelSubscriptionAtGateway in the folder classes/gateways, the foreach tried to look if the invoice was not closed and if the invoice sub was the same as the sub's id but never did anything if the invoice was closed already, so it always jumped to the catch for some reason, I don't know if this is an optimal solution, but it helps to understand the problem in someways. here the code i used to fix the problem inside the cancelSubscriptionAtGateway function:

				`if(!empty($invoices))
				{
					foreach($invoices->data as $invoice)
					{
						if(!$invoice->closed && $invoice->subscription == $subscription->id)
						{
							$invoice->closed = true;
							$invoice->save();
						}else if($invoice->closed && $invoice->subscription == $subscription->id){
							return true;
						}
					}
				}´

**Comment by ideadude** [comment]
Need to test again after this fix: https://github.com/strangerstudios/paid-memberships-pro/commit/96d13a541365b24b5f6c040ca27d662aff7c7478

**Comment by dparker1005** [comment]
The Stripe integration code was overhauled in the PMPro 2.1 update. As this issue no longer seems to be occurring, we are going to close this issue. If this is behavior that you are still seeing on your site, please feel free to open a new issue and we can look further into this there.
