### ISSUE TITLE
Enhancement: Show the same billing address form (long/short/international) on Billing page as Checkout page

### ISSUE THREAD

**Issue by messica** [strangerstudios/paid-memberships-pro#846]
We should probably be using the same billing address fields on the Billing page as we do on the Checkout page, or setting them to international and longform addresses by default.

https://www.paidmembershipspro.com/forums/topic/membership-billing-page-issues/

**Comment by ideadude** [comment]
Fixed here and other commits: https://github.com/strangerstudios/paid-memberships-pro/commit/46ee3e492f52db1c438cc8a21746a830eef9b213#diff-1e56d2d9eaaa144a0bbe4604cdbc7e53c14cf0d07d0a9c77ca82c6b2bf31e10e
