### ISSUE TITLE
Allow Googlebot to Index Paywalled Content

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#851]
A user has asked if there is a way (other than Limit Post Views) to allow Googlebot to index restricted content. See: 

https://developers.google.com/search/docs/data-types/paywalled-content#googlebot
https://support.google.com/webmasters/answer/80553

**Comment by ideadude** [comment]
Based on the latest I've read about this by Google, something like Limit Post Views is the correct way to do this. Other methods (e.g. detecting Googlebot and changing the behavior of the site) could result in breaking the Google TOS and being removed from the index/etc.
