### ISSUE TITLE
BUG: the membership shortcode [membership] does not work as expected in Gutenberg.

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/paid-memberships-pro#856]
When using the visual editor of Gutenberg, the shortcode gets interpreted as regular text. The workaround is to switch the editing to HTML mode and delete the paragraph tags added by Gutenberg.

**Comment by andrewlimaza** [comment]
I think if people are using the block editor for this, they should rather use the Gutenburg Require membership block.

I don't think you'd be able to have the `[membership]` in different 'blocks'.

**Comment by dparker1005** [comment]
As Andrew mentioned, the Require Membership block should be used instead of the shortcode.
