### ISSUE TITLE
Bug: Discount Code is lost when user logs in to existing account

### ISSUE THREAD

**Issue by woodwardmatt** [strangerstudios/paid-memberships-pro#867]
Hey Guys, 

I spotted an issue today with the discount code workflow.

**Scenario**: 

An existing user, that is logged out, wants to checkout a new membership with a discount code applied automatically  via the url.

**Repro Steps**: 

- Visit the checkout url code supplied with the discount code embedded 
- Notice that you are logged out, and click the "Log In Now" link (notice the url on the link and the absence of the discount code)
- Log in and be redirected back to the checkout page.
- Notice that your discount code has now been removed.

**Proposed solution**: 

Update https://github.com/strangerstudios/paid-memberships-pro/blob/dev/pages/checkout.php#L171 to include the following link structure which includes the discount code:

`<a href="<?php echo wp_login_url(pmpro_url("checkout", "?level=" . $pmpro_level->id . "&discount_code=" . $discount_code)); ?>"><?php _e('Log in here', 'paid-memberships-pro' );?></a>`

I've tested the workflow and this fixes the above issue. Not sure however if this will interrupt, or cause issues with, existing logic / workflow.

Any thoughts?

**Comment by woodwardmatt** [comment]
I can confirm this issue is still active after the 2.0.4 update. @strangerstudios

**Comment by ideadude** [comment]
Thanks again for posting this issue. I agree that we should fix this and your fix looks good. We could perhaps check first if a discount code exists before adding it to the URL. It could be confusing (i.e. discourage sales) on sites that don't have discount codes or keep them hidden.

Would you like to do a PR with your fix? If not, I can have someone on the team do it. Would be nice to get you credit on github here.

**Comment by andrewlimaza** [comment]
@woodwardmatt hope you don't mind I worked on a solution - https://github.com/strangerstudios/paid-memberships-pro/pull/994

This checks to see if the discount code is set, if it is then it'll add in the discount code when the person returns. I am still thinking that add_query_args may work here.

**Comment by woodwardmatt** [comment]
Thanks @andrewlimaza & @ideadude - apologies for not reaching back out (just been swamped recently!). Let me know if you want me to test anything from my end
