### ISSUE TITLE
Buying a gift code will end existing subscription when checking out with Stripe gateway

### ISSUE THREAD

**Issue by jayjay91** [strangerstudios/paid-memberships-pro#868]
I’ve been getting complaints of active subscribers whose subscription ends within three days once they buy a gift code for someone else. Even when a user has paid a year in advance, their subscription will suddenly end within two or three days after a gift code is purchased. The subscription is ended both within PmPro, and over at Stripe.

I’ve gone into this in a staging site and found that this **only** happens when Stripe credit card gateway is used for checkout. It does not happen with with Paypal Express. I am also using a custom made Stripe direct debit gateway, no problems there either.

There is a piece of code within pmpro_gift_levels/pmpro_gift_levels.php that should set an "existing member flag", but it does not work for Stripe credit card users. Since it works for all other gateways, I suspect its a bug within the Stripe gateway.

The issue has been successfully replicated by Hersha Venkatesh, see here https://www.paidmembershipspro.com/forums/topic/gift-levels-plugin-ends-user-subscription-when-using-stripe-credit-card-gateway/

**Comment by ideadude** [comment]
This has been fixed.
