### ISSUE TITLE
User Reported Issue with v2.0

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#882]
From the user: Error in PMPRO 2.0, after updating to version 2.0 we noticed an error which causes css to break on our website and many wordpress functions with it. This might only happen for people using Autooptimize (Javascript minifying). Anyway here's what we noticed. In paid-ememberships-pro\blocks\blocks.php line 80, wp_enqueue_style(
'pmpro-blocks-css', should be pmpro_blocks_style?
Atleast making it so, solved CSS render breaking errors on our end.

**Comment by pbrocks** [comment]
The user here is suggesting a change in the handle, which points to a customization on their site as the issue. AFAIK, there isn't any issue with using hyphens vs underscores.
