### ISSUE TITLE
Enable changing a user's level

### ISSUE THREAD

**Issue by dchenk** [strangerstudios/paid-memberships-pro#886]
Currently there doesn't appear to be a way to change a member's level without their membership getting canceled and forcing the user to log in to their account and check out for another level. Just as Stripe lets you add or change any customer's subscriptions, PMPro should let an administrator change any member's level and thereby the price the member is paying. This is important especially if the members are clients who almost never actually log in to their account and would like the site admin to change their membership plan when necessary.

Please make it possible to change a member's level without everything getting screwed up. Thanks in advance.

**Comment by andrewlimaza** [comment]
This may not be possible with some gateways, you are able to change the user's membership level by logging into your WordPress dashboard as an admin / Membership Manager and edit the user in question.

In the edit user page, there is an option to update the user's membership level which won't require the user to re-checkout for a new level (Unless you need the billing to be changed to a different amount) although you may change the user's recurring fee in some payment gateways themself.

Changing the user's membership level in the WordPress profile page also allows you to cancel or keep their current billing plans.

I hope this helps.
