### ISSUE TITLE
disable autocomplete on "honeypot" field "fullname" on checkout page

### ISSUE THREAD

**Issue by dillilabs** [strangerstudios/paid-memberships-pro#893]
Steps to reproduce :
1) Open FIREFOX and Go to checkout
2) Enter all the information manually (do not use auto complete) making sure to enter an invalid email address so that the form submission fails.
3) Submit. When prompted by Firefox, store the form submission for autocomplete next time.
4) Check out page is going to show an error about email field. Now, use autocomplete to refill the fields from the saved user autocomplete information. Fix the email field.
5) Submit. Notice an error that says "Are you a spammer?". This is because `fullname` field gets auto filled using the values from `first_name` and `last_name`. Expected : No error.

This is due to the honeypot 'fullname' field on checkout page. Consider turning off autocomplete for this field in checkout.php as follows :

`<input id="fullname" name="fullname" type="text" class="input " size="30" value="" autocomplete="off">`

**Comment by ideadude** [comment]
I agree.

I think there might have been a reason we didn't do this sooner? Maybe the autocomplete="off" param wasn't being supported back then. Maybe it breaks the honeypot for scripts. I just had a bit of dejavu while reading this that I looked into this a few years ago.

I'm probably going to include something like this in future updates (and feel free to patch your version for this if you are confident), but I'm going to do some tests and research first.
