### ISSUE TITLE
Multiple ID tags on cancel link on account page.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#895]
We have multiple 'id' attributes on the cancel links on the account page, there should be only one.

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/shortcodes/pmpro_account.php#L72

**Comment by kimcoleman** [comment]
Fixed in https://github.com/strangerstudios/paid-memberships-pro/commit/3681a66dac82d0020889c0548420e1c677042177
