### ISSUE TITLE
Consider adding 'high' priority to "Require Membership" meta box

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#898]
Right now we do not set a priority on the meta box added to the Page and Post edit screen. When you are using Paid Memberships Pro alongside the Memberlite Elements plugin, for example, the "custom sidebar" meta box appears before ours. 

I don't use many plugins that are adding 'side' context meta boxes, but should we consider adding the "high" priority so that our meta box is more visible?

Reference: https://developer.wordpress.org/reference/functions/add_meta_box/#parameters

Code: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/metaboxes.php#L105-L106

**Comment by ideadude** [comment]
I agree. Let's do it.
