### ISSUE TITLE
Price below 0.01 fails to set.

### ISSUE THREAD

**Issue by sapph1re** [strangerstudios/paid-memberships-pro#902]
I have a currency with >2 decimals. I'm trying to set membership price to 0.005. It saves the membership level successfully, but the price remains unchanged.

I figured that the plugin code actually allows prices to have any number of decimals, but in the database tables there is a limitation:
```
initial_payment   | decimal(10,2)
```

So MySQL engine simply doesn't allow me to set a price with more than 2 decimals.

For now I'm just going to edit the table schema directly. But I hope it can be resolved in a more elegant way in the future.

**Comment by ideadude** [comment]
For now, you need to edit the DB. We are going to eventually ship a change like this:
https://gist.github.com/ideadude/0d52d42db217bd9d874095a1712d4c7a

But it could potentially break existing sites, so we are waiting for the next "major" update 2.1 to include it.

**Comment by ideadude** [comment]
Implement the SQL queries above on a test site, then note everywhere the decimals break for currencies with 2 or fewer decimals.

It may break during gateway API calls as well, not just in places where an amount is displayed. Then we need fixes for each individual case.

**Comment by dparker1005** [comment]
This changed was implemented here: https://github.com/strangerstudios/paid-memberships-pro/commit/464b4784d5e38e496fd8fc752374b98cb892511d
