### ISSUE TITLE
Missing dependency for "wp-blocks" when trying to enqueue "pmpro-blocks-css"

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#914]
Bug/Issue

As reported in our support system by user kliewvii.

> Latest on all three.
> 
> No missing dependencies.
> 
> When using the Classic Editor and no “blocks,” PM Pro generates a missing dependency for “wp-blocks” when trying to enqueue “pmpro-blocks-css”
> 
> To see the error, turn on Classic Editor / no blocks, then use query monitor.

**Comment by dparker1005** [comment]
Could not replicate this after installing query monitor and creating a PMPro account page using the classic editor. Furthermore, the string `blocks-css` never occurs in our code base nor its files.
