### ISSUE TITLE
Bug: Setting incorrect timestamp for every order.

### ISSUE THREAD

**Issue by messica** [strangerstudios/paid-memberships-pro#915]
The timestamp of the order is shifted by the GMT offset every time getMemberOrderByID() is called and the order is updated.

https://github.com/strangerstudios/paid-memberships-pro/blob/532fed27b91a9ee71b12d1b10f62c6430a2d5c24/classes/class.memberorder.php#L81

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/bug-incorrect-timestamps-in-pmpro_membership_orders/

**Comment by ideadude** [comment]
related to https://github.com/strangerstudios/paid-memberships-pro/issues/907
