### ISSUE TITLE
Bug/Enhancement: Better handling of customer updates at Stripe.

### ISSUE THREAD

**Issue by messica** [strangerstudios/paid-memberships-pro#921]
Our Stripe webhook handler does not handle "customer.source.updated" for updated billing information at Stripe or even more general "customer.updated" events.

**Support Ticket (Moderators Only)**:
https://www.paidmembershipspro.com/forums/topic/recurring-invoice-references-old-cc-but-new-cc-is-processed/

**Comment by kimcoleman** [comment]
We should also double check Order details when recurring payments come in.

**Comment by kimcoleman** [comment]
We're using Churnbuster and seeing this - customer information is updated in Stripe but the order created for the successful charge retry uses previous order's billing information

**Comment by kimcoleman** [comment]
We may also want to update the user meta on change.

**Comment by dparker1005** [comment]
We now pull order information directly from Stripe invoices. This data is no longer stored in user meta.
