### ISSUE TITLE
Display Order "Status" on the Invoices page and single Invoice page  

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#923]
v2.0 added additional order statuses to the display of the Membership Account page's "Invoices" section as well as the "Invoices" page. The single Invoice and table-view of Invoices should be updated to include the order's "status" as well.

How it appears on the Account page: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/shortcodes/pmpro_account.php#L130

Need to add a new "column" to this table here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/pages/invoice.php#L98-L105

Need to add as a list item above the hook here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/pages/invoice.php#L35

**Comment by andrewlimaza** [comment]
Pull Request - https://github.com/strangerstudios/paid-memberships-pro/pull/956
