### ISSUE TITLE
Bug: Creates notice if SITEURL is already defined.

### ISSUE THREAD

**Issue by messica** [strangerstudios/paid-memberships-pro#924]
A notice is generated if SITEURL is already defined. It doesn't look like this constant is used anywhere in the plugin either.

https://github.com/strangerstudios/paid-memberships-pro/blob/532fed27b91a9ee71b12d1b10f62c6430a2d5c24/paid-memberships-pro.php#L124

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/constant-siteurl-already-defined/

**Comment by andrewlimaza** [comment]
Pull Request -> https://github.com/strangerstudios/paid-memberships-pro/pull/957
