### ISSUE TITLE
Blank discount code results in undefined index error

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/paid-memberships-pro#930]
To reproduce...

1) enter an invalid discount code in the bottom discount code field and click "Submit".

2) you will see an error message. Now, remove the discount code from the lower discount code field and click "Submit".

3) it will result in a PHP error for an undefined index for the other_discount_code field.

**Comment by andrewlimaza** [comment]
I keep on getting the error "Discount code not found", on step 2 do you have to select "Apply"? When I click Apply it doesn't remove the discount code and I get the error mentioned above still.

**Comment by andrewlimaza** [comment]
It then refreshes the checkout page and the discount code is still showing in the field.

**Comment by kimcoleman** [comment]
I am doing a few discount code adjustments and cannot reproduce this. This may be fixed.
