### ISSUE TITLE
Feature Request: Distinguish between New and Renewal subscriptions in the Reports & Email notifications

### ISSUE THREAD

**Issue by AnsieLima** [strangerstudios/paid-memberships-pro#935]
Feature Request: 
A user reached out that they need data to see how many people renew. In the reports, there is only the amount of Signups and not distinguishing between new and renewal subscriptions.

**Comment by AnsieLima** [comment]
UPDATE: Email notification to distinguish between members renewing vs joining as a new member.

**Comment by davidryal** [comment]
2nd this feature request

**Comment by ChemaDeveloper** [comment]
Yeah, we really need this feature for controlling what emails are we sending to our subscribers.

**Comment by kimwhite** [comment]
Still need this feature!
