### ISSUE TITLE
Billing Information Page if user visits page AFTER level already cancels 

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#938]
There's a current odd case where if a user doesn't get to updating their billing information page BEFORE their level cancels, they may get to the page and see the "This subscription is not recurring. So you don't need to update your billing information." message here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/pages/billing.php#L378

For most sites, the user's level will have cancelled to "None", while others may have a cancel/downgrade level filter in place.  It would be useful to discuss and implement an enhancement for this case. There should be a bit more detail provided to the member and possibly a link to "renew my last membership level".

**Comment by andrewlimaza** [comment]
Also related to this, that we should discuss. Is access to the account page after a user has cancelled / expired. This would allow 'old' members to still access their past orders etc and may be a good way to upsell a membership if a user doesn't have one. (i.e. "To regain access to premium content, please signup for a membership level")
