### ISSUE TITLE
Discount Codes – Custom trial bug

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/paid-memberships-pro#939]
https://www.paidmembershipspro.com/forums/topic/discount-codes-custom-trial-bug/

This line of code `if(jQuery(this).attr('checked'))` isn't working on this customer's site, so she's changed it to `if(jQuery(this).is(':checked')`

**Comment by ideadude** [comment]
Let's see what jQuery prefers in their docs for the version that is shipped with WP.

If the .is('checked') is preferred, let's test it in a few browsers etc and ship if it always works better.

**Comment by andrewlimaza** [comment]
https://stackoverflow.com/questions/15081335/js-checked-vs-jquery-attrchecked-what-is-the-difference

**Comment by femiyb** [comment]
https://github.com/strangerstudios/paid-memberships-pro/pull/1010
