### ISSUE TITLE
Feature request: add filter by date in the PMPro Members dashboard

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/paid-memberships-pro#945]
User suggested there is an option to filter users by date on the members dashboard

https://www.paidmembershipspro.com/forums/topic/how-to-add-afilter-by-date-in-the-pmpro-dashboard-area/

**Comment by eighty20results** [comment]
A version of the members list that includes ordering by date is available in the WordPress.org repository: https://wordpress.org/plugins/e20r-members-list/

**Comment by ideadude** [comment]
We also had Paul's work converting the members list to use WP List Table that is close to complete and allows for this. We can try to get that incorporated into v2.1 or 2.2

**Comment by ideadude** [comment]
Duplicate https://github.com/strangerstudios/paid-memberships-pro/issues/611
