### ISSUE TITLE
Bug: pmpro_member shortcode attribute member_code doesn't return anything

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/paid-memberships-pro#950]
Shortcode [pmpro_member field="membership_code"] doesn't return anything.

Using `[pmpro_member field="membership_code_id"]` returns the discount code listed in `code_id` field of the `pmpro_memberships_users` table but not the discount code the code_id references from `wp_pmpro_discount_codes.code`

Other fields that has the name `code` for pmpro_membership_* tables is `pmpro_membership_orders.code`. It also doesn't return the value of this table field.

Database was double checked to contain values for user_id queried in sql from function `pmpro_getMembershipLevelForUser`.

**Comment by andrewlimaza** [comment]
I think this was added as a mistake as we only retrieve data from memberships_users and memberships_level.

PR - https://github.com/strangerstudios/paid-memberships-pro/pull/955

**Comment by ipokkel** [comment]
Thank you for the feedback and info.

**Comment by ipokkel** [comment]
Fix for this has been merged into v2.0.5 release.
Thank You.
