### ISSUE TITLE
Translations of Addons on GlotPress

### ISSUE THREAD

**Issue by AiratHalitov** [strangerstudios/paid-memberships-pro#953]
Hi!
Can you [prepare](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/) your plugins/addons for localization with using GlotPress?

1) Paid Memberships Pro – BuddyPress Add On
https://translate.wordpress.org/projects/wp-plugins/pmpro-buddypress

2) Paid Memberships Pro – bbPress Add On
https://translate.wordpress.org/projects/wp-plugins/pmpro-bbpress

3) Paid Memberships Pro – Email Templates Add On
https://translate.wordpress.org/projects/wp-plugins/pmpro-email-templates-addon

I will help you with Russian translations.

I’m `ru_RU` PTE of your PMPro plugin
https://translate.wordpress.org/locale/ru/default/wp-plugins/paid-memberships-pro

Example: https://translate.wordpress.org/locale/ru/default/wp-plugins/pmpro-woocommerce

[Paid Memberships Pro – BuddyPress Add On](https://wordpress.org/plugins/pmpro-buddypress/) 1.2.1 ([GitHub](https://github.com/strangerstudios/pmpro-buddypress))
[Paid Memberships Pro – bbPress Add On](https://wordpress.org/plugins/pmpro-bbpress/) 1.5.5 ([GitHub](https://github.com/strangerstudios/pmpro-bbpress))
[Paid Memberships Pro – Email Templates Add On](https://wordpress.org/plugins/pmpro-email-templates-addon/) 0.7.2 ([GitHub](https://github.com/strangerstudios/pmpro-email-templates))

Related topic: https://wordpress.org/support/topic/translations-on-glotpress-7

**Comment by andrewlimaza** [comment]
We are working on getting our Add Ons i18n ready. This should happen within the next update of the plugins. Hang tight! :)

**Comment by AiratHalitov** [comment]
One year has passed. Are there any updates?

**Comment by dparker1005** [comment]
I have just created an Issue in the PMPro BuddyPress repository with this request as PMPro bbPress is already localization-ready and PMPro Email Templates is planned to eventually merged into PMPro core:
https://github.com/strangerstudios/pmpro-buddypress/issues/79
