### ISSUE TITLE
[BUG] Error trial_period and Stripe.

### ISSUE THREAD

**Issue by Alejobcn** [strangerstudios/paid-memberships-pro#958]
Hello,

There is a problem with the parameter: trial_period_days in Stripe.

I do not have subscriptions with trial periods:

Image: https://i.gyazo.com/d9fb6fa337e229eeec46f6fd43143c13.png

Stripe Image: https://i.gyazo.com/dfbd9dc0f31406600006a70454dd18ea.png

But it also makes the payment of the amount (in the example: € 1).

Image Payment: https://i.gyazo.com/cfbc2e6f802ff78ca52e3ad988aa7f8a.png

What would be the solution?

Thank you

**Comment by andrewlimaza** [comment]
I believe that it shows "Trial" inside Stripe as the recurring payment has not occurred yet. Once the recurring payment occurs it should change the status. I hope this clears things up.

**Comment by Alejobcn** [comment]
Hello,

So is it normal?

Everything is correct?

Thank you

**Comment by hbcondo** [comment]
My site appears to be having a similar issue. Stripe is not charging our customers the initial payment as specified in the membership level billing details Settings. More specifically, we have the Initial Payment set to $9.99 but Stripe shows an amount of $0.00 being charged. Stripe also shows as a “trial” but there is nothing in the PMP membership settings that indicates this is a trial level.

@andrewlimaza, I created a support ticket here with a screenshot:
https://www.paidmembershipspro.com/forums/topic/initial-payment-not-being-captured-with-stripe-production/

**Comment by ideadude** [comment]
This is related to how we integrate with Stripe and most gateways.

We will charge the initial payment and then setup a 1 period trial before the subscription starts. This allows you to have an initial payment that is different from the recurring amount.

If you do set a trial, that trial period is extended.

This shouldn't affect anything related to your customers unless you have other services that are doing something special during the "trial period" for your Stripe customers.

@hbcondo's issue seems to be a different one where the initial payment is not being made for some reason. We will follow up with you on your ticket to address that.
