### ISSUE TITLE
Enhancement: Clearer Refund/Void Messaging for PayPal Gateways

### ISSUE THREAD

**Issue by messica** [strangerstudios/paid-memberships-pro#959]
We should provide more context in our error message about the refunded payment when the initial payment of a membership succeeds but the subscription fails. We only mention the refunded payment if the refund fails as well currently.

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/transactions-going-to-paypal-even-with-error-reoccurring-billing-vs-payments/

**Comment by ideadude** [comment]
Dupe: https://github.com/strangerstudios/paid-memberships-pro/issues/926
