### ISSUE TITLE
Bug/Enhancement: Update last subscription order when billing information is updated.

### ISSUE THREAD

**Issue by messica** [strangerstudios/paid-memberships-pro#961]
If a member updates their billing information, they might be confused if the updated information isn't displayed on new orders created for recurring payments. Should we be updating the last order with the updated billing information so it gets copied to new orders for recurring payments?

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/updated-member-address-not-reflected-on-invoices/

**Comment by dparker1005** [comment]
We no longer update previous orders on billing update. The update now only happens within the gateway.
