### ISSUE TITLE
body_class Filter Checking for Shortcode presence, not Block

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#967]
If you are using the block method instead of the shortcode method to insert the appropriate generated page content on a PMPro-page, the logic to filter the page's body_class is not properly working.

See: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/init.php#L141

We need to update this to check if the page has the block and also append the correct body_class.

**Comment by andrewlimaza** [comment]
We'd need to use this to see if there is the membership block inside post content - https://developer.wordpress.org/reference/functions/parse_blocks/

**Comment by andrewlimaza** [comment]
I've tested this further, the `post->content` should have `[pmpro_account]` in it for example.
<img width="780" alt="Screen Shot 2019-05-03 at 08 50 57" src="https://user-images.githubusercontent.com/12629136/57123043-a00da100-6d80-11e9-9210-b3b28d516d69.png">

Would like to dive into this further.

**Comment by ideadude** [comment]
There is a has_block function
https://developer.wordpress.org/reference/functions/has_block/
