### ISSUE TITLE
Enhancement: Functionality to prevent subscriptions and memberships from being cancelled when users are deleted.

### ISSUE THREAD

**Issue by messica** [strangerstudios/paid-memberships-pro#973]
Adding a filter or making this an Advanced Setting could prevent subscriptions from being cancelled accidentally (WooCommerce deleting inactive accounts, etc).

https://github.com/strangerstudios/paid-memberships-pro/blob/991993479b6df3217b4b80d2fb63f1fee970e300/includes/cleanup.php#L2-L22

**Comment by ideadude** [comment]
This specific issue with WC deleting users should be updated by us using a filter in WC to keep them from deleting a user or considering them "inactive" if they have a subscription in PMPro.

I'm okay with adding a filter here. pmpro_cancel_membership_when_delete_user or something like that. Default to true and if false, just return;

We should probably second guess this decision to cancel subscriptions when a user is deleted. How often do we delete users without cancelling first/etc? We should perhaps instead generate a report or email with users who were deleted and warn the admin that they may still have active subscriptions.

Checking subscription status is heavy (so in cancelling). Including a users email in the warning to cross reference with the gateway is tricky if the user is being deleted for privacy reasons.

Maybe we don't let you delete a user with an active subscription and give a warning instead. This would stop WC or anyone else from deleting the user. The warning can include a way to "are you sure? with a checkbox to cancel the sub as well".

Needs a lot of thought.

**Comment by kimcoleman** [comment]
Maybe a notice hooked here if the user has an active membership "Deleting this user will also cancel their membership and recurring subscription (if active)." 

https://github.com/WordPress/WordPress/blob/master/wp-admin/users.php#L335

**Comment by kimcoleman** [comment]
I've added an admin notice when deleting users with membership in this PR https://github.com/strangerstudios/paid-memberships-pro/pull/1048

**Comment by dparker1005** [comment]
Closing as a warning was added when users are deleted. Can also unhook `pmpro_delete_user` using a code recipe if desired.
