### ISSUE TITLE
Update Checkout to Support the new SCA regulations and implementations.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#981]
Phase one:
* Fix Stripe and Braintree

Phase two:
* Authorize.net, Cybersource, Payflow

**Comment by messica** [comment]
Requirements doc: https://docs.google.com/spreadsheets/d/1b-lAtz12_26Zi-eS2AnpgDUUKpvuWtiAiaRw-9YTJ8g/edit?usp=sharing

**Comment by BradleyFletcher** [comment]
Will the user need to take relevant steps within Stripes interface to comply or will the plugin do this automatically?

Stripe is asking its developers/users to take some steps within the Stripe interface to prepare for the upgrade.

**Comment by talkytoaster** [comment]
Any news on this as the deadline is 14th September 2019, only just over a month away? If you can't sort it out (at least for Stripe) I will have to look at other third party solutions or risk losing customers!

**Comment by messica** [comment]
We are targeting a release candidate for the core Paid Memberships Pro plugin with the SCA updates for August 19, along with a blog post and email campaign to ensure our users are prepared for the changes with adequate time to test.

Depending on your gateway, you may need to enable 3DS 2.0 support and/or upgrade your API version in your gateway’s settings. PayPal, CyberSource, Authorize.net, and Braintree users will have to create new API credentials for 3DS 2.0 providers like Cardinal Cruise. There will be more detailed instructions in the upcoming blog post. If you are unsure, you should follow your gateway’s instructions.

**Comment by contemplate** [comment]
Any update?  

Feels like we need to include this as well: 
https://github.com/strangerstudios/paid-memberships-pro/issues/626

This is very important to all of my clients.

**Comment by messica** [comment]
Please see https://github.com/strangerstudios/paid-memberships-pro/releases/tag/v2.1-Beta1

@contemplate The update included in this prerelease uses stripe.js v3 & Elements (Stripe's hosted payment information fields), [which makes the pre-filled SAQ-A the only requirement for PCI compliance](https://stripe.com/docs/security). We will be adding support for additional payment methods such as Apple Pay in a later update.

**Comment by contemplate** [comment]
Awesome @messica  Thank you!

**Comment by hbcondo** [comment]
> Please see https://github.com/strangerstudios/paid-memberships-pro/releases/tag/v2.1-Beta1

@messica, thanks for your update. Looks like there are already issues with the v2.1 Beta such as #1061. How are these beta releases being distributed? We have plugins auto-update enabled on our site using Jetpack. Does this mean our site will automatically be updated with this beta release or is this beta release a manual update only?

Also, does PMP have a demo site that has this update implemented so we can test out these features before doing our own updates? I would really like to try v3 of Stripe beforehand.

**Comment by messica** [comment]
These beta pre-releases have to be installed manually. There is no demo site with the beta pre-release installed already at the moment. We will be updating https://www.paidmembershipspro.com/sca-psd2-pmpro-version-2-1-beta-notes/ as we have more information.
