### ISSUE TITLE
Setting post__not_in no matter what

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#989]
Looks like a bad merge made it so we are always setting post__not_in

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/content.php#L147-L150

We need to either remove the duplicate line that sets it again or remove the conditional check for if it's not really needed.

**Comment by ideadude** [comment]
Fixed here https://github.com/strangerstudios/paid-memberships-pro/commit/a28c5ac423323ae9c9c718c4e58d46255d1ad6ac
