### ISSUE TITLE
Tax being added to subtotal on recurring orders.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#992]
Tax is being added to the subtotal in the order for recurring memberships.

For example if the recurring order is $1 per month recurring it may create the order and subtotal as $1.07 and in the order the tax column is $0.

This seems to be happening for PayPal transactions.

**Comment by andrewlimaza** [comment]
This is also happening with Stripe subscriptions, we should test this with all gateways.

**Comment by ideadude** [comment]
We should be adjusting for this now with PayPal here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/services/ipnhandler.php#L128

For Stripe, we aren't sending the tax as a separate value to the gateway and so it should be included in the total amount. We are checking for subtotal and tax here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/services/stripe-webhook.php#L140-L145

Our VAT tax add on and the AvaTax add on have been updated to try to account for this on recurring orders too.

I'm going to close this issue, although there may still be related issues for some setups. If so, open a new ticket. Thanks.
